import { createHash } from "node:crypto";
import { beforeEach,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({getUser:vi.fn(),rpc:vi.fn(),upload:vi.fn(),remove:vi.fn(),storageFrom:vi.fn()}));
vi.mock("@/lib/supabase/server",()=>({getSupabaseServerClient:async()=>({auth:{getUser:mocks.getUser},rpc:mocks.rpc,storage:{from:mocks.storageFrom}})}));
vi.mock("@/lib/i18n/locale",()=>({isLocale:(value:string)=>value==="fr"||value==="ar"}));
vi.mock("@/lib/provider-qualification/model",async()=>await import("../../../../lib/provider-qualification/model"));
import { declareProviderCapacity,recordProviderDocument,requestProviderService,submitProviderProfile,type ProviderActionState } from "./actions";
const idle:ProviderActionState={status:"idle"};const org="11111111-1111-4111-8111-111111111111";const service="22222222-2222-4222-8222-222222222222";const key="33333333-3333-4333-8333-333333333333";
function base(){const form=new FormData();form.set("locale","fr");form.set("organizationId",org);form.set("idempotencyKey",key);return form}
const pdf=Uint8Array.from([0x25,0x50,0x44,0x46,0x2d,0x31,0x2e,0x37]);
function documentForm(file:File){const form=base();form.set("documentKind","LEGAL");form.set("code","RC");form.set("issuerName","Tribunal");form.set("referenceNumber","RC-2026");form.set("issuedOn","2026-01-01");form.set("expiresOn","");form.set("changeReason","Première version");form.set("documentFile",file);return form}
beforeEach(()=>{mocks.getUser.mockReset().mockResolvedValue({data:{user:{id:"user-1"}}});mocks.rpc.mockReset().mockResolvedValue({data:{outcome:"PROVIDER_OPERATION_RECORDED",command_id:"44444444-4444-4444-8444-444444444444"},error:null});mocks.upload.mockReset().mockResolvedValue({data:{path:"ok"},error:null});mocks.remove.mockReset().mockResolvedValue({data:[],error:null});mocks.storageFrom.mockReset().mockReturnValue({upload:mocks.upload,remove:mocks.remove})});
describe("provider qualification actions",()=>{
 it("never calls RPC for invalid profile",async()=>{const form=base();form.set("expectedRowVersion","0");form.set("activitySummary","court");form.set("teamSize","0");form.set("yearsExperience","-1");await expect(submitProviderProfile(idle,form)).resolves.toEqual({status:"error",reason:"VALIDATION"});expect(mocks.rpc).not.toHaveBeenCalled()});
 it("maps the service request to RPC 062",async()=>{const form=base();form.set("serviceId",service);await expect(requestProviderService(idle,form)).resolves.toEqual({status:"success",outcome:"PROVIDER_OPERATION_RECORDED"});expect(mocks.rpc).toHaveBeenCalledWith("request_provider_service",{p_provider_organization_id:org,p_service_id:service,p_idempotency_key:key})});
 it("enforces PAUSED capacity without units",async()=>{const form=base();form.set("serviceId",service);form.set("capacityStatus","PAUSED");form.set("availableUnits","12");form.set("leadTimeDays","4");form.set("reason","Congé planifié");await expect(declareProviderCapacity(idle,form)).resolves.toEqual({status:"success",outcome:"PROVIDER_OPERATION_RECORDED"});expect(mocks.rpc).toHaveBeenCalledWith("declare_provider_capacity",expect.objectContaining({p_capacity_status:"PAUSED",p_available_units:null}))});
 it("does not invoke business RPC without session",async()=>{mocks.getUser.mockResolvedValueOnce({data:{user:null}});const form=base();form.set("serviceId",service);await expect(requestProviderService(idle,form)).resolves.toEqual({status:"error",reason:"UNAUTHENTICATED"});expect(mocks.rpc).not.toHaveBeenCalled()});
 it("reserves a private path, uploads real bytes and binds a server-computed hash",async()=>{const path=`${org}/user-1/55555555-5555-4555-8555-555555555555.pdf`;mocks.rpc.mockResolvedValueOnce({data:{outcome:"PROVIDER_DOCUMENT_UPLOAD_RESERVED",upload_id:"55555555-5555-4555-8555-555555555555",storage_bucket:"provider-qualification",storage_object_path:path},error:null}).mockResolvedValueOnce({data:{outcome:"PROVIDER_DOCUMENT_VERSION_RECORDED",command_id:"44444444-4444-4444-8444-444444444444"},error:null});await expect(recordProviderDocument(idle,documentForm(new File([pdf],"registre.pdf",{type:"application/pdf"})))).resolves.toEqual({status:"success",outcome:"PROVIDER_DOCUMENT_VERSION_RECORDED"});expect(mocks.upload).toHaveBeenCalledWith(path,expect.any(Uint8Array),expect.objectContaining({contentType:"application/pdf",upsert:false}));expect(mocks.rpc).toHaveBeenNthCalledWith(2,"record_provider_document_version",expect.objectContaining({p_document:expect.objectContaining({storage_object_path:path,content_hash:createHash("sha256").update(pdf).digest("hex")})}));expect(JSON.stringify(mocks.rpc.mock.calls)).not.toContain("registre.pdf")});
 it("rejects forged PDF content before reserving storage",async()=>{await expect(recordProviderDocument(idle,documentForm(new File(["not a pdf"],"fake.pdf",{type:"application/pdf"})))).resolves.toEqual({status:"error",reason:"VALIDATION"});expect(mocks.rpc).not.toHaveBeenCalled();expect(mocks.upload).not.toHaveBeenCalled()});
 it("removes an unbound object when document recording fails",async()=>{const path=`${org}/user-1/55555555-5555-4555-8555-555555555555.pdf`;mocks.rpc.mockResolvedValueOnce({data:{outcome:"PROVIDER_DOCUMENT_UPLOAD_RESERVED",upload_id:"55555555-5555-4555-8555-555555555555",storage_bucket:"provider-qualification",storage_object_path:path},error:null}).mockResolvedValueOnce({data:null,error:{code:"42501"}});await expect(recordProviderDocument(idle,documentForm(new File([pdf],"registre.pdf",{type:"application/pdf"})))).resolves.toEqual({status:"error",reason:"FORBIDDEN"});expect(mocks.remove).toHaveBeenCalledWith([path])});
});
