begin;
set local search_path=public,extensions;
select plan(41);

select ok((select count(*)=5 and bool_and(p.prosecdef and p.proconfig::text like '%search_path=pg_catalog%') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('begin_catalog_import','stage_catalog_import_rows','validate_catalog_import','commit_catalog_import','get_catalog_import_report')),'all five import RPCs are SECURITY DEFINER with fixed search paths');
select ok(not exists(select 1 from (values('public.catalog_source_files'),('public.catalog_import_chunks'),('public.catalog_import_chunk_rows'))t(name) cross join(values('anon'),('authenticated'),('service_role'))r(role) where has_table_privilege(r.role,t.name,'SELECT,INSERT,UPDATE,DELETE')),'source, chunk and row-link evidence tables expose no direct runtime privilege');
select ok((select count(*)=5 and bool_and(has_function_privilege('authenticated',p.oid,'EXECUTE') and not has_function_privilege('anon',p.oid,'EXECUTE') and not has_function_privilege('service_role',p.oid,'EXECUTE')) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('begin_catalog_import','stage_catalog_import_rows','validate_catalog_import','commit_catalog_import','get_catalog_import_report')),'all import RPC signatures are authenticated-only');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname in('catalog_baseline_uuid','catalog_baseline_slug','catalog_canonical_json','catalog_import_payload_error','assert_catalog_baseline_actor','catalog_import_actual_counts') and(has_function_privilege('anon',p.oid,'EXECUTE')or has_function_privilege('authenticated',p.oid,'EXECUTE')or has_function_privilege('service_role',p.oid,'EXECUTE'))),'private import helpers are inaccessible to runtime roles');

insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values
('f3000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','baseline-admin@example.invalid','',now(),'{}','{}',now(),now()),
('f3000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000000','authenticated','authenticated','baseline-other@example.invalid','',now(),'{}','{}',now(),now());
insert into public.platform_user_roles(user_id,role_code) values('f3000000-0000-0000-0000-000000000001','MATRICIA_ADMIN'),('f3000000-0000-0000-0000-000000000002','MATRICIA_ADMIN');
insert into public.organizations(id,legal_name,display_name,status,created_by) values
('f3010000-0000-0000-0000-000000000001','Baseline Test Steward','Baseline Test','ACTIVE','f3000000-0000-0000-0000-000000000001'),
('f3010000-0000-0000-0000-000000000002','Other Baseline Steward','Other Baseline','ACTIVE','f3000000-0000-0000-0000-000000000002');

create temporary table p06_import_fixture(manifest jsonb,expected jsonb,sources jsonb,bundle_hash text,batch_id uuid,begin_response jsonb,validate_response jsonb,commit_expected integer,commit_response jsonb);
create temporary table p06_import_errors(test_key text primary key,sqlstate text,message text);
grant select,update on p06_import_fixture to authenticated;
grant select,insert on p06_import_errors to authenticated;
grant usage on schema extensions to authenticated;
grant execute on function extensions.is(anyelement,anyelement,text),extensions.ok(boolean,text) to authenticated;
insert into p06_import_fixture(manifest,expected,sources,bundle_hash) values(
 jsonb_build_object('catalog_version','1.0.0','counts',jsonb_build_object('libraries',10,'categories',40,'subcategories',80,'services',200,'service_subcategory_links',212,'rfq_questions',5000,'diagnostic_questions',700,'provider_questions',300,'total_questions',6000),'by_library',jsonb_build_object('TST',jsonb_build_object('categories',4,'subcategories',8,'services',20,'rfq_questions',500,'diagnostic_questions',70,'provider_questions',30))),
 jsonb_build_object('libraries',1,'categories',4,'subcategories',8,'services',20,'service_subcategory_links',20,'rfq_questions',500,'diagnostic_questions',70,'provider_questions',30,'total_questions',600),
 (select jsonb_agg(jsonb_build_object('path','catalogue/Matricia_Catalogue_Metier_V1/'||name,'sha256',repeat(substr(md5(name),1,1),64),'byte_size',100,'data_rows',rows,'generator_version','1.0.0')) from(values('catalog_manifest.json',1),('libraries.csv',10),('categories.csv',40),('subcategories.csv',80),('services.csv',200),('service_subcategory_links.csv',212),('questions_rfq.csv',5000),('questions_diagnostic.csv',700),('questions_provider_qualification.csv',300),('questions_all.jsonl',6000))s(name,rows)),repeat('f',64));
update p06_import_fixture f set bundle_hash=encode(extensions.digest(convert_to(private.catalog_canonical_json(jsonb_build_object('manifest',f.manifest,'sources',(select jsonb_agg(jsonb_build_object('path',s->>'path','sha256',s->>'sha256','byte_size',(s->>'byte_size')::bigint,'data_rows',(s->>'data_rows')::integer)order by s->>'path')from jsonb_array_elements(f.sources)s))),'UTF8'),'sha256'),'hex');

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
do $runtime$begin perform public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:NO_AAL',repeat('e',64),f.manifest,'TST','f3010000-0000-0000-0000-000000000001',f.expected,f.sources,'baseline-no-aal') from p06_import_fixture f;exception when others then insert into p06_import_errors values('no-aal',sqlstate,sqlerrm);end$runtime$;
reset role;
select is((select sqlstate||':'||message from p06_import_errors where test_key='no-aal'),'42501:CATALOG_IMPORT_DENIED'::text,'missing AAL claim fails closed');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
select extensions.throws_ok($$select public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:BAD_ALLOWLIST',f.bundle_hash,f.manifest,'TST','f3010000-0000-0000-0000-000000000001',f.expected,f.sources-0,'baseline-bad-allowlist')from p06_import_fixture f$$,'22023'::char(5),'INVALID_CATALOG_IMPORT_REQUEST','begin rejects an incomplete source allowlist');
select extensions.throws_ok($$select public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:BAD_BUNDLE',repeat('0',64),f.manifest,'TST','f3010000-0000-0000-0000-000000000001',f.expected,f.sources,'baseline-bad-bundle')from p06_import_fixture f$$,'22000'::char(5),'CATALOG_BUNDLE_HASH_MISMATCH','begin rejects a bundle hash not recomputed from canonical sources and manifest');
update p06_import_fixture set begin_response=(select public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:TST',bundle_hash,manifest,'TST','f3010000-0000-0000-0000-000000000001',expected,sources,'baseline-test-begin','f3020000-0000-0000-0000-000000000001') from p06_import_fixture);
update p06_import_fixture set batch_id=(begin_response->>'batch_id')::uuid;
select is((select begin_response->>'outcome' from p06_import_fixture),'CATALOG_IMPORT_RECEIVED'::text,'begin import creates a received batch');
select is((select public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:TST',bundle_hash,manifest,'TST','f3010000-0000-0000-0000-000000000001',expected,sources,'baseline-test-begin','f3020000-0000-0000-0000-000000000001') from p06_import_fixture),(select begin_response from p06_import_fixture),'begin import replays the same response');
reset role;
update public.catalog_import_batches set steward_organization_id='f3010000-0000-0000-0000-000000000002' where id=(select batch_id from p06_import_fixture);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
do $runtime$begin perform public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:TST',f.bundle_hash,f.manifest,'TST','f3010000-0000-0000-0000-000000000001',f.expected,f.sources,'baseline-test-begin','f3020000-0000-0000-0000-000000000001') from p06_import_fixture f;exception when others then insert into p06_import_errors values('begin-replay-scope',sqlstate,sqlerrm);end$runtime$;
reset role;
update public.catalog_import_batches set steward_organization_id='f3010000-0000-0000-0000-000000000001' where id=(select batch_id from p06_import_fixture);
select is((select sqlstate||':'||message from p06_import_errors where test_key='begin-replay-scope'),'42501:CATALOG_IMPORT_REPLAY_SCOPE_MISMATCH'::text,'begin replay revalidates durable organization, creator, library, manifest, counts, sources and command scope');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
do $runtime$begin perform public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:TST:CHANGED',f.bundle_hash,f.manifest,'TST','f3010000-0000-0000-0000-000000000001',f.expected,f.sources,'baseline-test-begin') from p06_import_fixture f;exception when others then insert into p06_import_errors values('begin-mismatch',sqlstate,sqlerrm);end$runtime$;
select is((select sqlstate||':'||message from p06_import_errors where test_key='begin-mismatch'),'22000:IDEMPOTENCY_PAYLOAD_MISMATCH'::text,'begin import rejects idempotency payload mismatch');
do $runtime$begin perform public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:TST',f.bundle_hash,f.manifest,'TST','f3010000-0000-0000-0000-000000000002',f.expected,f.sources,'baseline-cross-org-begin','f3020000-0000-0000-0000-000000000001') from p06_import_fixture f;exception when others then insert into p06_import_errors values('begin-cross-org',sqlstate,sqlerrm);end$runtime$;
select is((select sqlstate||':'||message from p06_import_errors where test_key='begin-cross-org'),'42501:CATALOG_IMPORT_BATCH_SCOPE_MISMATCH'::text,'an existing baseline batch can never be reused as proof for another organization');
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000002","role":"authenticated","aal":"aal2"}',true);
do $runtime$begin perform public.begin_catalog_import('MATRICIA_GOLD_MASTER_BASELINE_TEST:TST',f.bundle_hash,f.manifest,'TST','f3010000-0000-0000-0000-000000000001',f.expected,f.sources,'baseline-cross-actor-begin','f3020000-0000-0000-0000-000000000001') from p06_import_fixture f;exception when others then insert into p06_import_errors values('begin-cross-actor',sqlstate,sqlerrm);end$runtime$;
select is((select sqlstate||':'||message from p06_import_errors where test_key='begin-cross-actor'),'42501:CATALOG_IMPORT_BATCH_SCOPE_MISMATCH'::text,'an existing baseline batch remains bound to its creating principal');
reset role;
select ok((select count(*) from public.audit_events where action='catalog.import.begun' and resource_id=(select batch_id::text from p06_import_fixture))=1 and(select count(*) from public.event_outbox where event_type='CatalogImportBegunV1' and aggregate_id=(select batch_id::text from p06_import_fixture) and causation_id=(select (begin_response->>'command_id')::uuid from p06_import_fixture))=1,'begin emits one command-caused audit and Outbox event');

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
do $runtime$begin perform public.stage_catalog_import_rows(f.batch_id,'catalogue/Matricia_Catalogue_Metier_V1/libraries.csv','LIBRARY',jsonb_build_array(jsonb_build_object('line_number',1,'business_key','TST','payload',jsonb_build_object('code','TST'))),'stage-csv-header-line') from p06_import_fixture f;exception when others then insert into p06_import_errors values('csv-header-line',sqlstate,sqlerrm);end$runtime$;
select is((select sqlstate||':'||message from p06_import_errors where test_key='csv-header-line'),'22023:INVALID_CATALOG_IMPORT_ROW'::text,'CSV staging rejects header line 1 before persistence');
do $runtime$begin perform public.stage_catalog_import_rows(f.batch_id,'catalogue/Matricia_Catalogue_Metier_V1/libraries.csv','LIBRARY',jsonb_build_array(jsonb_build_object('line_number',12,'business_key','TST','payload',jsonb_build_object('code','TST'))),'stage-csv-after-eof') from p06_import_fixture f;exception when others then insert into p06_import_errors values('csv-after-eof',sqlstate,sqlerrm);end$runtime$;
select is((select sqlstate||':'||message from p06_import_errors where test_key='csv-after-eof'),'22023:INVALID_CATALOG_IMPORT_ROW'::text,'CSV staging rejects line numbers after data_rows plus the header');
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/libraries.csv','LIBRARY',jsonb_build_array(jsonb_build_object('line_number',2,'business_key','TST','payload',jsonb_build_object('code','TST','name_fr','Informatique','description_fr','Bibliothèque informatique de référence','order',1,'status','ACTIVE','version',1,'franchisee_can_edit',true,'central_approval_for_sensitive_changes',true))),'stage-library') from p06_import_fixture;
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/categories.csv','CATEGORY',(select jsonb_agg(jsonb_build_object('line_number',n+1,'business_key','TST-MACRO-'||n,'payload',jsonb_build_object('library_code','TST','code','TST-MACRO-'||n,'name_fr','Catégorie '||n,'description_fr','Description catégorie '||n,'order',n,'status','ACTIVE','version',1,'franchisee_can_edit',true,'subcategories_json','[]'::jsonb)))from generate_series(1,4)n),'stage-categories') from p06_import_fixture;
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/subcategories.csv','SUBCATEGORY',(select jsonb_agg(jsonb_build_object('line_number',n+1,'business_key','TST-SUB-'||n,'payload',jsonb_build_object('library_code','TST','macro_category_code','TST-MACRO-'||ceil(n/2.0)::integer,'code','TST-SUB-'||n,'name_fr','Sous-catégorie '||n,'description_fr','Description sous-catégorie '||n,'order',n,'status','ACTIVE','version',1,'franchisee_can_edit',true)))from generate_series(1,8)n),'stage-subcategories') from p06_import_fixture;
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/services.csv','SERVICE',(select jsonb_agg(jsonb_build_object('line_number',n+1,'business_key','TST-SVC-'||n,'payload',jsonb_build_object('library_code','TST','category_code','TST-SUB-'||(((n-1)%8)+1),'macro_category_code','TST-MACRO-'||ceil((((n-1)%8)+1)/2.0)::integer,'subcategory_code','TST-SUB-'||(((n-1)%8)+1),'code','TST-SVC-'||n,'name_fr','Service informatique '||n,'description_fr','Description complète du service '||n,'service_type','AUDIT','unit_label_fr','unité','credit_eligible',false,'volume_eligible',false,'recurring_eligible',false,'central_approval_flags','[]'::jsonb,'standard_deliverables_fr','Livrable vérifié','standard_proof_fr','Preuve vérifiée','order',n,'status','ACTIVE','version',1)))from generate_series(1,20)n),'stage-services') from p06_import_fixture;
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/service_subcategory_links.csv','SERVICE_SUBCATEGORY_LINK',(select jsonb_agg(jsonb_build_object('line_number',n+1,'business_key','TST-SVC-'||n||':TST-SUB-'||(((n-1)%8)+1),'payload',jsonb_build_object('library_code','TST','service_code','TST-SVC-'||n,'subcategory_code','TST-SUB-'||(((n-1)%8)+1),'link_type','PRIMARY','status','ACTIVE')))from generate_series(1,20)n),'stage-links') from p06_import_fixture;

select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/questions_all.jsonl','QUESTION',(select jsonb_agg(jsonb_build_object('line_number',n,'business_key','Q-RFQ-TST-'||n,'payload',jsonb_build_object('library_code','TST','category_code','TST-SUB-'||((((ceil(n/25.0)::integer)-1)%8)+1),'service_code','TST-SVC-'||ceil(n/25.0)::integer,'phase','RFQ','section','Cadrage','order',((n-1)%25)+1,'label_fr','Question RFQ '||n,'help_fr','Aide RFQ','answer_type','LONG_TEXT','required',true,'required_for_quote',true,'options','[]'::jsonb,'validation_schema','{}'::jsonb,'condition','{}'::jsonb,'data_key','rfq.tst.'||n,'weight',1,'max_score',10,'sensitivity','BUSINESS','template_key','RFQ_BASE'))order by n)from generate_series(1,200)n),'stage-questions-1') from p06_import_fixture;
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/questions_all.jsonl','QUESTION',(select jsonb_agg(jsonb_build_object('line_number',n,'business_key','Q-RFQ-TST-'||n,'payload',jsonb_build_object('library_code','TST','category_code','TST-SUB-'||((((ceil(n/25.0)::integer)-1)%8)+1),'service_code','TST-SVC-'||ceil(n/25.0)::integer,'phase','RFQ','section','Cadrage','order',((n-1)%25)+1,'label_fr','Question RFQ '||n,'help_fr','Aide RFQ','answer_type','LONG_TEXT','required',true,'required_for_quote',true,'options','[]'::jsonb,'validation_schema','{}'::jsonb,'condition','{}'::jsonb,'data_key','rfq.tst.'||n,'weight',1,'max_score',10,'sensitivity','BUSINESS','template_key','RFQ_BASE'))order by n)from generate_series(201,400)n),'stage-questions-2') from p06_import_fixture;
select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/questions_all.jsonl','QUESTION',(select jsonb_agg(x order by n)from(select n,jsonb_build_object('line_number',n,'business_key','Q-RFQ-TST-'||n,'payload',jsonb_build_object('library_code','TST','category_code','TST-SUB-'||((((ceil(n/25.0)::integer)-1)%8)+1),'service_code','TST-SVC-'||ceil(n/25.0)::integer,'phase','RFQ','section','Cadrage','order',((n-1)%25)+1,'label_fr','Question RFQ '||n,'help_fr','Aide RFQ','answer_type','LONG_TEXT','required',true,'required_for_quote',true,'options','[]'::jsonb,'validation_schema','{}'::jsonb,'condition','{}'::jsonb,'data_key','rfq.tst.'||n,'weight',1,'max_score',10,'sensitivity','BUSINESS','template_key','RFQ_BASE'))x from generate_series(401,500)n union all select 500+n,jsonb_build_object('line_number',500+n,'business_key','Q-DIAG-TST-'||n,'payload',jsonb_build_object('library_code','TST','category_code','TST-SUB-'||(((n-1)%8)+1),'service_code','','phase','DIAGNOSTIC','section','Diagnostic','order',n,'label_fr','Question diagnostic '||n,'help_fr','Aide diagnostic','answer_type','LONG_TEXT','required',false,'required_for_quote',false,'options','[]'::jsonb,'validation_schema','{}'::jsonb,'condition','{}'::jsonb,'data_key','diagnostic.tst.'||n,'weight',1,'max_score',10,'sensitivity','BUSINESS','template_key','DIAG_BASE'))from generate_series(1,70)n union all select 570+n,jsonb_build_object('line_number',570+n,'business_key','Q-PROVIDER-TST-'||n,'payload',jsonb_build_object('library_code','TST','category_code','TST-SUB-'||(((n-1)%8)+1),'service_code','','phase','PROVIDER_QUALIFICATION','section','Qualification','order',n,'label_fr','Question qualification '||n,'help_fr','Aide qualification','answer_type','LONG_TEXT','required',true,'required_for_quote',false,'options','[]'::jsonb,'validation_schema','{}'::jsonb,'condition','{}'::jsonb,'data_key','provider.tst.'||n,'weight',1,'max_score',10,'sensitivity','BUSINESS','template_key','PROVIDER_BASE'))from generate_series(1,30)n)s),'stage-questions-3') from p06_import_fixture;

reset role;
select is((select count(*)::integer from public.catalog_import_rows where batch_id=(select batch_id from p06_import_fixture)),653,'bounded chunks stage all slice rows');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
select is((select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/libraries.csv','LIBRARY',jsonb_build_array(jsonb_build_object('line_number',2,'business_key','TST','payload',jsonb_build_object('code','TST','name_fr','Informatique','description_fr','Bibliothèque informatique de référence','order',1,'status','ACTIVE','version',1,'franchisee_can_edit',true,'central_approval_for_sensitive_changes',true))),'stage-library')->>'accepted' from p06_import_fixture),'1'::text,'staging chunk replays idempotently');
do $runtime$begin perform public.stage_catalog_import_rows(f.batch_id,'catalogue/Matricia_Catalogue_Metier_V1/libraries.csv','LIBRARY','[{"line_number":2,"business_key":"IT","payload":{"code":"IT","name_fr":"Mutation"}}]'::jsonb,'stage-library') from p06_import_fixture f;exception when others then insert into p06_import_errors values('stage-mismatch',sqlstate,sqlerrm);end$runtime$;
select is((select sqlstate||':'||message from p06_import_errors where test_key='stage-mismatch'),'22000:IDEMPOTENCY_PAYLOAD_MISMATCH'::text,'staging mismatch is rejected');
reset role;
select ok((select count(*)=8 and count(distinct causation_id)=8 from public.event_outbox where event_type='CatalogImportRowsStagedV1' and aggregate_id=(select batch_id::text from p06_import_fixture)) and(select count(*)=8 from public.audit_events where action='catalog.import.rows_staged' and resource_id=(select batch_id::text from p06_import_fixture)),'each accepted chunk emits one independently caused audit and Outbox event');
select ok((select count(*)=8 from public.catalog_import_chunks where batch_id=(select batch_id from p06_import_fixture)) and(select count(*)=653 from public.catalog_import_chunk_rows cr join public.catalog_import_rows r on r.id=cr.import_row_id where r.batch_id=(select batch_id from p06_import_fixture)) and not exists(select 1 from public.catalog_import_chunks c join public.catalog_source_files s on s.batch_id=c.batch_id and s.source_path=c.source_file where c.batch_id=(select batch_id from p06_import_fixture) and(c.source_sha256 is distinct from s.sha256 or c.source_byte_size is distinct from s.byte_size or c.source_data_rows is distinct from s.data_rows)),'all staged rows are singly bound to chunks carrying registered source metadata');

savepoint invalid_payload;
update public.catalog_import_rows set payload=jsonb_set(payload,'{answer_type}','"UNKNOWN"'::jsonb) where batch_id=(select batch_id from p06_import_fixture) and business_key='Q-RFQ-TST-1';
update public.catalog_import_rows set row_hash=private.canonical_request_hash(payload) where batch_id=(select batch_id from p06_import_fixture) and business_key='Q-RFQ-TST-1';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
select is((select public.validate_catalog_import(f.batch_id,(public.get_catalog_import_report(f.batch_id)->>'row_version')::integer,'baseline-invalid-payload')->>'outcome' from p06_import_fixture f),'CATALOG_IMPORT_INVALID'::text,'validation rejects a typed payload before READY');
select ok((select public.get_catalog_import_report(batch_id)#>'{errors,0}' from p06_import_fixture)@>jsonb_build_object('source_file','catalogue/Matricia_Catalogue_Metier_V1/questions_all.jsonl','line_number',1,'business_key','Q-RFQ-TST-1','error_code','QUESTION_TYPE_INVALID'),'invalid report identifies the deterministic source row without exposing its payload');
rollback to savepoint invalid_payload;

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
update p06_import_fixture f set validate_response=public.validate_catalog_import(f.batch_id,(public.get_catalog_import_report(f.batch_id)->>'row_version')::integer,'baseline-test-validate','f3020000-0000-0000-0000-000000000002');
reset role;
select is((select validate_response->>'outcome' from p06_import_fixture),'CATALOG_IMPORT_VALIDATED'::text,'validation recalculates and accepts the complete slice');
select is((select actual_counts from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)),(select expected from p06_import_fixture),'actual counts equal expected counts');
select ok((select count(*)=1 and bool_and((metadata->>'command_id')::uuid=(select (validate_response->>'command_id')::uuid from p06_import_fixture)) from public.audit_events where action='catalog.import.validated' and resource_id=(select batch_id::text from p06_import_fixture)) and(select count(*)=1 and bool_and(causation_id=(select (validate_response->>'command_id')::uuid from p06_import_fixture)) from public.event_outbox where event_type='CatalogImportValidatedV1' and aggregate_id=(select batch_id::text from p06_import_fixture)),'validation exposes its own command and binds audit metadata to Outbox causation');

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
update p06_import_fixture f set commit_expected=(public.get_catalog_import_report(f.batch_id)->>'row_version')::integer;
reset role;
insert into public.catalog_libraries(id,code,slug,status,steward_organization_id,created_by) values(private.catalog_baseline_uuid('catalog-library','TST'),'TST','tampered-tst','DRAFT','f3010000-0000-0000-0000-000000000001','f3000000-0000-0000-0000-000000000001');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
do $runtime$begin perform public.commit_catalog_import(f.batch_id,f.commit_expected,'baseline-conflict-commit')from p06_import_fixture f;exception when others then insert into p06_import_errors values('materialized-conflict',sqlstate,sqlerrm);end$runtime$;
reset role;
select is((select sqlstate||':'||message from p06_import_errors where test_key='materialized-conflict'),'22000:CATALOG_BASELINE_TARGET_ALREADY_EXISTS'::text,'commit refuses any pre-existing deterministic materialization instead of adopting conflicted state');
select ok((select status='READY' and row_version=(select commit_expected from p06_import_fixture) from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)) and not exists(select 1 from public.catalog_library_versions where library_id=private.catalog_baseline_uuid('catalog-library','TST')) and not exists(select 1 from public.catalog_releases where library_id=private.catalog_baseline_uuid('catalog-library','TST')),'failed materialization is atomic and leaves the validated batch retryable');
delete from public.catalog_libraries where id=private.catalog_baseline_uuid('catalog-library','TST');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
update p06_import_fixture set commit_response=public.commit_catalog_import(batch_id,commit_expected,'baseline-test-commit','f3020000-0000-0000-0000-000000000003');
reset role;
select is((select commit_response->>'outcome' from p06_import_fixture),'CATALOG_IMPORT_COMMITTED'::text,'commit materializes the validated slice');
select ok((select count(*) from public.catalog_libraries where code='TST')=1 and(select count(*) from public.catalog_categories where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)))=4 and(select count(*) from public.catalog_subcategories where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)))=8 and(select count(*) from public.catalog_services where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)))=20,'commit creates deterministic catalogue identities');
select ok((select count(*) from public.questionnaires where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)))=22 and(select count(*) from public.question_bank_questions where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)))=600,'commit creates 22 targeted questionnaires and 600 question identities');
select ok((select count(*)=600 and bool_and(status='DRAFT' and translation_review_status='PENDING' and source_phase is not null and source_import_batch_id=(select batch_id from p06_import_fixture) and source_file='catalogue/Matricia_Catalogue_Metier_V1/questions_all.jsonl' and source_line_number is not null and source_row_hash=content_hash) from public.question_versions where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture))),'question versions remain DRAFT/PENDING and preserve phase, service and source provenance');
select ok((select count(*) from public.question_rules where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)))=0,'empty source conditions do not create fictitious rules');
select ok((select status='DRAFT' from public.catalog_releases where id=(select candidate_release_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture))) and not exists(select 1 from public.catalog_library_versions where library_id=(select library_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture)) and translation_review_status<>'PENDING'),'French-only baseline remains a non-published translation-pending candidate');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"f3000000-0000-0000-0000-000000000001","role":"authenticated","aal":"aal2"}',true);
select is((select public.commit_catalog_import(batch_id,commit_expected,'baseline-test-commit','f3020000-0000-0000-0000-000000000003') from p06_import_fixture),(select commit_response from p06_import_fixture),'commit replay returns the exact durable response');
select is((select public.stage_catalog_import_rows(batch_id,'catalogue/Matricia_Catalogue_Metier_V1/libraries.csv','LIBRARY',jsonb_build_array(jsonb_build_object('line_number',2,'business_key','TST','payload',jsonb_build_object('code','TST','name_fr','Informatique','description_fr','Bibliothèque informatique de référence','order',1,'status','ACTIVE','version',1,'franchisee_can_edit',true,'central_approval_for_sensitive_changes',true))),'stage-library')->>'accepted' from p06_import_fixture),'1'::text,'stage replay is returned after the batch reaches IMPORTED');
select is((select get_catalog_import_report(batch_id)->>'status' from p06_import_fixture),'IMPORTED'::text,'bounded report exposes final status without staged payloads');
reset role;
select ok((select count(*)=1 and bool_and((metadata->>'command_id')::uuid=(select (commit_response->>'command_id')::uuid from p06_import_fixture)) from public.audit_events where action='catalog.import.committed' and resource_id=(select batch_id::text from p06_import_fixture)) and(select count(*)=1 and bool_and(causation_id=(select (commit_response->>'command_id')::uuid from p06_import_fixture)) from public.event_outbox where event_type='CatalogImportCommittedV1' and aggregate_id=(select batch_id::text from p06_import_fixture)),'commit replay stays unique and exposes the command shared by audit metadata and Outbox causation');
select ok((select count(distinct command_id)=3 from (select (begin_response->>'command_id')::uuid command_id from p06_import_fixture union all select (validate_response->>'command_id')::uuid from p06_import_fixture union all select (commit_response->>'command_id')::uuid from p06_import_fixture)c),'begin, validate and commit use distinct command causation identifiers');

select is((select count(*)::integer from public.catalog_release_items where release_id=(select candidate_release_id from public.catalog_import_batches where id=(select batch_id from p06_import_fixture))),53,'candidate release freezes 1+4+8+20+20 catalogue versions');
select ok((select count(*) from public.catalog_source_files where batch_id=(select batch_id from p06_import_fixture))=10 and not exists(select 1 from public.catalog_source_files where source_path like '%..%'),'source registry contains the exact ten canonical bounded paths');

select * from finish();
rollback;
