begin;
set local search_path=public,extensions;
select plan(18);

select ok((select pg_get_functiondef(p.oid)like'%CLIENT_OWNER%'and pg_get_functiondef(p.oid)like'%CLIENT_ADMIN%'and pg_get_functiondef(p.oid)like'%PROVIDER_MANAGER%'and pg_get_functiondef(p.oid)like'%FRANCHISE_MANAGER%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='marketing_manage_access'),'daily marketing management retains owner and manager roles');
select ok((select pg_get_functiondef(p.oid)not like'%PROVIDER_SALES%'and pg_get_functiondef(p.oid)not like'%CLIENT_BUYER%'and pg_get_functiondef(p.oid)not like'%ACCOUNTING%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='marketing_manage_access'),'daily management excludes sales buyer and accounting roles');
select ok((select pg_get_functiondef(p.oid)like'%CLIENT_OWNER%'and pg_get_functiondef(p.oid)like'%PROVIDER_OWNER%'and pg_get_functiondef(p.oid)like'%FRANCHISE_OWNER%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='marketing_consent_access'),'consent authority recognises the three organization owner roles');
select ok((select pg_get_functiondef(p.oid)not like'%CLIENT_ADMIN%'and pg_get_functiondef(p.oid)not like'%PROVIDER_MANAGER%'and pg_get_functiondef(p.oid)not like'%FRANCHISE_MANAGER%'and pg_get_functiondef(p.oid)not like'%has_platform_role%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='marketing_consent_access'),'consent authority is owner-only with no platform override');
select ok((select pg_get_functiondef(p.oid)like'%CLIENT_OWNER%'and pg_get_functiondef(p.oid)like'%PROVIDER_OWNER%'and pg_get_functiondef(p.oid)like'%FRANCHISE_OWNER%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='marketing_autopilot_owner_access'),'AUTOPILOT authority recognises the three organization owner roles');
select ok((select pg_get_functiondef(p.oid)not like'%CLIENT_ADMIN%'and pg_get_functiondef(p.oid)not like'%PROVIDER_MANAGER%'and pg_get_functiondef(p.oid)not like'%FRANCHISE_MANAGER%'and pg_get_functiondef(p.oid)not like'%has_platform_role%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='marketing_autopilot_owner_access'),'AUTOPILOT authority is owner-only with no platform override');
select ok((select count(*)=3 and bool_and(p.prosecdef and p.proconfig::text like'%search_path=%')from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname=any(array['marketing_manage_access','marketing_consent_access','marketing_autopilot_owner_access'])),'authorization helpers are security definer with fixed search paths');
select ok((select count(*)=2 and bool_and(not has_function_privilege('authenticated',p.oid,'EXECUTE')and not has_function_privilege('anon',p.oid,'EXECUTE')and not has_function_privilege('service_role',p.oid,'EXECUTE'))from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname=any(array['marketing_consent_access','marketing_autopilot_owner_access'])),'owner-only helpers are not directly executable by API roles');
select ok((select pg_get_functiondef(p.oid)like'%marketing_consent_access(p_organization_id,a)%'and pg_get_functiondef(p.oid)not like'%marketing_manage_access(p_organization_id,a)%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='record_marketing_consent'),'consent command uses the dedicated owner-only guard');
select ok((select pg_get_functiondef(p.oid)like'%MARKETING_CONSENT_OWNER_REQUIRED%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='record_marketing_consent'),'unauthorized consent mutation fails explicitly');
select ok((select pg_get_functiondef(p.oid)like'%pg_advisory_xact_lock%'and pg_get_functiondef(p.oid)like'%marketing-consent:%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='record_marketing_consent'),'concurrent consent changes serialize per organization and purpose');
select ok((select regexp_replace(pg_get_functiondef(p.oid),'[[:space:]]','','g')like'%p_mode=''AUTOPILOT''%'and regexp_replace(pg_get_functiondef(p.oid),'[[:space:]]','','g')like'%marketing_autopilot_owner_access(p_organization_id,a)%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='create_marketing_campaign'),'AUTOPILOT creation invokes the owner-only guard');
select ok((select pg_get_functiondef(p.oid)like'%marketing_consent_active%'and pg_get_functiondef(p.oid)like'%social_connections%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='create_marketing_campaign'),'owner activation still requires consent and active social connection');
select ok((select regexp_replace(pg_get_functiondef(p.oid),'[[:space:]]','','g')like'%marketing_manage_access(p_organization_id,a)%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='create_marketing_campaign'),'MANUAL and ASSISTED campaign creation retains scoped management guard');
select ok((select pg_get_functiondef(p.oid)like'%begin_contract_command%'and pg_get_functiondef(p.oid)like'%audit_events%'and pg_get_functiondef(p.oid)like'%event_outbox%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='record_marketing_consent'),'consent hardening preserves idempotency audit and Outbox');
select ok((select pg_get_functiondef(p.oid)like'%begin_contract_command%'and pg_get_functiondef(p.oid)like'%audit_events%'and pg_get_functiondef(p.oid)like'%event_outbox%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='create_marketing_campaign'),'campaign hardening preserves idempotency audit and Outbox');
select ok((select qual like'%marketing_manage_access%'from pg_policies where schemaname='public'and tablename='marketing_campaigns'),'campaign RLS consumes the narrowed management helper');
select ok((select column_default like'%ASSISTED%'from information_schema.columns where table_schema='public'and table_name='marketing_campaigns'and column_name='mode'),'ASSISTED remains the safe default mode');

select * from finish();
rollback;
