begin;
set local search_path=public,extensions;
select plan(45);

select has_table('public','provider_feedback_snapshots','anonymised non-selected feedback snapshots exist');
select has_table('public','provider_reputation_policy_versions','reputation policies are versioned');
select has_table('public','provider_reputation_snapshots','provider reputation snapshots exist');
select has_table('public','provider_badge_policy_versions','badge calculation policies are versioned');
select has_table('public','provider_badge_evaluations','badge evaluations are calculated snapshots');
select has_table('public','provider_badge_decisions','badge publication decisions are versioned');
select has_table('public','client_provider_favorites','client provider favourites exist');
select has_table('public','favorite_eligibility_revalidations','favourite reuse eligibility is snapshotted');

select has_function('public','publish_not_selected_feedback',array['uuid','jsonb','text','uuid','text','uuid'],'feedback publication command exists');
select has_function('public','calculate_provider_reputation',array['uuid','uuid','jsonb','jsonb','text','text','uuid'],'six-dimensional reputation command exists');
select has_function('public','evaluate_provider_badge',array['uuid','uuid','uuid','uuid','text','uuid'],'badge evaluation command exists');
select has_function('public','decide_provider_badge',array['uuid','text','text','text','uuid'],'human badge decision command exists');
select has_function('public','set_provider_favorite',array['uuid','uuid','uuid','boolean','text','integer','text','uuid'],'favourite lifecycle command exists');
select has_function('public','revalidate_provider_favorite',array['uuid','uuid','text','uuid'],'favourite revalidation command exists');

select ok((select bool_and(p.prosecdef and p.proconfig::text like '%search_path=pg_catalog%') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('publish_not_selected_feedback','calculate_provider_reputation','evaluate_provider_badge','decide_provider_badge','set_provider_favorite','revalidate_provider_favorite')),'all public commands are security definer with fixed search paths');
select ok(not has_function_privilege('anon','public.calculate_provider_reputation(uuid,uuid,jsonb,jsonb,text,text,uuid)','EXECUTE') and not has_function_privilege('service_role','public.decide_provider_badge(uuid,text,text,text,uuid)','EXECUTE'),'anonymous and service roles cannot calculate reputation or decide badges');
select ok(not has_table_privilege('authenticated','public.provider_feedback_snapshots','INSERT') and not has_table_privilege('authenticated','public.provider_reputation_snapshots','UPDATE') and not has_table_privilege('authenticated','public.provider_badge_decisions','DELETE') and not has_table_privilege('authenticated','public.client_provider_favorites','INSERT'),'direct mutations are denied');
select ok((select bool_and(c.relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('provider_feedback_snapshots','provider_reputation_policy_versions','provider_reputation_snapshots','provider_badge_policy_versions','provider_badge_evaluations','provider_badge_decisions','client_provider_favorites','favorite_eligibility_revalidations')),'every module table enforces RLS');
select ok((select count(*)=0 from information_schema.columns where table_schema='public' and table_name in('provider_feedback_snapshots','provider_reputation_policy_versions','provider_reputation_snapshots','provider_badge_policy_versions','provider_badge_evaluations','provider_badge_decisions','client_provider_favorites','favorite_eligibility_revalidations') and data_type in('real','double precision')),'reputation and badges contain no floating point fields');
select ok((select count(*)=6 from information_schema.columns where table_schema='public' and table_name='provider_reputation_snapshots' and column_name in('quality_basis_points','delivery_basis_points','compliance_basis_points','responsiveness_basis_points','satisfaction_basis_points','finance_basis_points')),'the six required reputation dimensions are persisted');
select col_type_is('public','provider_reputation_snapshots','overall_basis_points','integer','overall reputation uses integer basis points');
select ok((select count(*)=6 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('provider_feedback_snapshots','provider_reputation_snapshots','provider_badge_evaluations','provider_badge_decisions','favorite_eligibility_revalidations','provider_reputation_policy_versions') and not t.tgisinternal and t.tgname like '%immutable'),'feedback, reputation, evaluations, decisions, revalidations and policies are immutable');
select ok((select qual like '%provider_organization_id%' and qual not like '%client_organization_id%' from pg_policies where schemaname='public' and tablename='provider_feedback_snapshots' and policyname='provider_feedback_recipient_read'),'feedback rows are readable by the recipient provider, not competing clients');
select ok((select p.prosrc like '%CONFIDENTIAL_FEEDBACK_CONTENT%' and p.prosrc like '%winner%' and p.prosrc like '%prix exact%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname='assert_improvement_axes'),'feedback rejects competitor identity, contacts and exact-price disclosure');
select ok((select p.prosrc like '%NOT_SELECTED%' and p.prosrc like '%FEEDBACK_REQUIRES_COMPLETED_SELECTION%' and p.prosrc like '%ranking_position%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='publish_not_selected_feedback'),'feedback requires a completed selection and exposes only personal ranking');
select ok((select p.prosrc like '%INTEGER_WEIGHTED_AVERAGE_BASIS_POINTS%' and p.prosrc like '%overall_basis_points%' and p.prosrc like '%evidence_refs%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='calculate_provider_reputation'),'reputation is explainable, integer-computed and evidence-backed');
select ok((select p.prosrc like '%HUMAN_REPUTATION_REVIEW_REQUIRED%' and p.prosrc like '%has_platform_role%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='calculate_provider_reputation'),'reputation publication requires an authorised human reviewer');
select ok((select p.prosrc like '%minimum_basis_points%' and p.prosrc like '%minimum_evidence_count%' and p.prosrc like '%eligible%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='evaluate_provider_badge'),'badge eligibility is deterministically calculated from versioned thresholds');
select ok((select p.prosrc like '%HUMAN_BADGE_DECISION_REQUIRED%' and p.prosrc like '%INELIGIBLE_BADGE_CANNOT_BE_PUBLISHED%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='decide_provider_badge'),'badge publication is a human decision and cannot override failed eligibility');
select ok((select p.prosrc like '%INVALID_BADGE_DECISION_TRANSITION%' and p.prosrc like '%REVOKED%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='decide_provider_badge'),'badge publication and revocation transitions are governed');
select ok((select p.prosrc like '%SELF_PROVIDER_FAVORITE_FORBIDDEN%' and p.prosrc like '%STALE_PROVIDER_FAVORITE%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_provider_favorite'),'favourites forbid self-selection and enforce optimistic concurrency');
select ok(
 (select p.prosrc like '%private.revalidate_provider_favorite%' and p.prosrc like '%FAVORITE_ACCESS_DENIED%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='revalidate_provider_favorite')
 and
 (select p.prosrc like '%current_provider_service_eligibility%' and p.prosrc like '%ELIGIBILITY_NOT_CONFIRMED%' and p.prosrc like '%reasons%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname='revalidate_provider_favorite'),
 'every favourite reuse passes the anti-oracle facade then invokes current explainable provider eligibility');
select ok((select p.prosrc like '%FAVORITE_SERVICE_MISMATCH%' and p.prosrc like '%INACTIVE_PROVIDER_FAVORITE%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='revalidate_provider_favorite'),'inactive or service-mismatched favourites cannot be reused');
select ok((select bool_and(p.prosrc like '%audit_events%') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('publish_not_selected_feedback','calculate_provider_reputation','evaluate_provider_badge','decide_provider_badge','set_provider_favorite','revalidate_provider_favorite')),'every sensitive command writes an audit event');
select ok((select bool_and(p.prosrc like '%event_outbox%') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('publish_not_selected_feedback','calculate_provider_reputation','evaluate_provider_badge','decide_provider_badge','set_provider_favorite','revalidate_provider_favorite')),'every sensitive command writes an outbox event');
select ok((select p.prosrc like '%IDEMPOTENCY_PAYLOAD_MISMATCH%' and p.prosrc like '%IDEMPOTENCY_IN_PROGRESS%' and p.prosrc like '%pg_advisory_xact_lock%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname='begin_provider_reputation_command'),'commands use concurrency-safe canonical idempotency');
select has_index('public','provider_feedback_snapshots','provider_feedback_recipient_idx','provider feedback recipient timeline is indexed');
select has_index('public','provider_reputation_snapshots','provider_reputation_latest_idx','latest reputation lookup is indexed');
select has_index('public','client_provider_favorites','client_provider_favorites_client_idx','client favourites are indexed');
select has_index('public','favorite_eligibility_revalidations','favorite_revalidations_request_idx','request revalidations are indexed');
select ok(exists(select 1 from pg_constraint where conrelid='public.provider_badge_evaluations'::regclass and contype='f' and pg_get_constraintdef(oid) like '%reputation_snapshot_id, provider_organization_id%'),'badge evaluation cannot cross provider reputation scope');
select is((select weights from public.provider_reputation_policy_versions where policy_version='PROVIDER-REPUTATION-V1'),'{"quality":20,"delivery":20,"compliance":20,"responsiveness":15,"satisfaction":15,"finance":10}'::jsonb,'V1 reputation weights cover all six dimensions');
select ok(exists(select 1 from pg_constraint where conrelid='public.provider_feedback_snapshots'::regclass and contype='u' and pg_get_constraintdef(oid) like '%quote_id%'),'one confidential feedback snapshot exists per non-selected quote');
select ok(exists(select 1 from pg_indexes where schemaname='public' and tablename='client_provider_favorites' and indexname='client_provider_favorite_global_uidx'),'global favourites cannot be duplicated when service is null');
select ok(exists(select 1 from pg_constraint where conrelid='public.favorite_eligibility_revalidations'::regclass and contype='c' and pg_get_constraintdef(oid) like '%eligible%' and pg_get_constraintdef(oid) like '%exclusion_reasons%'),'failed favourite eligibility must carry explicit exclusion reasons');

select * from finish();
rollback;
