begin;
set local search_path=public,extensions;
select plan(28);

select ok((select count(*)=3 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relname=any(array['direct_client_provider_payments','matricia_own_revenue_payments','provider_commission_receipts'])),'three financial flows have separate records');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='direct_client_provider_payments' and column_name='financial_journal_id'),'direct provider-payment evidence has no Matricia journal column');
select ok((select count(*)=3 and bool_and(relrowsecurity) from pg_class where oid=any(array['public.direct_client_provider_payments'::regclass,'public.matricia_own_revenue_payments'::regclass,'public.provider_commission_receipts'::regclass])),'three flow tables have RLS');
select ok(exists(select 1 from pg_constraint where conrelid='public.direct_client_provider_payments'::regclass and contype='c' and pg_get_constraintdef(oid) like '%MATRICIA_NEVER_HOLDS_PRINCIPAL%'),'direct flow encodes the no-principal boundary');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name=any(array['direct_client_provider_payments','matricia_own_revenue_payments','provider_commission_receipts']) and data_type in('real','double precision')),'financial boundaries use no floats');
select ok((select pg_get_functiondef(oid) not like '%financial_journals%' and pg_get_functiondef(oid) like '%DirectClientProviderPaymentRecordedV1%' from pg_proc where proname='record_direct_client_provider_payment'),'direct-payment command never posts Matricia cash and emits Outbox');
select ok((select pg_get_functiondef(oid) like '%begin_provider_billing_command%' and pg_get_functiondef(oid) like '%direct.payment.recorded%' from pg_proc where proname='record_direct_client_provider_payment'),'direct-payment command is idempotent and audited');

select ok((select count(*)=18 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relname=any(array['vendors','vendor_bank_accounts','purchase_requests','purchase_request_lines','purchase_approvals','purchase_orders','purchase_order_lines','goods_service_receipts','supplier_invoices','supplier_invoice_lines','supplier_credit_notes','accounts_payable','outbound_payments','outbound_payment_allocations','expense_categories','expense_allocations','vendor_contracts','vendor_subscriptions'])),'procurement/AP required table set exists');
select ok((select count(*)=18 and bool_and(relrowsecurity) from pg_class where oid=any(array['public.vendors'::regclass,'public.vendor_bank_accounts'::regclass,'public.purchase_requests'::regclass,'public.purchase_request_lines'::regclass,'public.purchase_approvals'::regclass,'public.purchase_orders'::regclass,'public.purchase_order_lines'::regclass,'public.goods_service_receipts'::regclass,'public.supplier_invoices'::regclass,'public.supplier_invoice_lines'::regclass,'public.supplier_credit_notes'::regclass,'public.accounts_payable'::regclass,'public.outbound_payments'::regclass,'public.outbound_payment_allocations'::regclass,'public.expense_categories'::regclass,'public.expense_allocations'::regclass,'public.vendor_contracts'::regclass,'public.vendor_subscriptions'::regclass])),'all procurement/AP tables have RLS');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name=any(array['purchase_request_lines','purchase_order_lines','supplier_invoices','supplier_invoice_lines','supplier_credit_notes','accounts_payable','outbound_payments','outbound_payment_allocations','expense_allocations']) and data_type in('real','double precision')),'procurement/AP uses no floats');
select ok((select count(*)>=2 from pg_constraint where conrelid='public.supplier_invoices'::regclass and contype='c' and (pg_get_constraintdef(oid) like '%total_minor%' or pg_get_constraintdef(oid) like '%ACCOUNTANT_REVIEW_REQUIRED%')),'supplier invoice totals and fiscal-review state are constrained');
select ok((select count(*)=1 from pg_constraint where conrelid='public.outbound_payment_allocations'::regclass and contype='u' and pg_get_constraintdef(oid) like '%outbound_payment_id, accounts_payable_id%'),'outbound allocations cannot duplicate a payable');
select ok((select pg_get_viewdef('public.accounts_payable_balances'::regclass,true) like '%outstanding_minor%' and reloptions @> array['security_invoker=true'] from pg_class where oid='public.accounts_payable_balances'::regclass),'AP balance is derived through invoker-security view');
select ok((select count(*)>=1 from pg_constraint where conrelid='public.expense_allocations'::regclass and contype='c' and pg_get_constraintdef(oid) like '%PLATFORM%BOX%BENEFIT%LIBRARY%FRANCHISE%CLIENT%PROJECT%COST_CENTER%MARKETING_CAMPAIGN%'),'all V4.1 analytical scopes are constrained');
select ok((select pg_get_functiondef(oid) like '%REQUESTER_CANNOT_APPROVE%' and pg_get_functiondef(oid) like '%auth.jwt()%aal%aal2%' from pg_proc where proname='approve_purchase_request'),'purchase approval enforces four-eyes and MFA');
select ok((select pg_get_functiondef(oid) like '%PAYMENT_OVERALLOCATED%' and pg_get_functiondef(oid) like '%for update%' from pg_proc where proname='reconcile_outbound_payment'),'outbound reconciliation locks and prevents over-allocation');

select ok((select count(*)=2 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relname=any(array['vendor_bank_account_versions','bank_account_change_approvals'])),'RIB version and approval evidence exist');
select ok((select count(*)=2 and bool_and(relrowsecurity) from pg_class where oid=any(array['public.vendor_bank_account_versions'::regclass,'public.bank_account_change_approvals'::regclass])),'RIB evidence tables have RLS');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='vendor_bank_account_versions' and column_name in('iban','account_number','routing_number')),'RIB versions expose no plaintext bank-coordinate column');
select ok((select is_nullable='NO' from information_schema.columns where table_schema='public' and table_name='vendor_bank_account_versions' and column_name='cooling_until'),'RIB activation requires a cooling deadline');
select ok((select pg_get_functiondef(oid) like '%aal2%' and pg_get_functiondef(oid) like '%BankAccountChangeProposedV1%' and pg_get_functiondef(oid) like '%risk_flag%' from pg_proc where proname='propose_vendor_bank_account_version'),'RIB proposal requires MFA, risk evaluation, audit/Outbox');
select ok((select pg_get_functiondef(oid) like '%PROPOSER_CANNOT_APPROVE%' and pg_get_functiondef(oid) like '%cooling_until%' from pg_proc where proname='approve_vendor_bank_account_version'),'RIB activation enforces four-eyes and cooling');

select ok((select count(*)=5 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relname=any(array['payment_refunds','payment_disputes','payment_provider_events','payment_reconciliation_runs','payment_reconciliation_items'])),'own-payment completion tables exist');
select ok((select count(*)=5 and bool_and(relrowsecurity) from pg_class where oid=any(array['public.payment_refunds'::regclass,'public.payment_disputes'::regclass,'public.payment_provider_events'::regclass,'public.payment_reconciliation_runs'::regclass,'public.payment_reconciliation_items'::regclass])),'own-payment tables have RLS');
select ok((select count(*)>=1 from pg_constraint where conrelid='public.payment_provider_events'::regclass and contype='u' and pg_get_constraintdef(oid) like '%provider, provider_event_id%'),'payment webhook events are replay-safe');
select ok((select count(*)>=1 from pg_constraint where conrelid='public.payment_refunds'::regclass and contype='c' and pg_get_constraintdef(oid) like '%refund_amount_minor%'),'refund amount is exact and positive');

select ok((select count(*)>=12 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any(array['direct_client_provider_payments','matricia_own_revenue_payments','provider_commission_receipts','purchase_approvals','supplier_invoices','supplier_credit_notes','accounts_payable','outbound_payments','outbound_payment_allocations','vendor_bank_account_versions','bank_account_change_approvals','payment_refunds','payment_provider_events']) and t.tgname like '%_immutable' and not t.tgisinternal),'sensitive finance evidence is append-only');
select ok(not exists(select 1 from information_schema.role_table_grants where grantee='authenticated' and table_schema='public' and table_name=any(array['direct_client_provider_payments','matricia_own_revenue_payments','provider_commission_receipts','supplier_invoices','accounts_payable','outbound_payments','vendor_bank_account_versions','payment_refunds','payment_provider_events']) and privilege_type in('INSERT','UPDATE','DELETE')),'direct sensitive finance mutations remain denied');

select * from finish();
rollback;
