begin;
set local search_path=public,extensions;
select plan(16);
select has_table('public','admin_external_validation_cases','External validation cases exist');
select has_table('public','admin_external_validation_evidence_versions','Versioned evidence exists');
select has_table('public','admin_external_validation_decisions','Immutable decisions exist');
select has_function('public','submit_admin_external_validation_v41',array['text','text','text','text','text','date','date','text','text','jsonb','text','uuid'],'Submit command exists');
select has_function('public','decide_admin_external_validation_v41',array['uuid','text','text','text','integer','text','uuid'],'Decision command exists');
select has_function('public','list_admin_external_validations_v41',array['integer'],'Bounded dashboard query exists');
select ok(has_function_privilege('authenticated','public.list_admin_external_validations_v41(integer)','EXECUTE')and not has_function_privilege('anon','public.list_admin_external_validations_v41(integer)','EXECUTE'),'Dashboard is authenticated-only');
select ok(not has_table_privilege('authenticated','public.admin_external_validation_cases','INSERT')and not has_table_privilege('authenticated','public.admin_external_validation_cases','UPDATE'),'Direct case mutation is denied');
select ok((select relrowsecurity from pg_class where oid='public.admin_external_validation_cases'::regclass),'Cases use RLS');
select ok((select relrowsecurity from pg_class where oid='public.admin_external_validation_evidence_versions'::regclass),'Evidence uses RLS');
select ok((select relrowsecurity from pg_class where oid='public.admin_external_validation_decisions'::regclass),'Decisions use RLS');
select ok((select pg_get_functiondef(p.oid)like'%aal2%'and pg_get_functiondef(p.oid)like'%v41_json_has_sensitive_keys%'and pg_get_functiondef(p.oid)like'%begin_admin_command%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='submit_admin_external_validation_v41'),'Submission enforces AAL2 secret rejection and idempotency');
select ok((select pg_get_functiondef(p.oid)like'%a=x.submitted_by%'and pg_get_functiondef(p.oid)like'%STALE_EXTERNAL_VALIDATION%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='decide_admin_external_validation_v41'),'Decision enforces four-eyes and optimistic concurrency');
select ok((select pg_get_functiondef(p.oid)like'%audit_events%'and pg_get_functiondef(p.oid)like'%event_outbox%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='decide_admin_external_validation_v41'),'Decision is audited and emits Outbox');
select ok((select count(*)=2 from pg_trigger where not tgisinternal and tgname in('admin_external_validation_evidence_immutable','admin_external_validation_decisions_immutable')),'Evidence and decisions are immutable');
select ok((select pg_get_functiondef(p.oid)like'%PRODUCTION_AUTHORIZATION%'and pg_get_functiondef(p.oid)like'%SUPER_ADMIN%'from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private'and p.proname='can_manage_external_validation'),'Production authorization is SUPER_ADMIN-only');
select*from finish();
rollback;
