begin;set local search_path=public,extensions;select plan(26);
select has_table('public','social_publication_attempt_events','immutable attempt events exist');
select has_table('public','marketing_publication_quota_versions','provider organization quotas are versioned');
select has_column('public','social_publication_jobs','lease_token','jobs hold an unguessable lease token');
select has_column('public','social_publication_attempt_events','provider_request_key','attempt registry freezes the provider request key');
select has_index('public','social_publication_attempt_events','social_publication_attempt_events_provider_request_uidx','a provider request key can be claimed only once');
select ok(exists(select 1 from pg_constraint where conrelid='public.social_publication_jobs'::regclass and pg_get_constraintdef(oid)like'%RECONCILIATION_REQUIRED%'and pg_get_constraintdef(oid)like'%UNKNOWN%'),'job lifecycle models ambiguous timeouts');
select ok(exists(select 1 from pg_trigger where tgname='social_publication_attempt_events_immutable'and not tgisinternal),'attempt history is immutable');
select ok((select relrowsecurity from pg_class where oid='public.social_publication_attempt_events'::regclass),'attempt events use RLS');
select ok(not has_table_privilege('service_role','public.social_publication_attempt_events','INSERT'),'service role cannot bypass attempt RPCs');
select ok((select count(*)=2 from public.marketing_publication_quota_versions where organization_id is null and status='ACTIVE'),'both providers have safe initial quotas');
select has_function('public','record_social_publication_worker_result_v42',array['uuid','uuid','text','text','text','text','uuid'],'lease-bound result RPC exists');
select has_function('public','mark_timed_out_social_publication_attempts_v1',array['integer','uuid'],'timeout marker RPC exists');
select has_function('public','reconcile_social_publication_attempt_v1',array['uuid','uuid','text','text','text','jsonb','text','uuid'],'reconciliation RPC requires structured provider evidence');
select has_function('public','detect_marketing_calendar_shortages_v1',array['date','uuid'],'calendar shortage detector exists');
select ok((select count(*)from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname=any(array['record_social_publication_worker_result_v42','mark_timed_out_social_publication_attempts_v1','reconcile_social_publication_attempt_v1','detect_marketing_calendar_shortages_v1']))=4
  and not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname=any(array['record_social_publication_worker_result_v42','mark_timed_out_social_publication_attempts_v1','reconcile_social_publication_attempt_v1','detect_marketing_calendar_shortages_v1'])
    and(not has_function_privilege('service_role',p.oid,'EXECUTE')or has_function_privilege('authenticated',p.oid,'EXECUTE')or has_function_privilege('anon',p.oid,'EXECUTE'))),'all new worker RPCs are service-only');
select isnt_empty($$select 1 from pg_get_functiondef('public.claim_next_social_publication_job_v41(text,uuid)'::regprocedure)d where d like'%lease_token%'and d like'%provider_idempotency_key%'and d like'%marketing-quota:%''||j.organization_id::text||'':''||j.provider%'and d like'%evidence_snapshot_hash%'and d like'%SocialPublicationQuotaExhaustedV1%'$$,'claim snapshots proof and enforces stable-lock atomic auditable provider quota');
select isnt_empty($$select 1 from pg_get_functiondef('public.record_social_publication_worker_result_v42(uuid,uuid,text,text,text,text,uuid)'::regprocedure)d where d like'%MARKETING_RESULT_LEASE_INVALID%'and d like'%begin_marketing_worker_command%'$$,'results require live matching lease and hashed idempotency');
select isnt_empty($$select 1 from pg_get_functiondef('public.record_social_publication_worker_result_v42(uuid,uuid,text,text,text,text,uuid)'::regprocedure)d where d like'%p_error_code=''PROVIDER_HTTP_429''%'and d not like'%RATE_LIMITED%'and d not like'%PROVIDER_429%'and d like'%RECONCILIATION_REQUIRED%'and d like'%SocialPublicationReconciliationRequiredV1%'$$,'only the publisher contract code PROVIDER_HTTP_429 retries; ambiguous transport failures require reconciliation');
select isnt_empty($$select 1 from pg_get_functiondef('public.record_social_publication_worker_result_v41(uuid,text,text,text,text,uuid)'::regprocedure)d where d like'%LEASE_TOKEN_REQUIRED%'$$,'legacy result RPC fails closed');
select isnt_empty($$select 1 from pg_get_functiondef('public.mark_timed_out_social_publication_attempts_v1(integer,uuid)'::regprocedure)d where d like'%UNKNOWN%'and d like'%RECONCILIATION_REQUIRED%'and d like'%SocialPublicationReconciliationRequiredV1%'$$,'timeouts become unknown and require outboxed reconciliation');
select isnt_empty($$select 1 from pg_get_functiondef('public.reconcile_social_publication_attempt_v1(uuid,uuid,text,text,text,jsonb,text,uuid)'::regprocedure)d where d like'%MARKETING_RECONCILIATION_LEASE_INVALID%'and d like'%provider_state%''NOT_SENT''%'and d like'%STALE_MARKETING_RECONCILIATION_EVIDENCE%'and d like'%EVIDENCE_HASH_MISMATCH%'and d like'%SocialPublicationReconciledV1%'$$,'requeue requires fresh hash-bound provider-confirmed NOT_SENT evidence');
select isnt_empty($$select 1 from pg_get_functiondef('public.reconcile_social_publication_attempt_v1(uuid,uuid,text,text,text,jsonb,text,uuid)'::regprocedure)d where d like'%claim_evidence->>''authorization_evidence_hash''%'and d like'%claim_evidence->>''consent_evidence_hash''%'$$,'reconciled publication journals the original claim evidence rather than current history');
select isnt_empty($$select 1 from pg_get_functiondef('public.detect_marketing_calendar_shortages_v1(date,uuid)'::regprocedure)d where d like'%pg_advisory_xact_lock%'and d like'%CALENDAR_CONTENT_SHORTAGE%'$$,'shortage exception deduplication is transactionally serialized');
select ok((select count(*)=3 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('claim_social_publication_job_v41','record_social_publication_result_v41','record_social_publication_worker_result_v41')and p.prosrc like'%LEASE_TOKEN_REQUIRED%'),'all legacy publication mutation RPCs fail closed');
select ok(exists(select 1 from pg_constraint where conrelid='public.social_publication_attempt_events'::regclass and pg_get_constraintdef(oid)like'%300%')
  and exists(select 1 from pg_constraint where conrelid='public.social_publication_attempt_events'::regclass and pg_get_constraintdef(oid)like'%100%'),'provider identifiers and error codes are bounded');
select isnt_empty($$select 1 from pg_get_functiondef('public.detect_marketing_calendar_shortages_v1(date,uuid)'::regprocedure)d where d like'%CALENDAR_CONTENT_SHORTAGE%'and d like'%MarketingCalendarShortageDetectedV1%'$$,'calendar shortages create auditable exceptions');
select*from finish();rollback;
