import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({rpc:vi.fn(),deliver:vi.fn()}));
vi.mock("@/modules/shared/lib/supabase/admin",()=>({getSupabaseAdminClient:()=>({rpc:mocks.rpc})}));vi.mock("@/modules/shared/lib/notification-delivery/adapter",()=>({deliverNotification:mocks.deliver}));
vi.mock("node:crypto",async(importOriginal)=>{const original=await importOriginal<typeof import("node:crypto")>();return{...original,randomUUID:()=>"33333333-3333-4333-8333-333333333333"}});
import{POST}from"./route";
const secret="n".repeat(32),delivery="11111111-1111-4111-8111-111111111111",lease="22222222-2222-4222-8222-222222222222";
function req(query="",token=secret){return new Request(`http://localhost/api/workers/notifications${query}`,{method:"POST",headers:{authorization:`Bearer ${token}`}})}
describe("notification worker",()=>{beforeEach(()=>{vi.clearAllMocks();process.env.CRON_SECRET=secret});
 it("refuse un appel non autorisé",async()=>{expect((await POST(req("","bad"))).status).toBe(401);expect(mocks.rpc).not.toHaveBeenCalled()});
 it("réclame, revérifie la préférence et enregistre une livraison",async()=>{mocks.rpc.mockResolvedValueOnce({data:[{delivery_id:delivery,lease_token:lease,worker_id:"notifications-33333333-3333-4333-8333-333333333333",row_version:2,channel:"EMAIL",attempt:1,provider_idempotency_key:`notification-delivery:${delivery}`,recipient_email:"owner@example.com",locale:"fr-MA",subject:"Sujet",body:"Corps",cta_path:null}],error:null}).mockResolvedValueOnce({data:{authorized:true},error:null}).mockResolvedValueOnce({data:{status:"DELIVERED"},error:null});mocks.deliver.mockResolvedValue({outcome:"DELIVERED",providerMessageId:"msg-1",evidence:{adapter:"EMAIL_DEMO"}});const response=await POST(req("?limit=1"));expect(response.status).toBe(200);expect((await response.json()).delivered).toBe(1);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"authorize_notification_delivery_send_v1",expect.objectContaining({p_delivery_id:delivery,p_lease_token:lease}));expect(mocks.rpc).toHaveBeenLastCalledWith("record_notification_delivery_worker_result_v1",expect.objectContaining({p_delivery_id:delivery,p_lease_token:lease,p_outcome:"DELIVERED"}))});
 it("bloque un email si la préférence est retirée après le claim",async()=>{mocks.rpc.mockResolvedValueOnce({data:[{delivery_id:delivery,lease_token:lease,worker_id:"notifications-33333333-3333-4333-8333-333333333333",row_version:2,channel:"EMAIL",attempt:1,provider_idempotency_key:`notification-delivery:${delivery}`,recipient_email:"owner@example.com",locale:"fr-MA",subject:"Sujet",body:"Corps",cta_path:null}],error:null}).mockResolvedValueOnce({data:{authorized:false,outcome:"NOTIFICATION_SEND_BLOCKED"},error:null});const response=await POST(req("?limit=1"));expect(response.status).toBe(200);expect(await response.json()).toMatchObject({blockedByPreference:1,delivered:0});expect(mocks.deliver).not.toHaveBeenCalled()});
 it("échoue fermé sur claim invalide sans livrer",async()=>{mocks.rpc.mockResolvedValue({data:[{delivery_id:delivery}],error:null});const response=await POST(req("?limit=1"));expect(response.status).toBe(503);expect(await response.json()).toMatchObject({code:"NOTIFICATION_CLAIM_INVALID",summary:{reconciliationRequired:1}});expect(mocks.deliver).not.toHaveBeenCalled()});
 it("refuse un résultat SQL inconnu",async()=>{mocks.rpc.mockResolvedValueOnce({data:[{delivery_id:delivery,lease_token:lease,worker_id:"notifications-33333333-3333-4333-8333-333333333333",row_version:2,channel:"IN_APP",attempt:1,provider_idempotency_key:null,recipient_email:null,locale:"fr-MA",subject:"Sujet",body:"Corps",cta_path:null}],error:null}).mockResolvedValueOnce({data:{authorized:true},error:null}).mockResolvedValueOnce({data:{status:"UNKNOWN"},error:null});mocks.deliver.mockResolvedValue({outcome:"DELIVERED",providerMessageId:"in-app-1",evidence:{adapter:"IN_APP"}});const response=await POST(req("?limit=1"));expect(response.status).toBe(503);expect(await response.json()).toMatchObject({code:"NOTIFICATION_RESULT_INVALID",summary:{delivered:0,reconciliationRequired:1}})});
 it("retourne non-200 si la preuve SQL ne peut pas être enregistrée",async()=>{mocks.rpc.mockResolvedValueOnce({data:[{delivery_id:delivery,lease_token:lease,worker_id:"notifications-33333333-3333-4333-8333-333333333333",row_version:2,channel:"IN_APP",attempt:1,provider_idempotency_key:null,recipient_email:null,locale:"fr-MA",subject:"Sujet",body:"Corps",cta_path:null}],error:null}).mockResolvedValueOnce({data:{authorized:true},error:null}).mockResolvedValueOnce({data:null,error:{message:"write failed"}});mocks.deliver.mockResolvedValue({outcome:"DELIVERED",providerMessageId:"in-app-1",evidence:{adapter:"IN_APP"}});const response=await POST(req("?limit=1"));expect(response.status).toBe(503);expect(await response.text()).not.toContain("write failed")});
 it("masque les erreurs SQL",async()=>{mocks.rpc.mockResolvedValue({data:null,error:{message:"private recipient"}});const response=await POST(req());expect(response.status).toBe(503);expect(await response.text()).not.toContain("private recipient")});
});
