import type { Locale } from "@/lib/i18n/locale";
import type { QuestionnaireFailure } from "@/lib/questionnaire-sessions/contracts";
import type { z } from "zod";
import type { answerType, sessionStatus } from "@/lib/questionnaire-sessions/model";

const fr = {
  navigation: "Navigation des questionnaires", back: "Diagnostics", language: "العربية", eyebrow: "Espace Client", title: "Mes questionnaires", description: "Démarrez un questionnaire publié, reprenez vos réponses enregistrées et soumettez une version complète.",
  privacyTitle: "Enregistrement sécurisé", privacy: "Chaque réponse est validée par le serveur, isolée par organisation et enregistrée dans la version du questionnaire choisie. Les champs sensibles ne sont jamais affichés dans les messages techniques.",
  startTitle: "Démarrer un questionnaire", organization: "Organisation", questionnaire: "Questionnaire publié", version: "Version", dueAt: "Échéance", optional: "Facultatif", start: "Démarrer", starting: "Démarrage…", startSuccess: "La session est prête.", openSession: "Ouvrir la session",
  expiredAnswer: "Réponse expirée — confirmez-la à nouveau", revalidate: "Revalider cette réponse", revalidationSummary: "{count} réponse(s) expirée(s) nécessitent une confirmation légère avant soumission.",
  availableEmpty: "Aucun questionnaire Client publié n’est accessible à votre organisation.", sessionsTitle: "Sessions récentes", sessionsEmpty: "Aucune session enregistrée.", resume: "Reprendre", view: "Consulter", updated: "Mis à jour", submitted: "Soumis", progress: "Progression", answers: "réponses", currentSession: "Questionnaire en cours", noSelection: "Choisissez une session pour afficher ses questions.",
  required: "Obligatoire", saved: "Enregistrée", notSaved: "À renseigner", why: "Pourquoi cette question ?", clear: "Effacer cette réponse", save: "Enregistrer", saving: "Enregistrement…", autoSave: "Les modifications sont enregistrées automatiquement après une courte pause. Le bouton permet aussi un enregistrement immédiat.", amountMinor: "Montant en unités mineures", currency: "Devise ISO", startDate: "Date de début", endDate: "Date de fin", localDate: "Date locale", localTime: "Heure locale", timeZone: "Fuseau IANA", dstPolicy: "Gestion du changement d’heure", earlier: "Occurrence la plus tôt", later: "Occurrence la plus tard", reject: "Refuser une heure ambiguë", yes: "Oui", no: "Non", choose: "Choisir",
  chooseDocument: "Document privé existant", chooseDocuments: "Documents privés existants", chooseDocumentPlaceholder: "Choisir un document", noPrivateDocuments: "Aucun document privé téléversé compatible n’est disponible.", itemCount: "{count} élément(s) sélectionné(s)", itemNumber: "Élément {number}", itemBounds: "Minimum {min}, maximum {max}.", addItem: "Ajouter un élément", removeItem: "Retirer cet élément", invalidPublishedStructure: "La structure publiée est invalide. Cette réponse est bloquée par sécurité.", personName: "Nom complet", email: "Adresse e-mail", phone: "Téléphone", organizationName: "Raison sociale", organizationIdentifier: "Identifiant légal", productName: "Produit", quantity: "Quantité", siteName: "Site", address: "Adresse", milestoneTitle: "Jalon", milestoneDate: "Échéance", budgetLine: "Ligne budgétaire {number}", budgetLabel: "Libellé", addBudgetLine: "Ajouter une ligne budgétaire",
  submitTitle: "Soumettre le questionnaire", submitHelp: "La soumission fige un manifeste vérifiable des réponses. Elle est définitive pour cette session.", submit: "Soumettre", submitting: "Soumission…", submitSuccess: "Le questionnaire a été soumis.", alreadySubmitted: "Cette session est soumise et reste consultable en lecture seule.", progressName: "Progression du questionnaire : {percentage} %", terminalStates: { SUBMITTED: "Cette session a été soumise et reste consultable en lecture seule.", ABANDONED: "Cette session a été abandonnée et ne peut plus être modifiée.", EXPIRED: "Cette session a expiré et ne peut plus être modifiée." },
  validation: "Vérifiez la réponse et les champs indiqués.", conflict: "La session a changé. Actualisez la page avant de continuer.", forbidden: "Vous n’avez pas l’autorisation d’accéder à ce questionnaire.", unavailable: "L’opération n’a pas abouti. Réessayez sans exposer de données sensibles.", requiredMissing: "Certaines réponses obligatoires manquent encore.", notEditable: "Cette session n’est plus modifiable.", notSubmittable: "Cette session ne peut pas être soumise dans son état actuel.", bounds: "Ce questionnaire dépasse la limite de 100 questions par session Client.", loadError: "Impossible de charger les questionnaires.", retry: "Réessayer",
  emptyValue: "Aucune valeur",
  statuses: { DRAFT: "Brouillon", IN_PROGRESS: "En cours", READY: "Prêt", SUBMITTED: "Soumis", ABANDONED: "Abandonné", EXPIRED: "Expiré" },
  documentStatuses: { PENDING_REVIEW: "En vérification", VERIFIED: "Vérifié" },
  types: { YES_NO: "Oui / non", SINGLE_CHOICE: "Choix unique", MULTIPLE_CHOICE: "Choix multiples", SHORT_TEXT: "Texte court", LONG_TEXT: "Texte long", INTEGER: "Nombre entier", DECIMAL: "Nombre décimal", PERCENTAGE: "Pourcentage", MONEY: "Montant", CURRENCY: "Devise", DATE: "Date", DATE_RANGE: "Période", TIME: "Heure locale", EMAIL: "Adresse e-mail", PHONE: "Téléphone", URL: "Adresse web HTTPS", ADDRESS: "Adresse", GEO_AREA: "Zone géographique", RATING_5: "Note sur 5", RATING_10: "Note sur 10", QUANTITY: "Quantité", UNIT_VALUE: "Valeur unitaire", FILE: "Référence de fichier", MULTI_FILE: "Références de fichiers", IMAGE: "Référence d’image", TABLE: "Tableau structuré", REPEATER: "Liste structurée", CONTACT: "Contact structuré", ORGANIZATION: "Organisation structurée", PRODUCT_LIST: "Liste de produits", SITE_LIST: "Liste de sites", MILESTONE_LIST: "Liste de jalons", BUDGET_BREAKDOWN: "Ventilation budgétaire" },
} as const;

const ar = {
  ...fr,
  navigation: "التنقل في الاستبيانات", back: "التشخيصات", language: "Français", eyebrow: "فضاء العميل", title: "استبياناتي", description: "ابدأ استبياناً منشوراً، واستأنف إجاباتك المحفوظة، ثم أرسل نسخة مكتملة.",
  privacyTitle: "حفظ آمن", privacy: "يتحقق الخادم من كل إجابة ويعزلها حسب المؤسسة ويحفظها ضمن نسخة الاستبيان المختارة. لا تظهر الحقول الحساسة في الرسائل التقنية.",
  startTitle: "بدء استبيان", organization: "المؤسسة", questionnaire: "الاستبيان المنشور", version: "النسخة", dueAt: "تاريخ الاستحقاق", optional: "اختياري", start: "بدء", starting: "جارٍ البدء…", startSuccess: "الجلسة جاهزة.", openSession: "فتح الجلسة",
  expiredAnswer: "انتهت صلاحية الإجابة — أكدها من جديد", revalidate: "إعادة تأكيد هذه الإجابة", revalidationSummary: "تحتاج {count} إجابة منتهية إلى تأكيد بسيط قبل الإرسال.",
  availableEmpty: "لا يوجد استبيان عميل منشور متاح لمؤسستك.", sessionsTitle: "الجلسات الأخيرة", sessionsEmpty: "لا توجد جلسة محفوظة.", resume: "استئناف", view: "عرض", updated: "آخر تحديث", submitted: "تم الإرسال", progress: "التقدم", answers: "إجابات", currentSession: "الاستبيان الحالي", noSelection: "اختر جلسة لعرض أسئلتها.",
  required: "إلزامي", saved: "محفوظة", notSaved: "تحتاج إلى إجابة", why: "لماذا نطرح هذا السؤال؟", clear: "مسح هذه الإجابة", save: "حفظ", saving: "جارٍ الحفظ…", autoSave: "تُحفظ التعديلات تلقائياً بعد مهلة قصيرة. ويمكن استخدام الزر للحفظ فوراً.", amountMinor: "المبلغ بالوحدات الصغرى", currency: "رمز العملة ISO", startDate: "تاريخ البداية", endDate: "تاريخ النهاية", localDate: "التاريخ المحلي", localTime: "الوقت المحلي", timeZone: "المنطقة الزمنية IANA", dstPolicy: "معالجة تغيير التوقيت", earlier: "الوقوع الأبكر", later: "الوقوع الأحدث", reject: "رفض الوقت الملتبس", yes: "نعم", no: "لا", choose: "اختر",
  chooseDocument: "مستند خاص موجود", chooseDocuments: "مستندات خاصة موجودة", chooseDocumentPlaceholder: "اختر مستنداً", noPrivateDocuments: "لا يوجد مستند خاص مرفوع ومتوافق.", itemCount: "العناصر المحددة: {count}", itemNumber: "العنصر {number}", itemBounds: "الحد الأدنى {min} والحد الأقصى {max}.", addItem: "إضافة عنصر", removeItem: "إزالة هذا العنصر", invalidPublishedStructure: "البنية المنشورة غير صالحة. تم حظر الإجابة للحماية.", personName: "الاسم الكامل", email: "البريد الإلكتروني", phone: "الهاتف", organizationName: "اسم المؤسسة", organizationIdentifier: "المعرّف القانوني", productName: "المنتج", quantity: "الكمية", siteName: "الموقع", address: "العنوان", milestoneTitle: "المرحلة", milestoneDate: "الاستحقاق", budgetLine: "بند الميزانية {number}", budgetLabel: "البيان", addBudgetLine: "إضافة بند ميزانية",
  submitTitle: "إرسال الاستبيان", submitHelp: "يثبت الإرسال بياناً قابلاً للتحقق من الإجابات، وهو نهائي لهذه الجلسة.", submit: "إرسال", submitting: "جارٍ الإرسال…", submitSuccess: "تم إرسال الاستبيان.", alreadySubmitted: "تم إرسال هذه الجلسة وهي متاحة للقراءة فقط.", progressName: "تقدم الاستبيان: {percentage}٪", terminalStates: { SUBMITTED: "أُرسلت هذه الجلسة وتبقى متاحة للقراءة فقط.", ABANDONED: "تُركت هذه الجلسة ولا يمكن تعديلها.", EXPIRED: "انتهت صلاحية هذه الجلسة ولا يمكن تعديلها." },
  validation: "تحقق من الإجابة والحقول المحددة.", conflict: "تغيرت الجلسة. حدّث الصفحة قبل المتابعة.", forbidden: "ليست لديك صلاحية الوصول إلى هذا الاستبيان.", unavailable: "لم تنجح العملية. أعد المحاولة من دون كشف بيانات حساسة.", requiredMissing: "لا تزال بعض الإجابات الإلزامية ناقصة.", notEditable: "لم تعد هذه الجلسة قابلة للتعديل.", notSubmittable: "لا يمكن إرسال هذه الجلسة في حالتها الحالية.", bounds: "يتجاوز هذا الاستبيان حد 100 سؤال لكل جلسة عميل.", loadError: "تعذر تحميل الاستبيانات.", retry: "إعادة المحاولة",
  emptyValue: "لا توجد قيمة",
  statuses: { DRAFT: "مسودة", IN_PROGRESS: "قيد الإنجاز", READY: "جاهز", SUBMITTED: "مُرسل", ABANDONED: "متروك", EXPIRED: "منتهي" },
  documentStatuses: { PENDING_REVIEW: "قيد التحقق", VERIFIED: "موثّق" },
  types: { YES_NO: "نعم / لا", SINGLE_CHOICE: "اختيار واحد", MULTIPLE_CHOICE: "اختيارات متعددة", SHORT_TEXT: "نص قصير", LONG_TEXT: "نص طويل", INTEGER: "عدد صحيح", DECIMAL: "عدد عشري", PERCENTAGE: "نسبة مئوية", MONEY: "مبلغ", CURRENCY: "عملة", DATE: "تاريخ", DATE_RANGE: "فترة", TIME: "وقت محلي", EMAIL: "بريد إلكتروني", PHONE: "هاتف", URL: "رابط HTTPS", ADDRESS: "عنوان", GEO_AREA: "منطقة جغرافية", RATING_5: "تقييم من 5", RATING_10: "تقييم من 10", QUANTITY: "كمية", UNIT_VALUE: "قيمة الوحدة", FILE: "مرجع ملف", MULTI_FILE: "مراجع ملفات", IMAGE: "مرجع صورة", TABLE: "جدول منظم", REPEATER: "قائمة منظمة", CONTACT: "بيانات اتصال منظمة", ORGANIZATION: "مؤسسة منظمة", PRODUCT_LIST: "قائمة منتجات", SITE_LIST: "قائمة مواقع", MILESTONE_LIST: "قائمة مراحل", BUDGET_BREAKDOWN: "تفصيل الميزانية" },
} as const;

type Status = z.infer<typeof sessionStatus>; type Answer = z.infer<typeof answerType>;
export type QuestionnaireMessages = Omit<typeof fr, "statuses" | "types"> & { statuses: Record<Status, string>; types: Record<Answer, string> };
export function getQuestionnaireMessages(locale: Locale): QuestionnaireMessages { return (locale === "ar" ? ar : fr) as QuestionnaireMessages; }
export function failureMessage(messages: QuestionnaireMessages, reason: QuestionnaireFailure | "VALIDATION") { if (reason === "VALIDATION" || reason === "INVALID_INPUT" || reason === "INVALID_RESPONSE") return messages.validation; if (reason === "CONFLICT") return messages.conflict; if (reason === "FORBIDDEN") return messages.forbidden; if (reason === "REQUIRED_MISSING") return messages.requiredMissing; if (reason === "NOT_EDITABLE") return messages.notEditable; if (reason === "NOT_SUBMITTABLE") return messages.notSubmittable; if (reason === "BOUNDS_EXCEEDED") return messages.bounds; return messages.unavailable; }
