"use client";
import { useActionState,useState } from "react";
import { Button } from "@/modules/shared/ui/button";
import { Input } from "@/modules/shared/ui/input";
import { Textarea } from "@/modules/shared/ui/textarea";
import { formatMinorAmount,type DisputeDetail } from "@/modules/shared/lib/disputes/model";
import { activateAction,appealAction,approveAction,decideAction,idle,proposeAction,respondAction,type ActionState } from "./actions";
import { EvidenceFields } from "./evidence-fields";
import type { DisputeMessages } from "./messages";

function Hidden({locale,id,keyValue}:{locale:string;id:string;keyValue:string}){return <><input type="hidden" name="locale" value={locale}/><input type="hidden" name="caseId" value={id}/><input type="hidden" name="idempotencyKey" value={keyValue}/></>;}
function Feedback({s,m}:{s:ActionState;m:DisputeMessages}){return s.status==="idle"?null:<p role={s.status==="error"?"alert":"status"} className={s.status==="error"?"text-sm text-destructive":"text-sm text-primary"}>{s.status==="success"?m.success:s.reason==="VALIDATION"?m.validation:m.error}</p>;}
function Box({children}:{children:React.ReactNode}){return <div className="space-y-3 rounded-xl border bg-card p-4">{children}</div>;}

export function ActionPanel({locale,d,m,keys}:{locale:"fr"|"ar";d:DisputeDetail;m:DisputeMessages;keys:Record<string,string>}){
 const[response,respond,p1]=useActionState(respondAction,idle),[appeal,appealDo,p2]=useActionState(appealAction,idle),[decision,decide,p3]=useActionState(decideAction,idle),[proposal,propose,p4]=useActionState(proposeAction,idle),[approval,approve,p5]=useActionState(approveAction,idle),[activation,activate,p6]=useActionState(activateAction,idle);
 const[outcome,setOutcome]=useState<keyof typeof m.outcomes>("COMPLIANT"),hasActions=Object.values(d.capabilities).some(Boolean);
 return <div className="grid gap-4 lg:grid-cols-2">
  {!hasActions?<p className="rounded-xl border bg-card p-4 text-muted-foreground lg:col-span-2">{m.noAction}</p>:null}
  {d.capabilities.respond?<Box><form action={respond} className="space-y-3"><Hidden locale={locale} id={d.id} keyValue={keys.respond}/><label className="grid gap-1">{m.responseType}<select name="responseType" className="min-h-11 rounded-md border bg-background px-3">{Object.entries(m.responseTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1">{m.reason}<Textarea name="reason" minLength={10} required/></label><EvidenceFields m={m}/><Button disabled={p1} className="min-h-11 w-full">{m.respond}</Button><Feedback s={response} m={m}/></form></Box>:null}
  {d.capabilities.appeal?<Box><form action={appealDo} className="space-y-3"><Hidden locale={locale} id={d.id} keyValue={keys.appeal}/><label className="grid gap-1">{m.reason}<Textarea name="reason" minLength={10} required/></label><EvidenceFields m={m}/><Button disabled={p2} className="min-h-11 w-full">{m.appeal}</Button><Feedback s={appeal} m={m}/></form></Box>:null}
  {d.capabilities.decide?<Box><form action={decide} className="space-y-3"><Hidden locale={locale} id={d.id} keyValue={keys.decide}/><label className="grid gap-1">{m.outcome}<select name="outcome" value={outcome} onChange={event=>setOutcome(event.target.value as keyof typeof m.outcomes)} className="min-h-11 rounded-md border bg-background px-3">{Object.entries(m.outcomes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1">{m.reason}<Textarea name="reason" minLength={10} required/></label><fieldset className="space-y-2 rounded-lg border p-3"><legend className="px-1 font-medium">{m.evidenceIds}</legend>{d.evidence.length===0?<p className="text-sm text-destructive">{m.selectEvidence}</p>:d.evidence.map(item=><label key={item.id} className="flex min-h-11 items-start gap-3 rounded-md border p-3"><input type="checkbox" name="evidenceIds" value={item.id} className="mt-1 size-4"/><span className="min-w-0"><strong>{item.type}</strong><span className="block break-words text-sm text-muted-foreground">{item.statement??item.url}</span></span></label>)}</fieldset><label className="grid gap-1">{m.ruleVersion}<Input name="ruleVersion" required/></label><label className="grid gap-1">{m.ruleHash}<Input name="ruleHash" pattern="[0-9a-f]{64}" dir="ltr" required/></label>{outcome==="NON_COMPLIANT_CONFIRMED"?<><label className="grid gap-1">{m.penalty}<Input name="penalty" inputMode="decimal" dir="ltr" required/></label><label className="grid gap-1">{m.commission}<Input name="commission" inputMode="decimal" dir="ltr" required/></label></>:null}<Button disabled={p3||d.evidence.length===0} className="min-h-11 w-full">{m.decide}</Button><Feedback s={decision} m={m}/></form></Box>:null}
  {d.capabilities.propose&&d.reassignment?<Box><form action={propose} className="space-y-3"><Hidden locale={locale} id={d.id} keyValue={keys.propose}/><input type="hidden" name="reassignmentId" value={d.reassignment.id}/><input type="hidden" name="rowVersion" value={d.reassignment.rowVersion}/><p>{m.originalCost}: <strong dir="ltr">{formatMinorAmount(d.reassignment.originalCostMinor,d.reassignment.currency,locale)}</strong></p><label className="grid gap-1">{m.provider}<select name="providerId" className="min-h-11 rounded-md border bg-background px-3" required>{d.candidates.map(candidate=><option key={candidate.organizationId} value={candidate.organizationId}>{candidate.displayName} — {candidate.qualificationStatus} / {candidate.capacityStatus}</option>)}</select></label><label className="grid gap-1">{m.pricing}<select name="pricing" className="min-h-11 rounded-md border bg-background px-3"><option value="FRAMEWORK_RATE">FRAMEWORK_RATE</option><option value="NEW_QUOTE">NEW_QUOTE</option></select></label><label className="grid gap-1">{m.quoteVersion}<Input name="quoteVersion" dir="ltr"/></label><label className="grid gap-1">{m.proposedCost}<Input name="cost" inputMode="decimal" dir="ltr" required/></label><Button disabled={p4||d.candidates.length===0} className="min-h-11 w-full">{m.propose}</Button><Feedback s={proposal} m={m}/></form></Box>:null}
  {d.capabilities.approve&&d.reassignment?<Box><form action={approve} className="space-y-3"><Hidden locale={locale} id={d.id} keyValue={keys.approve}/><input type="hidden" name="reassignmentId" value={d.reassignment.id}/><input type="hidden" name="rowVersion" value={d.reassignment.rowVersion}/><p>{m.proposedCost}: <strong dir="ltr">{formatMinorAmount(d.reassignment.proposedCostMinor??"0",d.reassignment.currency,locale)}</strong></p><p>{m.costDelta}: <strong dir="ltr">{formatMinorAmount(d.reassignment.costDeltaMinor??"0",d.reassignment.currency,locale)}</strong></p><Button disabled={p5} className="min-h-11 w-full">{m.approve}</Button><Feedback s={approval} m={m}/></form></Box>:null}
  {d.capabilities.activate&&d.reassignment?<Box><form action={activate} className="space-y-3"><Hidden locale={locale} id={d.id} keyValue={keys.activate}/><input type="hidden" name="reassignmentId" value={d.reassignment.id}/><input type="hidden" name="rowVersion" value={d.reassignment.rowVersion}/><label className="grid gap-1">{m.replacementContract}<Input name="replacementContract" dir="ltr" required/></label><label className="grid gap-1">{m.replacementMission}<Input name="replacementMission" dir="ltr" required/></label><Button disabled={p6} className="min-h-11 w-full">{m.activate}</Button><Feedback s={activation} m={m}/></form></Box>:null}
 </div>;
}
