import { z } from "zod";
import type { ClientRfqRepository, Result } from "./contracts";
import { hashSchema, quoteStatusSchema, requestStatusSchema, uuidSchema } from "./model";

type QueryResponse = { data: unknown; error: { code?: string } | null };
export type ClientRfqDependencies = {
  userId(): Promise<string | null>; memberships(userId: string): Promise<QueryResponse>; roles(membershipIds: string[]): Promise<QueryResponse>;
  organizations(ids: string[]): Promise<QueryResponse>; requests(organizationIds: string[], requestId?: string): Promise<QueryResponse>;
  versions(requestIds: string[]): Promise<QueryResponse>; matchingRuns(requestIds: string[]): Promise<QueryResponse>; rfqs(requestIds: string[]): Promise<QueryResponse>; quotes(rfqIds: string[]): Promise<QueryResponse>; comparisons(rfqId: string): Promise<QueryResponse>;
  rpc(name: string, input: Record<string, unknown>): Promise<QueryResponse>;
};
const membershipRow=z.object({id:uuidSchema,organization_id:uuidSchema}).strict();
const roleRow=z.object({membership_id:uuidSchema,role_code:z.enum(["CLIENT_OWNER","CLIENT_ADMIN","CLIENT_BUYER","CLIENT_VIEWER"]),revoked_at:z.string().nullable()}).strict();
const organizationRow=z.object({id:uuidSchema,display_name:z.string().min(1).max(200)}).strict();
const exactMinor=z.union([z.string().regex(/^\d+$/u),z.number().int().nonnegative().safe()]).transform(String);
const requestRow=z.object({id:uuidSchema,client_organization_id:uuidSchema,library_id:uuidSchema,service_id:uuidSchema,current_version_id:uuidSchema.nullable(),status:requestStatusSchema,created_at:z.string(),row_version:z.number().int().positive()}).strict();
const versionRow=z.object({id:uuidSchema,request_id:uuidSchema,description:z.string(),urgency:z.enum(["LOW","NORMAL","HIGH","CRITICAL"]),desired_date:z.string().nullable(),budget_minor:exactMinor.nullable(),currency_code:z.string().regex(/^[A-Z]{3}$/u)}).strict();
const rfqRow=z.object({id:uuidSchema,request_id:uuidSchema,deadline:z.string(),status:z.enum(["OPEN","CLOSED","CANCELLED","EXPIRED"])}).strict();
const matchingRow=z.object({id:uuidSchema,request_id:uuidSchema,status:z.enum(["RUNNING","COMPLETED","NO_CANDIDATE","FAILED"])}).strict();
const quoteRow=z.object({id:uuidSchema,rfq_id:uuidSchema,status:quoteStatusSchema}).strict();
const created=z.object({outcome:z.literal("SERVICE_REQUEST_CREATED"),request_id:uuidSchema,status:requestStatusSchema}).passthrough();
const ready=z.object({outcome:z.literal("SERVICE_REQUEST_READY"),request_id:uuidSchema,row_version:z.number().int().positive()}).passthrough();
const matched=z.object({outcome:z.enum(["MATCHING_COMPLETED","NO_MATCHING_PROVIDER"]),request_id:uuidSchema,matching_run_id:uuidSchema,eligible_count:z.number().int().nonnegative()}).passthrough();
const opened=z.object({outcome:z.literal("RFQ_OPENED"),request_id:uuidSchema,rfq_id:uuidSchema,invited_count:z.number().int().nonnegative()}).passthrough();
const comparisonRow=z.object({quote_id:uuidSchema,quote_version_id:uuidSchema,provider_organization_id:uuidSchema,version_number:z.number().int().positive(),currency:z.string().regex(/^[A-Z]{3}$/u),subtotal_minor:exactMinor,tax_minor:exactMinor,total_minor:exactMinor,recurring_subtotal_minor:exactMinor,duration_days:z.number().int().positive(),deliverables_count:z.number().int().nonnegative(),valid_until:z.string(),price_rank:z.number().int().positive(),explanation:z.array(z.string()).max(6)}).strict();
const comparisonSnapshotRow=z.object({id:uuidSchema,rfq_id:uuidSchema,normalization_version:z.string().regex(/^[A-Z0-9][A-Z0-9._-]{1,31}$/u),currency:z.string().regex(/^[A-Z]{3}$/u),comparison:z.object({criteria:z.array(z.string()).min(1).max(20),tax_basis:z.string(),rows:z.array(comparisonRow).min(1).max(100)}).strict(),created_at:z.string()}).strict();
const compared=z.object({outcome:z.literal("QUOTE_COMPARISON_CREATED"),comparison_snapshot_id:uuidSchema,currency:z.string().regex(/^[A-Z]{3}$/u),rows:z.array(comparisonRow).min(1).max(100)}).passthrough();
const selected=z.object({outcome:z.literal("QUOTE_SELECTED"),quote_id:uuidSchema,quote_version_id:uuidSchema,rfq_id:uuidSchema}).passthrough();
function fail(error:{code?:string}|null):Result<never>{return{status:"error",reason:error?.code==="42501"?"FORBIDDEN":"UNAVAILABLE"};}

export function createClientRfqRepository(d:ClientRfqDependencies):ClientRfqRepository{
 async function context(requestId?:string):Promise<Result<{organizations:{id:string;name:string}[];requests:import("./model").ClientRequestSummary[]}>>{
  const user=await d.userId();if(!user)return{status:"error",reason:"UNAUTHENTICATED"};
  const mr=await d.memberships(user);if(mr.error)return fail(mr.error);const memberships=z.array(membershipRow).max(100).safeParse(mr.data);if(!memberships.success)return{status:"error",reason:"INVALID_RESPONSE"};
  const rr=await d.roles(memberships.data.map(x=>x.id));if(rr.error)return fail(rr.error);const roles=z.array(roleRow).max(300).safeParse(rr.data);if(!roles.success)return{status:"error",reason:"INVALID_RESPONSE"};const readable=new Set(roles.data.filter(x=>x.revoked_at===null).map(x=>x.membership_id));const writable=new Set(roles.data.filter(x=>x.revoked_at===null&&x.role_code!=="CLIENT_VIEWER").map(x=>x.membership_id));const orgByMembership=new Map(memberships.data.map(x=>[x.id,x.organization_id]));const orgIds=memberships.data.filter(x=>readable.has(x.id)).map(x=>x.organization_id);const writableOrgIds=new Set([...writable].map(id=>orgByMembership.get(id)).filter((id):id is string=>Boolean(id)));
  const [or,qr]=await Promise.all([d.organizations([...writableOrgIds]),d.requests(orgIds,requestId)]);if(or.error||qr.error)return fail(or.error??qr.error);const orgs=z.array(organizationRow).max(100).safeParse(or.data);const requests=z.array(requestRow).max(500).safeParse(qr.data);if(!orgs.success||!requests.success)return{status:"error",reason:"INVALID_RESPONSE"};
  const ids=requests.data.map(x=>x.id);const [vr,mxr,rfr]=await Promise.all([d.versions(ids),d.matchingRuns(ids),d.rfqs(ids)]);if(vr.error||mxr.error||rfr.error)return fail(vr.error??mxr.error??rfr.error);const versions=z.array(versionRow).max(500).safeParse(vr.data);const matches=z.array(matchingRow).max(500).safeParse(mxr.data);const rfqs=z.array(rfqRow).max(500).safeParse(rfr.data);if(!versions.success||!matches.success||!rfqs.success)return{status:"error",reason:"INVALID_RESPONSE"};const versionById=new Map(versions.data.map(x=>[x.id,x]));const matchByRequest=new Map<string,z.infer<typeof matchingRow>>();for(const x of matches.data)if(!matchByRequest.has(x.request_id))matchByRequest.set(x.request_id,x);const rfqByRequest=new Map<string,z.infer<typeof rfqRow>>();for(const x of rfqs.data)if(!rfqByRequest.has(x.request_id))rfqByRequest.set(x.request_id,x);const qtr=await d.quotes(rfqs.data.map(x=>x.id));if(qtr.error)return fail(qtr.error);const quotes=z.array(quoteRow).max(2000).safeParse(qtr.data);if(!quotes.success)return{status:"error",reason:"INVALID_RESPONSE"};
  const summaries=requests.data.flatMap(q=>{const v=q.current_version_id?versionById.get(q.current_version_id):undefined;if(!v)return[];const rfq=rfqByRequest.get(q.id);const match=matchByRequest.get(q.id);return[{id:q.id,organizationId:q.client_organization_id,libraryId:q.library_id,serviceId:q.service_id,status:q.status,canManage:writableOrgIds.has(q.client_organization_id),rowVersion:q.row_version,description:v.description,urgency:v.urgency,desiredDate:v.desired_date,budgetMinor:v.budget_minor===null?null:String(v.budget_minor),currency:v.currency_code,createdAt:q.created_at,matchingRunId:match?.id??null,eligibleCount:match?.status==="NO_CANDIDATE"?0:null,rfqId:rfq?.id??null,rfqDeadline:rfq?.deadline??null,quoteCount:rfq?quotes.data.filter(x=>x.rfq_id===rfq.id&&["SUBMITTED","REVISED","SELECTED"].includes(x.status)).length:0}]});
  return{status:"success",value:{organizations:orgs.data.map(x=>({id:x.id,name:x.display_name})),requests:summaries}};
 }
 return{
  list:()=>context(),async detail(id){if(!uuidSchema.safeParse(id).success)return{status:"error",reason:"INVALID_INPUT"};const r=await context(id);return r.status==="error"?r:{status:"success",value:r.value.requests[0]??null};},
  async comparison(rfqId){if(!uuidSchema.safeParse(rfqId).success)return{status:"error",reason:"INVALID_INPUT"};if(!await d.userId())return{status:"error",reason:"UNAUTHENTICATED"};const response=await d.comparisons(rfqId);if(response.error)return fail(response.error);const parsed=z.array(comparisonSnapshotRow).max(1).safeParse(response.data);if(!parsed.success)return{status:"error",reason:"INVALID_RESPONSE"};const snapshot=parsed.data[0];if(!snapshot)return{status:"success",value:null};return{status:"success",value:{snapshotId:snapshot.id,rfqId:snapshot.rfq_id,normalizationVersion:snapshot.normalization_version,currency:snapshot.currency,rows:snapshot.comparison.rows.map(x=>({quoteId:x.quote_id,quoteVersionId:x.quote_version_id,versionNumber:x.version_number,currency:x.currency,subtotalMinor:String(x.subtotal_minor),taxMinor:String(x.tax_minor),totalMinor:String(x.total_minor),recurringSubtotalMinor:String(x.recurring_subtotal_minor),durationDays:x.duration_days,deliverablesCount:x.deliverables_count,validUntil:x.valid_until,priceRank:x.price_rank})),createdAt:snapshot.created_at}};},
  async create(i){if(![i.organizationId,i.libraryId,i.serviceId,i.questionnaireVersionId,i.idempotencyKey,i.correlationId].every(x=>uuidSchema.safeParse(x).success)||![i.catalogSnapshotHash,i.questionnaireSnapshotHash].every(x=>hashSchema.safeParse(x).success))return{status:"error",reason:"INVALID_INPUT"};const r=await d.rpc("create_service_request",{p_client_organization_id:i.organizationId,p_library_id:i.libraryId,p_service_id:i.serviceId,p_questionnaire_version_id:i.questionnaireVersionId,p_payload:{description:i.description,urgency:i.urgency,desired_date:i.desiredDate,budget_minor:i.budgetMinor,currency_code:i.currency,required_quote_data:{region_code:i.regionCode},required_fields_complete:true,catalog_snapshot_hash:i.catalogSnapshotHash,questionnaire_snapshot_hash:i.questionnaireSnapshotHash},p_change_reason:i.changeReason,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(r.error)return fail(r.error);const p=created.safeParse(r.data);return p.success?{status:"success",value:{requestId:p.data.request_id,status:p.data.status}}:{status:"error",reason:"INVALID_RESPONSE"};},
  async ready(i){const r=await d.rpc("mark_service_request_ready",{p_request_id:i.requestId,p_expected_row_version:i.rowVersion,p_change_reason:i.reason,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(r.error)return fail(r.error);const p=ready.safeParse(r.data);return p.success&&p.data.request_id===i.requestId?{status:"success",value:{requestId:p.data.request_id,rowVersion:p.data.row_version}}:{status:"error",reason:"INVALID_RESPONSE"};},
  async match(i){const r=await d.rpc("run_service_request_matching",{p_request_id:i.requestId,p_policy_version:"MATCH-V1",p_target_panel_size:i.targetPanelSize,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(r.error)return fail(r.error);const p=matched.safeParse(r.data);return p.success?{status:"success",value:{requestId:p.data.request_id,matchingRunId:p.data.matching_run_id,eligibleCount:p.data.eligible_count,outcome:p.data.outcome}}:{status:"error",reason:"INVALID_RESPONSE"};},
  async openRfq(i){const r=await d.rpc("open_service_request_rfq",{p_request_id:i.requestId,p_matching_run_id:i.matchingRunId,p_deadline:i.deadline,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(r.error)return fail(r.error);const p=opened.safeParse(r.data);return p.success?{status:"success",value:{requestId:p.data.request_id,rfqId:p.data.rfq_id,invitedCount:p.data.invited_count}}:{status:"error",reason:"INVALID_RESPONSE"};},
  async compare(i){const r=await d.rpc("compare_quotes",{p_rfq_id:i.rfqId,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(r.error)return fail(r.error);const p=compared.safeParse(r.data);return p.success?{status:"success",value:{snapshotId:p.data.comparison_snapshot_id,currency:p.data.currency,rows:p.data.rows.map(x=>({quoteId:x.quote_id,quoteVersionId:x.quote_version_id,versionNumber:x.version_number,currency:x.currency,subtotalMinor:String(x.subtotal_minor),taxMinor:String(x.tax_minor),totalMinor:String(x.total_minor),recurringSubtotalMinor:String(x.recurring_subtotal_minor),durationDays:x.duration_days,deliverablesCount:x.deliverables_count,validUntil:x.valid_until,priceRank:x.price_rank}))}}:{status:"error",reason:"INVALID_RESPONSE"};},
  async select(i){const r=await d.rpc("select_quote",{p_quote_id:i.quoteId,p_expected_version_id:i.quoteVersionId,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(r.error)return fail(r.error);const p=selected.safeParse(r.data);return p.success&&p.data.quote_version_id===i.quoteVersionId?{status:"success",value:{quoteId:p.data.quote_id,rfqId:p.data.rfq_id}}:{status:"error",reason:"INVALID_RESPONSE"};}
 };
}
