"use client";
import { useActionState, useId } from "react";
import { Alert, AlertDescription } from "@/modules/shared/ui/alert";
import { Badge } from "@/modules/shared/ui/badge";
import { Button } from "@/modules/shared/ui/button";
import { Input } from "@/modules/shared/ui/input";
import { Label } from "@/modules/shared/ui/label";
import { Textarea } from "@/modules/shared/ui/textarea";
import type { AdminClientCase, AdminClientDocument, AdminClientQuestion, AdminClientsDashboard } from "@/modules/admin/data/clients/model";
import type { Locale } from "@/modules/shared/lib/i18n/locale";
import { decideCompliance, reviewComplianceDocument, reviewComplianceResponse, type AdminClientActionState } from "./actions";
import type { AdminClientMessages } from "./messages";
const idle: AdminClientActionState = { status: "idle" }; const selectClass="min-h-11 w-full rounded-md border bg-background px-3 text-sm shadow-xs outline-none focus-visible:ring-2 focus-visible:ring-ring";
function Feedback({state,m}:{state:AdminClientActionState;m:AdminClientMessages}){const value=state.status==="success"?m.success:state.status==="error"?m[state.reason==="VALIDATION"?"validation":state.reason==="FOUR_EYES"?"fourEyes":state.reason==="MFA_REQUIRED"?"mfaAction":state.reason==="FORBIDDEN"||state.reason==="UNAUTHENTICATED"?"forbidden":state.reason==="CONFLICT"?"conflict":"failed"]:"";return <p role={state.status==="error"?"alert":"status"} aria-live="polite" className={state.status==="error"?"min-h-5 text-sm text-destructive":"min-h-5 text-sm text-primary"}>{value}</p>}
function Hidden({name,value}:{name:string;value:string}){return <input type="hidden" name={name} value={value}/>}
function Field({id,label,children}:{id:string;label:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
function DecisionForm({item,locale,m,keyValue}:{item:AdminClientCase;locale:Locale;m:AdminClientMessages;keyValue:string}){const id=useId(),[state,action,pending]=useActionState(decideCompliance,idle);return <form action={action} className="mt-4 grid gap-4 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2"><Hidden name="caseId" value={item.id}/><Hidden name="locale" value={locale}/><Hidden name="idempotencyKey" value={keyValue}/><Field id={`${id}-decision`} label={m.decision}><select id={`${id}-decision`} name="decision" className={selectClass}><option value="VERIFIED">VERIFIED</option><option value="QUESTION_REQUIRED">QUESTION REQUIRED</option><option value="REJECTED">REJECTED</option></select></Field><Field id={`${id}-reason`} label={m.publicReason}><Textarea id={`${id}-reason`} name="publicReason" maxLength={1000}/></Field><label className="flex min-h-11 items-center gap-3 sm:col-span-2"><input type="checkbox" name="confirmed" value="yes" required className="size-4"/><span className="text-sm">{m.confirm}</span></label><div className="sm:col-span-2"><Button disabled={pending} className="min-h-11">{pending?m.processing:m.submit}</Button><Feedback state={state} m={m}/></div></form>}
function DocumentReview({item,locale,m,keyValue}:{item:AdminClientDocument;locale:Locale;m:AdminClientMessages;keyValue:string}){const id=useId(),[state,action,pending]=useActionState(reviewComplianceDocument,idle);return <form action={action} className="mt-4 grid gap-4 border-t pt-4 sm:grid-cols-2"><Hidden name="documentId" value={item.id}/><Hidden name="locale" value={locale}/><Hidden name="idempotencyKey" value={keyValue}/><Field id={`${id}-decision`} label={m.decision}><select id={`${id}-decision`} name="decision" className={selectClass}><option value="VERIFIED">VERIFIED</option><option value="REJECTED">REJECTED</option><option value="QUARANTINED">QUARANTINED</option></select></Field><Field id={`${id}-hash`} label={m.verifiedHash}><Input id={`${id}-hash`} name="verifiedSha256" autoComplete="off" maxLength={64}/></Field><Field id={`${id}-public`} label={m.publicReason}><Textarea id={`${id}-public`} name="publicReason"/></Field><Field id={`${id}-internal`} label={m.internalReason}><Textarea id={`${id}-internal`} name="internalReason"/></Field><Button disabled={pending} className="min-h-11">{pending?m.processing:m.submit}</Button><Feedback state={state} m={m}/></form>}
function ResponseReview({item,locale,m,keyValue}:{item:AdminClientQuestion;locale:Locale;m:AdminClientMessages;keyValue:string}){const id=useId(),[state,action,pending]=useActionState(reviewComplianceResponse,idle);return <form action={action} className="mt-4 flex flex-wrap items-end gap-3 border-t pt-4"><Hidden name="questionId" value={item.id}/><Hidden name="locale" value={locale}/><Hidden name="idempotencyKey" value={keyValue}/><Field id={`${id}-accepted`} label={m.decision}><select id={`${id}-accepted`} name="accepted" className={selectClass}><option value="yes">{m.accept}</option><option value="no">{m.reject}</option></select></Field><Button disabled={pending} className="min-h-11">{pending?m.processing:m.submit}</Button><Feedback state={state} m={m}/></form>}
function CaseCard({item,locale,m,keys}:{item:AdminClientCase;locale:Locale;m:AdminClientMessages;keys:Record<string,string>}){return <article className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{item.organizationName}</h2><p className="mt-1 text-sm text-muted-foreground">{m.profileVersion} : {item.profileVersion??"—"}</p></div><Badge variant="outline">{item.status.replaceAll("_"," ")}</Badge></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">{m.submitted}</dt><dd>{item.submittedAt??"—"}</dd></div><div><dt className="text-muted-foreground">{m.updated}</dt><dd>{item.updatedAt}</dd></div></dl>{item.publicReason?<p className="mt-4 rounded-lg bg-muted p-3 text-sm">{item.publicReason}</p>:null}<section className="mt-6"><h3 className="text-lg font-semibold">{m.documents}</h3>{item.documents.length?<div className="mt-3 grid gap-3">{item.documents.map(document=><article key={document.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-medium">{document.type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">{m.version} {document.version} · {m.scan} {document.scanStatus} · {m.expires} {document.expiresOn??m.noExpiry}</p></div><Badge variant="secondary">{document.status.replaceAll("_"," ")}</Badge></div>{document.status==="PENDING_REVIEW"?(document.canReview?<DocumentReview item={document} locale={locale} m={m} keyValue={keys[`document:${document.id}`]!}/>:<p className="mt-3 text-sm text-muted-foreground">{m.fourEyesBlocked}</p>):null}</article>)}</div>:<p className="mt-2 text-sm text-muted-foreground">{m.noDocuments}</p>}</section><section className="mt-6 border-t pt-6"><h3 className="text-lg font-semibold">{m.questions}</h3>{item.questions.length?<div className="mt-3 grid gap-3">{item.questions.map(question=><article key={question.id} className="rounded-xl border p-4"><div className="flex justify-between gap-2"><p className="font-medium">{question.text}</p><Badge variant="outline">{question.status}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{question.responseVersion ? `${m.response} · v${question.responseVersion} · ${question.responseSubmittedAt ?? "—"}` : m.noResponse}</p>{question.status==="ANSWERED"?(question.canReview?<ResponseReview item={question} locale={locale} m={m} keyValue={keys[`response:${question.id}`]!}/>:<p className="mt-3 text-sm text-muted-foreground">{m.fourEyesBlocked}</p>):null}</article>)}</div>:<p className="mt-2 text-sm text-muted-foreground">{m.noQuestions}</p>}</section>{["UNDER_REVIEW","RESPONSE_RECEIVED"].includes(item.status)?item.canDecide?<DecisionForm item={item} locale={locale} m={m} keyValue={keys[`case:${item.id}`]!}/>:<p className="mt-5 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">{m.fourEyesBlocked}</p>:null}</article>}
export function ClientsPanel({dashboard,locale,m,keys}:{dashboard:AdminClientsDashboard;locale:Locale;m:AdminClientMessages;keys:Record<string,string>}){return <div className="space-y-5">{dashboard.limitsReached.length?<Alert><AlertDescription>{m.limited}</AlertDescription></Alert>:null}{dashboard.capabilities.readOnly?<Alert><AlertDescription>{m.readOnly}</AlertDescription></Alert>:null}{dashboard.cases.length?<div className="grid gap-5">{dashboard.cases.map(item=><CaseCard key={item.id} item={item} locale={locale} m={m} keys={keys}/>)}</div>:<p className="rounded-xl border bg-card p-5 text-muted-foreground">{m.empty}</p>}</div>}
