import { timingSafeEqual } from "node:crypto";
import { z } from "zod";
import { getSupabaseAdminClient } from "@/modules/shared/lib/supabase/admin";

export const dynamic="force-dynamic";
const headers={"cache-control":"no-store"} as const;
const metadataSchema=z.object({utm_campaign:z.string().max(200).optional(),utm_source:z.string().max(80).optional(),utm_medium:z.string().max(80).optional(),utm_content:z.string().max(200).optional(),landing_path:z.string().max(500).optional(),referrer_host:z.string().max(253).optional()}).strict();
const bodySchema=z.object({organizationId:z.string().uuid(),campaignId:z.string().uuid(),contentId:z.string().uuid().nullable().optional(),eventType:z.enum(["CONTENT_VIEWED","CTA_CLICKED","LANDING_VIEWED","REGISTRATION_STARTED","DIAGNOSTIC_STARTED","OPPORTUNITY_CREATED","RFQ_STARTED","CONTRACT_SIGNED"]),source:z.string().trim().min(2).max(80),medium:z.string().trim().min(2).max(80),visitorHash:z.string().regex(/^[0-9a-f]{64}$/),economicValueMinor:z.string().regex(/^\d+$/).nullable().optional(),occurredAt:z.string().datetime({offset:true}),metadata:metadataSchema.default({}),idempotencyKey:z.string().uuid()}).strict();
function authorized(request:Request){const expected=process.env.CRON_SECRET??"",supplied=request.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1]??"";const a=Buffer.from(expected),b=Buffer.from(supplied);return a.length>=32&&a.length===b.length&&timingSafeEqual(a,b)}
export async function POST(request:Request){if(!authorized(request))return Response.json({code:"UNAUTHORIZED"},{status:401,headers});let raw:unknown;try{raw=await request.json()}catch{return Response.json({code:"INVALID_REQUEST"},{status:400,headers})}const parsed=bodySchema.safeParse(raw);if(!parsed.success)return Response.json({code:"INVALID_REQUEST"},{status:400,headers});const p=parsed.data,result=await getSupabaseAdminClient().rpc("ingest_marketing_attribution_event_v1",{p_organization_id:p.organizationId,p_campaign_id:p.campaignId,p_content_id:p.contentId??null,p_event_type:p.eventType,p_source:p.source,p_medium:p.medium,p_visitor_hash:p.visitorHash,p_economic_value_minor:p.economicValueMinor??null,p_occurred_at:p.occurredAt,p_metadata:p.metadata,p_idempotency_key:p.idempotencyKey});if(result.error)return Response.json({code:"INGEST_FAILED"},{status:503,headers});return Response.json(result.data,{headers});}
