import { z } from "zod";
import type { DisputesRepository,Result } from "./contracts";
import { evidenceTypeSchema,outcomeSchema,statusSchema,uuidSchema,visibilitySchema,type DisputeCapabilities,type DisputeSummary } from "./model";

type Query={data:unknown;error:unknown};
export type DisputeSource={userId():Promise<string|null>;memberships(id:string):Promise<Query>;orgRoles(ids:string[]):Promise<Query>;platformRoles(id:string):Promise<Query>;missions():Promise<Query>;cases(id?:string):Promise<Query>;evidence(ids:string[]):Promise<Query>;responses?(ids:string[]):Promise<Query>;decisions?(ids:string[]):Promise<Query>;appeals?(ids:string[]):Promise<Query>;events(ids:string[]):Promise<Query>;reassignments(ids:string[]):Promise<Query>;rpc(name:string,input:Record<string,unknown>):Promise<Query>};
const member=z.object({id:uuidSchema,organization_id:uuidSchema}).strict(),role=z.object({membership_id:uuidSchema,role_code:z.string(),revoked_at:z.string().nullable()}).strict(),platform=z.object({role_code:z.string()}).strict();
const mission=z.object({id:uuidSchema,status:z.string()}).strict();
const caseRow=z.object({id:uuidSchema,mission_id:uuidSchema,client_organization_id:uuidSchema,provider_organization_id:uuidSchema,obligation_key:z.string(),description:z.string(),urgency:z.enum(["STANDARD","URGENT"]),status:statusSchema,policy_snapshot:z.record(z.string(),z.unknown()),response_due_at:z.string(),review_due_at:z.string().nullable(),appeal_due_at:z.string().nullable(),row_version:z.number().int().positive()}).strict();
const evidence=z.object({id:uuidSchema,dispute_case_id:uuidSchema,evidence_type:evidenceTypeSchema,statement:z.string().nullable(),url:z.string().nullable(),evidence_hash:z.string(),visibility:visibilitySchema,created_at:z.string()}).strict();
const response=z.object({id:uuidSchema,dispute_case_id:uuidSchema,response_type:z.enum(["ACKNOWLEDGE_AND_CORRECT","CONTEST","OUT_OF_SCOPE"]),statement:z.string(),submitted_at:z.string()}).strict();
const decision=z.object({id:uuidSchema,dispute_case_id:uuidSchema,decision_number:z.number().int().positive(),outcome:outcomeSchema,reason:z.string(),evidence_ids:z.array(uuidSchema),rule_snapshot:z.record(z.string(),z.unknown()),decided_at:z.string()}).strict();
const appeal=z.object({id:uuidSchema,dispute_case_id:uuidSchema,grounds:z.string(),submitted_at:z.string()}).strict();
const event=z.object({id:z.union([z.string(),z.number()]),dispute_case_id:uuidSchema,event_type:z.string(),from_status:z.string().nullable(),to_status:z.string(),created_at:z.string()}).strict();
const reassignment=z.object({id:uuidSchema,dispute_case_id:uuidSchema,reassignment_key:z.string(),status:z.string(),original_cost_minor:z.union([z.string(),z.number().int()]),proposed_cost_minor:z.union([z.string(),z.number().int()]).nullable(),cost_delta_minor:z.union([z.string(),z.number().int()]).nullable(),currency:z.string(),row_version:z.number().int().positive()}).strict();
const candidateEnvelope=z.object({service_id:uuidSchema,candidates:z.array(z.object({organization_id:uuidSchema,display_name:z.string().min(1),qualification_status:z.string(),capacity_status:z.string()}).strict())}).strict();

function fail(reason:"UNAUTHENTICATED"|"FORBIDDEN"|"INVALID_INPUT"|"INVALID_RESPONSE"|"UNAVAILABLE"):Result<never>{return{status:"error",reason};}
function rows<T>(schema:z.ZodType<T>,q:Query):T[]|null{if(q.error)return null;const parsed=z.array(schema).safeParse(q.data);return parsed.success?parsed.data:null;}
function summary(d:z.infer<typeof caseRow>):DisputeSummary{return{id:d.id,missionId:d.mission_id,obligationKey:d.obligation_key,description:d.description,urgency:d.urgency,status:d.status,responseDueAt:d.response_due_at,reviewDueAt:d.review_due_at,appealDueAt:d.appeal_due_at,rowVersion:d.row_version};}

export function createDisputesRepository(source:DisputeSource):DisputesRepository{return{
 async list(){
  const user=await source.userId();if(!user)return fail("UNAUTHENTICATED");
  const[cases,missions,memberships,platformRoles]=await Promise.all([source.cases(),source.missions(),source.memberships(user),source.platformRoles(user)]),cs=rows(caseRow,cases),ms=rows(mission,missions),membershipRows=rows(member,memberships),platformRows=rows(platform,platformRoles);
  if(!cs||!ms||!membershipRows||!platformRows)return fail("UNAVAILABLE");const roles=rows(role,await source.orgRoles(membershipRows.map(x=>x.id)));if(!roles)return fail("UNAVAILABLE");
  const canOpen=roles.some(x=>x.revoked_at===null&&["CLIENT_OWNER","CLIENT_ADMIN"].includes(x.role_code));return{status:"success",value:{cases:cs.map(summary),missions:canOpen?ms:[],canOpen}};
 },
 async detail(id){
  if(!uuidSchema.safeParse(id).success)return fail("INVALID_INPUT");const user=await source.userId();if(!user)return fail("UNAUTHENTICATED");const base=rows(caseRow,await source.cases(id));if(!base)return fail("UNAVAILABLE");if(!base[0])return{status:"success",value:null};const d=base[0];
  const membershipRows=rows(member,await source.memberships(user)),platformRows=rows(platform,await source.platformRoles(user));if(!membershipRows||!platformRows)return fail("UNAVAILABLE");const roles=rows(role,await source.orgRoles(membershipRows.map(x=>x.id)));if(!roles)return fail("UNAVAILABLE");
  const[ev,responses,decisions,appeals,events,reas]=await Promise.all([source.evidence([id]),source.responses?.([id])??Promise.resolve({data:[],error:null}),source.decisions?.([id])??Promise.resolve({data:[],error:null}),source.appeals?.([id])??Promise.resolve({data:[],error:null}),source.events([id]),source.reassignments([id])]);
  const evidenceRows=rows(evidence,ev),responseRows=rows(response,responses),decisionRows=rows(decision,decisions),appealRows=rows(appeal,appeals),eventRows=rows(event,events),reassignmentRows=rows(reassignment,reas);if(!evidenceRows||!responseRows||!decisionRows||!appealRows||!eventRows||!reassignmentRows)return fail("UNAVAILABLE");
  const byMembership=new Map(membershipRows.map(x=>[x.id,x.organization_id])),rolePairs=roles.filter(x=>x.revoked_at===null).map(x=>({org:byMembership.get(x.membership_id),role:x.role_code})),manager=platformRows.some(x=>["SUPER_ADMIN","MATRICIA_ADMIN","DISPUTE_MANAGER"].includes(x.role_code)),client=rolePairs.some(x=>x.org===d.client_organization_id&&["CLIENT_OWNER","CLIENT_ADMIN"].includes(x.role)),provider=rolePairs.some(x=>x.org===d.provider_organization_id&&["PROVIDER_OWNER","PROVIDER_MANAGER"].includes(x.role)),party=rolePairs.some(x=>x.org===d.client_organization_id||x.org===d.provider_organization_id),r=reassignmentRows[0]??null;
  const candidateQuery=manager&&r?.status==="OPEN"?await source.rpc("list_dispute_reassignment_candidates",{p_reassignment_id:r.id,p_limit:30}):{data:{service_id:d.mission_id,candidates:[]},error:null},candidateData=candidateEnvelope.safeParse(candidateQuery.data);if(candidateQuery.error||!candidateData.success)return fail("UNAVAILABLE");
  const now=Date.now(),caps:DisputeCapabilities={open:client,respond:provider&&d.status==="WARNING_LEVEL_1",decide:manager&&(d.status==="MEDIATION_REVIEW"||d.status==="APPEALED"||(d.status==="WARNING_LEVEL_1"&&Date.parse(d.response_due_at)<now)),appeal:party&&d.status==="DECIDED"&&d.appeal_due_at!==null&&Date.parse(d.appeal_due_at)>=now,propose:manager&&r?.status==="OPEN"&&candidateData.data.candidates.length>0,approve:client&&r?.status==="AWAITING_CLIENT_APPROVAL",activate:manager&&r?.status==="APPROVED"&&d.status!=="APPEALED"&&(d.appeal_due_at===null||Date.parse(d.appeal_due_at)<now)};
  return{status:"success",value:{...summary(d),clientOrganizationId:d.client_organization_id,providerOrganizationId:d.provider_organization_id,policyVersion:String(d.policy_snapshot.version??"—"),evidence:evidenceRows.map(x=>({id:x.id,type:x.evidence_type,statement:x.statement,url:x.url,visibility:x.visibility,hash:x.evidence_hash,createdAt:x.created_at})),response:responseRows[0]?{id:responseRows[0].id,type:responseRows[0].response_type,statement:responseRows[0].statement,submittedAt:responseRows[0].submitted_at}:null,decisions:decisionRows.map(x=>({id:x.id,number:x.decision_number,outcome:x.outcome,reason:x.reason,evidenceIds:x.evidence_ids,ruleVersion:String(x.rule_snapshot.version??"—"),decidedAt:x.decided_at})),appeal:appealRows[0]?{id:appealRows[0].id,grounds:appealRows[0].grounds,submittedAt:appealRows[0].submitted_at}:null,events:eventRows.map(x=>({id:String(x.id),type:x.event_type,from:x.from_status,to:x.to_status,createdAt:x.created_at})),reassignment:r?{id:r.id,key:r.reassignment_key,status:r.status,originalCostMinor:String(r.original_cost_minor),proposedCostMinor:r.proposed_cost_minor===null?null:String(r.proposed_cost_minor),costDeltaMinor:r.cost_delta_minor===null?null:String(r.cost_delta_minor),currency:r.currency,rowVersion:r.row_version}:null,candidates:candidateData.data.candidates.map(x=>({organizationId:x.organization_id,displayName:x.display_name,qualificationStatus:x.qualification_status,capacityStatus:x.capacity_status})),capabilities:caps}};
 },
 async command(name,input){const user=await source.userId();if(!user)return fail("UNAUTHENTICATED");const q=await source.rpc(name,input);if(q.error)return fail((q.error as{code?:string}).code==="42501"?"FORBIDDEN":"UNAVAILABLE");const parsed=z.record(z.string(),z.unknown()).safeParse(q.data);return parsed.success?{status:"success",value:parsed.data}:fail("INVALID_RESPONSE");}
};}
