"use client";

import { useActionState, useId, type ReactNode } from "react";
import { Button } from "@/modules/shared/ui/button";
import { Input } from "@/modules/shared/ui/input";
import { Label } from "@/modules/shared/ui/label";
import { Textarea } from "@/modules/shared/ui/textarea";
import type { Locale } from "@/modules/shared/lib/i18n/locale";
import { hasExactUnits, sumExactUnits } from "@/modules/shared/lib/volume-procurement/exact";
import { formatExactUnits, formatMinorExact, type VolumeDashboard } from "@/modules/shared/lib/volume-procurement/model";
import { allocateProviderUnits, consumeServiceUnits, reserveServiceUnits, type VolumeActionState } from "./actions";
import type { VolumeMessages } from "./messages";

const idle: VolumeActionState = { status: "idle" };
const control = "min-h-11 w-full rounded-md border bg-background px-3 text-base";

export function VolumePanel({ dashboard: sourceDashboard, locale, m, keys }: { dashboard: VolumeDashboard; locale: Locale; m: VolumeMessages; keys: [string, string, string] }) {
  const prefix = useId();
  const [reserveState, reserveAction, reservePending] = useActionState(reserveServiceUnits, idle);
  const [allocateState, allocateAction, allocatePending] = useActionState(allocateProviderUnits, idle);
  const [consumeState, consumeAction, consumePending] = useActionState(consumeServiceUnits, idle);
  const serverCapabilities = sourceDashboard.capabilities ?? { canReserve: true, canAllocate: false, canConsume: false };
  const dashboard = { ...sourceDashboard, capabilities: { ...serverCapabilities, canConsume: serverCapabilities.canConsume && sourceDashboard.allocations.length > 0 } };
  const total = (field: "availableUnits" | "reservedUnits" | "committedUnits" | "consumedUnits" | "releasedUnits") => sumExactUnits(dashboard.pools.map((pool) => pool[field]));

  return <div className="space-y-7">
    <section aria-label={m.totals} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      {[[m.available,total("availableUnits")],[m.reserved,total("reservedUnits")],[m.committed,total("committedUnits")],[m.consumed,total("consumedUnits")],[m.released,total("releasedUnits")]].map(([label,value]) => <div key={label} className="rounded-2xl border bg-card p-5 shadow-sm"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold" dir="ltr">{formatExactUnits(value,locale)}</p></div>)}
    </section>

    <section aria-labelledby={`${prefix}-pools`}><h2 id={`${prefix}-pools`} className="text-2xl font-semibold">{m.pools}</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{dashboard.pools.map((pool) => <article key={pool.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><span className="font-semibold" dir="ltr">{pool.id.slice(0,8)}</span><span className="rounded-full border px-3 py-1 text-sm" dir="ltr">{pool.status}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label={m.contracted} value={formatExactUnits(pool.contractedUnits,locale)}/><Metric label={m.available} value={formatExactUnits(pool.availableUnits,locale)}/><Metric label={m.reserved} value={formatExactUnits(pool.reservedUnits,locale)}/><Metric label={m.committed} value={formatExactUnits(pool.committedUnits,locale)}/><Metric label={m.consumed} value={formatExactUnits(pool.consumedUnits,locale)}/><Metric label={m.released} value={formatExactUnits(pool.releasedUnits,locale)}/><div className="col-span-2"><dt className="text-muted-foreground">{m.windowEnd}</dt><dd dir="ltr">{new Intl.DateTimeFormat(locale==="ar"?"ar-MA":"fr-MA",{dateStyle:"medium"}).format(new Date(pool.windowEnd))}</dd></div></dl></article>)}{dashboard.pools.length===0?<p className="text-muted-foreground">{m.empty}</p>:null}</div></section>

    <section aria-labelledby={`${prefix}-reservations`}><h2 id={`${prefix}-reservations`} className="text-2xl font-semibold">{m.reservations}</h2><ul className="mt-4 space-y-3">{dashboard.reservations.map((reservation) => <li key={reservation.id} className="rounded-xl border bg-card p-4"><strong>{reservation.benefitReference}</strong><span className="ms-3 text-muted-foreground"><span dir="ltr">{reservation.status}</span> · <span dir="ltr">{formatExactUnits(reservation.consumedUnits,locale)}/{formatExactUnits(reservation.reservedUnits,locale)}</span></span></li>)}</ul>{dashboard.reservations.length===0?<p className="mt-3 text-muted-foreground">{m.empty}</p>:null}</section>

    {dashboard.capabilities.canAllocate ? <><section aria-labelledby={`${prefix}-commitments`}><h2 id={`${prefix}-commitments`} className="text-2xl font-semibold">{m.commitments}</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{dashboard.commitments.map((commitment) => <article key={commitment.id} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap justify-between gap-3"><strong dir="ltr">{commitment.id.slice(0,8)}</strong><span dir="ltr">{commitment.status}</span></div><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Metric label={m.capacity} value={formatExactUnits(commitment.capacityUnits,locale)}/><Metric label={m.remaining} value={formatExactUnits(commitment.remainingUnits,locale)}/><Metric label={m.committed} value={formatExactUnits(commitment.committedUnits,locale)}/><Metric label={m.consumed} value={formatExactUnits(commitment.consumedUnits,locale)}/></dl></article>)}{dashboard.commitments.length===0?<p className="text-muted-foreground">{m.empty}</p>:null}</div></section><section aria-labelledby={`${prefix}-allocations`}><h2 id={`${prefix}-allocations`} className="text-2xl font-semibold">{m.allocations}</h2><ul className="mt-4 space-y-3">{dashboard.allocations.map((allocation) => <li key={allocation.id} className="rounded-xl border bg-card p-4"><span dir="ltr" className="font-medium">{allocation.id.slice(0,8)}</span><span className="ms-3 text-muted-foreground">{m.provider} <span dir="ltr">{allocation.providerOrganizationId.slice(0,8)}</span> · {formatExactUnits(allocation.allocatedUnits,locale)} · {formatMinorExact(allocation.unitPriceMinor,allocation.currency,locale)}</span></li>)}</ul>{dashboard.allocations.length===0?<p className="mt-3 text-muted-foreground">{m.empty}</p>:null}</section></> : null}

    <section aria-labelledby={`${prefix}-commands`}><h2 id={`${prefix}-commands`} className="text-2xl font-semibold">{m.commands}</h2><div className="mt-4 grid gap-5 xl:grid-cols-3">
      {dashboard.capabilities.canReserve && dashboard.organizationId ? <Command title={m.reserve}><form action={reserveAction} className="space-y-3"><Hidden locale={locale} keyValue={keys[0]} organizationId={dashboard.organizationId}/><Select id={`${prefix}-pool`} label={m.pool} name="poolId" values={dashboard.pools.filter((pool) => pool.status!=="EXHAUSTED"&&hasExactUnits(pool.availableUnits)).map((pool) => [pool.id,`${pool.id.slice(0,8)} · ${formatExactUnits(pool.availableUnits,locale)}`])}/><Text id={`${prefix}-benefit`} label={m.benefit} name="benefitReference"/><Text id={`${prefix}-units`} label={m.units} name="units"/><Field id={`${prefix}-expiry`} label={m.expires}><Input id={`${prefix}-expiry`} name="expiresAt" type="datetime-local" required className={control}/></Field><Submit pending={reservePending} label={m.reserve} m={m}/><Feedback state={reserveState} m={m}/></form></Command> : null}
      {dashboard.capabilities.canAllocate ? <Command title={m.allocate}><form action={allocateAction} className="space-y-3"><Hidden locale={locale} keyValue={keys[1]}/><Select id={`${prefix}-reservation`} label={m.reservation} name="reservationId" values={dashboard.reservations.filter((reservation) => reservation.status==="RESERVED").map((reservation) => [reservation.id,reservation.benefitReference])}/><Select id={`${prefix}-commitment`} label={m.commitment} name="providerCommitmentId" values={dashboard.commitments.filter((commitment) => hasExactUnits(commitment.remainingUnits)).map((commitment) => [commitment.id,`${commitment.id.slice(0,8)} · ${formatExactUnits(commitment.remainingUnits,locale)}`])}/><Text id={`${prefix}-allocated-units`} label={m.units} name="units"/><Field id={`${prefix}-rule`} label={m.rule}><Textarea id={`${prefix}-rule`} name="ruleSnapshot" defaultValue="{}" required dir="ltr"/></Field><Submit pending={allocatePending} label={m.allocate} m={m}/><Feedback state={allocateState} m={m}/></form></Command> : null}
      {dashboard.capabilities.canConsume ? <Command title={m.consume}><form action={consumeAction} className="space-y-3"><Hidden locale={locale} keyValue={keys[2]}/><Select id={`${prefix}-consume-reservation`} label={m.reservation} name="reservationId" values={dashboard.reservations.filter((reservation) => ["COMMITTED","PARTIALLY_CONSUMED"].includes(reservation.status)).map((reservation) => [reservation.id,reservation.benefitReference])}/><Select id={`${prefix}-allocation`} label={m.allocation} name="allocationId" values={dashboard.allocations.map((allocation) => [allocation.id,allocation.id.slice(0,8)])}/><Text id={`${prefix}-consumed-units`} label={m.units} name="units"/><Submit pending={consumePending} label={m.consume} m={m}/><Feedback state={consumeState} m={m}/></form></Command> : null}
      {!dashboard.capabilities.canReserve&&!dashboard.capabilities.canAllocate&&!dashboard.capabilities.canConsume?<p className="text-muted-foreground">{m.noCommands}</p>:null}
    </div></section>
  </div>;
}

function Feedback({state,m}:{state:VolumeActionState;m:VolumeMessages}){const value=state.status==="success"?m.success:state.status==="error"?m[state.reason.toLowerCase()]??m.failed:"";return <p role={state.status==="error"?"alert":"status"} aria-live="polite" className={state.status==="error"?"min-h-5 text-sm text-destructive":"min-h-5 text-sm text-primary"}>{value}</p>}
function Field({id,label,children}:{id:string;label:string;children:ReactNode}){return <div className="min-w-0 space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
function Select({id,label,name,values}:{id:string;label:string;name:string;values:Array<[string,string]>}){return <Field id={id} label={label}><select id={id} name={name} required className={control}><option value="">—</option>{values.map(([value,labelValue])=><option key={value} value={value}>{labelValue}</option>)}</select></Field>}
function Hidden({locale,keyValue,organizationId}:{locale:Locale;keyValue:string;organizationId?:string}){return <><input type="hidden" name="locale" value={locale}/><input type="hidden" name="idempotencyKey" value={keyValue}/>{organizationId?<input type="hidden" name="clientOrganizationId" value={organizationId}/>:null}</>}
function Submit({pending,label,m}:{pending:boolean;label:string;m:VolumeMessages}){return <Button type="submit" disabled={pending} className="min-h-11 w-full sm:w-auto">{pending?m.processing:label}</Button>}
function Command({title,children}:{title:string;children:ReactNode}){return <details className="rounded-2xl border bg-card p-4 shadow-sm open:p-5"><summary className="min-h-11 cursor-pointer text-lg font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">{title}</summary><div className="mt-4">{children}</div></details>}
function Text({id,label,name}:{id:string;label:string;name:string}){return <Field id={id} label={label}><Input id={id} name={name} required className={control} dir="ltr" inputMode="decimal"/></Field>}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-muted-foreground">{label}</dt><dd dir="ltr">{value}</dd></div>}
