import{z}from"zod";import type{Result,SolutionInsightsRepository}from"./contracts";import{solutionDecision,solutionLevel,uuid,type SolutionSet}from"./model";
type Q={data:unknown;error:unknown};export type Source={user():Promise<string|null>;sets():Promise<Q>;options(ids:string[]):Promise<Q>;decisions(ids:string[]):Promise<Q>;benchmarks():Promise<Q>;rpc(name:string,input:Record<string,unknown>):Promise<Q>};
const setRow=z.object({id:uuid,anomaly_id:uuid,version:z.number().int().positive(),rationale_fr:z.string(),rationale_ar:z.string(),created_at:z.string()}).strict();
const exactMinor=z.union([z.string().regex(/^\d+$/u),z.number().int().nonnegative().safe()]);
const optionRow=z.object({id:uuid,solution_set_id:uuid,level:solutionLevel,expected_score_bps:z.number().int(),estimated_amount_minor:exactMinor.nullable(),currency:z.string().regex(/^[A-Z]{3}$/u).nullable(),benefits:z.array(z.unknown()),tradeoffs:z.array(z.unknown()),explanation:z.record(z.string(),z.unknown())}).strict();
const decisionRow=z.object({id:uuid,solution_set_id:uuid,level:solutionLevel,decision:solutionDecision,reason:z.string(),deferred_until:z.string().nullable(),decided_at:z.string()}).strict();
const benchmarkRow=z.object({id:uuid,metric_code:z.string(),segment_key:z.string(),period_start:z.string(),period_end:z.string(),group_size_band:z.string(),rounded_mean:z.union([z.string(),z.number().finite()]),published_at:z.string()}).strict();
const decisionResponse=z.object({outcome:z.enum(["SOLUTION_ACCEPTED","SOLUTION_REJECTED","SOLUTION_DEFERRED"]),decision_id:uuid,solution_set_id:uuid,level:solutionLevel}).strict();
function parse<T>(schema:z.ZodType<T>,q:Q){if(q.error)return null;const parsed=z.array(schema).safeParse(q.data);return parsed.success?parsed.data:null}function fail(reason:"UNAUTHENTICATED"|"INVALID_INPUT"|"UNAVAILABLE"|"FORBIDDEN"):Result<never>{return{status:"error",reason}}
export function createSolutionInsightsRepository(s:Source):SolutionInsightsRepository{return{async list(){if(!await s.user())return fail("UNAUTHENTICATED");const[sq,bq]=await Promise.all([s.sets(),s.benchmarks()]);const sets=parse(setRow,sq),benchmarks=parse(benchmarkRow,bq);if(!sets||!benchmarks)return fail("UNAVAILABLE");const ids=sets.map(x=>x.id);const[oq,dq]=await Promise.all([s.options(ids),s.decisions(ids)]);const options=parse(optionRow,oq),decisions=parse(decisionRow,dq);if(!options||!decisions)return fail("UNAVAILABLE");const value:SolutionSet[]=sets.map(x=>({id:x.id,anomalyId:x.anomaly_id,version:x.version,rationaleFr:x.rationale_fr,rationaleAr:x.rationale_ar,createdAt:x.created_at,options:options.filter(o=>o.solution_set_id===x.id).map(o=>({id:o.id,level:o.level,expectedScoreBps:o.expected_score_bps,estimatedAmountMinor:o.estimated_amount_minor===null?null:String(o.estimated_amount_minor),currency:o.currency,benefits:o.benefits,tradeoffs:o.tradeoffs,explanation:o.explanation})),decisions:decisions.filter(d=>d.solution_set_id===x.id).map(d=>({id:d.id,level:d.level,decision:d.decision,reason:d.reason,deferredUntil:d.deferred_until,decidedAt:d.decided_at}))}));return{status:"success",value:{sets:value,benchmarks:benchmarks.map(x=>({id:x.id,metricCode:x.metric_code,segmentKey:x.segment_key,periodStart:x.period_start,periodEnd:x.period_end,groupSizeBand:x.group_size_band,roundedMean:String(x.rounded_mean),publishedAt:x.published_at}))}}},async decide(i){if(!uuid.safeParse(i.solutionSetId).success||!solutionLevel.safeParse(i.level).success||!solutionDecision.safeParse(i.decision).success||i.reason.trim().length<3)return fail("INVALID_INPUT");if(!await s.user())return fail("UNAUTHENTICATED");const q=await s.rpc("record_solution_decision",{p_solution_set_id:i.solutionSetId,p_level:i.level,p_decision:i.decision,p_reason:i.reason.trim(),p_deferred_until:i.deferredUntil,p_idempotency_key:i.idempotencyKey,p_correlation_id:i.correlationId});if(q.error)return fail((q.error as{code?:string}).code==="42501"?"FORBIDDEN":"UNAVAILABLE");const parsed=decisionResponse.safeParse(q.data);return parsed.success?{status:"success",value:parsed.data}:fail("UNAVAILABLE")}}}
