"use server";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { complianceDecisionInput, documentReviewInput, responseReviewInput } from "@/lib/admin-clients/model";
import { isLocale } from "@/lib/i18n/locale";
import { getSupabaseServerClient } from "@/lib/supabase/server";
export type AdminClientActionState = { status: "idle" } | { status: "success" } | { status: "error"; reason: "VALIDATION" | "UNAUTHENTICATED" | "MFA_REQUIRED" | "FORBIDDEN" | "FOUR_EYES" | "CONFLICT" | "FAILED" };
const text = (data: FormData, key: string) => String(data.get(key) ?? ""); const output = z.union([z.boolean(), z.object({ outcome: z.string().min(3) }).passthrough()]);
function failure(error: { code?: string; message?: string } | null): AdminClientActionState { if (error?.message?.includes("AAL2_REQUIRED")) return { status: "error", reason: "MFA_REQUIRED" }; if (error?.message?.includes("DUAL_CONTROL") || error?.message?.includes("ACTOR_REQUIRED") || error?.message?.includes("EVIDENCE_REQUIRED")) return { status: "error", reason: "FOUR_EYES" }; if (error?.code === "42501") return { status: "error", reason: "FORBIDDEN" }; if (["40001", "55000", "23505"].includes(error?.code ?? "") || error?.message?.includes("IDEMPOTENCY")) return { status: "error", reason: "CONFLICT" }; return { status: "error", reason: "FAILED" }; }
async function rpc(name: string, args: Record<string, unknown>, locale: string): Promise<AdminClientActionState> { if (!isLocale(locale)) return { status: "error", reason: "VALIDATION" }; const client = await getSupabaseServerClient(); const { data: auth } = await client.auth.getUser(); if (!auth.user) return { status: "error", reason: "UNAUTHENTICATED" }; const assurance = await client.rpc("get_my_account_security_requirement"); if (assurance.error) return failure(assurance.error); const requirement = z.array(z.object({ requirement_satisfied: z.boolean(), matched_role_codes: z.array(z.string()) }).passthrough()).safeParse(assurance.data); if (!requirement.success || requirement.data.length !== 1) return { status: "error", reason: "FAILED" }; if (!requirement.data[0]!.matched_role_codes.some((role) => ["SUPER_ADMIN", "MATRICIA_ADMIN", "COMPLIANCE_MANAGER"].includes(role))) return { status: "error", reason: "FORBIDDEN" }; if (!requirement.data[0]!.requirement_satisfied) return { status: "error", reason: "MFA_REQUIRED" }; const result = await client.rpc(name, args); if (result.error) return failure(result.error); if (!output.safeParse(result.data).success) return { status: "error", reason: "FAILED" }; revalidatePath(`/${locale}/administration/clients`); return { status: "success" }; }
export async function decideCompliance(_: AdminClientActionState, data: FormData): Promise<AdminClientActionState> { const parsed = complianceDecisionInput.safeParse({ caseId: text(data, "caseId"), decision: text(data, "decision"), publicReason: text(data, "publicReason"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("decide_client_compliance", { p_compliance_case_id: value.caseId, p_decision: value.decision, p_reason_public: value.publicReason || null, p_idempotency_key: value.idempotencyKey, p_correlation_id: randomUUID() }, text(data, "locale")); }
export async function reviewComplianceDocument(_: AdminClientActionState, data: FormData): Promise<AdminClientActionState> { const parsed = documentReviewInput.safeParse({ documentId: text(data, "documentId"), decision: text(data, "decision"), verifiedSha256: text(data, "verifiedSha256"), publicReason: text(data, "publicReason"), internalReason: text(data, "internalReason"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("review_client_compliance_document", { p_document_id: value.documentId, p_decision: value.decision, p_verified_sha256: value.verifiedSha256 || null, p_reason_public: value.publicReason || null, p_reason_internal: value.internalReason || null, p_idempotency_key: value.idempotencyKey, p_correlation_id: randomUUID() }, text(data, "locale")); }
export async function reviewComplianceResponse(_: AdminClientActionState, data: FormData): Promise<AdminClientActionState> { const parsed = responseReviewInput.safeParse({ questionId: text(data, "questionId"), accepted: text(data, "accepted"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; return rpc("accept_client_compliance_response", { p_question_id: parsed.data.questionId, p_accepted: parsed.data.accepted === "yes", p_idempotency_key: parsed.data.idempotencyKey, p_correlation_id: randomUUID() }, text(data, "locale")); }
