import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { buttonVariants } from "@/components/ui/button";
import { loadAdminClients } from "@/lib/admin-clients/repository";
import { isLocale } from "@/lib/i18n/locale";
import { cn } from "@/lib/utils";
import { ClientsPanel } from "./clients-panel";
import { getAdminClientMessages } from "./messages";
export default async function AdminClientsPage({params}:{params:Promise<{locale:string}>}){const{locale}=await params;if(!isLocale(locale))notFound();const m=getAdminClientMessages(locale),result=await loadAdminClients(locale);if(result.status==="error"&&result.reason==="UNAUTHENTICATED")redirect(`/${locale}/connexion`);const alternate=locale==="fr"?"ar":"fr",keys:Record<string,string>={};if(result.status==="success")for(const item of result.dashboard.cases){keys[`case:${item.id}`]=crypto.randomUUID();for(const document of item.documents)keys[`document:${document.id}`]=crypto.randomUUID();for(const question of item.questions)keys[`response:${question.id}`]=crypto.randomUUID()}return <main dir={locale==="ar"?"rtl":"ltr"} className="min-h-dvh bg-muted/40 px-4 py-6 sm:px-6 sm:py-8"><div className="mx-auto max-w-6xl space-y-7"><nav aria-label={m.navigation} className="flex flex-wrap justify-between gap-3"><Link href={`/${locale}/administration/command-center`} className={cn(buttonVariants({variant:"outline"}),"min-h-11")}>{m.back}</Link><Link href={`/${alternate}/administration/clients`} hrefLang={alternate} className="min-h-11 rounded-md px-3 py-2 font-medium text-primary hover:underline">{m.language}</Link></nav><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{m.eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{m.title}</h1><p className="mt-3 max-w-4xl leading-7 text-muted-foreground">{m.description}</p></header>{result.status==="error"?<Alert variant={result.reason==="MFA_REQUIRED"?"default":"destructive"}><AlertTitle>{result.reason==="MFA_REQUIRED"?m.mfaTitle:result.reason==="FORBIDDEN"?m.forbiddenPage:m.loadError}</AlertTitle><AlertDescription>{result.reason==="MFA_REQUIRED"?<><p>{m.mfaBody}</p><Link href={`/${locale}/securite/compte`} className={cn(buttonVariants(),"mt-4 min-h-11")}>{m.configureMfa}</Link></>:<Link href={`/${locale}/administration/clients`} className={cn(buttonVariants({variant:"outline"}),"mt-4 min-h-11")}>{m.retry}</Link>}</AlertDescription></Alert>:<ClientsPanel dashboard={result.dashboard} locale={locale} m={m} keys={keys}/>}</div></main>}
