import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardCheck, MessageSquareText, Route, Target } from "lucide-react";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n/locale";
import { getPublicJourneyCopy } from "@/lib/public-journey/copy";

export default async function PublicHomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const c = getPublicJourneyCopy(locale).home;
  const preview = [[c.responseLabel, c.exampleProblem, MessageSquareText], [c.priorityLabel, c.exampleTitle, Target], [c.actionLabel, c.exampleAction, ClipboardCheck]] as const;
  return <main id="contenu-principal" className="journey-home">
    <section className="journey-home-hero"><div className="journey-hero-copy"><p className="journey-eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p className="journey-lead">{c.intro}</p><div className="journey-actions"><Link className="journey-primary" href={"/" + locale + "/diagnostic"}>{c.start}<ArrowRight size={18} aria-hidden="true" /></Link><Link className="journey-secondary" href={"/" + locale + "/fournisseur"}>{c.provider}</Link></div><Link className="journey-known" href={"/" + locale + "/besoin"}>{c.known}<ArrowRight size={16} aria-hidden="true" /></Link><small>{c.note}</small></div><aside className="journey-preview" aria-label={c.example}><p className="journey-preview-label">{c.example}</p><div className="journey-preview-flow">{preview.map(([label, text, Icon], index) => <div className="journey-preview-step" key={label}><div className="journey-preview-card"><span><Icon aria-hidden="true" size={18}/>{label}</span><strong>{text}</strong></div>{index < preview.length - 1 ? <span className="journey-connector" aria-hidden="true"><ArrowRight size={17}/></span> : null}</div>)}</div></aside></section>
    <section id="comment-ca-marche" className="journey-home-section"><p className="journey-eyebrow">{c.stepsTitle}</p><div className="journey-steps">{c.steps.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{text}</p></article>)}</div></section>
    <section className="journey-home-section journey-value"><div className="journey-section-heading"><p className="journey-eyebrow">{locale === "fr" ? "UNE VALEUR IMMÉDIATE" : "قيمة فورية"}</p><h2>{c.valueTitle}</h2></div><div className="journey-value-grid">{c.values.map(([title, text], index) => <article key={title}>{index === 0 ? <Target aria-hidden="true"/> : index === 1 ? <Route aria-hidden="true"/> : <ClipboardCheck aria-hidden="true"/>}<h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="fournisseurs" className="journey-home-provider"><MessageSquareText aria-hidden="true" size={34}/><p className="journey-eyebrow">{c.provider}</p><h2>{c.providerTitle}</h2><p>{c.providerText}</p><Link className="journey-primary" href={"/" + locale + "/fournisseur"}>{c.providerAction}<ArrowRight size={18} aria-hidden="true" /></Link></section>
    <section className="journey-home-section"><p className="journey-eyebrow">{c.faqTitle}</p><div className="journey-faq">{c.faqs.map(([question, answer]) => <details key={question}><summary>{question}<CheckCircle2 aria-hidden="true" size={18}/></summary><p>{answer}</p></details>)}</div><Link className="journey-primary" href={"/" + locale + "/diagnostic"}>{c.start}<ArrowRight size={18} aria-hidden="true" /></Link></section>
  </main>;
}
