"use client";
import { useActionState, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cloneChecklist, cloneClauses, cloneQuestionnaire, type State } from "./actions";

type Choice = { value: string; label: string; scope?: string };
export type CloneChoices = { questionnaires: Choice[]; releases: Choice[]; contracts: Choice[]; clauseSets: Choice[]; checklists: Choice[]; services: Choice[]; organizations: Choice[] };
const idle = { status: "idle" } as State, control = "min-h-11 w-full rounded-md border bg-background px-3";
const copy = { fr: { q: "Cloner un questionnaire complet", c: "Cloner un jeu de clauses", k: "Cloner une checklist de service", source: "Contenu source", target: "Destination", org: "Organisation d’audit", code: "Nouveau code", reason: "Motif et provenance", save: "Cloner", ok: "Clone créé avec provenance.", error: "Échec de validation, autorisation ou conflit.", readOnly: "Vue en lecture seule : votre rôle ne permet pas de cloner.", contract: "Version de contrat", clause: "Version d’un jeu de clauses" }, ar: { q: "استنساخ استبيان كامل", c: "استنساخ مجموعة بنود", k: "استنساخ قائمة تحقق للخدمة", source: "المحتوى المصدر", target: "الوجهة", org: "مؤسسة التدقيق", code: "الرمز الجديد", reason: "السبب والمصدر", save: "استنساخ", ok: "تم إنشاء النسخة مع المصدر.", error: "فشل التحقق أو الترخيص أو يوجد تعارض.", readOnly: "عرض للقراءة فقط: لا يسمح دورك بالاستنساخ.", contract: "إصدار عقد", clause: "إصدار مجموعة بنود" } } as const;
function Select({ name, label, choices }: { name: string; label: string; choices: Choice[] }) { return <label className="grid gap-1 text-sm">{label}<select name={name} required className={control} disabled={!choices.length}><option value="">—</option>{choices.map((choice) => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label>; }
function Feedback({ state, locale }: { state: State; locale: "fr" | "ar" }) { const m = copy[locale]; return state.status === "idle" ? null : <p role={state.status === "error" ? "alert" : "status"} className={state.status === "error" ? "text-sm text-destructive" : "text-sm text-primary"}>{state.status === "error" ? m.error : m.ok}</p>; }
function Base({ locale, keyValue, reason, children, action, disabled }: { locale: "fr" | "ar"; keyValue: string; reason: string; children: ReactNode; action: (s: State, f: FormData) => Promise<State>; disabled: boolean }) { const [state, submit, pending] = useActionState(action, idle), m = copy[locale]; return <form action={submit} className="grid gap-3"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="key" value={keyValue}/>{children}<label className="grid gap-1 text-sm">{reason}<Input name="reason" minLength={3} maxLength={500} required/></label><Button disabled={pending || disabled}>{m.save}</Button><Feedback state={state} locale={locale}/></form>; }
export function ClonePanel({ locale, keys, choices, canMutate }: { locale: "fr" | "ar"; keys: string[]; choices: CloneChoices; canMutate: boolean }) {
  const m = copy[locale], [questionnaireId, setQuestionnaireId] = useState(choices.questionnaires[0]?.value ?? "");
  const questionnaire = choices.questionnaires.find((item) => item.value === questionnaireId);
  const releases = choices.releases.filter((item) => !questionnaire?.scope || item.scope === questionnaire.scope);
  if (!canMutate) return <p className="rounded-xl border bg-muted p-5">{m.readOnly}</p>;
  return <div className="grid gap-4 lg:grid-cols-3">
    <Card><CardHeader><CardTitle>{m.q}</CardTitle></CardHeader><CardContent><Base locale={locale} keyValue={keys[0]!} action={cloneQuestionnaire} reason={m.reason} disabled={!choices.questionnaires.length || !releases.length}><label className="grid gap-1 text-sm">{m.source}<select name="sourceId" value={questionnaireId} onChange={(event) => setQuestionnaireId(event.target.value)} required className={control}><option value="">—</option>{choices.questionnaires.map((choice) => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label><Select name="targetId" label={m.target} choices={releases}/><label className="grid gap-1 text-sm">{m.code}<Input name="code" required pattern="[A-Z][A-Z0-9_-]+" dir="ltr"/></label></Base></CardContent></Card>
    <Card><CardHeader><CardTitle>{m.c}</CardTitle></CardHeader><CardContent><Base locale={locale} keyValue={keys[1]!} action={cloneClauses} reason={m.reason} disabled={!choices.organizations.length || (!choices.contracts.length && !choices.clauseSets.length)}><Select name="organizationId" label={m.org} choices={choices.organizations}/><label className="grid gap-1 text-sm">{m.source}<select name="sourceSelection" required className={control}><option value="">—</option>{choices.contracts.map((choice) => <option key={choice.value} value={`CONTRACT_VERSION|${choice.value}`}>{m.contract} · {choice.label}</option>)}{choices.clauseSets.map((choice) => <option key={choice.value} value={`CLAUSE_SET_VERSION|${choice.value}`}>{m.clause} · {choice.label}</option>)}</select></label><label className="grid gap-1 text-sm">{m.code}<Input name="code" required pattern="[A-Z][A-Z0-9_-]+" dir="ltr"/></label></Base></CardContent></Card>
    <Card><CardHeader><CardTitle>{m.k}</CardTitle></CardHeader><CardContent><Base locale={locale} keyValue={keys[2]!} action={cloneChecklist} reason={m.reason} disabled={!choices.organizations.length || !choices.checklists.length || !choices.services.length}><Select name="organizationId" label={m.org} choices={choices.organizations}/><Select name="sourceId" label={m.source} choices={choices.checklists}/><Select name="targetId" label={m.target} choices={choices.services}/></Base></CardContent></Card>
  </div>;
}
