import{expect,test}from"@playwright/test";
import{runNotificationWorker}from"../../apps/web/app/api/workers/notifications/route";
import{runDomainSchedulerWorker}from"../../apps/web/app/api/workers/domain-schedulers/route";

for(const route of["notifications","domain-schedulers"]){
 test(`worker ${route} échoue fermé sans secret`,async({request})=>{const response=await request.post(`/api/workers/${route}`);expect(response.status()).toBe(401);expect(await response.json()).toEqual({code:"UNAUTHORIZED"})});
}

test("le worker autorisé exécute claim, recheck, adaptateur et preuve",async()=>{const secret="p".repeat(32),calls:string[]=[];let delivered=false;const response=await runNotificationWorker(new Request("http://localhost/api/workers/notifications?limit=1",{method:"POST",headers:{authorization:`Bearer ${secret}`}}),{env:{CRON_SECRET:secret},rpc:async(name,args)=>{calls.push(name);if(name==="claim_notification_deliveries_v1")return{data:[{delivery_id:"11111111-1111-4111-8111-111111111111",lease_token:"22222222-2222-4222-8222-222222222222",worker_id:args.p_worker_id,row_version:2,channel:"IN_APP",attempt:1,provider_idempotency_key:null,recipient_email:null,locale:"fr-MA",subject:"Sujet",body:"Corps",cta_path:null}],error:null};if(name==="authorize_notification_delivery_send_v1")return{data:{authorized:true},error:null};return{data:{status:"DELIVERED"},error:null}},deliver:async()=>{delivered=true;return{outcome:"DELIVERED",providerMessageId:"in-app-p27",evidence:{adapter:"IN_APP"}}}});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({claimed:1,delivered:1});expect(delivered).toBe(true);expect(calls).toEqual(["claim_notification_deliveries_v1","authorize_notification_delivery_send_v1","record_notification_delivery_worker_result_v1"])});

test("le scheduler autorisé draine une page partielle",async()=>{const secret="q".repeat(32),outcomes=["DOMAIN_AUTOMATIONS_PARTIAL","DOMAIN_AUTOMATIONS_COMPLETED"],calls:string[]=[];const response=await runDomainSchedulerWorker(new Request("http://localhost/api/workers/domain-schedulers?asOf=2026-09-13&limit=2",{method:"POST",headers:{authorization:`Bearer ${secret}`}}),{env:{CRON_SECRET:secret},rpc:async(name)=>{calls.push(name);return{data:{outcome:outcomes.shift(),has_more:outcomes.length>0},error:null}}});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({outcome:"DOMAIN_AUTOMATIONS_COMPLETED",pageCount:2,continuationRequired:false});expect(calls).toEqual(["run_domain_automation_schedulers_v1","run_domain_automation_schedulers_v1"])});
