import{approvalRows,baselineRows,conversionEventRows,conversionRows,decisionRows,grantRows,linkRows,membership,membershipRoleRows,platformRoleRows,recommendationRows,roiRows,ruleRows,sourceEventRows,submissionRows,walletRows,type RewardsDashboard}from"./model";
import{resolveClientOrganizationContext}from"@/modules/shared/client-organization-context";
import{loadMyPlatformAccess}from"@/modules/shared/lib/account-security/platform-access";

type Result={status:"success";dashboard:RewardsDashboard}|{status:"error";reason:"UNAUTHENTICATED"|"NO_ORGANIZATION"|"ORGANIZATION_SELECTION_REQUIRED"|"FORBIDDEN_ORGANIZATION"|"QUERY_FAILED"|"INVALID_RESPONSE"};
const sensitiveRoles=new Set(["SUPER_ADMIN","MATRICIA_ADMIN","FINANCE_MANAGER","COMPLIANCE_MANAGER"]),financeRoles=new Set(["CLIENT_OWNER","CLIENT_ADMIN","CLIENT_ACCOUNTING"]),referralRoles=new Set(["FRANCHISE_OWNER","FRANCHISE_MANAGER","CLIENT_OWNER","CLIENT_ADMIN"]);

export async function loadRewardsDashboard(requestedOrganizationId?:string):Promise<Result>{
 const access=await loadMyPlatformAccess();if(access.status==="error")return{status:"error",reason:access.reason==="UNAUTHENTICATED"?"UNAUTHENTICATED":access.reason==="INVALID_RESPONSE"?"INVALID_RESPONSE":"QUERY_FAILED"};
 const c=access.client,auth={user:{id:access.userId}};
 const memberQuery=await c.from("organization_memberships").select("id,organization_id,organizations!inner(display_name)").eq("user_id",auth.user.id).eq("status","ACTIVE").limit(100);if(memberQuery.error)return{status:"error",reason:"QUERY_FAILED"};const members=membership.array().max(100).safeParse(memberQuery.data);if(!members.success)return{status:"error",reason:"INVALID_RESPONSE"};const context=resolveClientOrganizationContext(members.data,requestedOrganizationId);if(context.status==="error")return{status:"error",reason:context.reason==="NO_CLIENT_ORGANIZATION"?"NO_ORGANIZATION":context.reason};const member=context.membership,org=member.organization_id;
 const aalPromise=c.auth.mfa.getAuthenticatorAssuranceLevel();
 const queries=await Promise.all([
  c.from("organization_member_roles").select("membership_id,role_code,revoked_at").eq("membership_id",member.id).is("revoked_at",null),Promise.resolve({data:(access.requirementSatisfied?[...access.roles]:[]).map((role_code)=>({role_code})),error:null}),
  c.from("reward_rule_versions").select("id,rule_code,version_number,status,trigger_event,audience_type,bonus_credits,per_recipient_cap_credits,global_cap_credits,window_days,cooldown_hours,credit_validity_days,eligibility_rule,requires_approval,effective_from,effective_until,content_hash,change_reason").order("rule_code").order("version_number",{ascending:false}),
  c.from("reward_grants").select("id,rule_version_id,rule_code,trigger_reference_type,trigger_reference_id,eligibility_evidence,quantity,credit_ledger_entry_id,credit_lot_id,approval_reference,granted_at").eq("organization_id",org).order("granted_at",{ascending:false}).limit(100),
  c.from("referral_links").select("id,referral_code,audience_type,campaign_reference,status,expires_at,max_conversions,created_at").eq("source_organization_id",org).order("created_at",{ascending:false}).limit(100),
  c.from("referral_conversions").select("id,referral_link_id,source_organization_id,target_organization_id,conversion_stage,origin_snapshot,registered_by,registered_at,row_version").or(`source_organization_id.eq.${org},target_organization_id.eq.${org}`).order("registered_at",{ascending:false}).limit(100),
  c.from("reward_source_events").select("id,event_type,audience_type,source_reference_type,source_reference_id,eligibility_snapshot,evidence_refs,evidence_hash,occurred_at,recorded_by").eq("organization_id",org).order("occurred_at",{ascending:false}).limit(100),
  c.from("reward_award_approvals").select("id,source_event_id,rule_version_id,decision,rationale,decided_by,decided_at").eq("organization_id",org).order("decided_at",{ascending:false}).limit(100),
  c.from("measurement_baseline_submissions").select("id,subject_type,subject_id,metric_code,baseline_amount_minor,currency,period_start,period_end,source_type,source_reference,evidence_refs,evidence_hash,methodology_version,submitted_by,submitted_at").eq("organization_id",org).order("submitted_at",{ascending:false}).limit(100),
  c.from("measurement_baseline_verification_decisions").select("id,submission_id,baseline_id,decision,rationale,decided_by,decided_at").eq("organization_id",org).order("decided_at",{ascending:false}).limit(100),
  c.from("measurement_baselines").select("id,subject_type,subject_id,metric_code,version_number,baseline_amount_minor,currency,period_start,period_end,source_type,source_reference,evidence_refs,evidence_hash,methodology_version,verification_status,verified_by,verified_at").eq("organization_id",org).order("verified_at",{ascending:false}).limit(100),
  c.from("recommendation_roi_snapshots").select("id,recommendation_id,baseline_id,actual_amount_minor,realized_value_minor,implementation_cost_minor,net_value_minor,roi_basis_points,currency,actual_period_start,actual_period_end,actual_source_type,actual_source_reference,evidence_refs,evidence_hash,formula_version,explanation,calculated_at").eq("organization_id",org).order("calculated_at",{ascending:false}).limit(100),
  c.from("diagnostic_recommendations").select("id,title_fr,title_ar").eq("organization_id",org).order("created_at",{ascending:false}).limit(100),c.from("credit_wallets").select("id,wallet_type,unit_code").eq("organization_id",org).limit(20),
 ]),aal=await aalPromise;
 if(queries.some(q=>q.error))return{status:"error",reason:"QUERY_FAILED"};
 const memberRoles=membershipRoleRows.safeParse(queries[0].data),platformRoles=platformRoleRows.safeParse(queries[1].data),rules=ruleRows.safeParse(queries[2].data),grants=grantRows.safeParse(queries[3].data),links=linkRows.safeParse(queries[4].data),conversions=conversionRows.safeParse(queries[5].data),sourceEvents=sourceEventRows.safeParse(queries[6].data),approvals=approvalRows.safeParse(queries[7].data),submissions=submissionRows.safeParse(queries[8].data),decisions=decisionRows.safeParse(queries[9].data),baselines=baselineRows.safeParse(queries[10].data),roiSnapshots=roiRows.safeParse(queries[11].data),recommendations=recommendationRows.safeParse(queries[12].data),wallets=walletRows.safeParse(queries[13].data);
 if(!memberRoles.success||!platformRoles.success||!rules.success||!grants.success||!links.success||!conversions.success||!sourceEvents.success||!approvals.success||!submissions.success||!decisions.success||!baselines.success||!roiSnapshots.success||!recommendations.success||!wallets.success)return{status:"error",reason:"INVALID_RESPONSE"};
 const roles=memberRoles.data.map(x=>x.role_code),platform=platformRoles.data.map(x=>x.role_code),aalLevel=aal.data?.currentLevel==="aal2"?"aal2":"aal1",sensitive=platform.some(x=>sensitiveRoles.has(x));
 const conversionIds=conversions.data.map(x=>x.id),eventsQuery=conversionIds.length?await c.from("referral_conversion_events").select("id,referral_conversion_id,from_stage,to_stage,evidence_refs,evidence_hash,actor_user_id,occurred_at").in("referral_conversion_id",conversionIds).order("occurred_at"): {data:[],error:null},events=conversionEventRows.safeParse(eventsQuery.data);if(eventsQuery.error||!events.success)return{status:"error",reason:"INVALID_RESPONSE"};
 return{status:"success",dashboard:{organizationId:org,organizationName:member.organizations.display_name,currentUserId:auth.user.id,aal:aalLevel,canCreateReferral:roles.some(x=>referralRoles.has(x))||platform.some(x=>x==="SUPER_ADMIN"||x==="MATRICIA_ADMIN"),canSubmitBaseline:roles.some(x=>financeRoles.has(x)),canReviewSensitive:sensitive&&aalLevel==="aal2",canCalculateRoi:roles.some(x=>financeRoles.has(x))||platform.some(x=>["SUPER_ADMIN","MATRICIA_ADMIN","FINANCE_MANAGER"].includes(x)),rules:rules.data,grants:grants.data,links:links.data,conversions:conversions.data,conversionEvents:events.data,sourceEvents:sourceEvents.data,approvals:approvals.data,submissions:submissions.data,decisions:decisions.data,baselines:baselines.data,roiSnapshots:roiSnapshots.data,recommendations:recommendations.data,wallets:wallets.data}};
}
