"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/modules/shared/lib/supabase/server";
import { favoriteCommandSchema, revalidateFavoriteSchema } from "@/modules/provider/data/reputation/model";
import { isLocale, type Locale } from "@/modules/shared/lib/i18n/locale";

export type FavoriteActionState={status:"idle"}|{status:"success";outcome:string}|{status:"error";reason:"VALIDATION"|"UNAUTHENTICATED"|"FORBIDDEN"|"CONFLICT"|"FAILED"};
const text=(form:FormData,key:string)=>String(form.get(key)??"");
function errorState(error:{code?:string;message?:string}|null):FavoriteActionState { if(error?.code==="42501")return{status:"error",reason:"FORBIDDEN"};if(error?.code==="23505"||error?.code==="40001"||error?.code==="55000"||error?.message?.includes("IDEMPOTENCY")||error?.message?.includes("VERSION"))return{status:"error",reason:"CONFLICT"};return{status:"error",reason:"FAILED"}; }
async function authorizeClientOrganization(organizationId:string){const client=await getSupabaseServerClient();const{data:auth}=await client.auth.getUser();if(!auth.user)return{client,reason:"UNAUTHENTICATED" as const};const result=await client.from("organization_memberships").select("id,organization_member_roles!inner(role_code,revoked_at)").eq("user_id",auth.user.id).eq("organization_id",organizationId).eq("status","ACTIVE").is("organization_member_roles.revoked_at",null).in("organization_member_roles.role_code",["CLIENT_OWNER","CLIENT_ADMIN","CLIENT_BUYER"]).limit(1).maybeSingle();if(result.error||!result.data)return{client,reason:"FORBIDDEN" as const};return{client};}
function validLocale(form:FormData):Locale|null{const value=text(form,"locale");return isLocale(value)?value:null;}

export async function setFavorite(_:FavoriteActionState,form:FormData):Promise<FavoriteActionState>{const locale=validLocale(form);if(!locale)return{status:"error",reason:"VALIDATION"};const parsed=favoriteCommandSchema.safeParse({clientOrganizationId:text(form,"clientOrganizationId"),providerOrganizationId:text(form,"providerOrganizationId"),serviceId:text(form,"serviceId"),active:text(form,"active")==="true",note:text(form,"note"),expectedRowVersion:text(form,"expectedRowVersion"),idempotencyKey:text(form,"idempotencyKey")});if(!parsed.success)return{status:"error",reason:"VALIDATION"};const auth=await authorizeClientOrganization(parsed.data.clientOrganizationId);if(auth.reason)return{status:"error",reason:auth.reason};const value=parsed.data;const result=await auth.client.rpc("set_provider_favorite",{p_client_organization_id:value.clientOrganizationId,p_provider_organization_id:value.providerOrganizationId,p_service_id:value.serviceId,p_active:value.active,p_note:value.note,p_expected_row_version:value.expectedRowVersion,p_idempotency_key:value.idempotencyKey});if(result.error)return errorState(result.error);revalidatePath(`/${locale}/client/favoris`);return{status:"success",outcome:"PROVIDER_FAVORITE_SAVED"};}
export async function revalidateFavorite(_:FavoriteActionState,form:FormData):Promise<FavoriteActionState>{const locale=validLocale(form);const parsed=revalidateFavoriteSchema.safeParse({favoriteId:text(form,"favoriteId"),requestId:text(form,"requestId"),idempotencyKey:text(form,"idempotencyKey")});if(!locale||!parsed.success)return{status:"error",reason:"VALIDATION"};const client=await getSupabaseServerClient();const{data:auth}=await client.auth.getUser();if(!auth.user)return{status:"error",reason:"UNAUTHENTICATED"};const favorite=await client.from("client_provider_favorites").select("client_organization_id").eq("id",parsed.data.favoriteId).maybeSingle();if(favorite.error||!favorite.data)return{status:"error",reason:"FORBIDDEN"};const authorized=await authorizeClientOrganization(String(favorite.data.client_organization_id));if(authorized.reason)return{status:"error",reason:authorized.reason};const result=await authorized.client.rpc("revalidate_provider_favorite",{p_favorite_id:parsed.data.favoriteId,p_request_id:parsed.data.requestId,p_idempotency_key:parsed.data.idempotencyKey});if(result.error)return errorState(result.error);revalidatePath(`/${locale}/client/favoris`);return{status:"success",outcome:"PROVIDER_FAVORITE_REVALIDATED"};}
