import { z } from "zod";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { ACTIVITY_TYPES, PIPELINE_STAGES, type FranchiseCrmDashboard } from "./model";

const id=z.string().uuid(), exact=z.union([z.string().regex(/^\d+$/u),z.number().int().nonnegative()]).transform(String);
const franchise=z.object({id,operator_organization_id:id,franchise_type:z.enum(["IT","STANDARD"]),operator_code:z.string()});
const territory=z.object({id,franchise_id:id,version:z.number().int().positive(),territory_code:z.string(),name_fr:z.string(),name_ar:z.string()});
const prospect=z.object({id,franchise_id:id,territory_version_id:id,prospect_type:z.enum(["CLIENT","PROVIDER"]),display_name:z.string(),contact_email:z.string(),organization_name:z.string().nullable(),source_code:z.string(),pipeline_stage:z.enum(PIPELINE_STAGES),next_followup_at:z.string().nullable(),row_version:z.number().int().positive()});
const activity=z.object({id:exact,prospect_id:id,activity_type:z.enum(ACTIVITY_TYPES),occurred_at:z.string(),summary:z.string(),evidence_refs:z.array(z.unknown())});
const pipelineEvent=z.object({id:exact,prospect_id:id,from_stage:z.enum(PIPELINE_STAGES).nullable(),to_stage:z.enum(PIPELINE_STAGES),reason_code:z.string(),occurred_at:z.string(),evidence_refs:z.array(z.unknown())});
const metric=z.object({id,metric_code:z.string(),version:z.number().int().positive(),axis_code:z.string(),label_fr:z.string(),label_ar:z.string(),weight_basis_points:z.number().int(),warning_below_basis_points:z.number().int()});
const snapshot=z.object({id,franchise_id:id,period_start:z.string(),period_end:z.string(),model_version:z.string(),global_score_basis_points:z.number().int(),library_quality_score_basis_points:z.number().int(),axis_scores:z.record(z.number().int()),health_suggestion:z.enum(["HEALTHY","ATTENTION","IMPROVEMENT_PLAN","UNDER_REVIEW"])});
const alert=z.object({id,franchise_id:id,snapshot_id:id,alert_type:z.string(),severity:z.enum(["INFO","WARNING","CRITICAL"]),status:z.enum(["OPEN","ACKNOWLEDGED","RESOLVED"]),metric_code:z.string().nullable(),explanation_fr:z.string(),explanation_ar:z.string(),evidence_refs:z.array(z.unknown()),rule_version:z.string()});
const objective=z.object({id,franchise_id:id,objective_code:z.string(),version:z.number().int().positive(),title_fr:z.string(),title_ar:z.string(),target_value:exact,current_value:exact,unit_code:z.string(),status:z.enum(["ACTIVE","ACHIEVED","CANCELLED"]),starts_on:z.string(),due_on:z.string(),rule_version:z.string()});
const membership=z.object({organization_id:id,organization_member_roles:z.array(z.object({role_code:z.string(),revoked_at:z.string().nullable()}))});

export type FranchiseCrmLoadResult={status:"success";dashboard:FranchiseCrmDashboard}|{status:"error";reason:"UNAUTHENTICATED"|"FORBIDDEN"|"QUERY_FAILED"|"INVALID_RESPONSE"};
export async function loadFranchiseCrm():Promise<FranchiseCrmLoadResult>{
 const c=await getSupabaseServerClient(),{data:auth}=await c.auth.getUser();if(!auth.user)return{status:"error",reason:"UNAUTHENTICATED"};
 const [platform,memberships,franchises,territories,prospects,activities,pipelineEvents,metrics,snapshots,alerts,objectives]=await Promise.all([
  c.from("platform_user_roles").select("role_code").eq("user_id",auth.user.id).is("revoked_at",null).limit(20),
  c.from("organization_memberships").select("organization_id,organization_member_roles(role_code,revoked_at)").eq("user_id",auth.user.id).eq("status","ACTIVE").limit(100),
  c.from("franchises").select("id,operator_organization_id,franchise_type,operator_code").order("created_at",{ascending:false}).limit(100),
  c.from("franchise_territory_versions").select("id,franchise_id,version,territory_code,name_fr,name_ar").order("version",{ascending:false}).limit(300),
  c.from("franchise_crm_prospects").select("id,franchise_id,territory_version_id,prospect_type,display_name,contact_email,organization_name,source_code,pipeline_stage,next_followup_at,row_version").order("updated_at",{ascending:false}).limit(300),
  c.from("franchise_crm_activities").select("id::text,prospect_id,activity_type,occurred_at,summary,evidence_refs").order("occurred_at",{ascending:false}).limit(1000),
  c.from("franchise_pipeline_events").select("id::text,prospect_id,from_stage,to_stage,reason_code,occurred_at,evidence_refs").order("occurred_at",{ascending:false}).limit(1000),
  c.from("franchise_performance_metric_versions").select("id,metric_code,version,axis_code,label_fr,label_ar,weight_basis_points,warning_below_basis_points").eq("status","ACTIVE").order("metric_code").limit(100),
  c.from("franchise_performance_score_snapshots").select("id,franchise_id,period_start,period_end,model_version,global_score_basis_points,library_quality_score_basis_points,axis_scores,health_suggestion").order("period_end",{ascending:false}).limit(300),
  c.from("franchise_performance_alerts").select("id,franchise_id,snapshot_id,alert_type,severity,status,metric_code,explanation_fr,explanation_ar,evidence_refs,rule_version").order("created_at",{ascending:false}).limit(500),
  c.from("franchise_performance_objective_versions").select("id,franchise_id,objective_code,version,title_fr,title_ar,target_value::text,current_value::text,unit_code,status,starts_on,due_on,rule_version").order("due_on").limit(300)
 ]);
 if([platform,memberships,franchises,territories,prospects,activities,pipelineEvents,metrics,snapshots,alerts,objectives].some(x=>x.error))return{status:"error",reason:"QUERY_FAILED"};
 const fp=z.array(franchise).safeParse(franchises.data),tp=z.array(territory).safeParse(territories.data),pp=z.array(prospect).safeParse(prospects.data),ap=z.array(activity).safeParse(activities.data),pep=z.array(pipelineEvent).safeParse(pipelineEvents.data),mp=z.array(metric).safeParse(metrics.data),sp=z.array(snapshot).safeParse(snapshots.data),alp=z.array(alert).safeParse(alerts.data),op=z.array(objective).safeParse(objectives.data),msp=z.array(membership).safeParse(memberships.data),pr=z.array(z.object({role_code:z.string()})).safeParse(platform.data);
 if(!fp.success||!tp.success||!pp.success||!ap.success||!pep.success||!mp.success||!sp.success||!alp.success||!op.success||!msp.success||!pr.success)return{status:"error",reason:"INVALID_RESPONSE"};
 if(!fp.data.length&&!pr.data.length)return{status:"error",reason:"FORBIDDEN"};
 const platformRoles=new Set(pr.data.map(x=>x.role_code)),writableOrgs=new Set(msp.data.filter(x=>x.organization_member_roles.some(r=>!r.revoked_at&&["FRANCHISE_OWNER","FRANCHISE_MANAGER"].includes(r.role_code))).map(x=>x.organization_id));
 return{status:"success",dashboard:{currentUserId:auth.user.id,canWrite:platformRoles.has("SUPER_ADMIN")||platformRoles.has("MATRICIA_ADMIN")||fp.data.some(x=>writableOrgs.has(x.operator_organization_id)),canRecordPerformance:platformRoles.has("SUPER_ADMIN")||platformRoles.has("MATRICIA_ADMIN"),franchises:fp.data.map(f=>{const t=tp.data.find(x=>x.franchise_id===f.id);return{id:f.id,operatorCode:f.operator_code,type:f.franchise_type,canWrite:platformRoles.has("SUPER_ADMIN")||platformRoles.has("MATRICIA_ADMIN")||writableOrgs.has(f.operator_organization_id),territory:t?{id:t.id,code:t.territory_code,nameFr:t.name_fr,nameAr:t.name_ar,version:t.version}:null}}),prospects:pp.data.map(p=>({...{id:p.id,franchiseId:p.franchise_id,territoryVersionId:p.territory_version_id,type:p.prospect_type,displayName:p.display_name,contactEmail:p.contact_email,organizationName:p.organization_name,sourceCode:p.source_code,stage:p.pipeline_stage,nextFollowupAt:p.next_followup_at,rowVersion:p.row_version},activities:ap.data.filter(a=>a.prospect_id===p.id).map(a=>({id:a.id,type:a.activity_type,occurredAt:a.occurred_at,summary:a.summary,evidenceRefs:a.evidence_refs})),pipelineEvents:pep.data.filter(e=>e.prospect_id===p.id).map(e=>({id:e.id,from:e.from_stage,to:e.to_stage,reasonCode:e.reason_code,occurredAt:e.occurred_at,evidenceRefs:e.evidence_refs}))})),metrics:mp.data.map(x=>({id:x.id,code:x.metric_code,axis:x.axis_code,labelFr:x.label_fr,labelAr:x.label_ar,weightBps:x.weight_basis_points,warningBelowBps:x.warning_below_basis_points,version:x.version})),snapshots:sp.data.map(x=>({id:x.id,franchiseId:x.franchise_id,periodStart:x.period_start,periodEnd:x.period_end,modelVersion:x.model_version,globalScoreBps:x.global_score_basis_points,libraryQualityScoreBps:x.library_quality_score_basis_points,axisScores:x.axis_scores,healthSuggestion:x.health_suggestion})),alerts:alp.data.map(x=>({id:x.id,franchiseId:x.franchise_id,snapshotId:x.snapshot_id,type:x.alert_type,severity:x.severity,status:x.status,metricCode:x.metric_code,explanationFr:x.explanation_fr,explanationAr:x.explanation_ar,evidenceRefs:x.evidence_refs,ruleVersion:x.rule_version})),objectives:op.data.map(x=>({id:x.id,franchiseId:x.franchise_id,code:x.objective_code,version:x.version,titleFr:x.title_fr,titleAr:x.title_ar,targetValue:x.target_value,currentValue:x.current_value,unitCode:x.unit_code,status:x.status,startsOn:x.starts_on,dueOn:x.due_on,ruleVersion:x.rule_version}))}};
}
