import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { AdminGovernanceDashboard } from "@/lib/admin-governance-disputes/model";
import { formatMinor, formatBps } from "@/lib/franchise-governance/model";
import type { AdminGovernanceMessages } from "./messages";

function date(value: string, locale: "fr" | "ar") { return new Date(value).toLocaleString(locale === "ar" ? "ar-MA" : "fr-MA"); }
function amount(value: string | null, currency: string, locale: "fr" | "ar") { return value === null ? "—" : formatMinor(value, currency, locale); }

export function GovernanceDashboard({ dashboard, locale, messages: m }: { dashboard: AdminGovernanceDashboard; locale: "fr" | "ar"; messages: AdminGovernanceMessages }) {
  const approvalSeparation = new Map(dashboard.approvalSeparation.map(value => [value.approvalRequestId, value]));
  return <div className="space-y-8">
    <Alert><AlertTitle>{m.roleNotice}</AlertTitle><AlertDescription>{dashboard.capabilities.fourEyesRequired ? m.independent : m.separationFailed}</AlertDescription></Alert>
    {dashboard.capabilities.governance && dashboard.franchise ? <>
      <section aria-labelledby="admin-governance"><h2 id="admin-governance" className="mb-4 text-2xl font-semibold">{m.governance}</h2><div className="grid gap-4 xl:grid-cols-2">
        {dashboard.franchise.franchises.length === 0 ? <p className="text-muted-foreground">{m.noData}</p> : dashboard.franchise.franchises.map(item => {
          const mandate = item.mandate;
          const itValid = item.type !== "IT" || Boolean(mandate && mandate.entryFeeMinor === "0" && mandate.franchiseeShareBps === 5000 && mandate.neoxaShareBps === 5000 && mandate.asmaShareBps === 0);
          return <Card key={item.id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>{m.franchise} {item.libraryCode}</CardTitle><Badge variant={item.type === "IT" ? "default" : "outline"}>{item.type}</Badge></div><CardDescription>{item.operatorCode} · {item.status}</CardDescription></CardHeader><CardContent className="space-y-3 text-sm">
            <p><span className="text-muted-foreground">{m.territory}: </span>{item.territoryCode} · {item.territoryVersions.length} {m.version.toLocaleLowerCase(locale)}</p>
            {mandate ? <div className="rounded-lg border p-3"><p className="font-medium">{m.mandate} · {m.version} {mandate.version}</p><p>{m.status}: {mandate.status}</p><p>{m.effective}: {date(mandate.effectiveFrom, locale)}</p><p>{m.entryFee}: <span dir="ltr">{amount(mandate.entryFeeMinor, "MAD", locale)}</span></p><p>{m.shares}: <span dir="ltr">{formatBps(mandate.franchiseeShareBps)} / {formatBps(mandate.neoxaShareBps)} / {formatBps(mandate.asmaShareBps)}</span></p></div> : <p>{m.humanPending}</p>}
            <p className={itValid ? "text-muted-foreground" : "font-semibold text-destructive"}>{item.type === "IT" ? itValid ? m.itRule : m.itMismatch : m.standardRule}</p>
          </CardContent></Card>;
        })}
      </div></section>
      <section aria-labelledby="admin-approvals"><h2 id="admin-approvals" className="mb-4 text-2xl font-semibold">{m.approvals}</h2><div className="space-y-3">
        {dashboard.franchise.approvals.length === 0 ? <p className="text-muted-foreground">{m.noData}</p> : dashboard.franchise.approvals.map(item => { const separation = approvalSeparation.get(item.id); return <Card key={item.id}><CardContent className="grid gap-2 p-4 sm:grid-cols-3"><div><p className="font-medium">{item.requestType}</p><p className="text-sm text-muted-foreground">{item.reason}</p></div><div><p>{m.status}: {item.status}</p><p>{date(item.requestedAt, locale)}</p></div><div><Badge variant={separation?.independentReviewer === false ? "destructive" : "outline"}>{!separation?.hasDecision ? m.humanPending : separation.independentReviewer ? m.independent : m.separationFailed}</Badge></div></CardContent></Card>; })}
      </div></section>
      {dashboard.capabilities.finance ? <section aria-labelledby="admin-finance"><h2 id="admin-finance" className="mb-4 text-2xl font-semibold">{m.finance}</h2><div className="grid gap-4 xl:grid-cols-2">
        {dashboard.franchise.books.length === 0 ? <p className="text-muted-foreground">{m.noData}</p> : dashboard.franchise.books.map(book => <Card key={book.id}><CardHeader><CardTitle>{book.type} · {book.operatorCode}</CardTitle><CardDescription>{book.status} · {book.currency}</CardDescription></CardHeader><CardContent className="space-y-3 text-sm">{book.latestClosure ? <div><p>{m.period}: {book.latestClosure.periodStart} — {book.latestClosure.periodEnd}</p><p>{m.profit}: <strong dir="ltr">{amount(book.latestClosure.profitMinor, book.currency, locale)}</strong></p></div> : <p>{m.noData}</p>}<ul className="space-y-1">{book.allocations.map(value => <li key={value.beneficiaryCode}>{m.allocation} · {value.beneficiaryCode}: <span dir="ltr">{formatBps(value.shareBps)} · {amount(value.amountMinor, book.currency, locale)}</span></li>)}</ul><ul className="space-y-1">{book.balances.map(value => <li key={value.beneficiaryCode}>{m.balance} · {value.beneficiaryCode}: <span dir="ltr">{amount(value.amountMinor, book.currency, locale)}</span></li>)}</ul></CardContent></Card>)}
      </div></section> : null}
    </> : null}
    {dashboard.capabilities.disputes ? <section aria-labelledby="admin-disputes"><h2 id="admin-disputes" className="mb-4 text-2xl font-semibold">{m.disputes}</h2><div className="space-y-4">
      {dashboard.disputes.length === 0 ? <p className="text-muted-foreground">{m.noData}</p> : dashboard.disputes.map(item => <Card key={item.id}><CardHeader><div className="flex flex-wrap justify-between gap-2"><CardTitle>{m.obligation}: {item.obligationKey}</CardTitle><Badge variant={item.urgency === "URGENT" ? "destructive" : "outline"}>{item.status}</Badge></div><CardDescription>{m.mission}: <span dir="ltr">{item.missionId}</span> · {m.policy} {item.policyVersion}</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><div className="space-y-2 text-sm"><p>{m.responseDue}: {date(item.responseDueAt, locale)}</p>{item.latestDecision ? <div className="rounded-lg border p-3"><p className="font-medium">{m.decision} #{item.latestDecision.number}</p><p>{item.latestDecision.outcome} · {item.latestDecision.reason}</p><p>{m.evidence}: {item.latestDecision.evidenceCount} · {m.version} {item.latestDecision.ruleVersion}</p><Badge variant={item.latestDecision.independentReviewer ? "outline" : "destructive"}>{item.latestDecision.independentReviewer ? m.independent : m.separationFailed}</Badge></div> : <p>{m.humanPending}</p>}</div><div className="space-y-2 text-sm">{item.reassignment ? <div className="rounded-lg border p-3"><p className="font-medium">{m.reassignment} {item.reassignment.key} · {item.reassignment.status}</p><p>{m.originalCost}: <span dir="ltr">{amount(item.reassignment.originalCostMinor, item.reassignment.currency, locale)}</span></p><p>{m.proposedCost}: <span dir="ltr">{amount(item.reassignment.proposedCostMinor, item.reassignment.currency, locale)}</span></p><p>{m.costDelta}: <span dir="ltr">{amount(item.reassignment.costDeltaMinor, item.reassignment.currency, locale)}</span></p><p>{m.clientApproval}: {item.reassignment.clientCostApproved ? m.yes : m.no}</p><p>{m.replacement}: <span dir="ltr">{item.reassignment.replacementContractId ?? "—"} / {item.reassignment.replacementMissionId ?? "—"}</span></p></div> : <p>{m.noData}</p>}<div><p className="font-medium">{m.consequences}</p>{item.consequences.length === 0 ? <p>{m.noData}</p> : <ul>{item.consequences.map((value, index) => <li key={`${value.type}-${index}`}>{value.type} · {value.direction}: <span dir="ltr">{amount(value.amountMinor, value.currency, locale)}</span></li>)}</ul>}</div></div></CardContent></Card>)}
    </div></section> : null}
  </div>;
}
