import type { Locale } from "@/modules/shared/lib/i18n/locale";
const fr={back:"Accueil franchise",language:"العربية",eyebrow:"Pilotage franchisé",title:"CRM et performance",subtitle:"Prospects territoriaux, activités traçables et performance indépendante sur des règles versionnées.",territoryControl:"Contrôle de territoire",territoryControlText:"Chaque prospect est rattaché à la version de territoire du mandat. Les accès hors périmètre sont refusés côté serveur.",itRule:"Exception IT inchangée : Hatim Ahmitech, droit d’entrée nul et partage 50/50 avec Jalil-NEOXA.",prospects:"Pipeline des prospects",newProspect:"Ajouter un prospect",client:"Client",provider:"Sous-traitant",name:"Nom",email:"Courriel",organization:"Organisation",source:"Code source",followup:"Prochaine relance",create:"Créer",activity:"Consigner une activité",activityType:"Type d’activité",occurredAt:"Date de l’activité",summary:"Compte rendu",evidence:"Référence de preuve",record:"Enregistrer",advance:"Passer à l’étape suivante",reasonCode:"Code motif",pipelineComplete:"Parcours contractualisé",performance:"Performance indépendante",performanceNote:"Les scores et alertes éclairent la revue humaine. Ils ne déclenchent jamais de sanction automatique.",globalScore:"Score global",libraryScore:"Qualité bibliothèque",model:"Modèle",period:"Période",health:"État suggéré",objectives:"Objectifs versionnés",target:"Cible",current:"Actuel",alerts:"Alertes explicables",rule:"Règle",noAlerts:"Aucune alerte visible.",noObjectives:"Aucun objectif visible.",noSnapshots:"Aucun score visible.",recordSnapshot:"Calculer un instantané",metric:"Indicateur",numerator:"Numérateur entier",denominator:"Dénominateur entier",evidenceHash:"Empreinte SHA-256 des preuves",submit:"Valider",pending:"Traitement…",success:"Opération enregistrée, auditée et émise dans l’outbox.",validation:"Vérifiez les champs et formats.",forbidden:"Action refusée hors de votre territoire ou mandat.",conflict:"Conflit de version ou transition invalide. Actualisez la page.",failed:"L’opération n’a pas abouti.",accessDenied:"Accès franchisé ou central requis.",queryFailed:"Impossible de charger les données autorisées.",empty:"Aucune donnée visible dans votre périmètre.",version:"Version",weight:"Poids",threshold:"Seuil d’alerte",status:"Statut",activities:"Historique immuable",unknownTerritory:"Territoire indisponible",pipeline:{SENT:"Invitation envoyée",OPENED:"Invitation ouverte",REGISTERED:"Inscrit",PROFILE_STARTED:"Profil commencé",VERIFIED:"Vérifié",DIAGNOSTIC_STARTED:"Diagnostic commencé",OPPORTUNITY_CREATED:"Opportunité créée",RFQ_STARTED:"Demande de devis commencée",CONTRACT_SIGNED:"Contrat signé"},healthLabels:{HEALTHY:"Sain",ATTENTION:"Attention",IMPROVEMENT_PLAN:"Plan d’amélioration",UNDER_REVIEW:"Sous revue humaine"}};
const ar:typeof fr={back:"الرئيسية",language:"Français",eyebrow:"قيادة الامتياز",title:"إدارة العلاقات والأداء",subtitle:"عملاء محتملون حسب المجال، أنشطة قابلة للتدقيق وأداء مستقل وفق قواعد مؤرخة.",territoryControl:"ضبط المجال",territoryControlText:"يرتبط كل عميل محتمل بإصدار مجال التفويض، ويرفض الخادم أي وصول خارج النطاق.",itRule:"استثناء تقنية المعلومات ثابت: حاتم أحميتك، رسم دخول صفري وتقاسم 50/50 مع جليل-نيوكسا.",prospects:"مسار العملاء المحتملين",newProspect:"إضافة عميل محتمل",client:"عميل",provider:"مقدم خدمة",name:"الاسم",email:"البريد الإلكتروني",organization:"المؤسسة",source:"رمز المصدر",followup:"المتابعة القادمة",create:"إنشاء",activity:"تسجيل نشاط",activityType:"نوع النشاط",occurredAt:"تاريخ النشاط",summary:"ملخص موثق",evidence:"مرجع الدليل",record:"تسجيل",advance:"الانتقال للمرحلة التالية",reasonCode:"رمز السبب",pipelineComplete:"تم توقيع العقد",performance:"الأداء المستقل",performanceNote:"تساعد الدرجات والتنبيهات في المراجعة البشرية ولا تؤدي أبداً إلى عقوبة تلقائية.",globalScore:"الدرجة الإجمالية",libraryScore:"جودة المكتبة",model:"النموذج",period:"الفترة",health:"الحالة المقترحة",objectives:"أهداف مؤرخة",target:"الهدف",current:"الحالي",alerts:"تنبيهات مفسرة",rule:"القاعدة",noAlerts:"لا توجد تنبيهات مرئية.",noObjectives:"لا توجد أهداف مرئية.",noSnapshots:"لا توجد درجات مرئية.",recordSnapshot:"حساب لقطة أداء",metric:"المؤشر",numerator:"البسط الصحيح",denominator:"المقام الصحيح",evidenceHash:"بصمة SHA-256 للأدلة",submit:"تأكيد",pending:"جارٍ التنفيذ…",success:"تم تسجيل العملية وتدقيقها وإرسال حدثها.",validation:"تحقق من الحقول والصيغ.",forbidden:"رُفض الإجراء خارج مجالك أو تفويضك.",conflict:"تعارض في الإصدار أو انتقال غير صالح. حدّث الصفحة.",failed:"تعذر إتمام العملية.",accessDenied:"يلزم نطاق امتياز أو إدارة مركزية.",queryFailed:"تعذر تحميل البيانات المصرح بها.",empty:"لا توجد بيانات مرئية ضمن نطاقك.",version:"الإصدار",weight:"الوزن",threshold:"حد التنبيه",status:"الحالة",activities:"سجل غير قابل للتعديل",unknownTerritory:"المجال غير متاح",pipeline:{SENT:"أرسلت الدعوة",OPENED:"فتحت الدعوة",REGISTERED:"مسجل",PROFILE_STARTED:"بدأ الملف",VERIFIED:"تم التحقق",DIAGNOSTIC_STARTED:"بدأ التشخيص",OPPORTUNITY_CREATED:"أنشئت الفرصة",RFQ_STARTED:"بدأ طلب العرض",CONTRACT_SIGNED:"وقع العقد"},healthLabels:{HEALTHY:"سليم",ATTENTION:"انتباه",IMPROVEMENT_PLAN:"خطة تحسين",UNDER_REVIEW:"قيد المراجعة البشرية"}};
export type FranchiseCrmMessages=typeof fr;
export function getFranchiseCrmMessages(locale:Locale):FranchiseCrmMessages{return locale==="ar"?ar:fr;}

const businessValues={
 fr:{
  activity:{CALL:"Appel",EMAIL:"Courriel",MEETING:"Réunion",NOTE:"Note",FOLLOW_UP:"Relance",INVITATION:"Invitation"},
  severity:{INFO:"Information",WARNING:"Avertissement",CRITICAL:"Critique"},
  alertStatus:{OPEN:"Ouverte",ACKNOWLEDGED:"Prise en compte",RESOLVED:"Résolue"},
  objectiveStatus:{ACTIVE:"Actif",ACHIEVED:"Atteint",CANCELLED:"Annulé"},
  axis:{CLIENT_NETWORK:"Réseau clients",LIBRARY_QUALITY:"Qualité de la bibliothèque",PROVIDER_NETWORK:"Réseau de sous-traitants",DELIVERY_PERFORMANCE:"Performance de livraison",CLIENT_SATISFACTION:"Satisfaction client",COMPLIANCE_FINANCE:"Conformité et finance"},
  alertType:{KPI_THRESHOLD:"Seuil d’indicateur",LIBRARY_QUALITY:"Qualité de la bibliothèque",SLA:"Engagement de service",FAVORITISM_RISK:"Risque de favoritisme",COMPLIANCE:"Conformité",FINANCE:"Finance"},
  franchiseType:{IT:"Technologies de l’information",STANDARD:"Franchise standard"}
 },
 ar:{
  activity:{CALL:"مكالمة",EMAIL:"بريد إلكتروني",MEETING:"اجتماع",NOTE:"ملاحظة",FOLLOW_UP:"متابعة",INVITATION:"دعوة"},
  severity:{INFO:"معلومة",WARNING:"تحذير",CRITICAL:"حرج"},
  alertStatus:{OPEN:"مفتوح",ACKNOWLEDGED:"تم الاطلاع",RESOLVED:"تم الحل"},
  objectiveStatus:{ACTIVE:"نشط",ACHIEVED:"محقق",CANCELLED:"ملغى"},
  axis:{CLIENT_NETWORK:"شبكة العملاء",LIBRARY_QUALITY:"جودة المكتبة",PROVIDER_NETWORK:"شبكة مقدمي الخدمات",DELIVERY_PERFORMANCE:"أداء التسليم",CLIENT_SATISFACTION:"رضا العملاء",COMPLIANCE_FINANCE:"الامتثال والمالية"},
  alertType:{KPI_THRESHOLD:"حد المؤشر",LIBRARY_QUALITY:"جودة المكتبة",SLA:"التزام الخدمة",FAVORITISM_RISK:"خطر المحاباة",COMPLIANCE:"الامتثال",FINANCE:"المالية"},
  franchiseType:{IT:"تقنية المعلومات",STANDARD:"امتياز قياسي"}
 }
}as const;
export type FranchiseCrmValueGroup=keyof typeof businessValues.fr;
export function localizeFranchiseCrmValue(locale:Locale,group:FranchiseCrmValueGroup,code:string):string{const values=businessValues[locale][group] as Record<string,string>;return values[code]??code;}
