import type { Locale } from "@/lib/i18n/locale";

const fr = {
  nav: { how: "Comment ça marche", providers: "Fournisseurs", plans: "Abonnements", register: "Créer un compte", login: "Connexion" },
  home: {
    eyebrow: "MATRICIA · COMPRENDRE AVANT D’AGIR",
    title: "Découvrez ce qui freine votre entreprise. Passez aux bonnes solutions.",
    intro: "Répondez à quelques questions. Matricia vous aide à comprendre vos priorités et à trouver les professionnels adaptés pour agir.",
    start: "Analyser mon entreprise", provider: "Proposer mes services", known: "J’ai déjà un besoin précis", note: "Un premier bilan indicatif, sans carte bancaire.",
    example: "Exemple illustratif", responseLabel: "Votre réponse", priorityLabel: "Priorité identifiée", actionLabel: "Action recommandée", exampleProblem: "Nos relances commerciales se font de mémoire.", exampleTitle: "Structurer le suivi des prospects.", exampleAction: "Mettre en place un suivi partagé et des rappels.",
    stepsTitle: "Comment ça marche", steps: [["Vous répondez", "Quelques questions utiles sur votre situation."], ["Vous comprenez vos priorités", "Des constats expliqués, sans score opaque."], ["Vous choisissez comment agir", "Une action autonome ou une demande préparée."]],
    valueTitle: "Vous repartez avec une direction claire.", values: [["Priorités expliquées", "Chaque constat indique ce qui a été relevé et pourquoi cela compte."], ["Actions proportionnées", "Vous avancez seul lorsque c’est réaliste, avec un professionnel lorsque c’est utile."], ["Décision maîtrisée", "Vous gardez le choix de préparer une demande, comparer les devis et agir."]],
    providerTitle: "Votre expertise peut répondre à de vrais besoins.", providerText: "Décrivez votre activité, confirmez vos compétences, puis accédez aux consultations qui vous sont réellement ouvertes.", providerAction: "Commencer mon parcours fournisseur",
    faqTitle: "Questions fréquentes",
    faqs: [["Faut-il connaître son besoin ?", "Non. Le bilan commence par votre situation et vous aide à la clarifier."], ["Que vaut le prédiagnostic ?", "Il est indicatif, fondé sur vos réponses et limité au périmètre analysé."], ["Quand créer un compte ?", "Après votre premier bilan, si vous souhaitez l’enregistrer ou être accompagné."], ["Comment sont obtenus les devis ?", "Une demande complète est partagée uniquement avec des fournisseurs autorisés et adaptés."], ["Qui fixe les prix ?", "Chaque fournisseur fixe librement son devis, ses délais et ses conditions."], ["Comment devenir fournisseur ?", "Décrivez votre activité puis complétez les éléments nécessaires à la qualification."]],
  },
  diagnostic: {
    eyebrow: "PRÉDIAGNOSTIC INDICATIF", title: "Commençons par votre situation.", intro: "Vos réponses restent sur cet appareil pendant sept jours. Aucun document ni donnée sensible n’est demandé.",
    back: "Retour", next: "Continuer", result: "Voir mon bilan", restart: "Recommencer", erase: "Effacer mes réponses", unknown: "Je ne sais pas", notApplicable: "Non concerné",
    progress: (current: number, total: number) => "Question " + current + " sur " + total,
    questions: [
      ["Qu’aimeriez-vous améliorer en priorité ?", "Vous pouvez sélectionner plusieurs sujets, puis choisir celui par lequel commencer.", ["Gagner du temps", "Maîtriser mes coûts", "Développer mes ventes", "Sécuriser mon activité", "Faire un point global"]],
      ["Quel est votre secteur d’activité ?", "Une réponse générale suffit pour personnaliser les questions utiles.", ["Services professionnels", "Commerce", "Bâtiment / immobilier", "Industrie / logistique", "Autre activité"]],
      ["Quelle est la taille de votre équipe ?", "Cela évite les questions qui ne concernent pas votre organisation.", ["Je travaille seul(e)", "1 à 9 personnes", "10 à 49 personnes", "50 personnes ou plus"]],
      ["Vos priorités sont-elles suivies dans un plan simple et partagé ?", "Par exemple une liste d’actions, des responsables et des échéances.", ["Oui, régulièrement", "Partiellement", "Non", "Je ne sais pas"]],
      ["Comment suivez-vous les demandes et ventes ?", "Choisissez l’option la plus proche de votre fonctionnement.", ["Outil ou processus partagé", "Tableaux manuels", "Au cas par cas", "Je ne sais pas"]],
      ["Avez-vous déjà testé la restauration de vos sauvegardes ?", "Cette question sert uniquement à apprécier votre préparation déclarée.", ["Oui, récemment", "Oui, il y a longtemps", "Non", "Je ne sais pas", "Non concerné"]],
      ["Comment gardez-vous la trace des décisions importantes ?", "Choisissez la réponse la plus proche de votre fonctionnement actuel.", ["Toujours dans un support partagé", "Seulement pour certains sujets", "Principalement à l’oral", "Je ne sais pas"]],
      ["Quelle action serait la plus utile dans les trois prochains mois ?", "Vous pouvez répondre en quelques mots.", []],
    ],
    resultTitle: "Voici ce que votre bilan met en avant.", scope: "Périmètre analysé", limits: "Limites de ce bilan", basedOn: "Analyse fondée sur vos réponses", other: "Voir les autres points", save: "Enregistrer mon bilan", assist: "Me faire accompagner", prepare: "Préparer une demande", loginNote: "Un compte est nécessaire pour conserver ce bilan ou envoyer une demande.", kindLabels: { declared: "Point déclaré", risk: "Risque potentiel", verify: "Information à vérifier", opportunity: "Opportunité d’amélioration" },
    priorities: {
      organization: ["Clarifier les priorités", "Vos réponses indiquent qu’un cadre de suivi peut être amélioré.", "Choisissez trois actions, un responsable et une première échéance."],
      sales: ["Rendre le suivi commercial plus fiable", "Le suivi des demandes est déclaré comme manuel ou variable.", "Mettre en place un suivi simple avant d’envisager un outil plus large."],
      security: ["Vérifier la capacité de reprise", "La restauration des sauvegardes n’est pas déclarée comme testée.", "Réaliser un test de restauration adapté à votre environnement."],
      verify: ["Vérifier un point d’organisation", "Une information importante n’est pas encore connue.", "Identifier la personne ou le document qui peut confirmer ce point."],
    },
  },
  need: {
    eyebrow: "BESOIN PRÉCIS", title: "Décrivez ce dont vous avez besoin.", intro: "Matricia structure votre demande et ne vous pose que les précisions utiles.", prompt: "De quoi avez-vous besoin ?", placeholder: "Ex. Je veux sécuriser le Wi‑Fi de mon bureau de quinze personnes.", continue: "Continuer", back: "Retour", location: "Où ou comment l’intervention doit-elle se faire ?", timing: "Quel délai visez-vous ?", constraints: "Y a-t-il une contrainte importante à signaler ?", optional: "Vous pouvez laisser ce champ vide.", readyTitle: "Votre demande est préparée.", readyText: "Le contexte sera conservé quand vous vous connecterez. Les informations manquantes seront demandées seulement si elles sont nécessaires.", login: "Me connecter pour continuer", diagnostic: "Faire un bilan d’abord", localOnly: "Brouillon local limité à cet appareil.",
  },
  provider: {
    eyebrow: "PARCOURS FOURNISSEUR", title: "Votre expertise mérite les bonnes opportunités.", intro: "Décrivez votre activité, confirmez vos compétences, faites qualifier votre profil puis répondez avec vos propres devis.", steps: ["Activité décrite", "Compétences confirmées", "Profil qualifié", "Devis libre"], activity: "Quelle activité proposez-vous ?", example: "Ex. Installation réseau, accompagnement RH, expertise comptable…", begin: "Commencer ma qualification", note: "La qualification reste soumise aux contrôles et décisions Matricia.", existing: "J’ai déjà un compte fournisseur",
  },
};

const ar: typeof fr = {
  nav: { how: "كيف تعمل المنصة", providers: "مقدمو الخدمات", plans: "الاشتراكات", register: "إنشاء حساب", login: "تسجيل الدخول" },
  home: {
    eyebrow: "ماتريسيا · نفهم قبل أن نتحرك", title: "اكتشفوا ما يبطئ شركتكم. وانتقلوا إلى الحلول المناسبة.", intro: "أجيبوا عن أسئلة قليلة. تساعدكم ماتريسيا على فهم أولوياتكم والعثور على المهنيين المناسبين للتحرك.", start: "حللوا شركتي", provider: "اقترحوا خدماتكم", known: "لدي احتياج محدد", note: "تقييم أولي إرشادي · بدون بطاقة بنكية.", example: "مثال توضيحي", responseLabel: "إجابتكم", priorityLabel: "الأولوية المحددة", actionLabel: "الإجراء المقترح", exampleTitle: "تنظيم متابعة العملاء المحتملين.", exampleProblem: "تتم متابعاتنا التجارية اعتماداً على الذاكرة.", exampleAction: "وضع متابعة مشتركة وتذكيرات.",
    stepsTitle: "كيف تعمل المنصة", steps: [["تجيبون", "أسئلة مفيدة عن وضعكم."], ["تفهمون أولوياتكم", "ملاحظات مفسرة دون درجة مبهمة."], ["تختارون طريقة التحرك", "إجراء مستقل أو طلب مُعد."]], valueTitle: "تغادرون باتجاه واضح.", values: [["أولويات مفسرة", "توضح كل ملاحظة ما تم رصده ولماذا هو مهم."], ["إجراءات متناسبة", "تتقدمون بأنفسكم عندما يكون ذلك واقعياً ومع مهني عند الحاجة."], ["قرار تحت سيطرتكم", "تحتفظون بخيار إعداد طلب ومقارنة العروض والتحرك."]], providerTitle: "خبرتكم يمكن أن تستجيب لاحتياجات حقيقية.", providerText: "صفوا نشاطكم، أكدوا مهاراتكم ثم اطلعوا على الاستشارات المتاحة لكم فعلاً.", providerAction: "بدء مسار مقدم الخدمة", faqTitle: "أسئلة متكررة", faqs: [["هل يجب أن أعرف احتياجي؟", "لا. يبدأ التقييم من وضعكم ويساعدكم على توضيحه."], ["ما قيمة التقييم الأولي؟", "هو إرشادي، مبني على إجاباتكم ومحدود بالنطاق الذي تم تحليله."], ["متى أنشئ حساباً؟", "بعد تقييمكم الأول إذا أردتم حفظه أو طلب المرافقة."], ["كيف أحصل على عروض الأسعار؟", "يُشارك الطلب الكامل فقط مع مقدمي خدمات مؤهلين ومناسبين."], ["من يحدد الأسعار؟", "كل مقدم خدمة يحدد بحرية عرضه وآجاله وشروطه."], ["كيف أصبح مقدم خدمة؟", "صفوا نشاطكم ثم أكملوا عناصر التأهيل المطلوبة."]]
  },
  diagnostic: {
    eyebrow: "تقييم أولي إرشادي", title: "لنبدأ بوضعكم.", intro: "تبقى إجاباتكم على هذا الجهاز لمدة سبعة أيام. لا نطلب أي وثيقة أو بيانات حساسة.", back: "رجوع", next: "متابعة", result: "عرض تقييمي", restart: "إعادة البدء", erase: "حذف إجاباتي", unknown: "لا أعلم", notApplicable: "غير معني", progress: (current: number, total: number) => "السؤال " + current + " من " + total,
    questions: [["ما الذي ترغبون في تحسينه أولاً؟", "يمكنكم اختيار عدة مواضيع ثم تحديد الأولوية.", ["توفير الوقت", "ضبط التكاليف", "تطوير المبيعات", "تأمين النشاط", "نظرة شاملة"]], ["ما هو قطاع نشاطكم؟", "إجابة عامة تكفي لتخصيص الأسئلة المفيدة.", ["خدمات مهنية", "تجارة", "بناء / عقار", "صناعة / لوجستيك", "نشاط آخر"]], ["ما حجم فريقكم؟", "لتجنب الأسئلة التي لا تخص مؤسستكم.", ["أعمل بمفردي", "1 إلى 9 أشخاص", "10 إلى 49 شخصاً", "50 شخصاً أو أكثر"]], ["هل تتم متابعة الأولويات في خطة بسيطة ومشتركة؟", "مثلاً قائمة إجراءات ومسؤولون وآجال.", ["نعم، بانتظام", "جزئياً", "لا", "لا أعلم"]], ["كيف تتابعون الطلبات والمبيعات؟", "اختاروا الأقرب لطريقة عملكم.", ["أداة أو عملية مشتركة", "جداول يدوية", "كل حالة على حدة", "لا أعلم"]], ["هل اختبرتم استعادة نسخكم الاحتياطية؟", "يُستخدم هذا السؤال فقط لتقدير الاستعداد المعلن.", ["نعم، مؤخراً", "نعم، منذ مدة", "لا", "لا أعلم", "غير معني"]], ["كيف تحتفظون بأثر القرارات المهمة؟", "اختاروا الجواب الأقرب إلى عملكم الحالي.", ["دائماً في وسيلة مشتركة", "لبعض المواضيع فقط", "شفهياً في الغالب", "لا أعلم"]], ["ما الإجراء الأكثر فائدة خلال الأشهر الثلاثة القادمة؟", "يمكن الإجابة بكلمات قليلة.", []]],
    resultTitle: "هذا ما يبرزه تقييمكم.", scope: "النطاق المحلل", limits: "حدود هذا التقييم", basedOn: "تحليل مبني على إجاباتكم", other: "عرض النقاط الأخرى", save: "حفظ تقييمي", assist: "طلب المرافقة", prepare: "إعداد طلب", loginNote: "يلزم حساب لحفظ هذا التقييم أو إرسال طلب.", kindLabels: { declared: "نقطة مصرح بها", risk: "خطر محتمل", verify: "معلومة تحتاج إلى تحقق", opportunity: "فرصة للتحسين" }, priorities: { organization: ["توضيح الأولويات", "تشير إجاباتكم إلى إمكانية تحسين إطار المتابعة.", "اختاروا ثلاثة إجراءات ومسؤولاً وأجلاً أولياً."], sales: ["جعل المتابعة التجارية أكثر موثوقية", "تم التصريح بأن متابعة الطلبات يدوية أو متغيرة.", "ضعوا متابعة بسيطة قبل التفكير في أداة أوسع."], security: ["التحقق من القدرة على الاستعادة", "لم يتم التصريح باختبار استعادة النسخ الاحتياطية.", "أجروا اختبار استعادة مناسباً لبيئتكم."], verify: ["التحقق من نقطة تنظيمية", "معلومة مهمة غير معروفة بعد.", "حددوا الشخص أو الوثيقة القادرة على تأكيدها."] },
  },
  need: { eyebrow: "احتياج محدد", title: "صفوا ما تحتاجون إليه.", intro: "تنظم ماتريسيا طلبكم ولا تسألكم إلا عن التفاصيل المفيدة.", prompt: "ماذا تحتاجون؟", placeholder: "مثال: أريد تأمين شبكة Wi‑Fi لمكتب يضم خمسة عشر شخصاً.", continue: "متابعة", back: "رجوع", location: "أين أو كيف يجب تنفيذ التدخل؟", timing: "ما الأجل الذي تستهدفونه؟", constraints: "هل توجد قيود مهمة يجب ذكرها؟", optional: "يمكن ترك هذا الحقل فارغاً.", readyTitle: "طلبكم مُعد.", readyText: "سيبقى السياق محفوظاً عند تسجيل الدخول. لن نطلب إلا المعلومات الناقصة الضرورية.", login: "تسجيل الدخول للمتابعة", diagnostic: "إجراء تقييم أولاً", localOnly: "مسودة محلية محدودة على هذا الجهاز." },
  provider: { eyebrow: "مسار مقدم الخدمة", title: "خبرتكم تستحق الفرص المناسبة.", intro: "صفوا نشاطكم وأكدوا مهاراتكم وأكملوا تأهيل ملفكم ثم قدموا عروضكم بحرية.", steps: ["وصف النشاط", "تأكيد المهارات", "تأهيل الملف", "عرض سعر حر"], activity: "ما النشاط الذي تقدمونه؟", example: "مثال: تركيب شبكات، مرافقة موارد بشرية، خبرة محاسبية…", begin: "بدء التأهيل", note: "يبقى التأهيل خاضعاً للضوابط وقرارات ماتريسيا.", existing: "لدي حساب مقدم خدمة بالفعل" },
};

export function getPublicJourneyCopy(locale: Locale) { return locale === "ar" ? ar : fr; }
