import type { Locale } from "@/lib/i18n/locale";

const fr = {
  navigation: "Navigation des demandes récurrentes", back: "Demandes", language: "العربية", eyebrow: "Espace Client", title: "Commander à nouveau et planifier", description: "Repartez d’une demande existante ou créez un rythme mensuel, trimestriel ou annuel. Chaque cycle reste un brouillon à vérifier.", safetyTitle: "Vous gardez le contrôle", safety: "Un cycle génère uniquement des brouillons. Il n’ouvre aucune consultation, n’invite aucun prestataire et n’engage aucune dépense.",
  cloneTitle: "Commander à nouveau", cloneDescription: "Les réponses utiles sont reprises, tandis que le catalogue et le questionnaire publiés sont revalidés par le serveur.", sourceRequest: "Demande source", desiredDate: "Nouvelle date souhaitée", optional: "Facultatif", reason: "Motif", clone: "Créer le brouillon", clonePending: "Création du brouillon…",
  createTitle: "Créer une prestation récurrente", createDescription: "Choisissez un modèle et une période. Seuls les services publiés marqués récurrents sont acceptés.", templateRequest: "Demande modèle", cadence: "Fréquence", startsOn: "Début", endsOn: "Fin", createPlan: "Créer le plan", createPending: "Création du plan…",
  plansTitle: "Plans récurrents", emptyPlans: "Aucun plan récurrent pour le moment.", emptyRequests: "Aucune demande disponible. Créez d’abord une demande à utiliser comme modèle.", version: "Version", schedule: "Période", openEnded: "Sans date de fin", template: "Modèle", occurrences: "Brouillons générés", noOccurrences: "Aucun brouillon généré.", viewDraft: "Ouvrir le brouillon", updated: "Mis à jour",
  planActions: "Piloter le plan", pause: "Mettre en pause", resume: "Reprendre", end: "Terminer", transitionPending: "Mise à jour…", transitionReason: "Motif du changement", generateTitle: "Générer les prochains cycles", throughDate: "Générer jusqu’au", maxOccurrences: "Nombre maximal de nouveaux brouillons", generate: "Générer", generatePending: "Génération…", generationLimit: "Maximum 24 nouveaux brouillons et horizon serveur de 366 jours.",
  successClone: "Le nouveau brouillon a été créé.", successCreate: "Le plan récurrent a été créé.", successTransition: "Le statut du plan a été mis à jour.", successGenerate: "Les cycles ont été générés.", generatedCount: "Nouveaux brouillons", validation: "Vérifiez les champs indiqués.", forbidden: "Vous n’avez pas l’autorisation de gérer cette demande.", conflict: "Le plan a changé ou cette commande est déjà en cours. Actualisez la page.", notEligible: "Le service publié de cette demande n’est pas admissible à la récurrence.", notActive: "La génération est disponible uniquement pour un plan actif.", invalidTransition: "Cette transition n’est plus permise. Actualisez la page.", bounds: "La génération doit rester entre aujourd’hui et 366 jours, avec 1 à 24 occurrences.", unavailable: "L’opération n’a pas abouti. Réessayez sans modifier les données afin de réutiliser la même commande.", loadError: "Impossible de charger les demandes récurrentes.", retry: "Réessayer",
  cadences: { MONTHLY: "Mensuelle", QUARTERLY: "Trimestrielle", ANNUALLY: "Annuelle" }, statuses: { ACTIVE: "Actif", PAUSED: "En pause", ENDED: "Terminé" }, requestStatuses: { DRAFT: "Brouillon", INFORMATION_REQUIRED: "Informations requises", READY: "Prête", MATCHING: "Matching", RFQ_OPEN: "Consultation ouverte", QUOTES_RECEIVED: "Devis reçus", CLIENT_REVIEW: "Revue client", PROVIDER_SELECTED: "Prestataire sélectionné", CONTRACT_PENDING: "Contrat en préparation", CONTRACTED: "Contractée", CANCELLED: "Annulée", EXPIRED: "Expirée", NO_PROVIDER_AVAILABLE: "Aucun prestataire" },
} as const;

const ar = {
  ...fr,
  navigation: "التنقل في الطلبات المتكررة", back: "الطلبات", language: "Français", eyebrow: "فضاء العميل", title: "إعادة الطلب والجدولة", description: "ابدأ من طلب سابق أو أنشئ وتيرة شهرية أو ربع سنوية أو سنوية. تبقى كل دورة مسودة للمراجعة.", safetyTitle: "التحكم بيدك", safety: "تنشئ الدورة مسودات فقط. لا تفتح طلب عروض ولا تدعو مقدمي خدمات ولا تنشئ أي إنفاق.",
  cloneTitle: "إعادة الطلب", cloneDescription: "تُعاد الاستفادة من الإجابات المفيدة، بينما يعيد الخادم التحقق من الكتالوج والاستبيان المنشورين.", sourceRequest: "الطلب المصدر", desiredDate: "التاريخ المطلوب الجديد", optional: "اختياري", reason: "السبب", clone: "إنشاء المسودة", clonePending: "جارٍ إنشاء المسودة…",
  createTitle: "إنشاء خدمة متكررة", createDescription: "اختر طلباً نموذجياً وفترة. لا يقبل الخادم إلا الخدمات المنشورة المؤهلة للتكرار.", templateRequest: "الطلب النموذجي", cadence: "التواتر", startsOn: "البداية", endsOn: "النهاية", createPlan: "إنشاء الخطة", createPending: "جارٍ إنشاء الخطة…",
  plansTitle: "الخطط المتكررة", emptyPlans: "لا توجد خطة متكررة حالياً.", emptyRequests: "لا يوجد طلب متاح. أنشئ أولاً طلباً لاستخدامه نموذجاً.", version: "النسخة", schedule: "الفترة", openEnded: "من دون تاريخ نهاية", template: "النموذج", occurrences: "المسودات المنشأة", noOccurrences: "لم تُنشأ أي مسودة.", viewDraft: "فتح المسودة", updated: "آخر تحديث",
  planActions: "إدارة الخطة", pause: "إيقاف مؤقت", resume: "استئناف", end: "إنهاء", transitionPending: "جارٍ التحديث…", transitionReason: "سبب التغيير", generateTitle: "إنشاء الدورات المقبلة", throughDate: "الإنشاء حتى", maxOccurrences: "الحد الأقصى للمسودات الجديدة", generate: "إنشاء", generatePending: "جارٍ الإنشاء…", generationLimit: "الحد الأقصى 24 مسودة جديدة وأفق الخادم 366 يوماً.",
  successClone: "تم إنشاء المسودة الجديدة.", successCreate: "تم إنشاء الخطة المتكررة.", successTransition: "تم تحديث حالة الخطة.", successGenerate: "تم إنشاء الدورات.", generatedCount: "المسودات الجديدة", validation: "تحقق من الحقول المحددة.", forbidden: "ليست لديك صلاحية إدارة هذا الطلب.", conflict: "تغيرت الخطة أو ما زال هذا الأمر قيد التنفيذ. حدّث الصفحة.", notEligible: "الخدمة المنشورة في هذا الطلب غير مؤهلة للتكرار.", notActive: "الإنشاء متاح فقط للخطة النشطة.", invalidTransition: "لم يعد هذا الانتقال مسموحاً. حدّث الصفحة.", bounds: "يجب أن يبقى الإنشاء بين اليوم و366 يوماً وبعدد من 1 إلى 24 دورة.", unavailable: "لم تنجح العملية. أعد المحاولة دون تغيير البيانات لإعادة استخدام الأمر نفسه.", loadError: "تعذر تحميل الطلبات المتكررة.", retry: "إعادة المحاولة",
  cadences: { MONTHLY: "شهري", QUARTERLY: "ربع سنوي", ANNUALLY: "سنوي" }, statuses: { ACTIVE: "نشطة", PAUSED: "متوقفة مؤقتاً", ENDED: "منتهية" }, requestStatuses: { DRAFT: "مسودة", INFORMATION_REQUIRED: "معلومات مطلوبة", READY: "جاهز", MATCHING: "مطابقة", RFQ_OPEN: "طلب العروض مفتوح", QUOTES_RECEIVED: "عروض مستلمة", CLIENT_REVIEW: "مراجعة العميل", PROVIDER_SELECTED: "تم اختيار مقدم الخدمة", CONTRACT_PENDING: "العقد قيد الإعداد", CONTRACTED: "متعاقد", CANCELLED: "ملغى", EXPIRED: "منتهي", NO_PROVIDER_AVAILABLE: "لا يوجد مقدم خدمة" },
} as const;

export type ClientRecurringMessages = { [K in Exclude<keyof typeof fr, "cadences" | "statuses" | "requestStatuses">]: string } & { cadences: Record<keyof typeof fr.cadences, string>; statuses: Record<keyof typeof fr.statuses, string>; requestStatuses: Record<keyof typeof fr.requestStatuses, string> };
export function getClientRecurringMessages(locale: Locale): ClientRecurringMessages { return locale === "ar" ? ar : fr; }

