"use client";
import { useActionState, useId, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Locale } from "@/lib/i18n/locale";
import { maskedProviderReference, type ClientFavoritesDashboard } from "@/lib/provider-reputation/model";
import type { FavoriteProviderOption } from "@/lib/provider-reputation/repository";
import { revalidateFavorite, setFavorite, type FavoriteActionState } from "./actions";
import type { FavoriteMessages } from "./messages";
const idle: FavoriteActionState = { status: "idle" };
function Feedback({ state, m }: { state: FavoriteActionState; m: FavoriteMessages }) { const message = state.status === "success" ? m.success : state.status === "error" ? state.reason === "VALIDATION" ? m.validation : state.reason === "FORBIDDEN" ? m.forbidden : state.reason === "CONFLICT" ? m.conflict : m.failed : ""; return <p role={state.status === "error" ? "alert" : "status"} aria-live="polite" className={state.status === "error" ? "min-h-5 text-sm text-destructive" : "min-h-5 text-sm text-primary"}>{message}</p>; }
function Toggle({ favorite, dashboard, locale, m }: { favorite: ClientFavoritesDashboard["favorites"][number]; dashboard: ClientFavoritesDashboard; locale: Locale; m: FavoriteMessages }) { const [state, action, pending] = useActionState(setFavorite, idle); return <form action={action} className="grid gap-2">{Object.entries({ locale, clientOrganizationId: dashboard.organizationId, providerOrganizationId: favorite.providerOrganizationId, serviceId: favorite.serviceId ?? "", note: favorite.note ?? "", active: favorite.status === "REMOVED" ? "true" : "false", expectedRowVersion: favorite.rowVersion, idempotencyKey: crypto.randomUUID() }).map(([name, value]) => <input key={name} type="hidden" name={name} value={String(value)} />)}<Button variant="outline" disabled={pending}>{pending ? m.saving : favorite.status === "REMOVED" ? m.restore : m.remove}</Button><Feedback state={state} m={m} /></form>; }
function Revalidate({ favorite, dashboard, locale, m }: { favorite: ClientFavoritesDashboard["favorites"][number]; dashboard: ClientFavoritesDashboard; locale: Locale; m: FavoriteMessages }) { const [state, action, pending] = useActionState(revalidateFavorite, idle), id = useId(), requests = dashboard.requests.filter((item) => !favorite.serviceId || item.serviceId === favorite.serviceId); if (favorite.status !== "ACTIVE" || !requests.length) return null; return <form action={action} className="grid gap-3 rounded-lg border p-3"><input type="hidden" name="locale" value={locale} /><input type="hidden" name="favoriteId" value={favorite.id} /><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()} /><label htmlFor={id}>{m.revalidate}</label><select id={id} name="requestId" required className="min-h-11 rounded-md border bg-background px-3"><option value="">{m.chooseRequest}</option>{requests.map((item) => <option key={item.id} value={item.id}>{item.reference} · {item.status}</option>)}</select><Button disabled={pending}>{pending ? m.saving : m.check}</Button><Feedback state={state} m={m} /></form>; }
function Create({ dashboard, providerOptions, locale, m }: { dashboard: ClientFavoritesDashboard; providerOptions: FavoriteProviderOption[]; locale: Locale; m: FavoriteMessages }) { const [state, action, pending] = useActionState(setFavorite, idle), [providerId, setProviderId] = useState(""), provider = providerOptions.find((item) => item.organizationId === providerId), providerInput = useId(), serviceInput = useId(), noteInput = useId(); return <Card><CardHeader><CardTitle>{m.add}</CardTitle></CardHeader><CardContent>{providerOptions.length ? <form action={action} className="grid gap-4"><input type="hidden" name="locale" value={locale} /><input type="hidden" name="clientOrganizationId" value={dashboard.organizationId} /><input type="hidden" name="active" value="true" /><input type="hidden" name="expectedRowVersion" value="0" /><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()} /><label htmlFor={providerInput} className="grid gap-2 font-medium">{m.providerId}<select id={providerInput} name="providerOrganizationId" required value={providerId} onChange={(event) => setProviderId(event.target.value)} className="min-h-11 rounded-md border bg-background px-3"><option value="">—</option>{providerOptions.map((item) => <option key={item.organizationId} value={item.organizationId}>{item.name}</option>)}</select></label><label htmlFor={serviceInput} className="grid gap-2 font-medium">{m.serviceId}<select id={serviceInput} name="serviceId" className="min-h-11 rounded-md border bg-background px-3"><option value="">{m.allServices}</option>{provider?.services.map((service) => <option key={service.id} value={service.id}>{locale === "ar" ? service.nameAr : service.nameFr}</option>)}</select></label><label htmlFor={noteInput} className="grid gap-2 font-medium">{m.note}<Input id={noteInput} name="note" maxLength={500} /></label><Button disabled={pending || !providerId}>{pending ? m.saving : m.save}</Button><Feedback state={state} m={m} /></form> : <p className="text-muted-foreground">{m.empty}</p>}</CardContent></Card>; }
export function FavoritesPanel({ dashboard, providerOptions, locale, m }: { dashboard: ClientFavoritesDashboard; providerOptions: FavoriteProviderOption[]; locale: Locale; m: FavoriteMessages }) { const date = (value: string) => new Intl.DateTimeFormat(locale === "ar" ? "ar-MA" : "fr-MA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); return <div className="grid gap-6"><p className="rounded-xl border bg-card p-4 text-sm text-muted-foreground">{m.privacy}</p>{dashboard.canManage ? <Create dashboard={dashboard} providerOptions={providerOptions} locale={locale} m={m} /> : <p>{m.readOnly}</p>}<section><h2 className="mb-4 text-xl font-semibold">{m.favorites}</h2>{dashboard.favorites.length ? <div className="grid gap-4 lg:grid-cols-2">{dashboard.favorites.map((favorite) => <Card key={favorite.id}><CardHeader><CardTitle>{m.provider} {maskedProviderReference(favorite.providerOrganizationId)}</CardTitle><CardDescription>{favorite.serviceId ? (locale === "ar" ? favorite.serviceLabelAr : favorite.serviceLabelFr) ?? favorite.serviceId : m.allServices}</CardDescription></CardHeader><CardContent className="grid gap-4"><Badge>{favorite.status === "ACTIVE" ? m.active : m.removed}</Badge>{favorite.note ? <p>{favorite.note}</p> : null}{favorite.latestRevalidation ? <p>{favorite.latestRevalidation.eligible ? m.eligible : m.ineligible} · {date(favorite.latestRevalidation.checkedAt)}</p> : <p>{m.notChecked}</p>}<Revalidate favorite={favorite} dashboard={dashboard} locale={locale} m={m} /><Toggle favorite={favorite} dashboard={dashboard} locale={locale} m={m} /></CardContent></Card>)}</div> : <p>{m.empty}</p>}</section></div>; }
