"use server";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createServerClientRfqRepository } from "../../../../lib/client-rfq/server-repository";
import { hashSchema, localeSchema, moneyToMinor, uuidSchema, type QuoteComparisonRow } from "../../../../lib/client-rfq/model";

export type ActionState={status:"idle"}|{status:"success";message:"CREATED"|"READY"|"MATCHED"|"RFQ_OPENED"|"SELECTED";requestId?:string;matchingRunId?:string;rfqId?:string}|{status:"error";reason:"VALIDATION"|"UNAUTHENTICATED"|"FORBIDDEN"|"UNAVAILABLE"};
export type ComparisonState={status:"idle"}|{status:"success";snapshotId:string;currency:string;rows:QuoteComparisonRow[]}|{status:"error";reason:"VALIDATION"|"UNAUTHENTICATED"|"FORBIDDEN"|"UNAVAILABLE"};
const base=z.object({locale:localeSchema,idempotencyKey:uuidSchema});
const createSchema=base.extend({organizationId:uuidSchema,libraryId:uuidSchema,serviceId:uuidSchema,questionnaireVersionId:uuidSchema,description:z.string().trim().min(10).max(8000),urgency:z.enum(["LOW","NORMAL","HIGH","CRITICAL"]),desiredDate:z.union([z.literal(""),z.string().regex(/^\d{4}-\d{2}-\d{2}$/u)]),budget:z.string().trim().max(20),currency:z.literal("MAD"),regionCode:z.string().trim().min(2).max(40).regex(/^[A-Z0-9_-]+$/u),catalogSnapshotHash:hashSchema,questionnaireSnapshotHash:hashSchema,changeReason:z.string().trim().min(3).max(500),confirmed:z.literal("yes")});
const readySchema=base.extend({requestId:uuidSchema,rowVersion:z.coerce.number().int().positive(),reason:z.string().trim().min(3).max(500)});
const matchSchema=base.extend({requestId:uuidSchema,targetPanelSize:z.coerce.number().int().min(1).max(100)});
const openSchema=base.extend({requestId:uuidSchema,matchingRunId:uuidSchema,deadline:z.string().datetime({offset:true})});
const compareSchema=base.extend({rfqId:uuidSchema});const selectSchema=base.extend({requestId:uuidSchema,quoteId:uuidSchema,quoteVersionId:uuidSchema});
function data(form:FormData,key:string){return form.get(key)}function reason(value:"UNAUTHENTICATED"|"FORBIDDEN"|"INVALID_INPUT"|"INVALID_RESPONSE"|"UNAVAILABLE"){return value==="INVALID_INPUT"||value==="INVALID_RESPONSE"?"UNAVAILABLE":value;}
export async function createRequestAction(_:ActionState,form:FormData):Promise<ActionState>{const parsed=createSchema.safeParse({locale:data(form,"locale"),idempotencyKey:data(form,"idempotencyKey"),organizationId:data(form,"organizationId"),libraryId:data(form,"libraryId"),serviceId:data(form,"serviceId"),questionnaireVersionId:data(form,"questionnaireVersionId"),description:data(form,"description"),urgency:data(form,"urgency"),desiredDate:data(form,"desiredDate"),budget:data(form,"budget"),currency:data(form,"currency"),regionCode:data(form,"regionCode"),catalogSnapshotHash:data(form,"catalogSnapshotHash"),questionnaireSnapshotHash:data(form,"questionnaireSnapshotHash"),changeReason:data(form,"changeReason"),confirmed:data(form,"confirmed")});if(!parsed.success)return{status:"error",reason:"VALIDATION"};const minor=parsed.data.budget?moneyToMinor(parsed.data.budget):null;if(parsed.data.budget&&minor===null)return{status:"error",reason:"VALIDATION"};const repo=await createServerClientRfqRepository();const r=await repo.create({...parsed.data,desiredDate:parsed.data.desiredDate||null,budgetMinor:minor,correlationId:randomUUID()});if(r.status==="error")return{status:"error",reason:reason(r.reason)};revalidatePath(`/${parsed.data.locale}/client/demandes`);return{status:"success",message:"CREATED",requestId:r.value.requestId};}
export async function readyRequestAction(_:ActionState,form:FormData):Promise<ActionState>{const p=readySchema.safeParse({locale:data(form,"locale"),idempotencyKey:data(form,"idempotencyKey"),requestId:data(form,"requestId"),rowVersion:data(form,"rowVersion"),reason:data(form,"reason")});if(!p.success)return{status:"error",reason:"VALIDATION"};const r=await(await createServerClientRfqRepository()).ready({...p.data,correlationId:randomUUID()});if(r.status==="error")return{status:"error",reason:reason(r.reason)};revalidatePath(`/${p.data.locale}/client/demandes/${p.data.requestId}`);return{status:"success",message:"READY",requestId:p.data.requestId};}
export async function matchRequestAction(_:ActionState,form:FormData):Promise<ActionState>{const p=matchSchema.safeParse({locale:data(form,"locale"),idempotencyKey:data(form,"idempotencyKey"),requestId:data(form,"requestId"),targetPanelSize:data(form,"targetPanelSize")});if(!p.success)return{status:"error",reason:"VALIDATION"};const r=await(await createServerClientRfqRepository()).match({...p.data,correlationId:randomUUID()});if(r.status==="error")return{status:"error",reason:reason(r.reason)};revalidatePath(`/${p.data.locale}/client/demandes/${p.data.requestId}`);return{status:"success",message:"MATCHED",requestId:p.data.requestId,matchingRunId:r.value.matchingRunId};}
export async function openRfqAction(_:ActionState,form:FormData):Promise<ActionState>{const p=openSchema.safeParse({locale:data(form,"locale"),idempotencyKey:data(form,"idempotencyKey"),requestId:data(form,"requestId"),matchingRunId:data(form,"matchingRunId"),deadline:data(form,"deadline")});if(!p.success)return{status:"error",reason:"VALIDATION"};const r=await(await createServerClientRfqRepository()).openRfq({...p.data,correlationId:randomUUID()});if(r.status==="error")return{status:"error",reason:reason(r.reason)};revalidatePath(`/${p.data.locale}/client/demandes/${p.data.requestId}`);return{status:"success",message:"RFQ_OPENED",requestId:p.data.requestId,rfqId:r.value.rfqId};}
export async function compareQuotesAction(_:ComparisonState,form:FormData):Promise<ComparisonState>{const p=compareSchema.safeParse({locale:data(form,"locale"),idempotencyKey:data(form,"idempotencyKey"),rfqId:data(form,"rfqId")});if(!p.success)return{status:"error",reason:"VALIDATION"};const r=await(await createServerClientRfqRepository()).compare({...p.data,correlationId:randomUUID()});return r.status==="error"?{status:"error",reason:reason(r.reason)}:{status:"success",...r.value};}
export async function selectQuoteAction(_:ActionState,form:FormData):Promise<ActionState>{const p=selectSchema.safeParse({locale:data(form,"locale"),idempotencyKey:data(form,"idempotencyKey"),requestId:data(form,"requestId"),quoteId:data(form,"quoteId"),quoteVersionId:data(form,"quoteVersionId")});if(!p.success)return{status:"error",reason:"VALIDATION"};const r=await(await createServerClientRfqRepository()).select({...p.data,correlationId:randomUUID()});if(r.status==="error")return{status:"error",reason:reason(r.reason)};revalidatePath(`/${p.data.locale}/client/demandes/${p.data.requestId}`);return{status:"success",message:"SELECTED",requestId:p.data.requestId};}
