export const MATRICIA_BREAKPOINT_MIN_PX = 360;

export const designTokens = Object.freeze({
  color: Object.freeze({
    brand: "#123B3B",
    brandStrong: "#0B2929",
    accent: "#9A6B18",
    canvas: "#F7F8F5",
    surface: "#FFFFFF",
    surfaceMuted: "#EEF2EF",
    text: "#172020",
    textMuted: "#526060",
    border: "#CBD5D1",
    focus: "#176B87",
    success: "#17643A",
    warning: "#805400",
    danger: "#A12828",
  }),
  typography: Object.freeze({
    sans: "Inter, Noto Sans Arabic, system-ui, sans-serif",
    mono: "ui-monospace, SFMono-Regular, Consolas, monospace",
    weightRegular: 400,
    weightMedium: 500,
    weightSemibold: 600,
    weightBold: 700,
  }),
  spacing: Object.freeze({
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    6: "1.5rem",
    8: "2rem",
    12: "3rem",
    16: "4rem",
  }),
  radius: Object.freeze({ small: "0.375rem", medium: "0.625rem", large: "1rem", pill: "9999px" }),
  shadow: Object.freeze({
    small: "0 1px 2px rgb(11 41 41 / 0.08)",
    medium: "0 8px 24px rgb(11 41 41 / 0.12)",
    overlay: "0 24px 64px rgb(11 41 41 / 0.18)",
  }),
  motion: Object.freeze({ fast: "120ms", standard: "200ms", deliberate: "320ms" }),
  breakpoint: Object.freeze({ compact: "360px", tablet: "768px", desktop: "1200px" }),
  focusRing: "0 0 0 3px rgb(23 107 135 / 0.35)",
} as const);

export const designTokenCssVariables = Object.freeze({
  "--mat-color-brand": designTokens.color.brand,
  "--mat-color-brand-strong": designTokens.color.brandStrong,
  "--mat-color-accent": designTokens.color.accent,
  "--mat-color-canvas": designTokens.color.canvas,
  "--mat-color-surface": designTokens.color.surface,
  "--mat-color-surface-muted": designTokens.color.surfaceMuted,
  "--mat-color-text": designTokens.color.text,
  "--mat-color-text-muted": designTokens.color.textMuted,
  "--mat-color-border": designTokens.color.border,
  "--mat-color-focus": designTokens.color.focus,
  "--mat-color-success": designTokens.color.success,
  "--mat-color-warning": designTokens.color.warning,
  "--mat-color-danger": designTokens.color.danger,
  "--mat-font-sans": designTokens.typography.sans,
  "--mat-font-mono": designTokens.typography.mono,
  "--mat-radius-small": designTokens.radius.small,
  "--mat-radius-medium": designTokens.radius.medium,
  "--mat-radius-large": designTokens.radius.large,
  "--mat-shadow-small": designTokens.shadow.small,
  "--mat-shadow-medium": designTokens.shadow.medium,
  "--mat-shadow-overlay": designTokens.shadow.overlay,
  "--mat-focus-ring": designTokens.focusRing,
} as const);
