"use server";
import { createHash } from "node:crypto";
import { z } from "zod";
import { isLocale } from "@/modules/shared/lib/i18n/locale";
import { approvalInput, assistedCalendarApprovalInput, brandEvidenceReviewInput, brandKitInput, campaignInput, consentInput, scheduleInput, scheduleRuleActivationInput, scheduleRuleInput, templateInitializationInput } from "@/modules/shared/lib/marketing-autopilot/model";
import { getSupabaseServerClient } from "@/modules/shared/lib/supabase/server";
export type MarketingActionState={status:"idle"}|{status:"success";outcome:string}|{status:"error";reason:"VALIDATION"|"UNAUTHENTICATED"|"FORBIDDEN"|"CONFLICT"|"FAILED"};
const output=z.object({outcome:z.string().min(3)}).passthrough(),text=(f:FormData,k:string)=>String(f.get(k)??"");
const consentEvidence=z.string().trim().min(3).max(500),audienceSegment=z.enum(["ALL_CONSENTED","CLIENTS_CONSENTED","PROVIDERS_CONSENTED","FRANCHISES_CONSENTED"]),campaignSource=z.enum(["INTERNAL_EDITORIAL","DIAGNOSTIC_THEMES","SERVICE_REFERENTIAL"]);
function digestCanonical(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex")}
async function rpc(name:string,args:Record<string,unknown>):Promise<MarketingActionState>{const client=await getSupabaseServerClient(),{data}=await client.auth.getUser();if(!data.user)return{status:"error",reason:"UNAUTHENTICATED"};const result=await client.rpc(name,args);if(result.error){if(result.error.code==="42501")return{status:"error",reason:"FORBIDDEN"};if(["40001","23505","23514","55000"].includes(result.error.code??"")||/IDEMPOTENCY|STALE|CONSENT|BLOCKED|FREQUENCY/i.test(result.error.message??""))return{status:"error",reason:"CONFLICT"};return{status:"error",reason:"FAILED"}}const parsed=output.safeParse(result.data);return parsed.success?{status:"success",outcome:parsed.data.outcome}:{status:"error",reason:"FAILED"}}
function valid(f:FormData){return isLocale(text(f,"locale"))}
export async function recordConsent(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const evidence=consentEvidence.safeParse(text(f,"evidenceNote"));if(!evidence.success)return{status:"error",reason:"VALIDATION"};const values={organizationId:text(f,"organizationId"),purpose:text(f,"purpose"),decision:text(f,"decision"),policyVersion:"MARKETING-CONSENT-V1",evidenceHash:digestCanonical({organizationId:text(f,"organizationId"),purpose:text(f,"purpose"),decision:text(f,"decision"),evidence:evidence.data}),idempotencyKey:text(f,"idempotencyKey")},p=consentInput.safeParse(values);return p.success?rpc("record_marketing_consent",{p_organization_id:p.data.organizationId,p_purpose:p.data.purpose,p_decision:p.data.decision,p_policy_version:p.data.policyVersion,p_evidence_hash:p.data.evidenceHash,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function createCampaign(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const audience=audienceSegment.safeParse(text(f,"audienceSegment")),source=campaignSource.safeParse(text(f,"sourceType"));if(!audience.success||!source.success)return{status:"error",reason:"VALIDATION"};const p=campaignInput.safeParse({organizationId:text(f,"organizationId"),brandKitVersionId:text(f,"brandKitVersionId"),mode:text(f,"mode"),titleFr:text(f,"titleFr"),titleAr:text(f,"titleAr"),frequencyMaxWeekly:text(f,"frequencyMaxWeekly"),riskThreshold:text(f,"riskThreshold"),audienceSnapshot:{segment:audience.data,consent_required:true,minimum_aggregate:10},sourceSnapshot:{source:source.data,derived_by:"MARKETING_ADMIN_UI",version:1},idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("create_marketing_campaign",{p_organization_id:p.data.organizationId,p_brand_kit_version_id:p.data.brandKitVersionId,p_mode:p.data.mode,p_title_fr:p.data.titleFr,p_title_ar:p.data.titleAr,p_frequency_max_weekly:p.data.frequencyMaxWeekly,p_risk_threshold:p.data.riskThreshold,p_audience_snapshot:p.data.audienceSnapshot,p_source_snapshot:p.data.sourceSnapshot,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function approveCampaign(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=approvalInput.safeParse({campaignId:text(f,"campaignId"),rowVersion:text(f,"rowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("approve_marketing_campaign",{p_campaign_id:p.data.campaignId,p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function scheduleCampaign(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const local=text(f,"scheduledAt"),scheduledAt=local?`${local}:00.000Z`:"",p=scheduleInput.safeParse({campaignId:text(f,"campaignId"),contentVersionId:text(f,"contentVersionId"),socialConnectionId:text(f,"socialConnectionId"),scheduledAt,rowVersion:text(f,"rowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("schedule_marketing_campaign",{p_campaign_id:p.data.campaignId,p_items:[{content_version_id:p.data.contentVersionId,social_connection_id:p.data.socialConnectionId,scheduled_at:p.data.scheduledAt}],p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function createScheduleRule(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const slots=[{dayOfMonth:Number(text(f,"slotDay1")),time:text(f,"slotTime1")}];if(text(f,"slotDay2")||text(f,"slotTime2"))slots.push({dayOfMonth:Number(text(f,"slotDay2")),time:text(f,"slotTime2")});const p=scheduleRuleInput.safeParse({organizationId:text(f,"organizationId"),socialAccountId:text(f,"socialAccountId"),timezone:text(f,"timezone"),postsPerMonth:text(f,"postsPerMonth"),reelsPerMonth:text(f,"reelsPerMonth"),generationDay:text(f,"generationDay"),allowedSlots:slots,maxServiceRepetition:text(f,"maxServiceRepetition"),privacyMinimumAggregate:text(f,"privacyMinimumAggregate"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("create_marketing_schedule_rule_version_v1",{p_organization_id:p.data.organizationId,p_social_account_id:p.data.socialAccountId,p_timezone:p.data.timezone,p_posts_per_month:p.data.postsPerMonth,p_reels_per_month:p.data.reelsPerMonth,p_generation_day:p.data.generationDay,p_allowed_slots:p.data.allowedSlots,p_max_service_repetition:p.data.maxServiceRepetition,p_privacy_minimum_aggregate:p.data.privacyMinimumAggregate,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function activateScheduleRule(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=scheduleRuleActivationInput.safeParse({ruleId:text(f,"ruleId"),headRowVersion:text(f,"headRowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("activate_marketing_schedule_rule_version_v1",{p_rule_id:p.data.ruleId,p_expected_head_row_version:p.data.headRowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function approveAssistedCalendar(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=assistedCalendarApprovalInput.safeParse({calendarId:text(f,"calendarId"),rowVersion:text(f,"rowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("approve_assisted_marketing_calendar_v1",{p_calendar_id:p.data.calendarId,p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
const brandColor=z.string().regex(/^#[0-9a-fA-F]{6}$/),brandTone=z.enum(["PROFESSIONAL","PREMIUM","DIRECT","WARM"]),brandCta=z.enum(["DIAGNOSTIC","CONTACT","NEED"]),httpsUrl=z.string().url().startsWith("https://"),evidenceReference=z.string().trim().min(3).max(300);
function list(value:string){return value.split(/[\n,]/u).map(item=>item.trim()).filter(Boolean)}
function submittedClaim(f:FormData){
  const values={key:text(f,"claimKey").trim(),textFr:text(f,"claimTextFr").trim(),textAr:text(f,"claimTextAr").trim(),evidenceReference:text(f,"claimEvidenceReference").trim()};
  if(Object.values(values).every(value=>!value))return{success:true as const,value:null};
  const parsed=z.object({key:z.string().min(2).max(120),textFr:z.string().min(3).max(500),textAr:z.string().min(3).max(500),evidenceReference}).safeParse(values);
  return parsed.success?{success:true as const,value:{...parsed.data,evidenceHash:digestCanonical(parsed.data)}}:{success:false as const};
}
function submittedCertification(f:FormData){
  const values={key:text(f,"certificationKey").trim(),name:text(f,"certificationName").trim(),evidenceReference:text(f,"certificationEvidenceReference").trim()};
  if(Object.values(values).every(value=>!value))return{success:true as const,value:null};
  const parsed=z.object({key:z.string().min(2).max(120),name:z.string().min(3).max(200),evidenceReference}).safeParse(values);
  return parsed.success?{success:true as const,value:{...parsed.data,evidenceHash:digestCanonical(parsed.data)}}:{success:false as const};
}
export async function saveBrandKit(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{
  if(!valid(f))return{status:"error",reason:"VALIDATION"};
  const claim=submittedClaim(f),certification=submittedCertification(f);
  const config=z.object({primaryColor:brandColor,tone:brandTone,primaryCta:brandCta,trackedUrl:httpsUrl,allowedHost:z.string().trim().min(3).max(253),hashtags:z.array(z.string().regex(/^#[\p{L}\p{N}_-]{2,50}$/u)).max(20),forbiddenTerms:z.array(z.string().min(2).max(100)).max(50)}).safeParse({primaryColor:text(f,"primaryColor"),tone:text(f,"tone"),primaryCta:text(f,"primaryCta"),trackedUrl:text(f,"trackedUrl"),allowedHost:text(f,"allowedHost"),hashtags:list(text(f,"approvedHashtags")),forbiddenTerms:list(text(f,"forbiddenTerms"))});
  if(!config.success||!claim.success||!certification.success)return{status:"error",reason:"VALIDATION"};
  if(new URL(config.data.trackedUrl).hostname.toLowerCase()!==config.data.allowedHost.toLowerCase())return{status:"error",reason:"VALIDATION"};
  const payload={primary_colors:[config.data.primaryColor.toUpperCase()],tone:[config.data.tone],languages:["FR","AR"],primary_cta:config.data.primaryCta,tracked_url:config.data.trackedUrl,allowed_url_hosts:[config.data.allowedHost.toLowerCase()],logo_assets:[],asset_restrictions:[],required_mentions:[],forbidden_terms:config.data.forbiddenTerms,approved_hashtags:config.data.hashtags};
  const p=brandKitInput.safeParse({organizationId:text(f,"organizationId"),payload,claims:claim.value?[claim.value]:[],certifications:certification.value?[certification.value]:[],changeReason:text(f,"changeReason"),markReady:text(f,"markReady")==="on",idempotencyKey:text(f,"idempotencyKey")});
  return p.success?rpc("save_marketing_brand_kit_v1",{p_organization_id:p.data.organizationId,p_payload:p.data.payload,p_claims:p.data.claims,p_certifications:p.data.certifications,p_change_reason:p.data.changeReason,p_mark_ready:p.data.markReady,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"};
}
export async function initializeTemplates(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=templateInitializationInput.safeParse({idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("initialize_standard_marketing_templates_v1",{p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function reviewBrandEvidence(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{
  if(!valid(f))return{status:"error",reason:"VALIDATION"};
  const lookup=z.object({brandKitVersionId:z.string().uuid(),evidenceType:z.enum(["CLAIM","CERTIFICATION"]),evidenceKey:z.string().trim().min(2).max(120)}).safeParse({brandKitVersionId:text(f,"brandKitVersionId"),evidenceType:text(f,"evidenceType"),evidenceKey:text(f,"evidenceKey")});
  if(!lookup.success)return{status:"error",reason:"VALIDATION"};
  const client=await getSupabaseServerClient(),{data:user}=await client.auth.getUser();if(!user.user)return{status:"error",reason:"UNAUTHENTICATED"};
  const {data,error}=await client.from("brand_kit_versions").select("claims,certifications").eq("id",lookup.data.brandKitVersionId).maybeSingle();if(error||!data)return{status:"error",reason:error?.code==="42501"?"FORBIDDEN":"FAILED"};
  const source=lookup.data.evidenceType==="CLAIM"?data.claims:data.certifications,items=z.array(z.object({key:z.string(),evidenceHash:z.string().regex(/^[0-9a-f]{64}$/)}).passthrough()).safeParse(source);const evidence=items.success?items.data.find(item=>item.key===lookup.data.evidenceKey):undefined;if(!evidence)return{status:"error",reason:"VALIDATION"};
  const until=text(f,"validUntil"),p=brandEvidenceReviewInput.safeParse({...lookup.data,decision:text(f,"decision"),evidenceHash:evidence.evidenceHash,validUntil:until?`${until}:00.000Z`:null,reason:text(f,"reason"),idempotencyKey:text(f,"idempotencyKey")});
  return p.success?rpc("review_marketing_brand_evidence_v1",{p_brand_kit_version_id:p.data.brandKitVersionId,p_evidence_type:p.data.evidenceType,p_evidence_key:p.data.evidenceKey,p_decision:p.data.decision,p_evidence_hash:p.data.evidenceHash,p_valid_until:p.data.validUntil,p_reason:p.data.reason,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"};
}
const uuid=z.string().uuid(),date=z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/).transform(v=>`${v}:00.000Z`);
export async function recordBrandAuthorization(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{
  if(!valid(f))return{status:"error",reason:"VALIDATION"};
  const p=z.object({organizationId:uuid,decision:z.enum(["GRANTED","WITHDRAWN"]),scope:z.enum(["CONTENT_ONLY","CONTENT_AND_SOCIAL"]),source:z.enum(["SIGNED_MANDATE","BOARD_DECISION","AUTHORIZED_EMAIL"]),reason:z.string().trim().min(3).max(500),from:date,until:z.union([date,z.literal("")]),key:z.string().uuid()}).safeParse({organizationId:text(f,"organizationId"),decision:text(f,"decision"),scope:text(f,"authorizationScope"),source:text(f,"authorizationSource"),reason:text(f,"authorizationReason"),from:text(f,"effectiveFrom"),until:text(f,"effectiveUntil"),key:text(f,"idempotencyKey")});
  if(!p.success)return{status:"error",reason:"VALIDATION"};const scopes=p.data.scope==="CONTENT_ONLY"?["CONTENT_GENERATION"]:["CONTENT_GENERATION","SOCIAL_PUBLISHING"],policy="MARKETING-BRAND-AUTHORIZATION-V1",evidence=digestCanonical({organizationId:p.data.organizationId,decision:p.data.decision,scopes,policy,source:p.data.source,reason:p.data.reason,from:p.data.from,until:p.data.until||null});
  return rpc("record_marketing_brand_authorization_v41",{p_organization_id:p.data.organizationId,p_decision:p.data.decision,p_authorization_scope:scopes,p_policy_version:policy,p_evidence_hash:evidence,p_effective_from:p.data.from,p_effective_until:p.data.until||null,p_idempotency_key:p.data.key});
}
export async function recordConnectionSecurity(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{
  if(!valid(f))return{status:"error",reason:"VALIDATION"};
  const p=z.object({connectionId:uuid,status:z.enum(["ACTIVE","REVOKED","ROTATION_REQUIRED"]),expires:z.union([date,z.literal("")]),reason:z.string().trim().min(3).max(500),key:z.string().uuid()}).safeParse({connectionId:text(f,"connectionId"),status:text(f,"status"),expires:text(f,"expiresAt"),reason:text(f,"securityReason"),key:text(f,"idempotencyKey")});if(!p.success)return{status:"error",reason:"VALIDATION"};
  const client=await getSupabaseServerClient(),{data:user}=await client.auth.getUser();if(!user.user)return{status:"error",reason:"UNAUTHENTICATED"};const {data,error}=await client.from("social_connections").select("id,provider,credential_reference,scopes").eq("id",p.data.connectionId).maybeSingle();if(error||!data)return{status:"error",reason:error?.code==="42501"?"FORBIDDEN":"FAILED"};
  const connection=z.object({id:uuid,provider:z.enum(["LINKEDIN","META"]),credential_reference:z.string().min(8).max(300),scopes:z.array(z.string().min(2)).min(1)}).safeParse(data);if(!connection.success)return{status:"error",reason:"FAILED"};const required=connection.data.provider==="LINKEDIN"?"w_member_social":"pages_manage_posts",scopes=Array.from(new Set([...connection.data.scopes,required]));const fingerprint=digestCanonical({connectionId:connection.data.id,credentialReference:connection.data.credential_reference,provider:connection.data.provider});
  return rpc("record_social_connection_security_v41",{p_social_connection_id:p.data.connectionId,p_status:p.data.status,p_vault_credential_reference:connection.data.credential_reference,p_ciphertext_fingerprint:fingerprint,p_approved_scopes:scopes,p_expires_at:p.data.expires||null,p_idempotency_key:p.data.key});
}
export async function setKillSwitch(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{
  if(!valid(f))return{status:"error",reason:"VALIDATION"};
  const p=z.object({organizationId:z.union([uuid,z.literal("")]),scope:z.enum(["GLOBAL","PROVIDER"]),provider:z.union([z.enum(["LINKEDIN","META"]),z.literal("")]),enabled:z.enum(["yes","no"]),reason:z.string().trim().min(3).max(1000),source:z.enum(["SECURITY_INCIDENT","COMPLIANCE_DECISION","OPERATIONAL_SAFETY","RESUME_APPROVED"]),key:z.string().uuid()}).safeParse({organizationId:text(f,"organizationId"),scope:text(f,"scope"),provider:text(f,"provider"),enabled:text(f,"enabled"),reason:text(f,"reason"),source:text(f,"decisionSource"),key:text(f,"idempotencyKey")});if(!p.success||(p.data.scope==="GLOBAL"&&p.data.provider)||(p.data.scope==="PROVIDER"&&!p.data.provider))return{status:"error",reason:"VALIDATION"};const evidence=digestCanonical({organizationId:p.data.organizationId||null,scope:p.data.scope,provider:p.data.provider||null,enabled:p.data.enabled==="yes",source:p.data.source,reason:p.data.reason});
  return rpc("set_marketing_kill_switch_v41",{p_organization_id:p.data.organizationId||null,p_scope:p.data.scope,p_provider:p.data.provider||null,p_enabled:p.data.enabled==="yes",p_reason:p.data.reason,p_evidence_hash:evidence,p_idempotency_key:p.data.key});
}
