import { z } from "zod";
export const uuid=z.string().uuid();export const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);export const currency=z.string().regex(/^[A-Z]{3}$/);export const minor=z.coerce.number().int().positive().max(Number.MAX_SAFE_INTEGER);export const hash=z.string().regex(/^[0-9a-f]{64}$/);
export const statementInput=z.object({organizationId:uuid,statementNumber:z.string().trim().min(3).max(80),periodStart:date,periodEnd:date,currency,idempotencyKey:uuid}).refine(v=>v.periodEnd>=v.periodStart,{path:["periodEnd"]});
export const payableInput=z.object({missionId:uuid,eventType:z.enum(["CLIENT_RECEIPT_CONFIRMED","COMMISSION_ACCRUAL","PENALTY_ACCRUAL","ADJUSTMENT"]),occurredOn:date,currency,grossAmountMinor:minor,clientReceiptReference:z.string().trim().min(3).max(200),proofHash:hash,idempotencyKey:uuid});
export const invoiceInput=z.object({statementId:uuid,invoiceNumber:z.string().trim().min(3).max(80),issuedOn:date,dueOn:date,receivableAccountId:uuid,revenueAccountId:uuid,taxLiabilityAccountId:uuid,idempotencyKey:uuid}).refine(v=>v.dueOn>=v.issuedOn,{path:["dueOn"]});
export const paymentInput=z.object({organizationId:uuid,paymentReference:z.string().trim().min(3).max(200),paidOn:date,paymentMethod:z.enum(["BANK_TRANSFER","CARD","CHECK","CASH","OTHER"]),currency,amountMinor:minor,proofHash:hash,cashAccountId:uuid,receivableAccountId:uuid,idempotencyKey:uuid});
export const reconciliationInput=z.object({paymentId:uuid,invoiceId:uuid,amountMinor:minor,idempotencyKey:uuid});
export type BillingDashboard={organizationId:string;organizationName:string;payables:Array<{id:string;occurredOn:string;eventType:string;currency:string;totalDueMinor:string}>;statements:Array<{id:string;number:string;periodStart:string;periodEnd:string;currency:string;totalMinor:string}>;invoices:Array<{id:string;number:string;currency:string;totalMinor:string;paidMinor:string;outstandingMinor:string;paymentStatus:string;dueOn:string}>;payments:Array<{id:string;reference:string;currency:string;amountMinor:string;paidOn:string}>;accounts:Array<{id:string;code:string;currency:string}>};
export function formatMinor(value:string,currencyCode:string,locale:"fr"|"ar"){const amount=BigInt(value);const hundred=BigInt(100);const whole=amount/hundred;const cents=(amount%hundred).toString().padStart(2,"0");const tag=locale==="ar"?"ar-MA":"fr-MA";const integer=new Intl.NumberFormat(tag,{maximumFractionDigits:0}).format(whole);return new Intl.NumberFormat(tag,{style:"currency",currency:currencyCode,minimumFractionDigits:2,maximumFractionDigits:2}).formatToParts(0).map(part=>part.type==="integer"?integer:part.type==="fraction"?cents:part.value).join("")}
