import { createHash } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({getUser:vi.fn(),rpc:vi.fn(),upload:vi.fn(),download:vi.fn(),remove:vi.fn()}));
vi.mock("@/modules/shared/lib/supabase/server",()=>({getSupabaseServerClient:async()=>({auth:{getUser:mocks.getUser},rpc:mocks.rpc,storage:{from:()=>({upload:mocks.upload,download:mocks.download,remove:mocks.remove})}})}));
vi.mock("@/modules/shared/lib/i18n/locale",()=>({isLocale:(value:string)=>value==="fr"||value==="ar"}));
vi.mock("@/modules/provider/data/missions/model",async()=>await import("@/modules/provider/data/missions/model"));
import{completeProviderChecklistItem,submitProviderDelivery,type DeliveryActionState}from"./actions";
const idle:DeliveryActionState={status:"idle"};
const deliverableId="11111111-1111-4111-8111-111111111111",key="22222222-2222-4222-8222-222222222222",userId="33333333-3333-4333-8333-333333333333";
const pdf=Uint8Array.from([0x25,0x50,0x44,0x46,0x2d,0x31,0x2e,0x37,0x0a]);
function valid(){const f=new FormData();f.set("locale","fr");f.set("deliverableId",deliverableId);f.set("description","Rapport final validé");f.set("linksText","https://example.test/result");f.set("proofNote","Version signée");f.set("idempotencyKey",key);f.set("proofFile",new File([pdf],"rapport final.pdf",{type:"application/pdf"}));return f;}
beforeEach(()=>{mocks.getUser.mockReset().mockResolvedValue({data:{user:{id:userId}}});mocks.rpc.mockReset().mockResolvedValue({data:{outcome:"DELIVERY_SUBMITTED"},error:null});mocks.upload.mockReset().mockResolvedValue({data:{path:"ok"},error:null});mocks.download.mockReset();mocks.remove.mockReset().mockResolvedValue({data:[],error:null});});
describe("provider delivery action",()=>{
  it("uploads the real file then binds its computed digest",async()=>{const digest=createHash("sha256").update(pdf).digest("hex");await expect(submitProviderDelivery(idle,valid())).resolves.toEqual({status:"success",outcome:"DELIVERY_SUBMITTED"});expect(mocks.upload).toHaveBeenCalledWith(`${userId}/${deliverableId}/${key}/rapport-final.pdf`,expect.any(Buffer),expect.objectContaining({contentType:"application/pdf",upsert:false}));expect(mocks.rpc).toHaveBeenCalledWith("submit_delivery",expect.objectContaining({p_deliverable_id:deliverableId,p_proofs:[expect.objectContaining({evidence_hash:digest,storage_path:`${userId}/${deliverableId}/${key}/rapport-final.pdf`,url:null})]}));});
  it("rejects forged MIME content before Storage",async()=>{const f=valid();f.set("proofFile",new File(["not a pdf"],"fake.pdf",{type:"application/pdf"}));await expect(submitProviderDelivery(idle,f)).resolves.toEqual({status:"error",reason:"VALIDATION"});expect(mocks.upload).not.toHaveBeenCalled();expect(mocks.rpc).not.toHaveBeenCalled();});
  it("fails closed when private Storage rejects the upload",async()=>{mocks.upload.mockResolvedValueOnce({data:null,error:{statusCode:"403"}});await expect(submitProviderDelivery(idle,valid())).resolves.toEqual({status:"error",reason:"FAILED"});expect(mocks.rpc).not.toHaveBeenCalled();});
  it("accepts a 409 replay only when the existing object has the same digest",async()=>{mocks.upload.mockResolvedValueOnce({data:null,error:{statusCode:"409"}});mocks.download.mockResolvedValueOnce({data:new Blob([pdf]),error:null});await expect(submitProviderDelivery(idle,valid())).resolves.toEqual({status:"success",outcome:"DELIVERY_SUBMITTED"});expect(mocks.rpc).toHaveBeenCalledTimes(1)});
  it("rejects a 409 collision with different bytes",async()=>{mocks.upload.mockResolvedValueOnce({data:null,error:{statusCode:"409"}});mocks.download.mockResolvedValueOnce({data:new Blob(["foreign"]),error:null});await expect(submitProviderDelivery(idle,valid())).resolves.toEqual({status:"error",reason:"CONFLICT"});expect(mocks.rpc).not.toHaveBeenCalled()});
  it("removes the newly uploaded orphan when binding RPC fails",async()=>{mocks.rpc.mockResolvedValueOnce({data:null,error:{code:"42501"}});await expect(submitProviderDelivery(idle,valid())).resolves.toEqual({status:"error",reason:"FORBIDDEN"});expect(mocks.remove).toHaveBeenCalledWith([`${userId}/${deliverableId}/${key}/rapport-final.pdf`])});
  it("never removes a pre-existing 409 replay object when RPC fails",async()=>{mocks.upload.mockResolvedValueOnce({data:null,error:{statusCode:"409"}});mocks.download.mockResolvedValueOnce({data:new Blob([pdf]),error:null});mocks.rpc.mockResolvedValueOnce({data:null,error:{code:"55000"}});await expect(submitProviderDelivery(idle,valid())).resolves.toEqual({status:"error",reason:"CONFLICT"});expect(mocks.remove).not.toHaveBeenCalled()});
});
describe("provider checklist action",()=>{it("binds a CLEAN proof candidate through the governed RPC",async()=>{const form=new FormData();form.set("locale","fr");form.set("itemId",deliverableId);form.set("expectedStatus","PENDING");form.set("proofId",userId);form.set("idempotencyKey",key);mocks.rpc.mockResolvedValueOnce({data:{outcome:"MISSION_CHECKLIST_ITEM_COMPLETED"},error:null});await expect(completeProviderChecklistItem(idle,form)).resolves.toEqual({status:"success",outcome:"MISSION_CHECKLIST_ITEM_COMPLETED"});expect(mocks.rpc).toHaveBeenCalledWith("complete_mission_checklist_item",{p_item_id:deliverableId,p_expected_status:"PENDING",p_proof_id:userId,p_idempotency_key:key})});});
