import { z } from "zod";

export const quoteUuid = z.string().uuid();
export const exactMinor = z.string().regex(/^\d{1,18}$/u);
export const exactQuantity = z.string().regex(/^\d{1,14}(?:\.\d{1,4})?$/u);
export const quoteDraftInput = z.object({
  locale:z.enum(["fr","ar"]),rfqProviderId:quoteUuid,currency:z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/u),solutionFr:z.string().trim().min(3).max(12000),solutionAr:z.string().trim().max(12000),deliverables:z.string().trim().min(2).max(6000),inclusions:z.string().max(6000),exclusions:z.string().max(6000),prerequisites:z.string().max(6000),warrantyFr:z.string().trim().min(3).max(2000),warrantyAr:z.string().trim().max(2000),correctionTermsFr:z.string().trim().min(3).max(2000),correctionTermsAr:z.string().trim().max(2000),proposedStartDate:z.string().date(),durationDays:z.coerce.number().int().min(1).max(3650),validUntil:z.string().datetime(),lineLabelFr:z.string().trim().min(2).max(500),lineLabelAr:z.string().trim().max(500),quantity:exactQuantity,unitCode:z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_]{0,31}$/u),unitPriceMinor:exactMinor,taxRuleVersionId:quoteUuid,itemKind:z.enum(["ONE_TIME","RECURRING"]),recurrenceInterval:z.enum(["","MONTH","QUARTER","YEAR"]),changeReason:z.string().trim().min(3).max(1000),idempotencyKey:quoteUuid,correlationId:quoteUuid,
}).superRefine((value,context)=>{if((value.itemKind==="RECURRING")!==(value.recurrenceInterval!==""))context.addIssue({code:"custom",path:["recurrenceInterval"],message:"RECURRENCE_MISMATCH"});if(Date.parse(value.validUntil)<=Date.now())context.addIssue({code:"custom",path:["validUntil"],message:"VALIDITY_EXPIRED"});});
export const invitationDecisionInput=z.object({locale:z.enum(["fr","ar"]),invitationId:quoteUuid,decision:z.enum(["ACCEPT","DECLINE"]),reason:z.string().trim().max(500),rowVersion:z.coerce.number().int().positive(),idempotencyKey:quoteUuid,correlationId:quoteUuid}).superRefine((v,c)=>{if(v.decision==="DECLINE"&&v.reason.length<3)c.addIssue({code:"custom",path:["reason"],message:"REASON_REQUIRED"});});
export const submitQuoteInput=z.object({locale:z.enum(["fr","ar"]),quoteId:quoteUuid,quoteVersionId:quoteUuid,idempotencyKey:quoteUuid,correlationId:quoteUuid});
export const lines=(value:string)=>value.split(/\r?\n/u).map(item=>item.trim()).filter(Boolean).slice(0,100);export function formatBasisPointsExact(value:number):string{if(!Number.isInteger(value)||value<0)throw new Error("INVALID_BASIS_POINTS");const digits=String(value).padStart(3,"0"),whole=digits.slice(0,-2),fraction=digits.slice(-2).replace(/0+$/u,"");return fraction?`${whole}.${fraction}`:whole;}
export type ProviderTaxRule={id:string;category:string;rateBasisPoints:number;effectiveFrom:string;effectiveTo:string|null};
export function isTaxRuleApplicable(rule:ProviderTaxRule,effectiveOn:string):boolean{return /^\d{4}-\d{2}-\d{2}$/u.test(effectiveOn)&&rule.effectiveFrom<=effectiveOn&&(rule.effectiveTo===null||rule.effectiveTo>=effectiveOn);}
export function taxRulesForCategory(rules:ProviderTaxRule[],category:string|null):ProviderTaxRule[]{return category!==null&&/^[A-Z][A-Z0-9_]{2,79}$/u.test(category)?rules.filter(rule=>rule.category===category):[];}
export type ProviderQuoteDashboard={organizations:{id:string;name:string}[];organizationId:string;organizationName:string;canManage:boolean;taxRules:ProviderTaxRule[];invitations:{id:string;status:"INVITED"|"VIEWED"|"ACCEPTED"|"DECLINED"|"WITHDRAWN"|"SUSPENDED";rowVersion:number;rfqId:string;deadline:string;requestId:string;description:string;regionCode:string;currency:string;taxCategoryCode:string|null;quote:null|{id:string;status:string;currentVersionId:string|null;versionNumber:number|null;currency:string|null;subtotalMinor:string|null;taxMinor:string|null;totalMinor:string|null}}[]};
