import type { Locale } from "@/modules/shared/lib/i18n/locale";

const fr = {
  eyebrow: "Administration Matricia", title: "Sous-traitants — qualification et facturation", description: "Traitez les preuves, décisions de qualification et exceptions financières sans contourner les contrôles métier.", back: "Centre de commande", language: "العربية", navigation: "Navigation administrateur", loadError: "Les données Sous-traitants ne peuvent pas être chargées.", forbiddenPage: "Votre rôle ne permet pas d’accéder à cette supervision.", retry: "Réessayer", limited: "Résultats plafonnés pour préserver les capacités de la plateforme. Affinez le traitement par file.", readOnly: "Consultation uniquement : votre rôle ne permet aucune décision.", noQualificationRights: "Votre rôle permet la consultation, mais pas les décisions de qualification.", noFinanceRights: "Votre rôle permet la consultation, mais pas les opérations financières.",
  providers: "Validation société", providersEmpty: "Aucun profil Sous-traitant dans la file.", services: "Qualifications par service", servicesEmpty: "Aucune qualification de service dans la file.", documents: "Preuves documentaires", documentsEmpty: "Aucun document dans la file.", finance: "Facturation et rapprochement", financeEmpty: "Aucune donnée financière disponible.", overview: "Vue d’ensemble", organization: "Organisation", service: "Service", companyStatus: "Statut société", overallStatus: "Statut global", contractStatus: "Contrat partenaire", requestStatus: "Demande", qualificationStatus: "Qualification", evidenceStatus: "Preuve", eligibility: "Éligibilité", eligible: "Éligible", notEligible: "Non éligible", noReason: "Aucun blocage retourné par le moteur.", ruleVersion: "Version de règle", decisionVersion: "Version de décision", checkedAt: "Vérifié le", expires: "Expiration", noExpiry: "Sans expiration", document: "Document", version: "Version",
  providerCount: "Sous-traitants", qualificationCount: "Services à examiner", documentCount: "Documents à examiner", overdueCount: "Factures en retard", invoiced: "Facturé", outstanding: "À recevoir", received: "Règlements", currencySummary: "Synthèse par devise", noFinancialTotals: "Aucun total financier.",
  decideCompany: "Décider la validation société", companyDecision: "Décision société", partnerContract: "Statut du contrat", contractExpiry: "Expiration du contrat", reason: "Motif documenté", rule: "Règle appliquée", submitDecision: "Enregistrer la décision", reviewDocument: "Examiner ce document", reviewStatus: "Résultat de l’examen", review: "Enregistrer l’examen", decideQualification: "Décider la qualification", questionnaireSession: "Dernier questionnaire soumis", score: "Résultat vérifié (%)", mandatoryChecks: "J’ai examiné le questionnaire soumis et les preuves obligatoires.", blockingConditions: "Conditions à lever (une par ligne)", decisionExpiry: "Expiration de la décision", qualificationDecision: "Décision de qualification",
  issueStatement: "Émettre un relevé", statementNumber: "Numéro du relevé", periodStart: "Début de période", periodEnd: "Fin de période", currency: "Devise", issue: "Émettre", issueInvoice: "Émettre la facture", statement: "Relevé", invoiceNumber: "Numéro de facture", issuedOn: "Date d’émission", dueOn: "Échéance", receivableAccount: "Compte client", revenueAccount: "Compte produit", taxAccount: "Compte fiscal", recordPayment: "Enregistrer un règlement", paymentReference: "Référence du règlement", paidOn: "Date du règlement", method: "Mode de paiement", amountMinor: "Montant", amount: "Montant", proofHash: "Preuve", proofFile: "Justificatif (PDF, JPG ou PNG)", cashAccount: "Compte trésorerie", reconcile: "Rapprocher", payment: "Règlement", invoice: "Facture", paymentAmount: "Montant du règlement", allocated: "Rapproché", unallocated: "Non rapproché", total: "Total", paid: "Payé", due: "Solde", actions: "Actions contrôlées", choose: "Sélectionner", processing: "Traitement…", success: "Opération enregistrée. Actualisez la page pour afficher le nouvel état.", validation: "Vérifiez les champs, les preuves et la cohérence de la décision.", forbidden: "Votre rôle ne permet pas cette opération.", conflict: "L’état ou le solde a changé. Actualisez avant de reprendre la décision.", failed: "Échec sans modification. Réessayez après vérification.", minorHelp: "Saisissez le montant dans la devise affichée.", amountHelp: "Saisissez le montant dans la devise affichée, par exemple 1 250,50 MAD. La conversion exacte est effectuée côté serveur.", bankTransfer: "Virement bancaire", card: "Carte", check: "Chèque", cash: "Espèces", other: "Autre", immutableHelp: "Les écritures et décisions sont ajoutées à l’historique ; elles ne sont pas modifiées sur place.",
  issueCreditNote: "Émettre un avoir", creditNumber: "Numéro d’avoir", subtotal: "Hors taxe", tax: "TVA", creditHint: "La TVA est recalculée par le moteur fiscal versionné à partir de la facture d’origine. La facture n’est jamais réécrite.",
  decidePlan: "Décider un échéancier", plan: "Échéancier", approvePlan: "Approuver", rejectPlan: "Rejeter", requestedPlansEmpty: "Aucun échéancier en attente.",
  openCollection: "Ouvrir un recouvrement", advanceCollection: "Avancer le recouvrement", collectionCase: "Dossier", formalNotice: "Mise en demeure", collection: "Recouvrement", closeCollection: "Clôturer", collectionHint: "Un dossier ouvert défait l’échéancier approuvé. Les statuts s’ajoutent à l’historique.",
  creditNotes: "Avoirs", paymentPlans: "Échéanciers", collectionCases: "Recouvrements",
} as const;
const ar: { [K in keyof typeof fr]: string } = {
  eyebrow: "إدارة ماتريسيا", title: "مقدمو الخدمات — التأهيل والفوترة", description: "عالج الأدلة وقرارات التأهيل والاستثناءات المالية دون تجاوز الضوابط المهنية.", back: "مركز القيادة", language: "Français", navigation: "تنقل الإدارة", loadError: "تعذر تحميل بيانات مقدمي الخدمات.", forbiddenPage: "دورك لا يسمح بالوصول إلى هذه المراقبة.", retry: "إعادة المحاولة", limited: "تم تحديد عدد النتائج للحفاظ على قدرة المنصة. عالج كل قائمة على حدة.", readOnly: "للقراءة فقط: دورك لا يسمح باتخاذ أي قرار.", noQualificationRights: "يسمح دورك بالاطلاع دون اتخاذ قرارات التأهيل.", noFinanceRights: "يسمح دورك بالاطلاع دون تنفيذ العمليات المالية.",
  providers: "التحقق من الشركة", providersEmpty: "لا يوجد ملف مقدم خدمات في القائمة.", services: "التأهيل حسب الخدمة", servicesEmpty: "لا توجد خدمة في قائمة التأهيل.", documents: "الأدلة الوثائقية", documentsEmpty: "لا يوجد مستند في القائمة.", finance: "الفوترة والمطابقة", financeEmpty: "لا توجد بيانات مالية متاحة.", overview: "نظرة عامة", organization: "المؤسسة", service: "الخدمة", companyStatus: "حالة الشركة", overallStatus: "الحالة العامة", contractStatus: "عقد الشريك", requestStatus: "الطلب", qualificationStatus: "التأهيل", evidenceStatus: "الدليل", eligibility: "الأهلية", eligible: "مؤهل", notEligible: "غير مؤهل", noReason: "لم يرجع المحرك أي عائق.", ruleVersion: "نسخة القاعدة", decisionVersion: "نسخة القرار", checkedAt: "تاريخ التحقق", expires: "الانتهاء", noExpiry: "دون انتهاء", document: "المستند", version: "النسخة",
  providerCount: "مقدمو الخدمات", qualificationCount: "خدمات للمراجعة", documentCount: "مستندات للمراجعة", overdueCount: "فواتير متأخرة", invoiced: "المفوتر", outstanding: "المستحق", received: "المدفوعات", currencySummary: "ملخص حسب العملة", noFinancialTotals: "لا توجد إجماليات مالية.",
  decideCompany: "اتخاذ قرار التحقق من الشركة", companyDecision: "قرار الشركة", partnerContract: "حالة العقد", contractExpiry: "انتهاء العقد", reason: "سبب موثق", rule: "القاعدة المطبقة", submitDecision: "تسجيل القرار", reviewDocument: "مراجعة المستند", reviewStatus: "نتيجة المراجعة", review: "تسجيل المراجعة", decideQualification: "اتخاذ قرار التأهيل", questionnaireSession: "آخر استبيان مرسل", score: "النتيجة المحققة (%)", mandatoryChecks: "راجعت الاستبيان المرسل والأدلة الإلزامية.", blockingConditions: "الشروط المطلوب استيفاؤها (شرط في كل سطر)", decisionExpiry: "انتهاء القرار", qualificationDecision: "قرار التأهيل",
  issueStatement: "إصدار كشف", statementNumber: "رقم الكشف", periodStart: "بداية الفترة", periodEnd: "نهاية الفترة", currency: "العملة", issue: "إصدار", issueInvoice: "إصدار الفاتورة", statement: "الكشف", invoiceNumber: "رقم الفاتورة", issuedOn: "تاريخ الإصدار", dueOn: "تاريخ الاستحقاق", receivableAccount: "حساب العميل", revenueAccount: "حساب الإيراد", taxAccount: "حساب الضريبة", recordPayment: "تسجيل دفعة", paymentReference: "مرجع الدفعة", paidOn: "تاريخ الدفع", method: "طريقة الدفع", amountMinor: "المبلغ", amount: "المبلغ", proofHash: "الإثبات", proofFile: "المستند المؤيد (PDF أو JPG أو PNG)", cashAccount: "حساب الخزينة", reconcile: "مطابقة", payment: "الدفعة", invoice: "الفاتورة", paymentAmount: "مبلغ الدفعة", allocated: "المطابق", unallocated: "غير المطابق", total: "المجموع", paid: "المدفوع", due: "الرصيد", actions: "إجراءات مضبوطة", choose: "اختر", processing: "جارٍ التنفيذ…", success: "تم تسجيل العملية. حدّث الصفحة لعرض الحالة الجديدة.", validation: "راجع الحقول والأدلة واتساق القرار.", forbidden: "دورك لا يسمح بهذه العملية.", conflict: "تغيرت الحالة أو الرصيد. حدّث الصفحة قبل متابعة القرار.", failed: "فشلت العملية دون تعديل. أعد المحاولة بعد التحقق.", minorHelp: "أدخل المبلغ بالعملة المعروضة.", amountHelp: "أدخل المبلغ بالعملة المعروضة، مثلاً 1 250,50 MAD. يتم التحويل الدقيق على الخادم.", bankTransfer: "تحويل بنكي", card: "بطاقة", check: "شيك", cash: "نقداً", other: "أخرى", immutableHelp: "تضاف القيود والقرارات إلى السجل ولا تعدل في مكانها.",
  issueCreditNote: "إصدار إشعار دائن", creditNumber: "رقم الإشعار الدائن", subtotal: "بدون ضريبة", tax: "الضريبة", creditHint: "يُعاد حساب الضريبة عبر المحرك الضريبي المُصدَّر من الفاتورة الأصلية. لا تُعاد كتابة الفاتورة.",
  decidePlan: "البت في جدول الاستحقاق", plan: "جدول الاستحقاق", approvePlan: "الموافقة", rejectPlan: "الرفض", requestedPlansEmpty: "لا يوجد جدول استحقاق قيد الانتظار.",
  openCollection: "فتح ملف تحصيل", advanceCollection: "تقديم ملف التحصيل", collectionCase: "الملف", formalNotice: "إنذار رسمي", collection: "تحصيل", closeCollection: "إغلاق", collectionHint: "يفسخ الملف المفتوح جدول الاستحقاق المعتمد. تُضاف الحالات إلى السجل.",
  creditNotes: "الإشعارات الدائنة", paymentPlans: "جداول الاستحقاق", collectionCases: "ملفات التحصيل",
};
export type AdminProviderMessages = { [K in keyof typeof fr]: string };
export function getAdminProviderMessages(locale: Locale): AdminProviderMessages { return locale === "ar" ? ar : fr; }
