import{z}from"zod";
export const uuid=z.string().uuid(),hash=z.string().regex(/^[0-9a-f]{64}$/),money=z.coerce.number().int().min(-Number.MAX_SAFE_INTEGER).max(Number.MAX_SAFE_INTEGER);
export const submitContractSchema=z.object({contractId:uuid,rowVersion:z.coerce.number().int().positive(),idempotencyKey:uuid});
export const signContractSchema=z.object({contractId:uuid,contractVersionId:uuid,organizationId:uuid,contractHash:hash,signerRole:z.string().trim().min(2).max(80),method:z.string().trim().min(2).max(80),signedAt:z.string().datetime(),evidenceHash:hash,idempotencyKey:uuid});
export const missionSchema=z.object({contractId:uuid,contractVersionId:uuid,milestoneKey:z.string().trim().regex(/^[A-Z][A-Z0-9_-]{1,79}$/),titleFr:z.string().trim().min(2).max(300),titleAr:z.string().trim().min(2).max(300),dueAt:z.union([z.literal(""),z.string().datetime()]),deliverableKey:z.string().trim().regex(/^[A-Z][A-Z0-9_-]{1,79}$/),labelFr:z.string().trim().min(2).max(300),labelAr:z.string().trim().min(2).max(300),criterionKey:z.string().trim().regex(/^[A-Z][A-Z0-9_-]{1,79}$/),idempotencyKey:uuid});
export const acceptanceSchema=z.object({deliverableId:uuid,criteria:z.array(z.object({criterion_key:z.string().min(2),status:z.enum(["COMPLIANT","NONCOMPLIANT","NA"]),comment:z.string().max(1000),evidence:z.array(z.unknown())})).min(1),idempotencyKey:uuid});
export const milestoneDecisionSchema=z.object({milestoneId:uuid,expectedRowVersion:z.coerce.number().int().positive(),decision:z.enum(["ACCEPTED","REJECTED"]),reason:z.string().trim().min(3).max(1000),idempotencyKey:uuid});
export const amendmentSchema=z.object({contractId:uuid,reason:z.string().trim().min(3).max(2000),scopeDelta:z.string().trim().min(2).max(4000),priceDeltaMinor:money,deadlineDeltaDays:z.coerce.number().int().min(-3650).max(3650),idempotencyKey:uuid});
export type ContractItemType="DELIVERABLE"|"EXCLUSION"|"ACCEPTANCE_CRITERION"|"PAYMENT_TERM"|"CORRECTION"|"PENALTY";
export type ContractItem={id:string;key:string;type:ContractItemType;label:string;sortOrder:number};
export type ContractSignature={id:string;organizationId:string;signerRole:string;contractHash:string;signedAt:string;method:string;evidenceHash:string};
export type MissionContractSnapshot={versionId:string;version:number;selectedQuoteVersionId:string;priceMinor:string;currency:string;contentHash:string;changeReason:string;createdAt:string;items:ContractItem[];signatures:ContractSignature[]};
export type ProofScanStatus="NONE"|"PENDING"|"CLEAN"|"INFECTED"|"ERROR";
export type ContractMissionDashboard={organizationId:string;organizationName:string;contracts:Array<{id:string;providerOrganizationId:string;status:string;currentVersion:number;rowVersion:number;versionId:string;selectedQuoteVersionId:string;priceMinor:string;currency:string;contentHash:string;changeReason:string;createdAt:string;signatureCount:number;signatures:ContractSignature[];items:ContractItem[];history:Array<{id:string;version:number;selectedQuoteVersionId:string;priceMinor:string;currency:string;contentHash:string;changeReason:string;createdAt:string}>}>;missions:Array<{id:string;contractId:string;contractVersionId:string;contractSnapshot:MissionContractSnapshot;status:string;startedAt:string|null;completedAt:string|null;milestones:Array<{id:string;key:string;title:string;status:string;dueAt:string|null;rowVersion:number}>;deliverables:Array<{id:string;key:string;label:string;status:string;currentVersion:number;proofScanStatus:ProofScanStatus;criteria:Array<{key:string;status:string}>}>}>};
export function formatExactMoney(minor:string,currency:string,locale:"fr"|"ar"){const n=BigInt(minor),zero=BigInt(0),hundred=BigInt(100),negative=n<zero,absolute=negative?-n:n,whole=absolute/hundred,fraction=(absolute%hundred).toString().padStart(2,"0"),tag=locale==="ar"?"ar-MA":"fr-MA";const integer=new Intl.NumberFormat(tag,{maximumFractionDigits:0}).format(whole),sample=negative?-1:0;return new Intl.NumberFormat(tag,{style:"currency",currency,minimumFractionDigits:2}).formatToParts(sample).map(p=>p.type==="integer"?integer:p.type==="fraction"?fraction:p.value).join("")}
