"use server";
import{z}from"zod";import{isLocale}from"@/lib/i18n/locale";import{activitySchema,pipelineSchema,prospectSchema,snapshotSchema}from"@/lib/franchise-crm/model";import{getSupabaseServerClient}from"@/lib/supabase/server";
export type FranchiseCrmActionState={status:"idle"}|{status:"success";outcome:string}|{status:"error";reason:"VALIDATION"|"UNAUTHENTICATED"|"FORBIDDEN"|"CONFLICT"|"FAILED"};
const outcome=z.object({outcome:z.string().min(3)}).passthrough(),text=(f:FormData,k:string)=>String(f.get(k)??""),evidence=(value:string)=>value?[{reference:value}]:[],iso=(value:string)=>{if(!value)return"";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toISOString()};
async function rpc(name:string,args:Record<string,unknown>):Promise<FranchiseCrmActionState>{const c=await getSupabaseServerClient(),{data:a}=await c.auth.getUser();if(!a.user)return{status:"error",reason:"UNAUTHENTICATED"};const r=await c.rpc(name,args);if(r.error){if(r.error.code==="42501")return{status:"error",reason:"FORBIDDEN"};if(["40001","23505","23514"].includes(r.error.code??"")||/STALE|IDEMPOTENCY|TRANSITION/i.test(r.error.message??""))return{status:"error",reason:"CONFLICT"};return{status:"error",reason:"FAILED"}}const p=outcome.safeParse(r.data);return p.success?{status:"success",outcome:p.data.outcome}:{status:"error",reason:"FAILED"}}
function locale(f:FormData){return isLocale(text(f,"locale"));}
export async function createProspect(_:FranchiseCrmActionState,f:FormData):Promise<FranchiseCrmActionState>{if(!locale(f))return{status:"error",reason:"VALIDATION"};const p=prospectSchema.safeParse({franchiseId:text(f,"franchiseId"),territoryVersionId:text(f,"territoryVersionId"),prospectType:text(f,"prospectType"),displayName:text(f,"displayName"),contactEmail:text(f,"contactEmail"),organizationName:text(f,"organizationName"),sourceCode:text(f,"sourceCode"),nextFollowupAt:iso(text(f,"nextFollowupAt")),ownerUserId:text(f,"ownerUserId"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("save_franchise_prospect",{p_franchise_id:p.data.franchiseId,p_prospect_id:null,p_territory_version_id:p.data.territoryVersionId,p_prospect_type:p.data.prospectType,p_display_name:p.data.displayName,p_contact_email:p.data.contactEmail,p_organization_name:p.data.organizationName||null,p_source_code:p.data.sourceCode,p_next_followup_at:p.data.nextFollowupAt||null,p_owner_user_id:p.data.ownerUserId,p_expected_row_version:0,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"};}
export async function recordActivity(_:FranchiseCrmActionState,f:FormData):Promise<FranchiseCrmActionState>{if(!locale(f))return{status:"error",reason:"VALIDATION"};const p=activitySchema.safeParse({prospectId:text(f,"prospectId"),activityType:text(f,"activityType"),occurredAt:iso(text(f,"occurredAt")),summary:text(f,"summary"),evidenceReference:text(f,"evidenceReference"),nextFollowupAt:iso(text(f,"nextFollowupAt")),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("record_franchise_activity",{p_prospect_id:p.data.prospectId,p_activity_type:p.data.activityType,p_occurred_at:p.data.occurredAt,p_summary:p.data.summary,p_evidence_refs:evidence(p.data.evidenceReference),p_next_followup_at:p.data.nextFollowupAt||null,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"};}
export async function advancePipeline(_:FranchiseCrmActionState,f:FormData):Promise<FranchiseCrmActionState>{if(!locale(f))return{status:"error",reason:"VALIDATION"};const p=pipelineSchema.safeParse({prospectId:text(f,"prospectId"),toStage:text(f,"toStage"),reasonCode:text(f,"reasonCode"),rowVersion:text(f,"rowVersion"),evidenceReference:text(f,"evidenceReference"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("advance_franchise_pipeline",{p_prospect_id:p.data.prospectId,p_to_stage:p.data.toStage,p_reason_code:p.data.reasonCode,p_evidence_refs:evidence(p.data.evidenceReference),p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"};}
export async function recordSnapshot(_:FranchiseCrmActionState,f:FormData):Promise<FranchiseCrmActionState>{if(!locale(f))return{status:"error",reason:"VALIDATION"};const p=snapshotSchema.safeParse({franchiseId:text(f,"franchiseId"),metricVersionId:text(f,"metricVersionId"),periodStart:text(f,"periodStart"),periodEnd:text(f,"periodEnd"),modelVersion:text(f,"modelVersion"),numerator:text(f,"numerator"),denominator:text(f,"denominator"),evidenceReference:text(f,"evidenceReference"),sourceEvidenceHash:text(f,"sourceEvidenceHash").toLowerCase(),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("record_franchise_performance_snapshot",{p_franchise_id:p.data.franchiseId,p_period_start:p.data.periodStart,p_period_end:p.data.periodEnd,p_model_version:p.data.modelVersion,p_measurements:[{metric_version_id:p.data.metricVersionId,numerator:p.data.numerator,denominator:p.data.denominator,evidence_refs:evidence(p.data.evidenceReference)}],p_source_evidence_hash:p.data.sourceEvidenceHash,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"};}
