"use client";
import { useActionState,useId,type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Locale } from "@/lib/i18n/locale";
import type { AdminCommandCenter,AdminWorkItem } from "@/lib/admin-command-center/model";
import { claimAdminWork,decideAdminAction,requestAdminAction,resolveAdminWork,type AdminActionState } from "./actions";
import type { CommandCenterMessages } from "./messages";

const idle:AdminActionState={status:"idle"},control="min-h-11 w-full rounded-md border bg-background px-3 text-base";
function Feedback({state,m}:{state:AdminActionState;m:CommandCenterMessages}){const text=state.status==="success"?m.success:state.status==="error"?m[state.reason.toLowerCase()]??m.failed:"";return <p role={state.status==="error"?"alert":"status"} aria-live="polite" className={state.status==="error"?"min-h-5 text-sm text-destructive":"min-h-5 text-sm text-primary"}>{text}</p>;}
function Field({id,label,children,help}:{id:string;label:string;children:ReactNode;help?:string}){return <div className="min-w-0 space-y-2"><Label htmlFor={id}>{label}</Label>{children}{help?<p id={`${id}-help`} className="text-xs leading-5 text-muted-foreground">{help}</p>:null}</div>;}
function Hidden({locale,keyValue,children}:{locale:Locale;keyValue:string;children?:ReactNode}){return <><input type="hidden" name="locale" value={locale}/><input type="hidden" name="idempotencyKey" value={keyValue}/>{children}</>;}
function Submit({pending,label,wait}:{pending:boolean;label:string;wait:string}){return <Button type="submit" disabled={pending} className="min-h-11 w-full sm:w-auto">{pending?wait:label}</Button>;}
function Text({id,label,name,required=true,help}:{id:string;label:string;name:string;required?:boolean;help?:string}){return <Field id={id} label={label} help={help}><Input id={id} name={name} required={required} className={control} dir="ltr" aria-describedby={help?`${id}-help`:undefined}/></Field>;}
function Select({id,label,name,values}:{id:string;label:string;name:string;values:string[]}){return <Field id={id} label={label}><select id={id} name={name} className={control} required>{values.map(value=><option key={value||"empty"} value={value}>{value||"—"}</option>)}</select></Field>;}

function WorkCard({item,locale,m,keys}:{item:AdminWorkItem;locale:Locale;m:CommandCenterMessages;keys:[string,string]}){
 const p=useId(),[claim,claimAction,claiming]=useActionState(claimAdminWork,idle),[resolve,resolveAction,resolving]=useActionState(resolveAdminWork,idle),title=locale==="ar"?item.titleAr:item.titleFr,queue=locale==="ar"?item.queueLabelAr:item.queueLabelFr;
 return <article className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">{queue}</p><h3 className="mt-1 text-lg font-semibold">{title}</h3><p className="mt-1 break-all text-sm text-muted-foreground">{m.resource}: <span dir="ltr">{item.resourceType}/{item.resourceId}</span></p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.priority==="CRITICAL"?"bg-destructive/10 text-destructive":item.priority==="HIGH"?"bg-amber-100 text-amber-900":"bg-muted text-foreground"}`}>{item.priority}</span></div><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">{m.status}</dt><dd>{item.status}</dd></div><div><dt className="text-muted-foreground">{m.due}</dt><dd dir="ltr">{new Intl.DateTimeFormat(locale==="ar"?"ar-MA":"fr-MA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.dueAt))}</dd></div><div><dt className="text-muted-foreground">{m.queue}</dt><dd>{item.queueKey}</dd></div></dl><div className="mt-4 grid gap-4 xl:grid-cols-2">
  {item.canClaim!==false?<form action={claimAction} className="space-y-3 rounded-xl border p-3"><Hidden locale={locale} keyValue={keys[0]}><input type="hidden" name="workItemId" value={item.id}/><input type="hidden" name="expectedRowVersion" value={item.rowVersion}/></Hidden><Field id={`${p}-claim`} label={m.reason}><Input id={`${p}-claim`} name="reason" required minLength={3}/></Field><Submit pending={claiming} label={m.claim} wait={m.processing}/><Feedback state={claim} m={m}/></form>:null}
  {item.canResolve!==false?<form action={resolveAction} className="space-y-3 rounded-xl border p-3"><Hidden locale={locale} keyValue={keys[1]}><input type="hidden" name="workItemId" value={item.id}/><input type="hidden" name="expectedRowVersion" value={item.rowVersion}/></Hidden><Field id={`${p}-code`} label={m.resolutionCode}><Input id={`${p}-code`} name="resolutionCode" required pattern="[A-Z][A-Z0-9_]{2,63}" dir="ltr"/></Field><Field id={`${p}-resolve-reason`} label={m.reason}><Textarea id={`${p}-resolve-reason`} name="reason" required minLength={10}/></Field><Field id={`${p}-evidence`} label={m.evidence}><Textarea id={`${p}-evidence`} name="evidence" required defaultValue="{}" dir="ltr"/></Field><Submit pending={resolving} label={m.resolve} wait={m.processing}/><Feedback state={resolve} m={m}/></form>:null}
 </div></article>;
}

function ActionCard({action,locale,m,keyValue}:{action:AdminCommandCenter["actions"][number];locale:Locale;m:CommandCenterMessages;keyValue:string}){
 const p=useId(),[state,formAction,pending]=useActionState(decideAdminAction,idle);return <article className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{action.actionType}</h3><span>{action.targetEnvironment} · {action.status}</span></div><p className="mt-2 break-all text-sm text-muted-foreground" dir="ltr">{action.resourceType}/{action.resourceId}</p><p className="mt-2 text-sm">{action.reason}</p><p className="mt-2 text-sm text-muted-foreground">{m.approvalsRequired}: <span dir="ltr">{action.approvalsRequired}</span></p>{action.canDecide!==false?<form action={formAction} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><Hidden locale={locale} keyValue={keyValue}><input type="hidden" name="actionRequestId" value={action.id}/><input type="hidden" name="expectedRowVersion" value={action.rowVersion}/></Hidden><Field id={`${p}-decision-reason`} label={m.decisionReason}><Input id={`${p}-decision-reason`} name="reason" required minLength={3}/></Field><div className="flex flex-wrap items-end gap-2"><Button type="submit" name="decision" value="APPROVE" disabled={pending} className="min-h-11">{m.approve}</Button><Button type="submit" name="decision" value="REJECT" variant="destructive" disabled={pending} className="min-h-11">{m.reject}</Button></div><div className="sm:col-span-2"><Feedback state={state} m={m}/></div></form>:<p className="mt-4 rounded-md bg-muted p-3 text-sm text-muted-foreground">{m.readOnlyDecision}</p>}</article>;
}

export function CommandCenterPanel({dashboard,locale,m,keys,currentTime}:{dashboard:AdminCommandCenter;locale:Locale;m:CommandCenterMessages;keys:string[];currentTime:string}){
 const p=useId(),[request,requestAction,requesting]=useActionState(requestAdminAction,idle),critical=dashboard.workItems.filter(x=>x.priority==="CRITICAL").length,now=new Date(currentTime).getTime(),overdue=dashboard.workItems.filter(x=>new Date(x.dueAt).getTime()<now).length;
 return <div className="space-y-7"><section aria-label={m.today} className="grid gap-3 sm:grid-cols-3">{[[m.critical,critical],[m.overdue,overdue],[m.pending,dashboard.actions.length]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-card p-5 shadow-sm"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold" dir="ltr">{value}</p></div>)}</section><section aria-labelledby={`${p}-today`} className="space-y-4"><h2 id={`${p}-today`} className="text-2xl font-semibold">{m.today}</h2>{dashboard.workItems.length===0?<p className="rounded-2xl border bg-card p-5 text-muted-foreground">{m.emptyWork}</p>:dashboard.workItems.map((item,index)=><WorkCard key={item.id} item={item} locale={locale} m={m} keys={[keys[index*2]!,keys[index*2+1]!]}/>)}</section><section aria-labelledby={`${p}-approvals`} className="space-y-4"><h2 id={`${p}-approvals`} className="text-2xl font-semibold">{m.sensitive}</h2>{dashboard.actions.length===0?<p className="rounded-2xl border bg-card p-5 text-muted-foreground">{m.emptyActions}</p>:dashboard.actions.map((action,index)=><ActionCard key={action.id} action={action} locale={locale} m={m} keyValue={keys[dashboard.workItems.length*2+index]!}/>)}</section>
 {dashboard.capabilities?.requestAction!==false?<details className="rounded-2xl border bg-card p-4 shadow-sm open:p-5"><summary className="min-h-11 cursor-pointer text-xl font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">{m.newAction}</summary><form action={requestAction} className="mt-5 space-y-4"><Hidden locale={locale} keyValue={keys.at(-1)!}/><div className="grid min-w-0 gap-4 sm:grid-cols-2"><Select id={`${p}-action`} label={m.actionType} name="actionType" values={["ASSIGN_CASE","CHANGE_CONFIGURATION","GRANT_SUPPORT_ACCESS","RESTRICT_ENTITY","SUSPEND_ENTITY","MANUAL_EXCEPTION","AUTHORIZE_PRODUCTION_CHANGE"]}/><Select id={`${p}-env`} label={m.environment} name="targetEnvironment" values={["DEVELOPMENT","STAGING","PRODUCTION"]}/><Text id={`${p}-resource-type`} label={m.resourceType} name="resourceType"/><Text id={`${p}-resource-id`} label={m.resourceId} name="resourceId"/><Text id={`${p}-org`} label={m.organizationId} name="organizationId" required={false}/><Text id={`${p}-work`} label={m.workItemId} name="workItemId" required={false}/><Text id={`${p}-hash`} label={m.payloadHash} name="requestPayloadHash"/><Field id={`${p}-summary`} label={m.redactedSummary}><Textarea id={`${p}-summary`} name="redactedSummary" defaultValue="{}" required dir="ltr"/></Field><Field id={`${p}-reason`} label={m.reason}><Textarea id={`${p}-reason`} name="reason" required minLength={10}/></Field><Text id={`${p}-prod`} label={m.productionReference} name="productionAuthorizationReference" required={false} help={m.productionHelp}/><Text id={`${p}-support-user`} label={m.supportUser} name="supportUserId" required={false}/><Select id={`${p}-support-mode`} label={m.supportMode} name="supportAccessMode" values={["","READ_ONLY","CASE_SCOPED"]}/><Field id={`${p}-support-expiry`} label={m.supportExpiry}><Input id={`${p}-support-expiry`} name="supportExpiresAt" type="datetime-local"/></Field></div><Submit pending={requesting} label={m.request} wait={m.processing}/><Feedback state={request} m={m}/></form></details>:<p className="rounded-2xl border bg-card p-5 text-muted-foreground">{m.readOnlyCommandCenter}</p>}
 </div>;
}
