import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ getUser: vi.fn(), rpc: vi.fn(), from: vi.fn() }));
vi.mock("@/lib/supabase/server", () => ({ getSupabaseServerClient: async () => ({ auth: { getUser: mocks.getUser }, rpc: mocks.rpc, from: mocks.from }) }));
vi.mock("@/lib/i18n/locale", () => ({ isLocale: (value: string) => value === "fr" || value === "ar" }));
vi.mock("@/lib/marketing-autopilot/model", async () => await import("../../../../lib/marketing-autopilot/model"));
import { activateScheduleRule, approveAssistedCalendar, approveCampaign, createCampaign, createScheduleRule, recordBrandAuthorization, recordConnectionSecurity, recordConsent, reviewBrandEvidence, saveBrandKit, scheduleCampaign, setKillSwitch, type MarketingActionState } from "./actions";
const idle: MarketingActionState = { status: "idle" }, id = "11111111-1111-4111-8111-111111111111";
function form(values: Record<string, string>) { const result = new FormData(); result.set("locale", "fr"); result.set("idempotencyKey", id); Object.entries(values).forEach(([key, value]) => result.set(key, value)); return result; }
beforeEach(() => {
  mocks.getUser.mockReset().mockResolvedValue({ data: { user: { id } } });
  mocks.rpc.mockReset().mockResolvedValue({ data: { outcome: "OK" }, error: null });
  mocks.from.mockReset().mockImplementation((table: string) => ({ select: () => ({ eq: () => ({ maybeSingle: async () => table === "social_connections" ? { data: { id, provider: "LINKEDIN", credential_reference: "vault://marketing/linkedin", scopes: ["r_liteprofile"] }, error: null } : { data: { claims: [{ key: "claim-1", evidenceHash: "a".repeat(64) }], certifications: [] }, error: null } }) }) }));
});
describe("marketing actions", () => {
  it("dérive côté serveur la preuve et la politique d’un retrait", async () => { await recordConsent(idle, form({ organizationId: id, purpose: "SOCIAL_PUBLISHING", decision: "WITHDRAWN", evidenceNote: "Demande écrite du responsable marketing" })); expect(mocks.rpc).toHaveBeenCalledWith("record_marketing_consent", expect.objectContaining({ p_decision: "WITHDRAWN", p_policy_version: "MARKETING-CONSENT-V1", p_evidence_hash: expect.stringMatching(/^[0-9a-f]{64}$/u) })); });
  it("rejette un choix d’audience hors liste", async () => { const result = await createCampaign(idle, form({ organizationId: id, brandKitVersionId: id, mode: "ASSISTED", titleFr: "Campagne", titleAr: "حملة", frequencyMaxWeekly: "8", riskThreshold: "20", audienceSegment: "RAW_CONTACTS", sourceType: "INTERNAL_EDITORIAL" })); expect(result).toEqual({ status: "error", reason: "VALIDATION" }); expect(mocks.rpc).not.toHaveBeenCalled(); });
  it("approuve avec verrou optimiste", async () => { await approveCampaign(idle, form({ campaignId: id, rowVersion: "3" })); expect(mocks.rpc).toHaveBeenCalledWith("approve_marketing_campaign", expect.objectContaining({ p_expected_row_version: 3 })); });
  it("planifie en UTC via un lot serveur", async () => { await scheduleCampaign(idle, form({ campaignId: id, contentVersionId: id, socialConnectionId: id, scheduledAt: "2026-09-14T09:30", rowVersion: "4" })); expect(mocks.rpc).toHaveBeenCalledWith("schedule_marketing_campaign", expect.objectContaining({ p_items: [expect.objectContaining({ scheduled_at: "2026-09-14T09:30:00.000Z" })] })); });
  it("échoue fermé sans session", async () => { mocks.getUser.mockResolvedValueOnce({ data: { user: null } }); expect(await approveCampaign(idle, form({ campaignId: id, rowVersion: "1" }))).toEqual({ status: "error", reason: "UNAUTHENTICATED" }); });
  it("crée une version de règle mensuelle avec des créneaux structurés", async () => { await createScheduleRule(idle, form({ organizationId: id, socialAccountId: id, timezone: "Africa/Casablanca", postsPerMonth: "8", reelsPerMonth: "4", generationDay: "25", slotDay1: "5", slotTime1: "09:00", maxServiceRepetition: "2", privacyMinimumAggregate: "10" })); expect(mocks.rpc).toHaveBeenCalledWith("create_marketing_schedule_rule_version_v1", expect.objectContaining({ p_allowed_slots: [{ dayOfMonth: 5, time: "09:00" }], p_posts_per_month: 8 })); });
  it("rejette les créneaux mensuels dupliqués", async () => { const result=await createScheduleRule(idle, form({ organizationId: id, socialAccountId: id, timezone: "Africa/Casablanca", postsPerMonth: "8", reelsPerMonth: "4", generationDay: "25", slotDay1: "5", slotTime1: "09:00", slotDay2: "5", slotTime2: "09:00", maxServiceRepetition: "2", privacyMinimumAggregate: "10" })); expect(result).toEqual({status:"error",reason:"VALIDATION"}); expect(mocks.rpc).not.toHaveBeenCalled(); });
  it("active une règle avec le verrou de tête", async () => { await activateScheduleRule(idle, form({ ruleId: id, headRowVersion: "0" })); expect(mocks.rpc).toHaveBeenCalledWith("activate_marketing_schedule_rule_version_v1", expect.objectContaining({ p_expected_head_row_version: 0 })); });
  it("approuve globalement un calendrier assisté avec verrou optimiste", async () => { await approveAssistedCalendar(idle, form({ calendarId: id, rowVersion: "2" })); expect(mocks.rpc).toHaveBeenCalledWith("approve_assisted_marketing_calendar_v1", expect.objectContaining({ p_calendar_id: id, p_expected_row_version: 2 })); });
  it("construit le Brand Kit depuis des champs métier et dérive la preuve", async () => { await saveBrandKit(idle, form({ organizationId: id, primaryColor: "#123B5D", tone: "PROFESSIONAL", primaryCta: "DIAGNOSTIC", trackedUrl: "https://matricia.ma/diagnostic", allowedHost: "matricia.ma", approvedHashtags: "#Matricia", forbiddenTerms: "garanti", claimKey: "impact", claimTextFr: "Impact documenté", claimTextAr: "أثر موثق", claimEvidenceReference: "document:impact-2026", changeReason: "Mise à jour annuelle" })); expect(mocks.rpc).toHaveBeenCalledWith("save_marketing_brand_kit_v1", expect.objectContaining({ p_payload: expect.objectContaining({ primary_colors: ["#123B5D"], allowed_url_hosts: ["matricia.ma"], forbidden_terms: ["garanti"] }), p_claims: [expect.objectContaining({ key: "impact", evidenceHash: expect.stringMatching(/^[0-9a-f]{64}$/u) })] })); });
  it("dérive politique, portée et preuve de l’autorisation de marque", async () => { await recordBrandAuthorization(idle, form({ organizationId: id, decision: "GRANTED", authorizationScope: "CONTENT_AND_SOCIAL", authorizationSource: "SIGNED_MANDATE", authorizationReason: "Mandat signé par la direction", effectiveFrom: "2026-09-15T09:00", effectiveUntil: "" })); expect(mocks.rpc).toHaveBeenCalledWith("record_marketing_brand_authorization_v41", expect.objectContaining({ p_authorization_scope: ["CONTENT_GENERATION", "SOCIAL_PUBLISHING"], p_policy_version: "MARKETING-BRAND-AUTHORIZATION-V1", p_evidence_hash: expect.stringMatching(/^[0-9a-f]{64}$/u) })); });
  it("réutilise la référence de connexion enregistrée sans exposer de secret", async () => { await recordConnectionSecurity(idle, form({ connectionId: id, status: "ACTIVE", securityReason: "Contrôle périodique effectué", expiresAt: "2026-12-01T09:00" })); expect(mocks.rpc).toHaveBeenCalledWith("record_social_connection_security_v41", expect.objectContaining({ p_vault_credential_reference: "vault://marketing/linkedin", p_ciphertext_fingerprint: expect.stringMatching(/^[0-9a-f]{64}$/u), p_approved_scopes: ["r_liteprofile", "w_member_social"] })); });
  it("retrouve côté serveur l’empreinte de la preuve à revoir", async () => { await reviewBrandEvidence(idle, form({ brandKitVersionId: id, evidenceType: "CLAIM", evidenceKey: "claim-1", decision: "VERIFIED", validUntil: "2026-12-01T09:00", reason: "Document contrôlé" })); expect(mocks.rpc).toHaveBeenCalledWith("review_marketing_brand_evidence_v1", expect.objectContaining({ p_evidence_hash: "a".repeat(64) })); });
  it("dérive la preuve de l’arrêt d’urgence depuis la décision métier", async () => { await setKillSwitch(idle, form({ organizationId: "", scope: "PROVIDER", provider: "META", enabled: "yes", decisionSource: "SECURITY_INCIDENT", reason: "Incident confirmé" })); expect(mocks.rpc).toHaveBeenCalledWith("set_marketing_kill_switch_v41", expect.objectContaining({ p_provider: "META", p_enabled: true, p_evidence_hash: expect.stringMatching(/^[0-9a-f]{64}$/u) })); });
});
