"use server";
import { z } from "zod";
import { isLocale } from "@/lib/i18n/locale";
import { approvalInput, assistedCalendarApprovalInput, campaignInput, consentInput, parseJsonObject, scheduleInput, scheduleRuleActivationInput, scheduleRuleInput } from "@/lib/marketing-autopilot/model";
import { getSupabaseServerClient } from "@/lib/supabase/server";
export type MarketingActionState={status:"idle"}|{status:"success";outcome:string}|{status:"error";reason:"VALIDATION"|"UNAUTHENTICATED"|"FORBIDDEN"|"CONFLICT"|"FAILED"};
const output=z.object({outcome:z.string().min(3)}).passthrough(),text=(f:FormData,k:string)=>String(f.get(k)??"");
async function rpc(name:string,args:Record<string,unknown>):Promise<MarketingActionState>{const client=await getSupabaseServerClient(),{data}=await client.auth.getUser();if(!data.user)return{status:"error",reason:"UNAUTHENTICATED"};const result=await client.rpc(name,args);if(result.error){if(result.error.code==="42501")return{status:"error",reason:"FORBIDDEN"};if(["40001","23505","23514","55000"].includes(result.error.code??"")||/IDEMPOTENCY|STALE|CONSENT|BLOCKED|FREQUENCY/i.test(result.error.message??""))return{status:"error",reason:"CONFLICT"};return{status:"error",reason:"FAILED"}}const parsed=output.safeParse(result.data);return parsed.success?{status:"success",outcome:parsed.data.outcome}:{status:"error",reason:"FAILED"}}
function valid(f:FormData){return isLocale(text(f,"locale"))}
export async function recordConsent(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=consentInput.safeParse({organizationId:text(f,"organizationId"),purpose:text(f,"purpose"),decision:text(f,"decision"),policyVersion:text(f,"policyVersion"),evidenceHash:text(f,"evidenceHash").toLowerCase(),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("record_marketing_consent",{p_organization_id:p.data.organizationId,p_purpose:p.data.purpose,p_decision:p.data.decision,p_policy_version:p.data.policyVersion,p_evidence_hash:p.data.evidenceHash,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function createCampaign(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const audience=parseJsonObject(text(f,"audienceSnapshot")),source=parseJsonObject(text(f,"sourceSnapshot"));if(!audience.success||!source.success)return{status:"error",reason:"VALIDATION"};const p=campaignInput.safeParse({organizationId:text(f,"organizationId"),brandKitVersionId:text(f,"brandKitVersionId"),mode:text(f,"mode"),titleFr:text(f,"titleFr"),titleAr:text(f,"titleAr"),frequencyMaxWeekly:text(f,"frequencyMaxWeekly"),riskThreshold:text(f,"riskThreshold"),audienceSnapshot:audience.data,sourceSnapshot:source.data,idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("create_marketing_campaign",{p_organization_id:p.data.organizationId,p_brand_kit_version_id:p.data.brandKitVersionId,p_mode:p.data.mode,p_title_fr:p.data.titleFr,p_title_ar:p.data.titleAr,p_frequency_max_weekly:p.data.frequencyMaxWeekly,p_risk_threshold:p.data.riskThreshold,p_audience_snapshot:p.data.audienceSnapshot,p_source_snapshot:p.data.sourceSnapshot,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function approveCampaign(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=approvalInput.safeParse({campaignId:text(f,"campaignId"),rowVersion:text(f,"rowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("approve_marketing_campaign",{p_campaign_id:p.data.campaignId,p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function scheduleCampaign(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const local=text(f,"scheduledAt"),scheduledAt=local?`${local}:00.000Z`:"",p=scheduleInput.safeParse({campaignId:text(f,"campaignId"),contentVersionId:text(f,"contentVersionId"),socialConnectionId:text(f,"socialConnectionId"),scheduledAt,rowVersion:text(f,"rowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("schedule_marketing_campaign",{p_campaign_id:p.data.campaignId,p_items:[{content_version_id:p.data.contentVersionId,social_connection_id:p.data.socialConnectionId,scheduled_at:p.data.scheduledAt}],p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function createScheduleRule(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const slots=parseJsonArray(text(f,"allowedSlots"));if(!slots.success)return{status:"error",reason:"VALIDATION"};const p=scheduleRuleInput.safeParse({organizationId:text(f,"organizationId"),socialAccountId:text(f,"socialAccountId"),timezone:text(f,"timezone"),postsPerMonth:text(f,"postsPerMonth"),reelsPerMonth:text(f,"reelsPerMonth"),generationDay:text(f,"generationDay"),allowedSlots:slots.data,maxServiceRepetition:text(f,"maxServiceRepetition"),privacyMinimumAggregate:text(f,"privacyMinimumAggregate"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("create_marketing_schedule_rule_version_v1",{p_organization_id:p.data.organizationId,p_social_account_id:p.data.socialAccountId,p_timezone:p.data.timezone,p_posts_per_month:p.data.postsPerMonth,p_reels_per_month:p.data.reelsPerMonth,p_generation_day:p.data.generationDay,p_allowed_slots:p.data.allowedSlots,p_max_service_repetition:p.data.maxServiceRepetition,p_privacy_minimum_aggregate:p.data.privacyMinimumAggregate,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function activateScheduleRule(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=scheduleRuleActivationInput.safeParse({ruleId:text(f,"ruleId"),headRowVersion:text(f,"headRowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("activate_marketing_schedule_rule_version_v1",{p_rule_id:p.data.ruleId,p_expected_head_row_version:p.data.headRowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
export async function approveAssistedCalendar(_:MarketingActionState,f:FormData):Promise<MarketingActionState>{if(!valid(f))return{status:"error",reason:"VALIDATION"};const p=assistedCalendarApprovalInput.safeParse({calendarId:text(f,"calendarId"),rowVersion:text(f,"rowVersion"),idempotencyKey:text(f,"idempotencyKey")});return p.success?rpc("approve_assisted_marketing_calendar_v1",{p_calendar_id:p.data.calendarId,p_expected_row_version:p.data.rowVersion,p_idempotency_key:p.data.idempotencyKey}):{status:"error",reason:"VALIDATION"}}
function parseJsonArray(value:string){try{return z.array(z.unknown()).safeParse(JSON.parse(value) as unknown)}catch{return{success:false as const}}}
