import type { ComponentPropsWithoutRef } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
vi.mock("@/components/ui/button",()=>({Button:({children,...props}:ComponentPropsWithoutRef<"button">)=><button {...props}>{children}</button>}));
vi.mock("@/components/ui/input",()=>({Input:(props:ComponentPropsWithoutRef<"input">)=><input {...props}/>}));
vi.mock("@/components/ui/label",()=>({Label:({children,...props}:ComponentPropsWithoutRef<"label">)=><label {...props}>{children}</label>}));
vi.mock("@/components/ui/textarea",()=>({Textarea:(props:ComponentPropsWithoutRef<"textarea">)=><textarea {...props}/>}));
vi.mock("@/lib/marketing-autopilot/model",async()=>await import("../../../../lib/marketing-autopilot/model"));
vi.mock("./actions",()=>({recordConsent:async()=>({status:"idle"}),createCampaign:async()=>({status:"idle"}),approveCampaign:async()=>({status:"idle"}),scheduleCampaign:async()=>({status:"idle"})}));
import { MarketingPanel } from "./marketing-panel";import { getMarketingMessages } from "./messages";
const id="11111111-1111-4111-8111-111111111111",dashboard={organizations:[{id,name:"Matricia"}],consents:[],brandVersions:[{id,organizationId:id,version:1,status:"READY",tradeName:"Matricia"}],connections:[{id,organizationId:id,provider:"LINKEDIN" as const,status:"ACTIVE"}],campaigns:[{id,organizationId:id,mode:"ASSISTED" as const,titleFr:"Expertise",titleAr:"خبرة",status:"VALIDATED_BY_RULES",frequencyMaxWeekly:8,riskThreshold:20,rowVersion:1,approvedAt:null}],contents:[{id,campaignId:id,channel:"LINKEDIN" as const,versionId:id,language:"FR" as const,hook:"Conseil",body:"Corps",cta:"Voir",hashtags:[],riskScore:10,status:"VALIDATED_BY_RULES",expiresAt:null}],calendar:[],performance:[{campaignId:id,published:"0",impressions:"0",clicks:"0",leads:"0",attributedValueMinor:"0",marketingCostMinor:"0",feedback:"KEEP"}]};const keys={consent:id,campaign:id,[`approve:${id}`]:id,[`schedule:${id}`]:id};
function visible(locale:"fr"|"ar"){return renderToStaticMarkup(<MarketingPanel dashboard={dashboard} locale={locale} m={getMarketingMessages(locale)} keys={keys}/>).replace(/<[^>]+>/g," ")}
describe("marketing visible localization",()=>{it("ne montre pas les codes métier en français",()=>{const text=visible("fr");expect(text).toContain("Publication sur les réseaux sociaux");expect(text).toContain("Assisté");expect(text).toContain("Validé par les règles");expect(text).toContain("LinkedIn · Français");expect(text).not.toMatch(/SOCIAL_PUBLISHING|VALIDATED_BY_RULES|ASSISTED/)});it("rend les mêmes valeurs en arabe",()=>{const text=visible("ar");expect(text).toContain("النشر على شبكات التواصل");expect(text).toContain("بمساعدة");expect(text).toContain("متحقق منه بالقواعد");expect(text).toContain("لينكدإن · الفرنسية")})});
