import{Badge}from"@/components/ui/badge";
import type{Locale}from"@/lib/i18n/locale";
import type{NotificationDashboard}from"@/lib/notifications/model";
import type{NotificationMessages}from"./messages";

type TemplateRow=NotificationDashboard["templates"][number];

export function NotificationTemplateCatalog({templates,locale,m}:{templates:TemplateRow[];locale:Locale;m:NotificationMessages}){
 const groups=new Map<string,{base:TemplateRow;fr?:TemplateRow;ar?:TemplateRow}>();
 for(const template of templates){const key=`${template.template_code}:${template.version}`;const group=groups.get(key)??{base:template};if(template.locale==="fr-MA")group.fr=template;else group.ar=template;groups.set(key,group)}
 const formatter=new Intl.DateTimeFormat(locale==="ar"?"ar-MA":"fr-MA",{dateStyle:"medium",timeStyle:"short"});
 return <section aria-labelledby="notification-templates" className="space-y-4"><div><h2 id="notification-templates" className="text-2xl font-semibold">{m.templateCatalog}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-muted-foreground">{m.templateCatalogDescription}</p></div>{groups.size===0?<div className="rounded-2xl border bg-card p-6 text-muted-foreground">{m.templateEmpty}</div>:<div className="grid gap-4 xl:grid-cols-2">{Array.from(groups.values()).map(({base,fr,ar})=><article key={`${base.template_code}:${base.version}`} className="min-w-0 rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="break-all font-mono text-sm" dir="ltr">{base.template_code}</p><p className="mt-1 text-sm text-muted-foreground">{m.templateVersion} {base.version} · {m.event} <span dir="ltr">{base.event_type}</span></p></div><div className="flex flex-wrap gap-2"><Badge variant={base.mandatory?"destructive":"secondary"}>{base.mandatory?m.mandatoryTemplate:m.optionalTemplate}</Badge>{base.channels.map(channel=><Badge key={channel} variant="outline"><span dir="ltr">{channel}</span></Badge>)}</div></header><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">{m.activeFrom}</dt><dd><time dateTime={base.effective_from}>{formatter.format(new Date(base.effective_from))}</time></dd></div><div><dt className="text-muted-foreground">{m.variables}</dt><dd className="break-words font-mono" dir="ltr">{base.variable_keys.length?base.variable_keys.join(", "):m.noVariables}</dd></div></dl><div className="mt-4 grid gap-3 sm:grid-cols-2">{fr?<TemplateTranslation template={fr} label={m.french} hashLabel={m.contentHash}/>:<MissingTranslation label={m.french} message={m.missingTranslation}/>} {ar?<TemplateTranslation template={ar} label={m.arabic} hashLabel={m.contentHash}/>:<MissingTranslation label={m.arabic} message={m.missingTranslation}/>}</div></article>)}</div>}</section>
}

function TemplateTranslation({template,label,hashLabel}:{template:TemplateRow;label:string;hashLabel:string}){return <section lang={template.locale==="ar-MA"?"ar":"fr"} dir={template.locale==="ar-MA"?"rtl":"ltr"} className="min-w-0 rounded-xl border bg-muted/30 p-3"><h3 className="text-sm font-semibold">{label}</h3><p className="mt-2 font-medium">{template.subject_template}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{template.body_template}</p><p className="mt-3 text-xs text-muted-foreground">{hashLabel}</p><p className="break-all font-mono text-[11px] text-muted-foreground" dir="ltr">{template.content_hash}</p></section>}
function MissingTranslation({label,message}:{label:string;message:string}){return <section className="rounded-xl border border-destructive/40 p-3"><h3 className="text-sm font-semibold">{label}</h3><p role="alert" className="mt-2 text-sm text-destructive">{message}</p></section>}
