export const moduleHubCopy = {
  fr: {
    title: "Espaces opérationnels",
    description: "Accédez aux modules autorisés pour vos rôles. Chaque espace applique ses contrôles serveur et RLS.",
    links: [
      ["Diagnostics et opportunités", "client/diagnostics"],
      ["Demandes et devis", "client/demandes"],
      ["Contrats et missions", "client/missions"],
      ["Litiges et réaffectation", "client/litiges"],
      ["Abonnement", "client/abonnement"],
      ["Boxes et crédits", "client/credits"],
      ["Achats groupés", "client/achats-groupes"],
      ["Qualification Sous-traitant", "sous-traitant/qualification"],
      ["Facturation Sous-traitant", "sous-traitant/facturation"],
      ["Missions Sous-traitant", "sous-traitant/missions"],
      ["Gouvernance Franchise", "franchise/gouvernance"],
      ["CRM et performance Franchise", "franchise/performance"],
      ["Notifications", "notifications"],
      ["Command Center", "administration/command-center"],
      ["Marketing Autopilot", "administration/marketing-autopilot"],
      ["Fiscalité Maroc", "administration/fiscalite-maroc"],
    ],
  },
  ar: {
    title: "مساحات العمليات",
    description: "ادخل إلى الوحدات المسموح بها لأدوارك. تطبق كل مساحة صلاحيات الخادم وسياسات RLS.",
    links: [
      ["التشخيصات والفرص", "client/diagnostics"],
      ["الطلبات والعروض", "client/demandes"],
      ["العقود والمهام", "client/missions"],
      ["النزاعات وإعادة الإسناد", "client/litiges"],
      ["الاشتراك", "client/abonnement"],
      ["الصناديق والاعتمادات", "client/credits"],
      ["المشتريات المجمعة", "client/achats-groupes"],
      ["تأهيل مقدم الخدمات", "sous-traitant/qualification"],
      ["فواتير مقدم الخدمات", "sous-traitant/facturation"],
      ["مهام مقدم الخدمات", "sous-traitant/missions"],
      ["حوكمة الامتياز", "franchise/gouvernance"],
      ["إدارة علاقات وأداء الامتياز", "franchise/performance"],
      ["الإشعارات", "notifications"],
      ["مركز القيادة", "administration/command-center"],
      ["التسويق الآلي", "administration/marketing-autopilot"],
      ["الضرائب بالمغرب", "administration/fiscalite-maroc"],
    ],
  },
} as const;
