"use client";
import { useActionState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { exactMoney,type Portfolio } from "@/lib/client-portfolio/model";
import { createCostCenter,createProject,idle,recordAllocation,saveBudget,saveTask,scheduleEvent } from "./actions";
import type { Messages } from "./messages";

type Keys={project:string;task:string;budget:string;center:string;allocation:string;event:string};
type Props={locale:"fr"|"ar";data:Portfolio;m:Messages;keys:Keys};
const statuses={project:["DRAFT","PLANNED","ACTIVE","ON_HOLD","COMPLETED","CANCELLED"],task:["PENDING","IN_PROGRESS","BLOCKED","SUBMITTED","ACCEPTED","CANCELLED"]};

export function PortfolioPanel({locale,data,m,keys}:Props){return <main className="min-h-dvh bg-muted/40 px-4 py-6 sm:px-6"><div className="mx-auto max-w-7xl space-y-7"><header><h1 className="text-3xl font-semibold">{m.title}</h1><p className="mt-2 max-w-4xl text-muted-foreground">{m.intro}</p></header>{data.organizations.length===0?<p>{m.empty}</p>:data.organizations.map(org=><OrganizationPortfolio key={org.id} locale={locale} data={data} m={m} keys={keys} organizationId={org.id}/>)}</div></main>}

function OrganizationPortfolio({locale,data,m,keys,organizationId}:Props&{organizationId:string}){const org=data.organizations.find(x=>x.id===organizationId)!;const projects=data.projects.filter(x=>x.organizationId===org.id),sites=data.sites.filter(x=>x.organizationId===org.id),budgets=data.budgets.filter(x=>x.organizationId===org.id),centers=data.costCenters.filter(x=>x.organizationId===org.id),allocations=data.allocations.filter(x=>x.organizationId===org.id),calendar=data.calendar.filter(x=>x.organizationId===org.id);const canPortfolio=org.capabilities.includes("MANAGE_PORTFOLIO"),canBudget=org.capabilities.includes("MANAGE_BUDGET");return <section className="space-y-6" aria-labelledby={`org-${org.id}`}><h2 id={`org-${org.id}`} className="border-b pb-2 text-2xl font-semibold">{org.name}</h2>
  <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{m.projects}</CardTitle></CardHeader><CardContent className="space-y-3">{projects.length===0?<p className="text-muted-foreground">{m.empty}</p>:projects.map(project=><article key={project.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{locale==="ar"?project.nameAr:project.nameFr}</strong><Badge>{project.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{project.code} · {m.version} {project.version}</p><p className="mt-2 text-sm">{locale==="ar"?project.descriptionAr:project.descriptionFr}</p><p className="mt-2 text-sm">{m.progress}: <span dir="ltr">{(project.progressBasisPoints/100).toFixed(2)}%</span></p><div className="mt-3 h-2 overflow-hidden rounded bg-muted" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={project.progressBasisPoints/100}><div className="h-full bg-primary" style={{width:`${project.progressBasisPoints/100}%`}}/></div></article>)}</CardContent></Card>
  <Card><CardHeader><CardTitle>{m.tasks}</CardTitle></CardHeader><CardContent className="space-y-3">{data.tasks.filter(task=>projects.some(project=>project.id===task.projectId)).length===0?<p className="text-muted-foreground">{m.empty}</p>:data.tasks.filter(task=>projects.some(project=>project.id===task.projectId)).map(task=><div key={task.id} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div><strong>{locale==="ar"?task.titleAr:task.titleFr}</strong><p className="text-sm text-muted-foreground">{projects.find(x=>x.id===task.projectId)?.code} · {task.type}{task.dueAt?` · ${new Date(task.dueAt).toLocaleString(locale)}`:""}</p></div><Badge variant="outline">{task.status}</Badge></div>)}</CardContent></Card></div>
  {canPortfolio?<div className="grid gap-4 xl:grid-cols-2"><ProjectForm locale={locale} orgId={org.id} sites={sites} m={m} keyValue={keys.project}/><TaskForm locale={locale} projects={projects} m={m} keyValue={keys.task}/></div>:<p className="rounded-lg border p-3 text-sm text-muted-foreground">{m.readOnly}</p>}
  <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{m.budgets}</CardTitle></CardHeader><CardContent className="space-y-3">{budgets.length===0?<p className="text-muted-foreground">{m.empty}</p>:budgets.map(budget=>{const net=allocations.filter(a=>a.budgetId===budget.id).reduce((sum,a)=>sum+(a.type==="RELEASE"?-BigInt(a.amountMinor):BigInt(a.amountMinor)),BigInt(0));const approved=BigInt(budget.approvedAmountMinor??budget.amountMinor);return <div key={budget.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><strong>{budget.fiscalYear} · {exactMoney(budget.amountMinor,budget.currency)}</strong><Badge>{budget.status}</Badge></div><dl className="mt-2 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-muted-foreground">{m.used}</dt><dd dir="ltr">{exactMoney(net.toString(),budget.currency)}</dd></div><div><dt className="text-muted-foreground">{m.remaining}</dt><dd dir="ltr">{exactMoney((approved-net).toString(),budget.currency)}</dd></div></dl></div>})}</CardContent></Card><Card><CardHeader><CardTitle>{m.centers}</CardTitle></CardHeader><CardContent className="space-y-3">{centers.length===0?<p className="text-muted-foreground">{m.empty}</p>:centers.map(center=><div key={center.id} className="flex justify-between rounded-lg border p-3"><span>{locale==="ar"?center.nameAr:center.nameFr} · {center.code}</span><Badge variant="outline">{center.status}</Badge></div>)}</CardContent></Card></div>
  {canBudget?<div className="grid gap-4 xl:grid-cols-3"><BudgetForm locale={locale} orgId={org.id} projects={projects} sites={sites} data={data} m={m} keyValue={keys.budget}/><CenterForm locale={locale} orgId={org.id} m={m} keyValue={keys.center}/><AllocationForm locale={locale} orgId={org.id} projects={projects} budgets={budgets.filter(x=>x.status==="APPROVED")} centers={centers.filter(x=>x.status==="ACTIVE")} m={m} keyValue={keys.allocation}/></div>:null}
  <Card><CardHeader><CardTitle>{m.calendar}</CardTitle></CardHeader><CardContent>{calendar.length===0?<p className="text-muted-foreground">{m.empty}</p>:<ol className="space-y-3">{calendar.map(item=><li key={`${item.sourceKind}-${item.itemId}`} className="flex flex-wrap items-start justify-between gap-3 border-b pb-3"><div><strong>{locale==="ar"?item.titleAr:item.titleFr}</strong><p className="text-sm text-muted-foreground">{new Date(item.startsAt).toLocaleString(locale)}{item.endsAt?` — ${new Date(item.endsAt).toLocaleString(locale)}`:""}</p></div><Badge variant="outline">{item.eventType}</Badge></li>)}</ol>}</CardContent></Card>{canPortfolio?<EventForm locale={locale} orgId={org.id} projects={projects} m={m} keyValue={keys.event}/>:null}
 </section>}

const Hidden=({locale,orgId,keyValue}:{locale:string;orgId?:string;keyValue:string})=><><input type="hidden" name="locale" value={locale}/>{orgId?<input type="hidden" name="organizationId" value={orgId}/>:null}<input type="hidden" name="idempotencyKey" value={keyValue}/></>;
function Feedback({state,m}:{state:{status:string;reason?:string};m:Messages}){if(state.status==="idle")return null;const value=state.status==="success"?m.success:state.reason==="VALIDATION"?m.validation:state.reason==="FORBIDDEN"?m.forbidden:m.unavailable;return <p role={state.status==="error"?"alert":"status"} className={state.status==="error"?"text-sm text-destructive":"text-sm text-primary"}>{value}</p>}
const Select=({name,label,children,required=true}:{name:string;label:string;children:React.ReactNode;required?:boolean})=><label className="grid gap-1 text-sm">{label}<select name={name} required={required} className="min-h-11 rounded-md border bg-background px-3">{children}</select></label>;

function ProjectForm({locale,orgId,sites,m,keyValue}:{locale:"fr"|"ar";orgId:string;sites:Portfolio["sites"];m:Messages;keyValue:string}){const[state,action,pending]=useActionState(createProject,idle);return <Card><CardHeader><CardTitle>{m.newProject}</CardTitle></CardHeader><CardContent><form action={action} className="grid gap-3"><Hidden locale={locale} orgId={orgId} keyValue={keyValue}/><Input name="projectCode" placeholder={m.code} pattern="[A-Z][A-Z0-9_-]+" required/><Select name="siteId" label={m.site} required={false}><option value="">{m.none}</option>{sites.map(x=><option key={x.id} value={x.id}>{locale==="ar"?x.nameAr:x.nameFr}</option>)}</Select><Input name="nameFr" placeholder={m.nameFr} required/><Input name="nameAr" dir="rtl" placeholder={m.nameAr} required/><Textarea name="descriptionFr" placeholder={m.descriptionFr} required/><Textarea name="descriptionAr" dir="rtl" placeholder={m.descriptionAr} required/><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-sm">{m.start}<Input name="startedOn" type="date"/></label><label className="grid gap-1 text-sm">{m.target}<Input name="targetEndOn" type="date"/></label></div><Input name="changeReason" placeholder={m.reason} required/><Button disabled={pending}>{m.save}</Button><Feedback state={state} m={m}/></form></CardContent></Card>}
function TaskForm({locale,projects,m,keyValue}:{locale:"fr"|"ar";projects:Portfolio["projects"];m:Messages;keyValue:string}){const[state,action,pending]=useActionState(saveTask,idle);return <Card><CardHeader><CardTitle>{m.newTask}</CardTitle></CardHeader><CardContent><form action={action} className="grid gap-3"><Hidden locale={locale} keyValue={keyValue}/><Select name="projectId" label={m.project}>{projects.map(x=><option key={x.id} value={x.id}>{x.code} · {locale==="ar"?x.nameAr:x.nameFr}</option>)}</Select><Input name="taskKey" placeholder={m.code} pattern="[A-Z][A-Z0-9_-]+" required/><Select name="taskType" label={m.taskType}><option value="TASK">TASK</option><option value="MILESTONE">MILESTONE</option></Select><Select name="status" label={m.status}>{statuses.task.map(x=><option key={x}>{x}</option>)}</Select><Input name="dueAt" type="datetime-local"/><Input name="titleFr" placeholder={m.nameFr} required/><Input name="titleAr" dir="rtl" placeholder={m.nameAr} required/><Textarea name="descriptionFr" placeholder={m.descriptionFr}/><Textarea name="descriptionAr" dir="rtl" placeholder={m.descriptionAr}/><Input name="changeReason" placeholder={m.reason} required/><Button disabled={pending||projects.length===0}>{m.save}</Button><Feedback state={state} m={m}/></form></CardContent></Card>}
function BudgetForm({locale,orgId,projects,sites,data,m,keyValue}:{locale:"fr"|"ar";orgId:string;projects:Portfolio["projects"];sites:Portfolio["sites"];data:Portfolio;m:Messages;keyValue:string}){const[state,action,pending]=useActionState(saveBudget,idle);return <Card><CardHeader><CardTitle>{m.newBudget}</CardTitle><CardDescription>{m.amount} (ex. 1250,00)</CardDescription></CardHeader><CardContent><form action={action} className="grid gap-3"><Hidden locale={locale} orgId={orgId} keyValue={keyValue}/><Input name="fiscalYear" type="number" min="2000" max="2200" defaultValue={new Date().getFullYear()} required/><Input name="currency" value="MAD" readOnly/><Select name="libraryId" label={m.library} required={false}><option value="">{m.none}</option>{data.libraries.map(x=><option key={x.id} value={x.id}>{locale==="ar"?x.nameAr:x.nameFr}</option>)}</Select><Select name="siteId" label={m.site} required={false}><option value="">{m.none}</option>{sites.map(x=><option key={x.id} value={x.id}>{locale==="ar"?x.nameAr:x.nameFr}</option>)}</Select><Select name="projectId" label={m.project} required={false}><option value="">{m.none}</option>{projects.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</Select><Input name="amount" inputMode="decimal" dir="ltr" placeholder="0,00" required/><Textarea name="rationale" placeholder={m.rationale} required/><input type="hidden" name="approve" value="no"/><label className="flex min-h-11 items-center gap-2"><input name="approve" type="checkbox" value="yes"/><span>{m.approve}</span></label><Button disabled={pending}>{m.save}</Button><Feedback state={state} m={m}/></form></CardContent></Card>}
function CenterForm({locale,orgId,m,keyValue}:{locale:"fr"|"ar";orgId:string;m:Messages;keyValue:string}){const[state,action,pending]=useActionState(createCostCenter,idle);return <Card><CardHeader><CardTitle>{m.newCenter}</CardTitle></CardHeader><CardContent><form action={action} className="grid gap-3"><Hidden locale={locale} orgId={orgId} keyValue={keyValue}/><Input name="centerCode" placeholder={m.code} pattern="[A-Z][A-Z0-9_-]+" required/><Input name="nameFr" placeholder={m.nameFr} required/><Input name="nameAr" dir="rtl" placeholder={m.nameAr} required/><Input name="changeReason" placeholder={m.reason} required/><Button disabled={pending}>{m.save}</Button><Feedback state={state} m={m}/></form></CardContent></Card>}
function AllocationForm({locale,orgId,projects,budgets,centers,m,keyValue}:{locale:"fr"|"ar";orgId:string;projects:Portfolio["projects"];budgets:Portfolio["budgets"];centers:Portfolio["costCenters"];m:Messages;keyValue:string}){const[state,action,pending]=useActionState(recordAllocation,idle);return <Card><CardHeader><CardTitle>{m.newAllocation}</CardTitle></CardHeader><CardContent><form action={action} className="grid gap-3"><Hidden locale={locale} orgId={orgId} keyValue={keyValue}/><Select name="budgetId" label={m.budgets}>{budgets.map(x=><option key={x.id} value={x.id}>{x.fiscalYear} · {exactMoney(x.amountMinor,x.currency)}</option>)}</Select><Select name="costCenterId" label={m.center}>{centers.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</Select><Select name="projectId" label={m.project} required={false}><option value="">{m.none}</option>{projects.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</Select><Select name="allocationType" label={m.allocationType}><option value="COMMITMENT">COMMITMENT</option><option value="ACTUAL">ACTUAL</option><option value="RELEASE">RELEASE</option></Select><Input name="amount" inputMode="decimal" dir="ltr" placeholder="0,00" required/><Input name="evidenceHash" dir="ltr" pattern="[0-9a-f]{64}" placeholder={m.evidence} required/><Button disabled={pending||budgets.length===0||centers.length===0}>{m.save}</Button><Feedback state={state} m={m}/></form></CardContent></Card>}
function EventForm({locale,orgId,projects,m,keyValue}:{locale:"fr"|"ar";orgId:string;projects:Portfolio["projects"];m:Messages;keyValue:string}){const[state,action,pending]=useActionState(scheduleEvent,idle);return <Card><CardHeader><CardTitle>{m.newEvent}</CardTitle></CardHeader><CardContent><form action={action} className="grid gap-3 md:grid-cols-2"><Hidden locale={locale} orgId={orgId} keyValue={keyValue}/><Select name="projectId" label={m.project} required={false}><option value="">{m.none}</option>{projects.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</Select><Select name="eventType" label={m.eventType}>{["CUSTOM","PROJECT_DEADLINE","APPROVAL","DOCUMENT","INVOICE","MISSION","RFQ"].map(x=><option key={x}>{x}</option>)}</Select><Input name="titleFr" placeholder={m.nameFr} required/><Input name="titleAr" dir="rtl" placeholder={m.nameAr} required/><label className="grid gap-1 text-sm">{m.start}<Input name="startsAt" type="datetime-local" required/></label><label className="grid gap-1 text-sm">{m.ends}<Input name="endsAt" type="datetime-local"/></label><Button disabled={pending} className="md:col-span-2">{m.save}</Button><Feedback state={state} m={m}/></form></CardContent></Card>}
