import { describe,expect,it,vi } from "vitest";
import { deliverNotification,type NotificationDeliveryJob } from "./adapter";

const job:NotificationDeliveryJob={deliveryId:"11111111-1111-4111-8111-111111111111",channel:"EMAIL",recipientEmail:"owner@example.com",locale:"fr-MA",subject:"Échéance",body:"Action requise",ctaPath:"/fr/notifications",providerIdempotencyKey:"notification-delivery:11111111-1111-4111-8111-111111111111"};

describe("notification delivery adapter",()=>{
 it("livre en démo avec une preuve déterministe",async()=>{const first=await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"DEMO"},fetch});const second=await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"DEMO"},fetch});expect(first).toEqual(second);expect(first.outcome).toBe("DELIVERED")});
 it("interdit toujours le mode démo en production",async()=>{expect(await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"DEMO",NODE_ENV:"production"},fetch:vi.fn()as unknown as typeof fetch})).toMatchObject({outcome:"PERMANENT_FAILURE",errorCode:"EMAIL_DEMO_FORBIDDEN"})});
 it("échoue fermé en externe hors allowlist",async()=>{const request=vi.fn();expect(await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"@matricia.ma",EMAIL_PROVIDER_ENDPOINT:"https://mailer.example/send",EMAIL_PROVIDER_TOKEN:"x".repeat(32)},fetch:request as unknown as typeof fetch})).toMatchObject({outcome:"PERMANENT_FAILURE",errorCode:"EMAIL_RECIPIENT_NOT_ALLOWLISTED"});expect(request).not.toHaveBeenCalled()});
 it("ne livre jamais si le mode est absent",async()=>{expect(await deliverNotification(job,{env:{},fetch})).toMatchObject({outcome:"PERMANENT_FAILURE",errorCode:"EMAIL_MODE_UNCONFIGURED"})});
 it("autorise une adresse et endpoint IP exacts, puis transmet l’idempotence",async()=>{const request=vi.fn().mockResolvedValue(new Response(null,{status:202,headers:{"x-message-id":"provider-123"}}));expect(await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"owner@example.com",EMAIL_PROVIDER_ENDPOINT:"https://8.8.8.8/send",EMAIL_PROVIDER_ENDPOINT_ALLOWLIST:"https://8.8.8.8/send",EMAIL_PROVIDER_TOKEN:"x".repeat(32)},fetch:request as unknown as typeof fetch})).toMatchObject({outcome:"DELIVERED",providerMessageId:"provider-123"});expect(request).toHaveBeenCalledWith("https://8.8.8.8/send",expect.objectContaining({redirect:"error",headers:expect.objectContaining({"idempotency-key":job.providerIdempotencyKey})}))});
 it("utilise nativement Resend avec l’expéditeur configuré et sans exposer la clé",async()=>{const request=vi.fn().mockResolvedValue(Response.json({id:"resend-message-123"},{status:200}));const result=await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"owner@example.com",RESEND_API_KEY:"r".repeat(32),RESEND_FROM_EMAIL:"notifications@matricia.example",RESEND_FROM_NAME:"Matricia"},fetch:request as unknown as typeof fetch});expect(result).toMatchObject({outcome:"DELIVERED",providerMessageId:"resend-message-123",evidence:{adapter:"EMAIL_RESEND"}});expect(request).toHaveBeenCalledWith("https://api.resend.com/emails",expect.objectContaining({redirect:"error",headers:expect.objectContaining({authorization:`Bearer ${"r".repeat(32)}`,"idempotency-key":job.providerIdempotencyKey}),body:expect.stringContaining('"from":"Matricia <notifications@matricia.example>"')}))});
 it.each([{}, {RESEND_API_KEY:"r".repeat(32),RESEND_FROM_EMAIL:"invalid"},{RESEND_API_KEY:"r".repeat(32),RESEND_FROM_EMAIL:"ok@example.com",RESEND_FROM_NAME:"bad\nname"}])("échoue fermé quand Resend est incomplet ou invalide",async(resend)=>{const request=vi.fn();expect(await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"owner@example.com",...resend},fetch:request as unknown as typeof fetch})).toMatchObject({outcome:"PERMANENT_FAILURE",errorCode:"EMAIL_PROVIDER_NOT_CONFIGURED"});expect(request).not.toHaveBeenCalled()});
 it.each(["https://mailer.example/send","https://127.0.0.1/send","https://100.64.0.1/send","https://198.18.0.1/send","https://224.0.0.1/send","https://192.0.2.1/send","https://192.88.99.1/send","https://[fd00::1]/send","https://[::ffff:7f00:1]/send","https://[2002:7f00:1::]/send","https://[3fff::1]/send"])("bloque endpoint non global ou sujet au rebinding %s",async(endpoint)=>{const request=vi.fn(),href=new URL(endpoint).href;expect(await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"@example.com",EMAIL_PROVIDER_ENDPOINT:endpoint,EMAIL_PROVIDER_ENDPOINT_ALLOWLIST:href,EMAIL_PROVIDER_TOKEN:"x".repeat(32)},fetch:request as unknown as typeof fetch})).toMatchObject({outcome:"PERMANENT_FAILURE",errorCode:"EMAIL_PROVIDER_NOT_CONFIGURED"});expect(request).not.toHaveBeenCalled()});
 it.each(["ab",`ok${"x".repeat(199)}`,"bad\u007fid"])("refuse un message-id non borné ou de contrôle",async(providerMessageId)=>{const response={ok:true,status:202,headers:{get:(name:string)=>name==="x-message-id"?providerMessageId:null}}as Response;expect(await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"@example.com",EMAIL_PROVIDER_ENDPOINT:"https://8.8.8.8/send",EMAIL_PROVIDER_ENDPOINT_ALLOWLIST:"https://8.8.8.8/send",EMAIL_PROVIDER_TOKEN:"x".repeat(32)},fetch:vi.fn().mockResolvedValue(response)as unknown as typeof fetch})).toMatchObject({outcome:"RETRYABLE_FAILURE",errorCode:"EMAIL_PROVIDER_MESSAGE_ID_INVALID"})});
 it("classe 429 en retry et 400 en échec permanent",async()=>{for(const [status,outcome]of[[429,"RETRYABLE_FAILURE"],[400,"PERMANENT_FAILURE"]]as const){const request=vi.fn().mockResolvedValue(new Response(null,{status}));expect((await deliverNotification(job,{env:{EMAIL_DELIVERY_MODE:"EXTERNAL",EMAIL_LIVE_DELIVERY_ENABLED:"true",EMAIL_RECIPIENT_ALLOWLIST:"@example.com",EMAIL_PROVIDER_ENDPOINT:"https://8.8.8.8/send",EMAIL_PROVIDER_ENDPOINT_ALLOWLIST:"https://8.8.8.8/send",EMAIL_PROVIDER_TOKEN:"x".repeat(32)},fetch:request as unknown as typeof fetch})).outcome).toBe(outcome)}});
});
