import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({rpc:vi.fn(),download:vi.fn(),lookup:vi.fn()}));
vi.mock("@/modules/shared/lib/supabase/admin",()=>({getSupabaseAdminClient:()=>({rpc:mocks.rpc,storage:{from:()=>({download:mocks.download})}})}));
vi.mock("node:dns/promises",()=>({lookup:mocks.lookup}));
import{POST}from"./route";
const token="s".repeat(32),worker="11111111-1111-4111-8111-111111111111",proof="22222222-2222-4222-8222-222222222222",lease="33333333-3333-4333-8333-333333333333",correlation="44444444-4444-4444-8444-444444444444",pdf=Buffer.from("%PDF-1.7 valid");
vi.mock("node:crypto",async(importOriginal)=>{const actual=await importOriginal<typeof import("node:crypto")>();let call=0;return{...actual,randomUUID:()=>++call%2?worker:correlation}});
function request(secret=token){return new Request("http://localhost/api/workers/delivery-proof-scans?limit=5",{method:"POST",headers:{authorization:`Bearer ${secret}`}})}
function claim(hash:string,media="application/pdf"){return{proof_id:proof,lease_token:lease,worker_id:worker,row_version:1,attempt_count:0,storage_bucket:"delivery-proofs",storage_path:`user/${proof}/proof.pdf`,expected_sha256:hash,media_type:media}}
async function signedScanner(result:"CLEAN"|"INFECTED",hash:string){const{createHmac}=await import("node:crypto"),body=JSON.stringify({result,sha256:hash,engineCode:"ACME_AV",engineVersion:"9.1"}),signature=createHmac("sha256","t".repeat(32)).update(body).digest("hex");vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(body,{status:200,headers:{"x-scan-signature":signature}})))}
describe("delivery proof scan worker",()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();process.env.CRON_SECRET=token;process.env.MALWARE_SCANNER_URL="https://8.8.8.8/v1/scan";process.env.MALWARE_SCANNER_ALLOWED_HOSTS="8.8.8.8";process.env.MALWARE_SCANNER_TOKEN="t".repeat(32);delete process.env.DELIVERY_PROOF_SCANNER_MODE;mocks.rpc.mockImplementation(async(name:string)=>name==="cleanup_delivery_proof_storage_orphans"?{data:{outcome:"DELIVERY_PROOF_ORPHANS_CLEANED",count:0},error:null}:name==="claim_provider_payment_proof_scan_jobs"?{data:[],error:null}:{data:null,error:{code:"UNMOCKED"}})});
 it("refuse un appel sans secret",async()=>{expect((await POST(new Request("http://localhost/api/workers/delivery-proof-scans"))).status).toBe(401);expect(mocks.rpc).not.toHaveBeenCalled()});
 it("valide une réponse CLEAN signée du scanner externe",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex");await signedScanner("CLEAN",hash);mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RECORDED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"complete_delivery_proof_scan_job",expect.objectContaining({p_result:"CLEAN",p_engine_code:"ACME_AV",p_computed_sha256:hash,p_lease_token:lease}))});
 it("quarantaine un verdict INFECTED signé",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex");await signedScanner("INFECTED",hash);mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RECORDED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"complete_delivery_proof_scan_job",expect.objectContaining({p_result:"INFECTED"}))});
 it("enregistre ERROR si le hash stocké ne correspond pas",async()=>{mocks.rpc.mockResolvedValueOnce({data:[claim("a".repeat(64))],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RECORDED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"complete_delivery_proof_scan_job",expect.objectContaining({p_result:"ERROR"}))});
 it("programme un retry si le scanner externe ne répond pas",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex");vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("provider down")));mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"fail_delivery_proof_scan_job",expect.objectContaining({p_failure_code:"SCANNER_UNAVAILABLE"}))});
 it("refuse un verdict externe dont le HMAC est invalide et le remet en attente",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex"),body=JSON.stringify({result:"CLEAN",sha256:hash,engineCode:"ACME_AV",engineVersion:"9.1"});vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(body,{headers:{"x-scan-signature":"0".repeat(64)}})));mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"fail_delivery_proof_scan_job",expect.objectContaining({p_failure_code:"SCANNER_INVALID_RESPONSE"}))});
 it("interdit le scanner SANDBOX en production et programme un retry",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex");process.env.DELIVERY_PROOF_SCANNER_MODE="SANDBOX";vi.stubEnv("NODE_ENV","production");delete process.env.MALWARE_SCANNER_URL;delete process.env.MALWARE_SCANNER_TOKEN;mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"fail_delivery_proof_scan_job",expect.any(Object))});
 it("bloque un endpoint scanner privé même s'il est allowlisté",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex");process.env.MALWARE_SCANNER_URL="https://127.0.0.1/scan";process.env.MALWARE_SCANNER_ALLOWED_HOSTS="127.0.0.1";const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});const response=await POST(request());expect(response.status).toBe(200);expect(fetchMock).not.toHaveBeenCalled()});
 it("bloque IPv6 ULA et IPv4-mapped pointé avant fetch",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex"),fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});for(const [url,host]of[["https://[fd00::1]/scan","fd00::1"],["https://[::ffff:192.168.1.8]/scan","::ffff:192.168.1.8"]]){process.env.MALWARE_SCANNER_URL=url;process.env.MALWARE_SCANNER_ALLOWED_HOSTS=host;mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});expect((await POST(request())).status).toBe(200);}expect(fetchMock).not.toHaveBeenCalled()});
 it("bloque IPv4-mapped hexadécimal et tout hostname sujet au rebinding",async()=>{const{createHash}=await import("node:crypto"),hash=createHash("sha256").update(pdf).digest("hex"),fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);process.env.MALWARE_SCANNER_URL="https://[::ffff:7f00:1]/scan";process.env.MALWARE_SCANNER_ALLOWED_HOSTS="::ffff:7f00:1";mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});mocks.download.mockResolvedValue({data:new Blob([pdf]),error:null});expect((await POST(request())).status).toBe(200);expect(fetchMock).not.toHaveBeenCalled();process.env.MALWARE_SCANNER_URL="https://scanner.example.test/scan";process.env.MALWARE_SCANNER_ALLOWED_HOSTS="scanner.example.test";mocks.rpc.mockResolvedValueOnce({data:[claim(hash)],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});expect((await POST(request())).status).toBe(200);expect(fetchMock).not.toHaveBeenCalled();expect(mocks.lookup).not.toHaveBeenCalled()});
 it("borne le lot à deux scans sous maxDuration et réserve une place aux preuves de paiement",async()=>{mocks.rpc.mockResolvedValueOnce({data:[],error:null});const response=await POST(request());expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith("claim_delivery_proof_scan_jobs",expect.objectContaining({p_limit:1}));expect(mocks.rpc).toHaveBeenCalledWith("claim_provider_payment_proof_scan_jobs",expect.objectContaining({p_limit:1}))});
 it("retry sans révéler l'erreur Storage",async()=>{mocks.rpc.mockResolvedValueOnce({data:[claim("a".repeat(64))],error:null}).mockResolvedValueOnce({data:{outcome:"DELIVERY_PROOF_SCAN_RETRY_SCHEDULED"},error:null});mocks.download.mockResolvedValue({data:null,error:{message:"bucket secret"}});const response=await POST(request());expect(response.status).toBe(200);expect(JSON.stringify(await response.json())).not.toContain("bucket secret")});
});
