-- Transversal, versioned abuse detection. No raw identifiers or secrets are persisted.

create table public.abuse_rule_versions(
 id uuid primary key default extensions.gen_random_uuid(),rule_code text not null check(rule_code~'^[A-Z][A-Z0-9_]{2,79}$'),version integer not null check(version>0),
 event_type text not null check(event_type~'^[A-Z][A-Z0-9_.-]{2,99}$'),window_seconds integer not null check(window_seconds between 60 and 2592000),max_events integer not null check(max_events between 1 and 100000),
 review_score integer not null check(review_score between 1 and 100),block_score integer not null check(block_score between review_score and 100),conditions jsonb not null default'{}'check(jsonb_typeof(conditions)='object'),
 status text not null default'DRAFT'check(status in('DRAFT','ACTIVE','RETIRED')),effective_from timestamptz,effective_until timestamptz,content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),
 unique(rule_code,version),check(effective_until is null or effective_from is not null and effective_until>effective_from)
);
create table public.abuse_signal_events(
 id bigint generated always as identity primary key,organization_id uuid references public.organizations(id)on delete restrict,rule_version_id uuid not null references public.abuse_rule_versions(id)on delete restrict,
 event_type text not null,subject_type text not null check(subject_type~'^[A-Z][A-Z0-9_]{2,79}$'),subject_hash text not null check(subject_hash~'^[0-9a-f]{64}$'),score integer not null check(score between 0 and 100),
 redacted_context jsonb not null default'{}'check(jsonb_typeof(redacted_context)='object'and octet_length(convert_to(redacted_context::text,'UTF8'))<=8192),occurred_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,idempotency_key text not null,
 unique(rule_version_id,idempotency_key)
);
create table public.abuse_review_cases(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid references public.organizations(id)on delete restrict,rule_version_id uuid not null references public.abuse_rule_versions(id)on delete restrict,
 subject_type text not null,subject_hash text not null check(subject_hash~'^[0-9a-f]{64}$'),risk_score integer not null check(risk_score between 0 and 100),event_count integer not null check(event_count>0),
 recommended_action text not null check(recommended_action in('REVIEW','BLOCK')),status text not null default'OPEN'check(status in('OPEN','APPROVED','BLOCKED','DISMISSED')),opened_at timestamptz not null default clock_timestamp(),closed_at timestamptz,row_version integer not null default 1 check(row_version>0)
);
create table public.abuse_case_decisions(
 id uuid primary key default extensions.gen_random_uuid(),case_id uuid not null references public.abuse_review_cases(id)on delete restrict,decision text not null check(decision in('APPROVED','BLOCKED','DISMISSED')),reason text not null check(length(btrim(reason))between 10 and 2000),evidence_hash text not null check(evidence_hash~'^[0-9a-f]{64}$'),decided_by uuid not null references auth.users(id),decided_at timestamptz not null default clock_timestamp(),unique(case_id)
);

create function private.prevent_abuse_history_change()returns trigger language plpgsql set search_path=pg_catalog as $$begin raise exception'ABUSE_HISTORY_IMMUTABLE'using errcode='55000';end$$;
create trigger abuse_rules_immutable before update or delete on public.abuse_rule_versions for each row execute function private.prevent_abuse_history_change();
create trigger abuse_signals_immutable before update or delete on public.abuse_signal_events for each row execute function private.prevent_abuse_history_change();
create trigger abuse_decisions_immutable before update or delete on public.abuse_case_decisions for each row execute function private.prevent_abuse_history_change();

create function public.create_abuse_rule_version(p_rule_code text,p_event_type text,p_window_seconds integer,p_max_events integer,p_review_score integer,p_block_score integer,p_conditions jsonb,p_activate boolean,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();n integer;h text;x uuid;r jsonb;begin if a is null or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','SECURITY_ADMIN'],a)or coalesce(auth.jwt()->>'aal','')<>'aal2'then raise exception'ABUSE_RULE_ADMIN_DENIED'using errcode='42501';end if;
if p_rule_code!~'^[A-Z][A-Z0-9_]{2,79}$'or p_event_type!~'^[A-Z][A-Z0-9_.-]{2,99}$'or p_window_seconds not between 60 and 2592000 or p_max_events not between 1 and 100000 or p_review_score not between 1 and 100 or p_block_score not between p_review_score and 100 or jsonb_typeof(p_conditions)<>'object'then raise exception'INVALID_ABUSE_RULE'using errcode='22023';end if;
perform pg_advisory_xact_lock(hashtextextended('abuse-rule:'||p_rule_code,0));select coalesce(max(version),0)+1 into n from public.abuse_rule_versions where rule_code=p_rule_code;h:=private.canonical_request_hash(jsonb_build_object('code',p_rule_code,'event',p_event_type,'window',p_window_seconds,'max',p_max_events,'review',p_review_score,'block',p_block_score,'conditions',p_conditions,'activate',p_activate,'key',p_idempotency_key));
insert into public.abuse_rule_versions(rule_code,version,event_type,window_seconds,max_events,review_score,block_score,conditions,status,effective_from,content_hash,created_by)values(p_rule_code,n,p_event_type,p_window_seconds,p_max_events,p_review_score,p_block_score,p_conditions,case when p_activate then'ACTIVE'else'DRAFT'end,case when p_activate then clock_timestamp()end,h,a)returning id into x;
r:=jsonb_build_object('outcome','ABUSE_RULE_VERSION_CREATED','rule_version_id',x,'version',n,'status',case when p_activate then'ACTIVE'else'DRAFT'end);insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(a,'USER','abuse.rule.version_created','abuse_rule_version',x::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values('abuse_rule',x::text,'AbuseRuleVersionCreatedV1',p_correlation_id,r,p_idempotency_key);return r;end$$;

create function public.evaluate_abuse_signal(p_organization_id uuid,p_event_type text,p_subject_type text,p_subject_hash text,p_score integer,p_redacted_context jsonb,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();v public.abuse_rule_versions%rowtype;n integer;s integer;action text:='ALLOW';c uuid;r jsonb;begin if a is null or not(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','SECURITY_ADMIN'],a)or(p_organization_id is not null and private.is_active_org_member(p_organization_id,a)))then raise exception'ABUSE_SIGNAL_DENIED'using errcode='42501';end if;
select*into v from public.abuse_rule_versions where event_type=p_event_type and status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp())order by version desc limit 1;if not found then return jsonb_build_object('outcome','NO_ACTIVE_ABUSE_RULE','action','ALLOW');end if;
if p_subject_type!~'^[A-Z][A-Z0-9_]{2,79}$'or p_subject_hash!~'^[0-9a-f]{64}$'or p_score not between 0 and 100 or jsonb_typeof(p_redacted_context)<>'object'or octet_length(convert_to(p_redacted_context::text,'UTF8'))>8192 then raise exception'INVALID_ABUSE_SIGNAL'using errcode='22023';end if;
perform pg_advisory_xact_lock(hashtextextended('abuse:'||v.id::text||':'||p_subject_hash,0));insert into public.abuse_signal_events(organization_id,rule_version_id,event_type,subject_type,subject_hash,score,redacted_context,correlation_id,idempotency_key)values(p_organization_id,v.id,p_event_type,p_subject_type,p_subject_hash,p_score,p_redacted_context,p_correlation_id,p_idempotency_key)on conflict(rule_version_id,idempotency_key)do nothing;
select count(*),greatest(coalesce(max(score),0),least(100,(count(*)*100/greatest(v.max_events,1))::integer))into n,s from public.abuse_signal_events where rule_version_id=v.id and subject_hash=p_subject_hash and occurred_at>=clock_timestamp()-make_interval(secs=>v.window_seconds);
if n>v.max_events or s>=v.block_score then action:='BLOCK';elsif s>=v.review_score then action:='REVIEW';end if;
if action<>'ALLOW'and not exists(select 1 from public.abuse_review_cases where rule_version_id=v.id and subject_hash=p_subject_hash and status='OPEN')then insert into public.abuse_review_cases(organization_id,rule_version_id,subject_type,subject_hash,risk_score,event_count,recommended_action)values(p_organization_id,v.id,p_subject_type,p_subject_hash,s,n,action)returning id into c;end if;
r:=jsonb_build_object('outcome','ABUSE_SIGNAL_EVALUATED','action',action,'risk_score',s,'event_count',n,'case_id',c,'rule_version_id',v.id);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','abuse.signal.evaluated','abuse_subject',p_subject_hash,p_correlation_id,r,repeat('0',64));if action<>'ALLOW'then insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'abuse_case',coalesce(c::text,p_subject_hash),'AbuseRiskDetectedV1',p_correlation_id,r,p_idempotency_key);end if;return r;end$$;

create function public.decide_abuse_case(p_case_id uuid,p_expected_row_version integer,p_decision text,p_reason text,p_evidence_hash text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();c public.abuse_review_cases%rowtype;x uuid;r jsonb;begin select*into c from public.abuse_review_cases where id=p_case_id for update;if a is null or not found or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','SECURITY_ADMIN'],a)or coalesce(auth.jwt()->>'aal','')<>'aal2'then raise exception'ABUSE_CASE_DECISION_DENIED'using errcode='42501';end if;if c.status<>'OPEN'or c.row_version<>p_expected_row_version or p_decision not in('APPROVED','BLOCKED','DISMISSED')or length(btrim(p_reason))not between 10 and 2000 or p_evidence_hash!~'^[0-9a-f]{64}$'then raise exception'INVALID_ABUSE_CASE_DECISION'using errcode='40001';end if;insert into public.abuse_case_decisions(case_id,decision,reason,evidence_hash,decided_by)values(c.id,p_decision,btrim(p_reason),p_evidence_hash,a)returning id into x;update public.abuse_review_cases set status=p_decision,closed_at=clock_timestamp(),row_version=row_version+1 where id=c.id;r:=jsonb_build_object('outcome','ABUSE_CASE_DECIDED','case_id',c.id,'decision_id',x,'decision',p_decision);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(c.organization_id,a,'USER','abuse.case.decided','abuse_case',c.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(c.organization_id,'abuse_case',c.id::text,'AbuseCaseDecidedV1',p_correlation_id,r,p_idempotency_key);return r;end$$;

alter table public.abuse_rule_versions enable row level security;alter table public.abuse_signal_events enable row level security;alter table public.abuse_review_cases enable row level security;alter table public.abuse_case_decisions enable row level security;
revoke all on public.abuse_rule_versions,public.abuse_signal_events,public.abuse_review_cases,public.abuse_case_decisions from public,anon,authenticated,service_role;
create policy abuse_rules_admin_read on public.abuse_rule_versions for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','SECURITY_ADMIN','READ_ONLY_AUDITOR']));
create policy abuse_cases_admin_read on public.abuse_review_cases for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','SECURITY_ADMIN','READ_ONLY_AUDITOR']));
create policy abuse_decisions_admin_read on public.abuse_case_decisions for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','SECURITY_ADMIN','READ_ONLY_AUDITOR']));
grant select on public.abuse_rule_versions,public.abuse_review_cases,public.abuse_case_decisions to authenticated;
revoke all on function public.create_abuse_rule_version(text,text,integer,integer,integer,integer,jsonb,boolean,text,uuid),public.evaluate_abuse_signal(uuid,text,text,text,integer,jsonb,text,uuid),public.decide_abuse_case(uuid,integer,text,text,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.create_abuse_rule_version(text,text,integer,integer,integer,integer,jsonb,boolean,text,uuid),public.evaluate_abuse_signal(uuid,text,text,text,integer,jsonb,text,uuid),public.decide_abuse_case(uuid,integer,text,text,text,text,uuid)to authenticated;
create index abuse_signals_window_idx on public.abuse_signal_events(rule_version_id,subject_hash,occurred_at desc);
create index abuse_cases_queue_idx on public.abuse_review_cases(status,risk_score desc,opened_at);

