-- P06 Question Builder commands: immutable versions, optimistic concurrency, audit and Outbox.

create function private.assert_question_builder_payload(p_library_id uuid,p_scope text,p_payload jsonb) returns void
language plpgsql stable security definer set search_path=pg_catalog as $$
declare v_service uuid;
begin
 if p_library_id is null or p_scope not in('GLOBAL','LIBRARY','CATEGORY','SUBCATEGORY','SERVICE') or jsonb_typeof(p_payload)<>'object'
  or not(p_payload?&array['label_fr','label_ar','answer_type','data_key','required_by_default','required_for_quote','required_for_publication','options','validation_schema','sensitivity','nullable','weight','maximum_score'])
  or exists(select 1 from jsonb_object_keys(p_payload)k where k not in('label_fr','label_ar','help_fr','help_ar','why_we_ask_fr','why_we_ask_ar','answer_type','data_key','required_by_default','required_for_quote','required_for_publication','options','validation_schema','structured_schema','visibility_rule','default_value','prefill_source','sensitivity','nullable','weight','maximum_score','template_key','validity_seconds','source_service_id'))
  or length(btrim(coalesce(p_payload->>'label_fr',''))) not between 1 and 1000 or length(btrim(coalesce(p_payload->>'label_ar',''))) not between 1 and 1000
  or coalesce(p_payload->>'answer_type','') not in('YES_NO','SINGLE_CHOICE','MULTIPLE_CHOICE','SHORT_TEXT','LONG_TEXT','INTEGER','DECIMAL','PERCENTAGE','MONEY','CURRENCY','DATE','DATE_RANGE','TIME','EMAIL','PHONE','URL','ADDRESS','GEO_AREA','RATING_5','RATING_10','QUANTITY','UNIT_VALUE','FILE','MULTI_FILE','IMAGE','TABLE','REPEATER','CONTACT','ORGANIZATION','PRODUCT_LIST','SITE_LIST','MILESTONE_LIST','BUDGET_BREAKDOWN')
  or coalesce(p_payload->>'data_key','')!~'^[A-Za-z][A-Za-z0-9_.-]{1,159}$'
  or jsonb_typeof(p_payload->'required_by_default')<>'boolean' or jsonb_typeof(p_payload->'required_for_quote')<>'boolean' or jsonb_typeof(p_payload->'required_for_publication')<>'boolean' or jsonb_typeof(p_payload->'nullable')<>'boolean'
  or jsonb_typeof(p_payload->'options')<>'array' or jsonb_typeof(p_payload->'validation_schema')<>'object'
  or coalesce(p_payload->>'sensitivity','') not in('PUBLIC','BUSINESS','CONFIDENTIAL','RESTRICTED')
  or jsonb_typeof(p_payload->'weight')<>'number' or jsonb_typeof(p_payload->'maximum_score')<>'number'
  or (p_payload->>'weight')!~'^(0|[1-9][0-9]{0,13})(\.[0-9]{1,6})?$' or (p_payload->>'maximum_score')!~'^(0|[1-9][0-9]{0,13})(\.[0-9]{1,6})?$'
  or exists(select 1 from jsonb_array_elements(p_payload->'options')o where jsonb_typeof(o)<>'string' or length(btrim(o#>>'{}')) not between 1 and 500)
  or jsonb_array_length(p_payload->'options')<>(select count(distinct o)from jsonb_array_elements_text(p_payload->'options')o)
  or (p_payload->>'answer_type' not in('SINGLE_CHOICE','MULTIPLE_CHOICE') and p_payload->'options'<>'[]'::jsonb)
  or (p_payload->>'answer_type' in('TABLE','REPEATER')) is distinct from (jsonb_typeof(p_payload->'structured_schema')='object')
  or (p_payload?'visibility_rule' and jsonb_typeof(p_payload->'visibility_rule') not in('object','null'))
  or (p_payload?'prefill_source' and p_payload->>'prefill_source' is not null and p_payload->>'prefill_source' not in('PROFILE','ORGANIZATION','SITE','PREVIOUS_ANSWER','DOCUMENT'))
  or (p_payload?'template_key' and p_payload->>'template_key' is not null and length(btrim(p_payload->>'template_key')) not between 1 and 160)
  or (p_payload?'validity_seconds' and (jsonb_typeof(p_payload->'validity_seconds')<>'number' or (p_payload->>'validity_seconds')!~'^[1-9][0-9]{0,8}$')) then raise exception 'INVALID_CATALOG_QUESTION' using errcode='22023';end if;
 if p_scope='SERVICE' then
  begin v_service:=(p_payload->>'source_service_id')::uuid;exception when others then raise exception 'INVALID_CATALOG_QUESTION' using errcode='22023';end;
  if not exists(select 1 from public.catalog_services s where s.id=v_service and s.library_id=p_library_id and s.status not in('RETIRED','ARCHIVED')) then raise exception 'CATALOG_QUESTION_SERVICE_SCOPE_MISMATCH' using errcode='23514';end if;
 elsif p_payload?'source_service_id' and p_payload->>'source_service_id' is not null then raise exception 'CATALOG_QUESTION_SERVICE_SCOPE_MISMATCH' using errcode='23514';end if;
end $$;

create function private.insert_question_builder_version(p_question_id uuid,p_library_id uuid,p_payload jsonb,p_change_reason text,p_actor uuid,p_version integer) returns uuid
language plpgsql security definer set search_path=pg_catalog,private as $$
declare v_id uuid;v_hash text:=private.canonical_request_hash(p_payload);v_validity interval;
begin
 if length(btrim(coalesce(p_change_reason,''))) not between 3 and 500 or p_version<1 then raise exception 'INVALID_CATALOG_QUESTION' using errcode='22023';end if;
 if p_payload?'validity_seconds' then v_validity:=make_interval(secs=>(p_payload->>'validity_seconds')::double precision);end if;
 insert into public.question_versions(question_id,library_id,version,status,label_fr,label_ar,help_fr,help_ar,why_we_ask_fr,why_we_ask_ar,answer_type,data_key,required_by_default,required_for_quote,required_for_publication,options,validation_schema,structured_schema,visibility_rule,default_value,prefill_source,sensitivity,nullable,weight,maximum_score,template_key,validity_interval,content_hash,change_reason,translation_review_status,created_by,source_service_id)
 values(p_question_id,p_library_id,p_version,'DRAFT',btrim(p_payload->>'label_fr'),btrim(p_payload->>'label_ar'),nullif(btrim(p_payload->>'help_fr'),''),nullif(btrim(p_payload->>'help_ar'),''),nullif(btrim(p_payload->>'why_we_ask_fr'),''),nullif(btrim(p_payload->>'why_we_ask_ar'),''),p_payload->>'answer_type',p_payload->>'data_key',(p_payload->>'required_by_default')::boolean,(p_payload->>'required_for_quote')::boolean,(p_payload->>'required_for_publication')::boolean,p_payload->'options',p_payload->'validation_schema',case when p_payload->>'answer_type'in('TABLE','REPEATER')then p_payload->'structured_schema'else null end,case when jsonb_typeof(p_payload->'visibility_rule')='object'then p_payload->'visibility_rule'else null end,p_payload->'default_value',nullif(p_payload->>'prefill_source',''),p_payload->>'sensitivity',(p_payload->>'nullable')::boolean,(p_payload->>'weight')::numeric,(p_payload->>'maximum_score')::numeric,nullif(btrim(p_payload->>'template_key'),''),v_validity,v_hash,btrim(p_change_reason),'PENDING',p_actor,case when p_payload->>'source_service_id' is null then null else(p_payload->>'source_service_id')::uuid end) returning id into v_id;
 return v_id;
end $$;

create function public.create_catalog_question(p_library_id uuid,p_question_key text,p_scope text,p_payload jsonb,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid()) returns jsonb
language plpgsql security definer set search_path=pg_catalog,extensions,private as $$
declare v_actor uuid:=auth.uid();v_hash text;v_command uuid;v_replay jsonb;v_question uuid;v_version uuid;v_org uuid;v_response jsonb;
begin
 perform private.assert_question_builder_payload(p_library_id,p_scope,p_payload);
 if v_actor is null or btrim(coalesce(p_question_key,''))!~'^[A-Z][A-Z0-9_.-]{1,119}$' or length(btrim(coalesce(p_change_reason,''))) not between 3 and 500 or not private.has_library_permission(p_library_id,'CATALOG_EDIT',v_actor) then raise exception 'CATALOG_SCOPE_DENIED' using errcode='42501';end if;
 if p_scope='GLOBAL' then perform private.assert_catalog_central_aal2_locked(v_actor);end if;if p_payload->>'sensitivity'in('CONFIDENTIAL','RESTRICTED')and auth.jwt()->>'aal' is distinct from'aal2'then raise exception 'CATALOG_SENSITIVE_MFA_REQUIRED' using errcode='42501';end if;
 v_hash:=private.canonical_request_hash(jsonb_build_object('operation','catalog.question.create.v1','library_id',p_library_id,'question_key',btrim(p_question_key),'scope',p_scope,'payload',p_payload,'change_reason',btrim(p_change_reason)));select b.command_id,b.response_body into v_command,v_replay from private.begin_catalog_command(v_actor,'catalog.question.create',p_idempotency_key,v_hash)b;
 perform pg_advisory_xact_lock(hashtextextended('catalog-library:'||p_library_id::text,0));perform private.assert_catalog_permission_locked(p_library_id,'CATALOG_EDIT',v_actor);if v_replay is not null then return v_replay;end if;
 select steward_organization_id into v_org from public.catalog_libraries where id=p_library_id and status not in('RETIRED','ARCHIVED');if not found then raise exception 'CATALOG_LIBRARY_NOT_FOUND' using errcode='P0002';end if;
 insert into public.question_bank_questions(library_id,question_key,scope,status,created_by)values(p_library_id,btrim(p_question_key),p_scope,'DRAFT',v_actor)returning id into v_question;
 v_version:=private.insert_question_builder_version(v_question,p_library_id,p_payload,p_change_reason,v_actor,1);update public.question_bank_questions set current_draft_version_id=v_version where id=v_question;
 v_response:=jsonb_build_object('outcome','CATALOG_QUESTION_CREATED','question_id',v_question,'library_id',p_library_id,'version_id',v_version,'identity_row_version',1,'version_row_version',1,'content_hash',private.canonical_request_hash(p_payload),'command_id',v_command);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,previous_hash,event_hash)values(v_org,v_actor,'USER','catalog.question.created','catalog_question',v_question::text,p_correlation_id,jsonb_build_object('version_id',v_version,'scope',p_scope,'command_id',v_command),null,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key,causation_id)values(v_org,'catalog_question',v_question::text,'CatalogQuestionCreatedV1',p_correlation_id,jsonb_build_object('question_id',v_question,'version_id',v_version),p_idempotency_key,v_command);perform private.finish_catalog_command(v_actor,'catalog.question.create',p_idempotency_key,v_response);return v_response;
end $$;

create function public.save_catalog_question_draft(p_question_id uuid,p_source_version_id uuid,p_scope text,p_payload jsonb,p_change_reason text,p_expected_identity_row_version integer,p_expected_source_row_version integer,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid()) returns jsonb
language plpgsql security definer set search_path=pg_catalog,extensions,private as $$
declare v_actor uuid:=auth.uid();v_identity public.question_bank_questions%rowtype;v_source public.question_versions%rowtype;v_hash text;v_command uuid;v_replay jsonb;v_number integer;v_version uuid;v_org uuid;v_response jsonb;
begin
 if v_actor is null or p_expected_identity_row_version<1 or p_expected_source_row_version<1 then raise exception 'INVALID_CATALOG_QUESTION' using errcode='22023';end if;select * into v_identity from public.question_bank_questions where id=p_question_id;if not found or not private.has_library_permission(v_identity.library_id,'CATALOG_EDIT',v_actor)then raise exception 'CATALOG_SCOPE_DENIED' using errcode='42501';end if;perform private.assert_question_builder_payload(v_identity.library_id,p_scope,p_payload);select * into v_source from public.question_versions where id=p_source_version_id and question_id=p_question_id;if not found then raise exception 'CATALOG_QUESTION_VERSION_NOT_FOUND' using errcode='P0002';end if;
 if p_scope='GLOBAL'then perform private.assert_catalog_central_aal2_locked(v_actor);end if;if p_payload->>'sensitivity'in('CONFIDENTIAL','RESTRICTED')and auth.jwt()->>'aal'is distinct from'aal2'then raise exception 'CATALOG_SENSITIVE_MFA_REQUIRED' using errcode='42501';end if;
 v_hash:=private.canonical_request_hash(jsonb_build_object('operation','catalog.question.save.v1','question_id',p_question_id,'source_version_id',p_source_version_id,'scope',p_scope,'payload',p_payload,'change_reason',btrim(p_change_reason),'expected_identity',p_expected_identity_row_version,'expected_source',p_expected_source_row_version));select b.command_id,b.response_body into v_command,v_replay from private.begin_catalog_command(v_actor,'catalog.question.save',p_idempotency_key,v_hash)b;
 perform pg_advisory_xact_lock(hashtextextended('catalog-question:'||p_question_id::text,0));select * into v_identity from public.question_bank_questions where id=p_question_id for update;select * into v_source from public.question_versions where id=p_source_version_id and question_id=p_question_id for share;perform private.assert_catalog_permission_locked(v_identity.library_id,'CATALOG_EDIT',v_actor);if v_replay is not null then return v_replay;end if;if v_identity.status='ARCHIVED'or p_source_version_id is distinct from coalesce(v_identity.current_draft_version_id,v_identity.current_published_version_id)then raise exception 'CATALOG_QUESTION_NOT_EDITABLE' using errcode='55000';end if;if v_identity.row_version is distinct from p_expected_identity_row_version or v_source.row_version is distinct from p_expected_source_row_version then raise exception 'STALE_CATALOG_VERSION' using errcode='40001';end if;
 select coalesce(max(version),0)+1 into v_number from public.question_versions where question_id=p_question_id;v_version:=private.insert_question_builder_version(p_question_id,v_identity.library_id,p_payload,p_change_reason,v_actor,v_number);select steward_organization_id into v_org from public.catalog_libraries where id=v_identity.library_id;update public.question_bank_questions set scope=p_scope,status=case when current_published_version_id is null then'DRAFT'else'PUBLISHED'end,current_draft_version_id=v_version,row_version=row_version+1 where id=p_question_id;
 v_response:=jsonb_build_object('outcome','CATALOG_QUESTION_DRAFT_SAVED','question_id',p_question_id,'library_id',v_identity.library_id,'version_id',v_version,'version_number',v_number,'identity_row_version',p_expected_identity_row_version+1,'version_row_version',1,'content_hash',private.canonical_request_hash(p_payload),'command_id',v_command);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,previous_hash,event_hash)values(v_org,v_actor,'USER','catalog.question.draft_saved','catalog_question',p_question_id::text,p_correlation_id,jsonb_build_object('source_version_id',p_source_version_id,'version_id',v_version,'command_id',v_command),v_source.content_hash,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key,causation_id)values(v_org,'catalog_question',p_question_id::text,'CatalogQuestionDraftSavedV1',p_correlation_id,jsonb_build_object('question_id',p_question_id,'version_id',v_version),p_idempotency_key,v_command);perform private.finish_catalog_command(v_actor,'catalog.question.save',p_idempotency_key,v_response);return v_response;
end $$;

create function public.duplicate_catalog_question(p_question_id uuid,p_source_version_id uuid,p_new_question_key text,p_new_data_key text,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid()) returns jsonb
language plpgsql security definer set search_path=pg_catalog,extensions,private as $$
declare v_actor uuid:=auth.uid();v_identity public.question_bank_questions%rowtype;v_source public.question_versions%rowtype;v_payload jsonb;v_hash text;v_command uuid;v_replay jsonb;v_question uuid;v_version uuid;v_org uuid;v_response jsonb;
begin
 if v_actor is null or btrim(coalesce(p_new_question_key,''))!~'^[A-Z][A-Z0-9_.-]{1,119}$'or coalesce(p_new_data_key,'')!~'^[A-Za-z][A-Za-z0-9_.-]{1,159}$'then raise exception 'INVALID_CATALOG_QUESTION' using errcode='22023';end if;select * into v_identity from public.question_bank_questions where id=p_question_id;select * into v_source from public.question_versions where id=p_source_version_id and question_id=p_question_id;if v_identity.id is null or v_source.id is null or not private.has_library_permission(v_identity.library_id,'CATALOG_EDIT',v_actor)then raise exception 'CATALOG_SCOPE_DENIED' using errcode='42501';end if;
 v_payload:=jsonb_strip_nulls(jsonb_build_object('label_fr',v_source.label_fr,'label_ar',v_source.label_ar,'help_fr',v_source.help_fr,'help_ar',v_source.help_ar,'why_we_ask_fr',v_source.why_we_ask_fr,'why_we_ask_ar',v_source.why_we_ask_ar,'answer_type',v_source.answer_type,'data_key',p_new_data_key,'required_by_default',v_source.required_by_default,'required_for_quote',v_source.required_for_quote,'required_for_publication',v_source.required_for_publication,'options',v_source.options,'validation_schema',v_source.validation_schema,'structured_schema',v_source.structured_schema,'visibility_rule',v_source.visibility_rule,'default_value',v_source.default_value,'prefill_source',v_source.prefill_source,'sensitivity',v_source.sensitivity,'nullable',v_source.nullable,'weight',v_source.weight,'maximum_score',v_source.maximum_score,'template_key',v_source.template_key,'validity_seconds',case when v_source.validity_interval is null then null else extract(epoch from v_source.validity_interval)::integer end,'source_service_id',v_source.source_service_id));perform private.assert_question_builder_payload(v_identity.library_id,v_identity.scope,v_payload);
 if v_source.sensitivity in('CONFIDENTIAL','RESTRICTED')and auth.jwt()->>'aal'is distinct from'aal2'then raise exception 'CATALOG_SENSITIVE_MFA_REQUIRED' using errcode='42501';end if;v_hash:=private.canonical_request_hash(jsonb_build_object('operation','catalog.question.duplicate.v1','question_id',p_question_id,'source_version_id',p_source_version_id,'new_question_key',btrim(p_new_question_key),'new_data_key',p_new_data_key,'change_reason',btrim(p_change_reason)));select b.command_id,b.response_body into v_command,v_replay from private.begin_catalog_command(v_actor,'catalog.question.duplicate',p_idempotency_key,v_hash)b;
 perform pg_advisory_xact_lock(hashtextextended('catalog-library:'||v_identity.library_id::text,0));perform private.assert_catalog_permission_locked(v_identity.library_id,'CATALOG_EDIT',v_actor);if v_replay is not null then return v_replay;end if;select steward_organization_id into v_org from public.catalog_libraries where id=v_identity.library_id;insert into public.question_bank_questions(library_id,question_key,scope,source_question_id,status,created_by)values(v_identity.library_id,btrim(p_new_question_key),v_identity.scope,p_question_id,'DRAFT',v_actor)returning id into v_question;v_version:=private.insert_question_builder_version(v_question,v_identity.library_id,v_payload,p_change_reason,v_actor,1);update public.question_bank_questions set current_draft_version_id=v_version where id=v_question;
 v_response:=jsonb_build_object('outcome','CATALOG_QUESTION_DUPLICATED','question_id',v_question,'source_question_id',p_question_id,'library_id',v_identity.library_id,'version_id',v_version,'identity_row_version',1,'version_row_version',1,'command_id',v_command);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,previous_hash,event_hash)values(v_org,v_actor,'USER','catalog.question.duplicated','catalog_question',v_question::text,p_correlation_id,jsonb_build_object('source_question_id',p_question_id,'source_version_id',p_source_version_id,'version_id',v_version,'command_id',v_command),v_source.content_hash,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key,causation_id)values(v_org,'catalog_question',v_question::text,'CatalogQuestionDuplicatedV1',p_correlation_id,jsonb_build_object('question_id',v_question,'source_question_id',p_question_id,'version_id',v_version),p_idempotency_key,v_command);perform private.finish_catalog_command(v_actor,'catalog.question.duplicate',p_idempotency_key,v_response);return v_response;
end $$;

create function public.set_catalog_question_archived(p_question_id uuid,p_expected_identity_row_version integer,p_archived boolean,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid()) returns jsonb
language plpgsql security definer set search_path=pg_catalog,extensions,private as $$
declare v_actor uuid:=auth.uid();v_identity public.question_bank_questions%rowtype;v_version public.question_versions%rowtype;v_hash text;v_command uuid;v_replay jsonb;v_org uuid;v_response jsonb;v_action text;v_event text;
begin
 if v_actor is null or p_expected_identity_row_version<1 or p_archived is null or length(btrim(coalesce(p_change_reason,'')))not between 3 and 500 then raise exception 'INVALID_CATALOG_QUESTION_ARCHIVE' using errcode='22023';end if;select * into v_identity from public.question_bank_questions where id=p_question_id;select * into v_version from public.question_versions where id=coalesce(v_identity.current_draft_version_id,v_identity.current_published_version_id);if v_identity.id is null or v_version.id is null or not private.has_library_permission(v_identity.library_id,'CATALOG_EDIT',v_actor)then raise exception 'CATALOG_SCOPE_DENIED' using errcode='42501';end if;if v_version.sensitivity in('CONFIDENTIAL','RESTRICTED')and auth.jwt()->>'aal'is distinct from'aal2'then raise exception 'CATALOG_SENSITIVE_MFA_REQUIRED' using errcode='42501';end if;
 v_hash:=private.canonical_request_hash(jsonb_build_object('operation','catalog.question.archive.v1','question_id',p_question_id,'expected_identity',p_expected_identity_row_version,'archived',p_archived,'change_reason',btrim(p_change_reason)));select b.command_id,b.response_body into v_command,v_replay from private.begin_catalog_command(v_actor,'catalog.question.archive',p_idempotency_key,v_hash)b;perform pg_advisory_xact_lock(hashtextextended('catalog-question:'||p_question_id::text,0));select * into v_identity from public.question_bank_questions where id=p_question_id for update;perform private.assert_catalog_permission_locked(v_identity.library_id,'CATALOG_EDIT',v_actor);if v_replay is not null then return v_replay;end if;if v_identity.row_version is distinct from p_expected_identity_row_version then raise exception 'STALE_CATALOG_VERSION' using errcode='40001';end if;if(p_archived and v_identity.status='ARCHIVED')or(not p_archived and v_identity.status<>'ARCHIVED')then raise exception 'CATALOG_QUESTION_STATE_UNCHANGED' using errcode='55000';end if;
 select steward_organization_id into v_org from public.catalog_libraries where id=v_identity.library_id;update public.question_bank_questions set status=case when p_archived then'ARCHIVED'when current_published_version_id is null then'DRAFT'else'PUBLISHED'end,archived_at=case when p_archived then clock_timestamp()else null end,row_version=row_version+1 where id=p_question_id;v_action:=case when p_archived then'catalog.question.archived'else'catalog.question.restored'end;v_event:=case when p_archived then'CatalogQuestionArchivedV1'else'CatalogQuestionRestoredV1'end;v_response:=jsonb_build_object('outcome',case when p_archived then'CATALOG_QUESTION_ARCHIVED'else'CATALOG_QUESTION_RESTORED'end,'question_id',p_question_id,'library_id',v_identity.library_id,'identity_row_version',p_expected_identity_row_version+1,'current_version_id',v_version.id,'command_id',v_command);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,previous_hash,event_hash)values(v_org,v_actor,'USER',v_action,'catalog_question',p_question_id::text,p_correlation_id,jsonb_build_object('current_version_id',v_version.id,'change_reason',btrim(p_change_reason),'command_id',v_command),v_version.content_hash,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key,causation_id)values(v_org,'catalog_question',p_question_id::text,v_event,p_correlation_id,jsonb_build_object('question_id',p_question_id,'current_version_id',v_version.id),p_idempotency_key,v_command);perform private.finish_catalog_command(v_actor,'catalog.question.archive',p_idempotency_key,v_response);return v_response;
end $$;

revoke all on function private.assert_question_builder_payload(uuid,text,jsonb),private.insert_question_builder_version(uuid,uuid,jsonb,text,uuid,integer),public.create_catalog_question(uuid,text,text,jsonb,text,text,uuid),public.save_catalog_question_draft(uuid,uuid,text,jsonb,text,integer,integer,text,uuid),public.duplicate_catalog_question(uuid,uuid,text,text,text,text,uuid),public.set_catalog_question_archived(uuid,integer,boolean,text,text,uuid) from public,anon,authenticated,service_role;
grant execute on function public.create_catalog_question(uuid,text,text,jsonb,text,text,uuid),public.save_catalog_question_draft(uuid,uuid,text,jsonb,text,integer,integer,text,uuid),public.duplicate_catalog_question(uuid,uuid,text,text,text,text,uuid),public.set_catalog_question_archived(uuid,integer,boolean,text,text,uuid) to authenticated;
