-- Admin lifecycle for immutable Provider badge policy versions.
create function public.create_provider_badge_policy_version(p_audit_organization_id uuid,p_badge_code text,p_label_fr text,p_label_ar text,p_dimension text,p_minimum_basis_points integer,p_minimum_evidence_count integer,p_effective_from timestamptz,p_effective_until timestamptz,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;cached jsonb;r jsonb;x uuid;v integer;
begin
 if a is null or auth.role()is distinct from'authenticated'or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER'],a)then raise exception'BADGE_POLICY_ADMIN_AAL2_REQUIRED'using errcode='42501';end if;
 if not exists(select 1 from public.organizations where id=p_audit_organization_id and status='ACTIVE')or p_badge_code!~'^[A-Z][A-Z0-9_]{2,63}$'or length(btrim(p_label_fr))not between 3 and 160 or length(btrim(p_label_ar))not between 3 and 160 or p_dimension not in('OVERALL','QUALITY','DELIVERY','COMPLIANCE','RESPONSIVENESS','SATISFACTION','FINANCE')or p_minimum_basis_points not between 0 and 10000 or p_minimum_evidence_count not between 1 and 100000 or p_effective_from is null or(p_effective_until is not null and p_effective_until<=p_effective_from)or length(btrim(coalesce(p_change_reason,'')))not between 3 and 1000 then raise exception'INVALID_BADGE_POLICY'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('operation','provider.badge.policy.create.v1','audit_organization',p_audit_organization_id,'badge_code',p_badge_code,'label_fr',btrim(p_label_fr),'label_ar',btrim(p_label_ar),'dimension',p_dimension,'minimum_basis_points',p_minimum_basis_points,'minimum_evidence_count',p_minimum_evidence_count,'effective_from',p_effective_from,'effective_until',p_effective_until,'change_reason',btrim(p_change_reason)));
 cached:=private.begin_contract_command(p_audit_organization_id,'provider.badge.policy.create',p_idempotency_key,h,a);if cached is not null then return cached;end if;
 perform pg_advisory_xact_lock(hashtextextended('provider-badge-policy:'||p_badge_code,0));
 if exists(select 1 from public.provider_badge_policy_versions p where p.badge_code=p_badge_code and tstzrange(p.effective_from,p.effective_until,'[)')&&tstzrange(p_effective_from,p_effective_until,'[)'))then raise exception'BADGE_POLICY_EFFECTIVE_WINDOW_OVERLAP'using errcode='23514';end if;
 select coalesce(max(version_number),0)+1 into v from public.provider_badge_policy_versions where badge_code=p_badge_code;
 insert into public.provider_badge_policy_versions(badge_code,version_number,label_fr,label_ar,dimension,minimum_basis_points,minimum_evidence_count,effective_from,effective_until,created_by)values(p_badge_code,v,btrim(p_label_fr),btrim(p_label_ar),p_dimension,p_minimum_basis_points,p_minimum_evidence_count,p_effective_from,p_effective_until,a)returning id into x;
 r:=jsonb_build_object('outcome','PROVIDER_BADGE_POLICY_VERSION_CREATED','badge_policy_id',x,'badge_code',p_badge_code,'version_number',v);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_audit_organization_id,a,'USER','provider.badge.policy.created','provider_badge_policy',x::text,p_correlation_id,jsonb_build_object('badge_code',p_badge_code,'version_number',v,'change_reason',btrim(p_change_reason)),repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_audit_organization_id,'provider_badge_policy',p_badge_code,'ProviderBadgePolicyVersionCreatedV1',p_correlation_id,r,p_idempotency_key);
 perform private.finish_contract_command(p_audit_organization_id,'provider.badge.policy.create',p_idempotency_key,r);return r;
end$$;
revoke all on function public.create_provider_badge_policy_version(uuid,text,text,text,text,integer,integer,timestamptz,timestamptz,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.create_provider_badge_policy_version(uuid,text,text,text,text,integer,integer,timestamptz,timestamptz,text,text,uuid)to authenticated;
