-- V4.1 P0 finance boundaries, Matricia Procurement/AP, beneficiary anti-fraud,
-- and Matricia-owned payment lifecycle. Additive only; no historical mutation.
create function private.v41_finance_access(p_organization_id uuid,p_user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path=pg_catalog,private as $$
  select private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER','READ_ONLY_AUDITOR'],p_user_id)
$$;

-- A: client pays provider directly. This evidence must never create Matricia cash.
create table public.direct_client_provider_payments(
 id uuid primary key default extensions.gen_random_uuid(),client_organization_id uuid not null references public.organizations(id)on delete restrict,provider_organization_id uuid not null references public.organizations(id)on delete restrict,
 mission_id uuid references public.missions(id)on delete restrict,contract_version_id uuid references public.contract_versions(id)on delete restrict,
 contractual_amount_minor bigint not null check(contractual_amount_minor>0),declared_paid_minor bigint not null check(declared_paid_minor>0 and declared_paid_minor<=contractual_amount_minor),currency char(3)not null check(currency~'^[A-Z]{3}$'),
 paid_at timestamptz not null,payment_method text not null check(payment_method in('BANK_TRANSFER','CARD','CHECK','CASH','OTHER')),provider_reference text not null check(length(btrim(provider_reference))between 3 and 200),proof_hash text check(proof_hash is null or proof_hash~'^[0-9a-f]{64}$'),
 confirmation_status text not null check(confirmation_status in('DECLARED','CONFIRMED','DISPUTED')),cash_boundary text not null default'MATRICIA_NEVER_HOLDS_PRINCIPAL' check(cash_boundary='MATRICIA_NEVER_HOLDS_PRINCIPAL'),
 correlation_id uuid not null,recorded_by uuid not null references auth.users(id),recorded_at timestamptz not null default clock_timestamp(),
 unique(client_organization_id,provider_organization_id,provider_reference),check(client_organization_id<>provider_organization_id)
);

-- B: only Matricia's own products/revenues may be recognized as Matricia cash.
create table public.matricia_own_revenue_payments(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,
 revenue_type text not null check(revenue_type in('SUBSCRIPTION','CREDITS','BOX','BENEFIT','MATRICIA_PRODUCT','MATRICIA_SERVICE')),source_reference text not null,
 amount_minor bigint not null check(amount_minor>0),currency char(3)not null check(currency~'^[A-Z]{3}$'),provider text not null,provider_payment_id text not null,
 financial_journal_id uuid references public.financial_journals(id)on delete restrict,paid_at timestamptz not null,correlation_id uuid not null,recorded_at timestamptz not null default clock_timestamp(),
 unique(provider,provider_payment_id),unique(organization_id,source_reference),unique(id,organization_id)
);

-- C: provider settles a Matricia commission invoice (never its service principal).
create table public.provider_commission_receipts(
 id uuid primary key default extensions.gen_random_uuid(),provider_organization_id uuid not null references public.organizations(id)on delete restrict,
 provider_payment_id uuid not null unique,provider_invoice_id uuid not null,
 commission_amount_minor bigint not null check(commission_amount_minor>0),tax_amount_minor bigint not null check(tax_amount_minor>=0),currency char(3)not null check(currency~'^[A-Z]{3}$'),
 Matricia_receipt_reference text not null,correlation_id uuid not null,recorded_at timestamptz not null default clock_timestamp(),unique(provider_organization_id,Matricia_receipt_reference),foreign key(provider_organization_id,provider_payment_id)references public.provider_payments(provider_organization_id,id)on delete restrict,foreign key(provider_organization_id,provider_invoice_id)references public.provider_invoices(provider_organization_id,id)on delete restrict
);

create function public.record_direct_client_provider_payment(p_client_organization_id uuid,p_provider_organization_id uuid,p_mission_id uuid,p_contract_version_id uuid,p_contractual_amount_minor bigint,p_declared_paid_minor bigint,p_currency char(3),p_paid_at timestamptz,p_payment_method text,p_provider_reference text,p_proof_hash text,p_confirmation_status text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;x uuid;
begin
 if a is null or not(private.has_org_role(p_client_organization_id,array['CLIENT_OWNER','CLIENT_ADMIN'],a)or private.has_org_role(p_provider_organization_id,array['PROVIDER_OWNER','PROVIDER_ACCOUNTING'],a)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER'],a))then raise exception'DIRECT_PAYMENT_RECORD_DENIED'using errcode='42501';end if;
 if p_client_organization_id=p_provider_organization_id or p_contractual_amount_minor<=0 or p_declared_paid_minor<=0 or p_declared_paid_minor>p_contractual_amount_minor or p_currency!~'^[A-Z]{3}$'or p_payment_method not in('BANK_TRANSFER','CARD','CHECK','CASH','OTHER')or p_confirmation_status not in('DECLARED','CONFIRMED','DISPUTED')or(p_proof_hash is not null and p_proof_hash!~'^[0-9a-f]{64}$')then raise exception'INVALID_DIRECT_PAYMENT_EVIDENCE'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('client',p_client_organization_id,'provider',p_provider_organization_id,'mission',p_mission_id,'contract_version',p_contract_version_id,'contractual_minor',p_contractual_amount_minor,'paid_minor',p_declared_paid_minor,'currency',p_currency,'paid_at',p_paid_at,'method',p_payment_method,'reference',p_provider_reference,'proof_hash',p_proof_hash,'status',p_confirmation_status));
 r:=private.begin_provider_billing_command(p_provider_organization_id,'v41.direct.client_provider_payment',p_idempotency_key,h,a);if r is not null then return r;end if;
 insert into public.direct_client_provider_payments(client_organization_id,provider_organization_id,mission_id,contract_version_id,contractual_amount_minor,declared_paid_minor,currency,paid_at,payment_method,provider_reference,proof_hash,confirmation_status,correlation_id,recorded_by)values(p_client_organization_id,p_provider_organization_id,p_mission_id,p_contract_version_id,p_contractual_amount_minor,p_declared_paid_minor,p_currency,p_paid_at,p_payment_method,p_provider_reference,p_proof_hash,p_confirmation_status,p_correlation_id,a)returning id into x;
 r:=jsonb_build_object('outcome','DIRECT_CLIENT_PROVIDER_PAYMENT_RECORDED','payment_evidence_id',x,'cash_boundary','MATRICIA_NEVER_HOLDS_PRINCIPAL','amount_minor',p_declared_paid_minor,'currency',p_currency);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_provider_organization_id,a,'USER','direct.payment.recorded','direct_client_provider_payment',x::text,p_correlation_id,r,repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_provider_organization_id,'direct_client_provider_payment',x::text,'DirectClientProviderPaymentRecordedV1',p_correlation_id,r,p_idempotency_key);
 perform private.finish_provider_billing_command(p_provider_organization_id,'v41.direct.client_provider_payment',p_idempotency_key,r);return r;
end$$;

-- Matricia internal procurement master data.
create table public.vendors(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,legal_name text not null,registration_identifier text,category text not null,status text not null default'ACTIVE'check(status in('ACTIVE','SUSPENDED','CLOSED')),risk_level text not null default'STANDARD'check(risk_level in('LOW','STANDARD','HIGH')),created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,legal_name));
create table public.vendor_bank_accounts(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,vendor_id uuid not null,current_version_id uuid,created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict);
create table public.vendor_bank_account_versions(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,bank_account_id uuid not null,version_no integer not null check(version_no>0),beneficiary_name text not null,masked_coordinates text not null check(length(masked_coordinates)between 4 and 80),coordinate_fingerprint text not null check(coordinate_fingerprint~'^[0-9a-f]{64}$'),encrypted_coordinates_reference text not null check(length(encrypted_coordinates_reference)between 8 and 500),evidence_hash text not null check(evidence_hash~'^[0-9a-f]{64}$'),status text not null default'PENDING_REVIEW'check(status in('PENDING_REVIEW','ACTIVE','REJECTED','SUPERSEDED')),risk_flag boolean not null,cooling_until timestamptz not null,proposed_by uuid not null references auth.users(id),proposed_at timestamptz not null default clock_timestamp(),unique(bank_account_id,version_no),unique(id,organization_id),foreign key(bank_account_id,organization_id)references public.vendor_bank_accounts(id,organization_id)on delete restrict);
alter table public.vendor_bank_accounts add constraint vendor_bank_current_version_fk foreign key(current_version_id,organization_id)references public.vendor_bank_account_versions(id,organization_id)on delete restrict deferrable initially deferred;
create table public.bank_account_change_approvals(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,bank_account_version_id uuid not null,decision text not null check(decision in('APPROVED','REJECTED')),decided_by uuid not null references auth.users(id),decision_reason text not null,decided_at timestamptz not null default clock_timestamp(),unique(bank_account_version_id),foreign key(bank_account_version_id,organization_id)references public.vendor_bank_account_versions(id,organization_id)on delete restrict);

create table public.expense_categories(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,code text not null,label text not null,active boolean not null default true,created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,code));
create table public.purchase_requests(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,vendor_id uuid,request_number text not null,need_description text not null,status text not null default'NEED'check(status in('NEED','PURCHASE_REQUEST','APPROVED','REJECTED','ORDERED','CLOSED')),currency char(3)not null check(currency~'^[A-Z]{3}$'),total_minor bigint not null check(total_minor>0),approval_threshold_minor bigint not null check(approval_threshold_minor>=0),requested_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,request_number),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict);
create table public.purchase_request_lines(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,purchase_request_id uuid not null,line_no integer not null check(line_no>0),description text not null,quantity_milli bigint not null check(quantity_milli>0),unit_price_minor bigint not null check(unit_price_minor>=0),line_total_minor bigint not null check(line_total_minor>=0),expense_category_id uuid,created_at timestamptz not null default clock_timestamp(),unique(purchase_request_id,line_no),foreign key(purchase_request_id,organization_id)references public.purchase_requests(id,organization_id)on delete restrict,foreign key(expense_category_id,organization_id)references public.expense_categories(id,organization_id)on delete restrict,check(line_total_minor=(quantity_milli*unit_price_minor)/1000));
create table public.purchase_approvals(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,purchase_request_id uuid not null,decision text not null check(decision in('APPROVED','REJECTED')),decided_by uuid not null references auth.users(id),reason text not null,decided_at timestamptz not null default clock_timestamp(),unique(purchase_request_id),foreign key(purchase_request_id,organization_id)references public.purchase_requests(id,organization_id)on delete restrict);
create table public.purchase_orders(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,purchase_request_id uuid not null,vendor_id uuid not null,order_number text not null,status text not null default'ISSUED'check(status in('ISSUED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED','CLOSED')),currency char(3)not null check(currency~'^[A-Z]{3}$'),total_minor bigint not null check(total_minor>0),contract_hash text check(contract_hash is null or contract_hash~'^[0-9a-f]{64}$'),issued_by uuid not null references auth.users(id),issued_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,order_number),unique(purchase_request_id),foreign key(purchase_request_id,organization_id)references public.purchase_requests(id,organization_id)on delete restrict,foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict);
create table public.purchase_order_lines(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,purchase_order_id uuid not null,line_no integer not null check(line_no>0),description text not null,quantity_milli bigint not null check(quantity_milli>0),unit_price_minor bigint not null check(unit_price_minor>=0),line_total_minor bigint not null check(line_total_minor=(quantity_milli*unit_price_minor)/1000),unique(purchase_order_id,line_no),foreign key(purchase_order_id,organization_id)references public.purchase_orders(id,organization_id)on delete restrict);
create table public.goods_service_receipts(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,purchase_order_id uuid not null,receipt_number text not null,receipt_type text not null check(receipt_type in('GOODS','SERVICE')),received_on date not null,evidence_hash text not null check(evidence_hash~'^[0-9a-f]{64}$'),confirmed_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,receipt_number),foreign key(purchase_order_id,organization_id)references public.purchase_orders(id,organization_id)on delete restrict);
create table public.supplier_invoices(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,vendor_id uuid not null,purchase_order_id uuid,invoice_reference text not null,invoice_date date not null,due_date date not null,currency char(3)not null check(currency~'^[A-Z]{3}$'),subtotal_minor bigint not null check(subtotal_minor>=0),tax_minor bigint not null check(tax_minor>=0),total_minor bigint not null check(total_minor=subtotal_minor+tax_minor and total_minor>0),fiscal_status text not null check(fiscal_status in('VALIDATED','ACCOUNTANT_REVIEW_REQUIRED')),tax_rule_version_id uuid references public.tax_rule_versions(id)on delete restrict,original_document_hash text not null check(original_document_hash~'^[0-9a-f]{64}$'),status text not null check(status in('REGISTERED','VALIDATED','DISPUTED')),created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,vendor_id,invoice_reference),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict,foreign key(purchase_order_id,organization_id)references public.purchase_orders(id,organization_id)on delete restrict,check(due_date>=invoice_date),check((fiscal_status='VALIDATED'and tax_rule_version_id is not null)or fiscal_status='ACCOUNTANT_REVIEW_REQUIRED'));
create table public.supplier_invoice_lines(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,supplier_invoice_id uuid not null,line_no integer not null check(line_no>0),description text not null,subtotal_minor bigint not null check(subtotal_minor>=0),tax_minor bigint not null check(tax_minor>=0),total_minor bigint not null check(total_minor=subtotal_minor+tax_minor),tax_rule_version_id uuid references public.tax_rule_versions(id)on delete restrict,expense_category_id uuid,unique(supplier_invoice_id,line_no),foreign key(supplier_invoice_id,organization_id)references public.supplier_invoices(id,organization_id)on delete restrict,foreign key(expense_category_id,organization_id)references public.expense_categories(id,organization_id)on delete restrict);
create table public.supplier_credit_notes(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,vendor_id uuid not null,supplier_invoice_id uuid not null,credit_reference text not null,subtotal_minor bigint not null check(subtotal_minor>=0),tax_minor bigint not null check(tax_minor>=0),total_minor bigint not null check(total_minor=subtotal_minor+tax_minor and total_minor>0),document_hash text not null check(document_hash~'^[0-9a-f]{64}$'),issued_on date not null,created_at timestamptz not null default clock_timestamp(),unique(organization_id,vendor_id,credit_reference),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict,foreign key(supplier_invoice_id,organization_id)references public.supplier_invoices(id,organization_id)on delete restrict);
create table public.accounts_payable(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,supplier_invoice_id uuid not null unique,currency char(3)not null check(currency~'^[A-Z]{3}$'),amount_due_minor bigint not null check(amount_due_minor>0),due_on date not null,scheduled_on date,status text not null default'OPEN'check(status in('OPEN','SCHEDULED','PARTIALLY_PAID','PAID','DISPUTED','CLOSED')),created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),foreign key(supplier_invoice_id,organization_id)references public.supplier_invoices(id,organization_id)on delete restrict);
create table public.outbound_payments(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,vendor_id uuid not null,bank_account_version_id uuid not null,payment_reference text not null,amount_minor bigint not null check(amount_minor>0),currency char(3)not null check(currency~'^[A-Z]{3}$'),status text not null check(status in('SCHEDULED','PAID','FAILED','CANCELLED')),paid_at timestamptz,provider_reference text,correlation_id uuid not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,payment_reference),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict,foreign key(bank_account_version_id,organization_id)references public.vendor_bank_account_versions(id,organization_id)on delete restrict);
create table public.outbound_payment_allocations(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,outbound_payment_id uuid not null,accounts_payable_id uuid not null,amount_minor bigint not null check(amount_minor>0),created_at timestamptz not null default clock_timestamp(),unique(outbound_payment_id,accounts_payable_id),foreign key(outbound_payment_id,organization_id)references public.outbound_payments(id,organization_id)on delete restrict,foreign key(accounts_payable_id,organization_id)references public.accounts_payable(id,organization_id)on delete restrict);
create table public.expense_allocations(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,supplier_invoice_line_id uuid not null references public.supplier_invoice_lines(id)on delete restrict,allocation_scope text not null check(allocation_scope in('PLATFORM','BOX','BENEFIT','LIBRARY','FRANCHISE','CLIENT','PROJECT','COST_CENTER','MARKETING_CAMPAIGN')),scope_reference_id text not null,amount_minor bigint not null check(amount_minor>0),currency char(3)not null check(currency~'^[A-Z]{3}$'),allocation_rule_version text not null,created_at timestamptz not null default clock_timestamp());
create table public.vendor_contracts(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,vendor_id uuid not null,contract_reference text not null,version_no integer not null check(version_no>0),starts_on date not null,ends_on date,document_hash text not null check(document_hash~'^[0-9a-f]{64}$'),status text not null check(status in('DRAFT','ACTIVE','EXPIRED','TERMINATED')),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id),unique(organization_id,vendor_id,contract_reference,version_no),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict,check(ends_on is null or ends_on>=starts_on));
create table public.vendor_subscriptions(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null,vendor_id uuid not null,vendor_contract_id uuid,service_name text not null,billing_interval text not null check(billing_interval in('MONTHLY','QUARTERLY','ANNUAL','USAGE')),amount_minor bigint not null check(amount_minor>=0),currency char(3)not null check(currency~'^[A-Z]{3}$'),renews_on date,cancel_notice_days integer not null default 30 check(cancel_notice_days>=0),status text not null check(status in('ACTIVE','CANCELLED','EXPIRED')),created_at timestamptz not null default clock_timestamp(),foreign key(vendor_id,organization_id)references public.vendors(id,organization_id)on delete restrict,foreign key(vendor_contract_id,organization_id)references public.vendor_contracts(id,organization_id)on delete restrict);

create view public.accounts_payable_balances with(security_invoker=true)as select a.*,coalesce(sum(x.amount_minor),0)::bigint paid_minor,(a.amount_due_minor-coalesce(sum(x.amount_minor),0))::bigint outstanding_minor from public.accounts_payable a left join public.outbound_payment_allocations x on x.accounts_payable_id=a.id group by a.id;

create function public.approve_purchase_request(p_purchase_request_id uuid,p_decision text,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();q public.purchase_requests%rowtype;h text;r jsonb;x uuid;begin select*into q from public.purchase_requests where id=p_purchase_request_id for update;if a is null or not found or not private.has_platform_role(array['SUPER_ADMIN','FINANCE_MANAGER'],a)or coalesce(auth.jwt()->>'aal','')<>'aal2'then raise exception'PURCHASE_APPROVAL_DENIED'using errcode='42501';end if;if q.requested_by=a then raise exception'REQUESTER_CANNOT_APPROVE'using errcode='42501';end if;if p_decision not in('APPROVED','REJECTED')then raise exception'INVALID_APPROVAL_DECISION'using errcode='22023';end if;h:=private.canonical_request_hash(jsonb_build_object('request',q.id,'decision',p_decision,'reason',p_reason));r:=private.begin_provider_billing_command(q.organization_id,'v41.purchase.approve',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.purchase_approvals(organization_id,purchase_request_id,decision,decided_by,reason)values(q.organization_id,q.id,p_decision,a,p_reason)returning id into x;update public.purchase_requests set status=case when p_decision='APPROVED'then'APPROVED'else'REJECTED'end where id=q.id;r:=jsonb_build_object('outcome','PURCHASE_REQUEST_'||p_decision,'purchase_request_id',q.id,'approval_id',x);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(q.organization_id,a,'USER','purchase.request.'||lower(p_decision),'purchase_request',q.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(q.organization_id,'purchase_request',q.id::text,'PurchaseRequest'||initcap(lower(p_decision))||'V1',p_correlation_id,r,p_idempotency_key);perform private.finish_provider_billing_command(q.organization_id,'v41.purchase.approve',p_idempotency_key,r);return r;end$$;

create function public.propose_vendor_bank_account_version(p_bank_account_id uuid,p_beneficiary_name text,p_masked_coordinates text,p_coordinate_fingerprint text,p_encrypted_coordinates_reference text,p_evidence_hash text,p_cooling_hours integer,p_near_large_payment boolean,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();b public.vendor_bank_accounts%rowtype;n integer;h text;r jsonb;x uuid;begin select*into b from public.vendor_bank_accounts where id=p_bank_account_id;if a is null or not found or not private.has_platform_role(array['SUPER_ADMIN','FINANCE_MANAGER'],a)or coalesce(auth.jwt()->>'aal','')<>'aal2'then raise exception'BANK_ACCOUNT_CHANGE_DENIED'using errcode='42501';end if;if p_coordinate_fingerprint!~'^[0-9a-f]{64}$'or p_evidence_hash!~'^[0-9a-f]{64}$'or p_cooling_hours not between 1 and 720 then raise exception'INVALID_BANK_ACCOUNT_CHANGE'using errcode='22023';end if;select coalesce(max(version_no),0)+1 into n from public.vendor_bank_account_versions where bank_account_id=b.id;h:=private.canonical_request_hash(jsonb_build_object('bank_account',b.id,'beneficiary',p_beneficiary_name,'masked',p_masked_coordinates,'fingerprint',p_coordinate_fingerprint,'encrypted_reference',p_encrypted_coordinates_reference,'evidence',p_evidence_hash,'cooling_hours',p_cooling_hours,'risk_flag',p_near_large_payment));r:=private.begin_provider_billing_command(b.organization_id,'v41.bank_account.propose',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.vendor_bank_account_versions(organization_id,bank_account_id,version_no,beneficiary_name,masked_coordinates,coordinate_fingerprint,encrypted_coordinates_reference,evidence_hash,risk_flag,cooling_until,proposed_by)values(b.organization_id,b.id,n,p_beneficiary_name,p_masked_coordinates,p_coordinate_fingerprint,p_encrypted_coordinates_reference,p_evidence_hash,p_near_large_payment,clock_timestamp()+make_interval(hours=>p_cooling_hours),a)returning id into x;r:=jsonb_build_object('outcome','BANK_ACCOUNT_CHANGE_PROPOSED','bank_account_version_id',x,'risk_flag',p_near_large_payment,'cooling_hours',p_cooling_hours);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(b.organization_id,a,'USER','bank_account.change.proposed','vendor_bank_account_version',x::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(b.organization_id,'vendor_bank_account',b.id::text,'BankAccountChangeProposedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_provider_billing_command(b.organization_id,'v41.bank_account.propose',p_idempotency_key,r);return r;end$$;

create function public.approve_vendor_bank_account_version(p_bank_account_version_id uuid,p_decision text,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();v public.vendor_bank_account_versions%rowtype;h text;r jsonb;x uuid;begin select*into v from public.vendor_bank_account_versions where id=p_bank_account_version_id for update;if a is null or not found or not private.has_platform_role(array['SUPER_ADMIN','FINANCE_MANAGER'],a)or coalesce(auth.jwt()->>'aal','')<>'aal2'then raise exception'BANK_ACCOUNT_APPROVAL_DENIED'using errcode='42501';end if;if v.proposed_by=a then raise exception'PROPOSER_CANNOT_APPROVE'using errcode='42501';end if;if p_decision not in('APPROVED','REJECTED')then raise exception'INVALID_BANK_ACCOUNT_DECISION'using errcode='22023';end if;if p_decision='APPROVED'and clock_timestamp()<v.cooling_until then raise exception'BANK_ACCOUNT_COOLING_PERIOD_ACTIVE'using errcode='55000';end if;h:=private.canonical_request_hash(jsonb_build_object('version',v.id,'decision',p_decision,'reason',p_reason));r:=private.begin_provider_billing_command(v.organization_id,'v41.bank_account.approve',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.bank_account_change_approvals(organization_id,bank_account_version_id,decision,decided_by,decision_reason)values(v.organization_id,v.id,p_decision,a,p_reason)returning id into x;if p_decision='APPROVED'then update public.vendor_bank_account_versions set status='SUPERSEDED'where bank_account_id=v.bank_account_id and status='ACTIVE';update public.vendor_bank_account_versions set status='ACTIVE'where id=v.id;update public.vendor_bank_accounts set current_version_id=v.id where id=v.bank_account_id;else update public.vendor_bank_account_versions set status='REJECTED'where id=v.id;end if;r:=jsonb_build_object('outcome','BANK_ACCOUNT_CHANGE_'||p_decision,'bank_account_version_id',v.id,'approval_id',x);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(v.organization_id,a,'USER','bank_account.change.'||lower(p_decision),'vendor_bank_account_version',v.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(v.organization_id,'vendor_bank_account',v.bank_account_id::text,'BankAccountChange'||initcap(lower(p_decision))||'V1',p_correlation_id,r,p_idempotency_key);perform private.finish_provider_billing_command(v.organization_id,'v41.bank_account.approve',p_idempotency_key,r);return r;end$$;

create function public.reconcile_outbound_payment(p_outbound_payment_id uuid,p_allocations jsonb,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();p public.outbound_payments%rowtype;h text;r jsonb;requested bigint;already bigint;x jsonb;outstanding bigint;begin select*into p from public.outbound_payments where id=p_outbound_payment_id for update;if a is null or not found or not private.has_platform_role(array['SUPER_ADMIN','FINANCE_MANAGER'],a)or coalesce(auth.jwt()->>'aal','')<>'aal2'then raise exception'OUTBOUND_RECONCILIATION_DENIED'using errcode='42501';end if;if jsonb_typeof(p_allocations)<>'array'or jsonb_array_length(p_allocations)=0 then raise exception'INVALID_PAYMENT_ALLOCATIONS'using errcode='22023';end if;select coalesce(sum((e->>'amount_minor')::bigint),0)into requested from jsonb_array_elements(p_allocations)e;select coalesce(sum(amount_minor),0)into already from public.outbound_payment_allocations where outbound_payment_id=p.id;if requested<=0 or requested+already>p.amount_minor then raise exception'PAYMENT_OVERALLOCATED'using errcode='23514';end if;for x in select*from jsonb_array_elements(p_allocations)loop select a.amount_due_minor-coalesce(sum(o.amount_minor),0)into outstanding from public.accounts_payable a left join public.outbound_payment_allocations o on o.accounts_payable_id=a.id where a.id=(x->>'accounts_payable_id')::uuid and a.organization_id=p.organization_id and a.currency=p.currency group by a.amount_due_minor;if outstanding is null or(x->>'amount_minor')::bigint<=0 or(x->>'amount_minor')::bigint>outstanding then raise exception'PAYABLE_OVERALLOCATED_OR_NOT_FOUND'using errcode='23514';end if;end loop;h:=private.canonical_request_hash(jsonb_build_object('payment',p.id,'allocations',p_allocations));r:=private.begin_provider_billing_command(p.organization_id,'v41.outbound_payment.reconcile',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.outbound_payment_allocations(organization_id,outbound_payment_id,accounts_payable_id,amount_minor)select p.organization_id,p.id,(e->>'accounts_payable_id')::uuid,(e->>'amount_minor')::bigint from jsonb_array_elements(p_allocations)e;r:=jsonb_build_object('outcome','OUTBOUND_PAYMENT_RECONCILED','outbound_payment_id',p.id,'allocated_minor',requested,'unallocated_minor',p.amount_minor-already-requested);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p.organization_id,a,'USER','outbound_payment.reconciled','outbound_payment',p.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p.organization_id,'outbound_payment',p.id::text,'OutboundPaymentReconciledV1',p_correlation_id,r,p_idempotency_key);perform private.finish_provider_billing_command(p.organization_id,'v41.outbound_payment.reconcile',p_idempotency_key,r);return r;end$$;

-- Matricia-owned payment completion: immutable provider facts and derived reconciliation.
create table public.payment_provider_events(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,provider text not null,provider_event_id text not null,event_type text not null check(event_type in('PAYMENT_SUCCEEDED','PAYMENT_FAILED','REFUND_SUCCEEDED','REFUND_FAILED','DISPUTE_OPENED','DISPUTE_WON','DISPUTE_LOST','CHARGEBACK')),provider_payment_id text not null,amount_minor bigint not null check(amount_minor>=0),currency char(3)not null check(currency~'^[A-Z]{3}$'),payload_hash text not null check(payload_hash~'^[0-9a-f]{64}$'),signature_fingerprint text not null check(signature_fingerprint~'^[0-9a-f]{64}$'),occurred_at timestamptz not null,received_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,unique(provider,provider_event_id),unique(id,organization_id));
create table public.payment_refunds(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,own_revenue_payment_id uuid not null,provider_event_id uuid not null unique,refund_amount_minor bigint not null check(refund_amount_minor>0),currency char(3)not null check(currency~'^[A-Z]{3}$'),reason text not null,status text not null check(status in('REQUESTED','SUCCEEDED','FAILED')),idempotency_key text not null,created_at timestamptz not null default clock_timestamp(),unique(organization_id,idempotency_key),foreign key(own_revenue_payment_id,organization_id)references public.matricia_own_revenue_payments(id,organization_id)on delete restrict,foreign key(provider_event_id,organization_id)references public.payment_provider_events(id,organization_id)on delete restrict);
create table public.payment_disputes(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,own_revenue_payment_id uuid not null,provider_dispute_id text not null,disputed_amount_minor bigint not null check(disputed_amount_minor>0),currency char(3)not null check(currency~'^[A-Z]{3}$'),status text not null check(status in('OPEN','WON','LOST','CHARGEBACK')),evidence_hash text check(evidence_hash is null or evidence_hash~'^[0-9a-f]{64}$'),opened_at timestamptz not null,closed_at timestamptz,unique(organization_id,provider_dispute_id),foreign key(own_revenue_payment_id,organization_id)references public.matricia_own_revenue_payments(id,organization_id)on delete restrict);
create table public.payment_reconciliation_runs(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,provider text not null,period_start timestamptz not null,period_end timestamptz not null,status text not null check(status in('RUNNING','MATCHED','EXCEPTIONS','FAILED')),source_file_hash text not null check(source_file_hash~'^[0-9a-f]{64}$'),correlation_id uuid not null,started_by uuid not null references auth.users(id),started_at timestamptz not null default clock_timestamp(),unique(id,organization_id),check(period_end>=period_start));
create table public.payment_reconciliation_items(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,reconciliation_run_id uuid not null,provider_payment_id text not null,own_revenue_payment_id uuid,provider_amount_minor bigint not null,ledger_amount_minor bigint not null,difference_minor bigint generated always as(provider_amount_minor-ledger_amount_minor)stored,currency char(3)not null check(currency~'^[A-Z]{3}$'),result text not null check(result in('MATCHED','MISSING_INTERNAL','MISSING_PROVIDER','AMOUNT_MISMATCH')),unique(reconciliation_run_id,provider_payment_id),foreign key(reconciliation_run_id,organization_id)references public.payment_reconciliation_runs(id,organization_id)on delete restrict,foreign key(own_revenue_payment_id,organization_id)references public.matricia_own_revenue_payments(id,organization_id)on delete restrict);

-- Append-only protection for financial evidence; workflow roots remain command-controlled.
do $$declare t text;begin foreach t in array array['direct_client_provider_payments','matricia_own_revenue_payments','provider_commission_receipts','purchase_approvals','goods_service_receipts','supplier_invoices','supplier_invoice_lines','supplier_credit_notes','accounts_payable','outbound_payments','outbound_payment_allocations','expense_allocations','bank_account_change_approvals','payment_provider_events','payment_refunds','payment_disputes','payment_reconciliation_runs','payment_reconciliation_items']loop execute format('create trigger %I_immutable before update or delete on public.%I for each row execute function private.prevent_update_delete()',t,t);end loop;end$$;

-- RLS fail-closed and read-only direct access. All writes go through audited commands/service adapters.
do $$declare t text;begin foreach t in array array['direct_client_provider_payments','matricia_own_revenue_payments','provider_commission_receipts','vendors','vendor_bank_accounts','vendor_bank_account_versions','bank_account_change_approvals','expense_categories','purchase_requests','purchase_request_lines','purchase_approvals','purchase_orders','purchase_order_lines','goods_service_receipts','supplier_invoices','supplier_invoice_lines','supplier_credit_notes','accounts_payable','outbound_payments','outbound_payment_allocations','expense_allocations','vendor_contracts','vendor_subscriptions','payment_provider_events','payment_refunds','payment_disputes','payment_reconciliation_runs','payment_reconciliation_items']loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);end loop;end$$;
create policy direct_payment_party_read on public.direct_client_provider_payments for select to authenticated using(private.has_org_role(client_organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_MEMBER'],auth.uid())or private.has_org_role(provider_organization_id,array['PROVIDER_OWNER','PROVIDER_ACCOUNTING'],auth.uid())or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER','READ_ONLY_AUDITOR'],auth.uid()));
grant select on public.direct_client_provider_payments to authenticated;
do $$declare t text;begin foreach t in array array['matricia_own_revenue_payments','vendors','vendor_bank_accounts','vendor_bank_account_versions','bank_account_change_approvals','expense_categories','purchase_requests','purchase_request_lines','purchase_approvals','purchase_orders','purchase_order_lines','goods_service_receipts','supplier_invoices','supplier_invoice_lines','supplier_credit_notes','accounts_payable','outbound_payments','outbound_payment_allocations','expense_allocations','vendor_contracts','vendor_subscriptions','payment_provider_events','payment_refunds','payment_disputes','payment_reconciliation_runs','payment_reconciliation_items']loop execute format('create policy %I_finance_read on public.%I for select to authenticated using(private.v41_finance_access(organization_id))',t,t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
create policy provider_commission_receipts_party_read on public.provider_commission_receipts for select to authenticated using(private.has_org_role(provider_organization_id,array['PROVIDER_OWNER','PROVIDER_ACCOUNTING'],auth.uid())or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER','READ_ONLY_AUDITOR'],auth.uid()));grant select on public.provider_commission_receipts to authenticated;
revoke all on public.accounts_payable_balances from public,anon,authenticated,service_role;grant select on public.accounts_payable_balances to authenticated;

revoke all on function private.v41_finance_access(uuid,uuid)from public,anon,authenticated,service_role;
grant execute on function private.v41_finance_access(uuid,uuid)to authenticated;
revoke all on function public.record_direct_client_provider_payment(uuid,uuid,uuid,uuid,bigint,bigint,character,timestamptz,text,text,text,text,text,uuid),public.approve_purchase_request(uuid,text,text,text,uuid),public.propose_vendor_bank_account_version(uuid,text,text,text,text,text,integer,boolean,text,uuid),public.approve_vendor_bank_account_version(uuid,text,text,text,uuid),public.reconcile_outbound_payment(uuid,jsonb,text,uuid)from public,anon,service_role;
grant execute on function public.record_direct_client_provider_payment(uuid,uuid,uuid,uuid,bigint,bigint,character,timestamptz,text,text,text,text,text,uuid),public.approve_purchase_request(uuid,text,text,text,uuid),public.propose_vendor_bank_account_version(uuid,text,text,text,text,text,integer,boolean,text,uuid),public.approve_vendor_bank_account_version(uuid,text,text,text,uuid),public.reconcile_outbound_payment(uuid,jsonb,text,uuid)to authenticated;

create index direct_provider_payment_mission_idx on public.direct_client_provider_payments(provider_organization_id,mission_id,paid_at desc);
create index own_revenue_org_paid_idx on public.matricia_own_revenue_payments(organization_id,paid_at desc);
create index purchase_requests_queue_idx on public.purchase_requests(organization_id,status,created_at);
create index supplier_invoices_due_idx on public.supplier_invoices(organization_id,due_date,status);
create index accounts_payable_due_idx on public.accounts_payable(organization_id,due_on,status);
create index outbound_allocations_payable_idx on public.outbound_payment_allocations(organization_id,accounts_payable_id);
create index bank_account_versions_review_idx on public.vendor_bank_account_versions(organization_id,status,cooling_until);
create index payment_provider_events_payment_idx on public.payment_provider_events(organization_id,provider,provider_payment_id,occurred_at);
