-- V1 MAT-FUNC-003/004/008/041/042: bounded deterministic assistance, human decisions only.

create table public.assistance_model_versions(
 id uuid primary key default extensions.gen_random_uuid(),model_key text not null check(model_key~'^[A-Z][A-Z0-9_.-]{2,79}$'),version integer not null check(version>0),provider_kind text not null default'DETERMINISTIC'check(provider_kind='DETERMINISTIC'),algorithm text not null check(algorithm='TOKEN_OVERLAP_V1'),configuration jsonb not null check(jsonb_typeof(configuration)='object'and configuration?&array['minimum_score_basis_points','duplicate_score_basis_points','candidate_limit']),status text not null check(status in('DRAFT','ACTIVE','SUPERSEDED','ARCHIVED')),effective_from timestamptz not null,effective_until timestamptz,content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),change_reason text not null check(length(btrim(change_reason))between 3 and 500),created_by uuid references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(model_key,version),check(effective_until is null or effective_until>effective_from),check((status='SUPERSEDED')=(effective_until is not null))
);
create unique index assistance_one_active_model_idx on public.assistance_model_versions(model_key)where status='ACTIVE';

create table public.assistance_profile_reassessments(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,profile_version_id uuid not null unique references public.client_profile_versions(id)on delete restrict,previous_profile_version_id uuid references public.client_profile_versions(id)on delete restrict,changed_keys text[]not null check(cardinality(changed_keys)between 1 and 100),status text not null default'PENDING'check(status in('PENDING','COMPLETED','DISMISSED')),created_at timestamptz not null default clock_timestamp(),completed_at timestamptz,check((status='COMPLETED')=(completed_at is not null))
);
create table public.assistance_requests(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,model_version_id uuid not null references public.assistance_model_versions(id)on delete restrict,profile_reassessment_id uuid references public.assistance_profile_reassessments(id)on delete restrict,context_type text not null check(context_type in('CONTEXTUAL_ASSISTANT','PROFILE_CHANGE','NEED_TEXT','QUESTIONNAIRE_QUALITY','SIMILARITY_REVIEW')),input_text text check(input_text is null or length(btrim(input_text))between 3 and 4000),input_hash text not null check(input_hash~'^[0-9a-f]{64}$'),candidate_service_version_ids uuid[]not null default'{}',candidate_question_version_ids uuid[]not null default'{}',known_data_keys text[]not null default'{}',status text not null default'COMPLETED'check(status in('COMPLETED','FAILED')),created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),check(cardinality(candidate_service_version_ids)<=50),check(cardinality(candidate_question_version_ids)<=50),check(cardinality(known_data_keys)<=100),check(context_type<>'NEED_TEXT'or input_text is not null)
);
create table public.assistance_suggestions(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,request_id uuid not null references public.assistance_requests(id)on delete restrict,suggestion_kind text not null check(suggestion_kind in('CONTEXTUAL_GUIDANCE','SERVICE_CANDIDATE','MISSING_QUESTION','QUESTION_AMBIGUITY','KNOWN_DATA_DUPLICATION','SEMANTIC_DUPLICATE')),target_type text not null check(target_type in('SERVICE_VERSION','QUESTION_VERSION','QUESTION_PAIR','SERVICE_PAIR','PROFILE')),target_id uuid,related_target_id uuid,score_basis_points integer not null check(score_basis_points between 0 and 10000),explanation_code text not null check(explanation_code~'^[A-Z][A-Z0-9_]{2,79}$'),explanation jsonb not null check(jsonb_typeof(explanation)='object'and explanation?&array['model_version','evidence','human_review_required']),proposed_payload jsonb not null default'{}'check(jsonb_typeof(proposed_payload)='object'),status text not null default'PROPOSED'check(status in('PROPOSED','ACCEPTED','REJECTED')),created_at timestamptz not null default clock_timestamp(),decided_at timestamptz,check((status='PROPOSED')=(decided_at is null)),check(target_id is not null or target_type='PROFILE'),check(related_target_id is null or related_target_id<>target_id)
);
create table public.assistance_suggestion_decisions(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,suggestion_id uuid not null unique references public.assistance_suggestions(id)on delete restrict,decision text not null check(decision in('ACCEPTED','REJECTED')),rationale text not null check(length(btrim(rationale))between 3 and 1000),decided_by uuid not null references auth.users(id),decided_at timestamptz not null default clock_timestamp()
);
create index assistance_reassessment_queue_idx on public.assistance_profile_reassessments(organization_id,status,created_at);
create index assistance_requests_tenant_time_idx on public.assistance_requests(organization_id,created_at desc);
create index assistance_suggestions_review_idx on public.assistance_suggestions(organization_id,status,suggestion_kind,score_basis_points desc);
create index assistance_suggestions_target_idx on public.assistance_suggestions(target_type,target_id,related_target_id);

create function private.enqueue_profile_assistance_reassessment()returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$declare prior public.client_profile_versions%rowtype;keys text[];begin
 select*into prior from public.client_profile_versions where compliance_case_id=new.compliance_case_id and version<new.version order by version desc limit 1;
 if found then select coalesce(array_agg(k order by k),'{}')into keys from(select x.key k from jsonb_object_keys(new.profile_data)as x(key)where prior.profile_data->x.key is distinct from new.profile_data->x.key union select x.key from jsonb_object_keys(prior.profile_data)as x(key)where new.profile_data->x.key is distinct from prior.profile_data->x.key)q;else select coalesce(array_agg(x.key order by x.key),'{}')into keys from jsonb_object_keys(new.profile_data)as x(key);end if;
 if cardinality(keys)>0 then insert into public.assistance_profile_reassessments(organization_id,profile_version_id,previous_profile_version_id,changed_keys)values(new.organization_id,new.id,prior.id,keys)on conflict(profile_version_id)do nothing;end if;return new;end$$;
create trigger client_profile_assistance_reassessment after insert on public.client_profile_versions for each row execute function private.enqueue_profile_assistance_reassessment();
create function private.assistance_tokens(p_text text)returns text[]language sql immutable strict set search_path=pg_catalog as $$select coalesce(array_agg(distinct token order by token),'{}')from regexp_split_to_table(lower(p_text),'[^[:alnum:]]+')token where length(token)>=3$$;
create function private.assistance_overlap_basis_points(p_left text,p_right text)returns integer language sql immutable strict set search_path=pg_catalog,private as $$with l as(select unnest(private.assistance_tokens(p_left))token),r as(select unnest(private.assistance_tokens(p_right))token),u as(select token from l union select token from r),i as(select token from l intersect select token from r)select coalesce((select count(*)::numeric*10000/nullif((select count(*)from u),0)from i)::integer,0)$$;
create function private.protect_assistance_model_version()returns trigger language plpgsql set search_path=pg_catalog as $$begin if tg_op='DELETE'then raise exception'ASSISTANCE_MODEL_VERSION_IMMUTABLE'using errcode='55000';end if;if row(new.id,new.model_key,new.version,new.provider_kind,new.algorithm,new.configuration,new.effective_from,new.content_hash,new.change_reason,new.created_by,new.created_at)is distinct from row(old.id,old.model_key,old.version,old.provider_kind,old.algorithm,old.configuration,old.effective_from,old.content_hash,old.change_reason,old.created_by,old.created_at)then raise exception'ASSISTANCE_MODEL_CONTENT_IMMUTABLE'using errcode='55000';end if;return new;end$$;

create function public.run_assisted_analysis(p_organization_id uuid,p_context_type text,p_input_text text,p_candidate_service_version_ids uuid[],p_candidate_question_version_ids uuid[],p_known_data_keys text[],p_model_version_id uuid,p_profile_reassessment_id uuid,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();m public.assistance_model_versions%rowtype;h text;cached jsonb;r jsonb;rid uuid;min_score integer;dup_score integer;s record;q1 record;q2 record;score integer;created_count integer:=0;reassess public.assistance_profile_reassessments%rowtype;
begin
 if a is null or not(private.is_active_org_member(p_organization_id,a)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a))then raise exception'ASSISTANCE_ACCESS_DENIED'using errcode='42501';end if;
 select*into m from public.assistance_model_versions where id=p_model_version_id and status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp());
 if not found or p_context_type not in('CONTEXTUAL_ASSISTANT','PROFILE_CHANGE','NEED_TEXT','QUESTIONNAIRE_QUALITY','SIMILARITY_REVIEW')or cardinality(coalesce(p_candidate_service_version_ids,'{}'))>50 or cardinality(coalesce(p_candidate_question_version_ids,'{}'))>50 or cardinality(coalesce(p_known_data_keys,'{}'))>100 or(p_context_type='NEED_TEXT'and length(btrim(coalesce(p_input_text,'')))not between 3 and 4000)then raise exception'INVALID_BOUNDED_ASSISTANCE_REQUEST'using errcode='22023';end if;
 if p_profile_reassessment_id is not null then select*into reassess from public.assistance_profile_reassessments where id=p_profile_reassessment_id and organization_id=p_organization_id and status='PENDING'for update;if not found then raise exception'PROFILE_REASSESSMENT_NOT_PENDING'using errcode='55000';end if;end if;
 min_score:=(m.configuration->>'minimum_score_basis_points')::integer;dup_score:=(m.configuration->>'duplicate_score_basis_points')::integer;
 if min_score not between 0 and 10000 or dup_score not between 0 and 10000 or(m.configuration->>'candidate_limit')::integer not between 1 and 50 then raise exception'INVALID_ASSISTANCE_MODEL_CONFIGURATION'using errcode='55000';end if;
 h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'context',p_context_type,'input',coalesce(p_input_text,''),'services',coalesce(p_candidate_service_version_ids,'{}'),'questions',coalesce(p_candidate_question_version_ids,'{}'),'known',coalesce(p_known_data_keys,'{}'),'model',m.id,'profile_reassessment',p_profile_reassessment_id));
 cached:=private.begin_contract_command(p_organization_id,'assistance.analyse',p_idempotency_key,h,a);if cached is not null then return cached;end if;
 insert into public.assistance_requests(organization_id,model_version_id,profile_reassessment_id,context_type,input_text,input_hash,candidate_service_version_ids,candidate_question_version_ids,known_data_keys,created_by)values(p_organization_id,m.id,p_profile_reassessment_id,p_context_type,nullif(btrim(p_input_text),''),h,coalesce(p_candidate_service_version_ids,'{}'),coalesce(p_candidate_question_version_ids,'{}'),coalesce(p_known_data_keys,'{}'),a)returning id into rid;
 if p_context_type in('NEED_TEXT','CONTEXTUAL_ASSISTANT','PROFILE_CHANGE')and p_input_text is not null then for s in select v.id,private.assistance_overlap_basis_points(p_input_text,v.name_fr||' '||v.short_description_fr)relevance from public.catalog_service_versions v where v.id=any(coalesce(p_candidate_service_version_ids,'{}'))and v.status='PUBLISHED'order by relevance desc,v.id limit(m.configuration->>'candidate_limit')::integer loop if s.relevance>=min_score then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'SERVICE_CANDIDATE','SERVICE_VERSION',s.id,s.relevance,'TOKEN_OVERLAP',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('algorithm',m.algorithm,'score_basis_points',s.relevance),'human_review_required',true),jsonb_build_object('service_version_id',s.id,'confirmation_required',true));created_count:=created_count+1;end if;end loop;end if;
 for q1 in select v.id,v.data_key,v.label_fr,v.required_for_quote from public.question_versions v where v.id=any(coalesce(p_candidate_question_version_ids,'{}'))and v.status='PUBLISHED'loop
  if q1.data_key=any(coalesce(p_known_data_keys,'{}'))then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'KNOWN_DATA_DUPLICATION','QUESTION_VERSION',q1.id,10000,'DATA_KEY_ALREADY_KNOWN',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('data_key',q1.data_key),'human_review_required',true),jsonb_build_object('recommended_action','PREFILL_AND_CONFIRM'));created_count:=created_count+1;
  elsif p_context_type='NEED_TEXT'and(q1.required_for_quote or private.assistance_overlap_basis_points(coalesce(p_input_text,''),q1.label_fr)>=min_score)then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'MISSING_QUESTION','QUESTION_VERSION',q1.id,case when q1.required_for_quote then 10000 else private.assistance_overlap_basis_points(p_input_text,q1.label_fr)end,'REQUIRED_INFORMATION_MISSING',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('required_for_quote',q1.required_for_quote,'data_key',q1.data_key),'human_review_required',true),jsonb_build_object('question_version_id',q1.id,'confirmation_required',true));created_count:=created_count+1;end if;
  if p_context_type in('QUESTIONNAIRE_QUALITY','SIMILARITY_REVIEW')and(length(btrim(q1.label_fr))<12 or lower(q1.label_fr)~'(^| )(autre|divers|etc|chose|information)( |$)')then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'QUESTION_AMBIGUITY','QUESTION_VERSION',q1.id,7000,'AMBIGUOUS_WORDING_HEURISTIC',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('rule','SHORT_OR_VAGUE_FR_V1'),'human_review_required',true),jsonb_build_object('recommended_action','REWRITE_AND_REVIEW'));created_count:=created_count+1;end if;
 end loop;
 if p_context_type in('QUESTIONNAIRE_QUALITY','SIMILARITY_REVIEW')then
  for q1 in select id,label_fr from public.question_versions where id=any(coalesce(p_candidate_question_version_ids,'{}'))and status='PUBLISHED'loop for q2 in select id,label_fr from public.question_versions where id=any(coalesce(p_candidate_question_version_ids,'{}'))and status='PUBLISHED'and id>q1.id loop score:=private.assistance_overlap_basis_points(q1.label_fr,q2.label_fr);if score>=dup_score then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,related_target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'SEMANTIC_DUPLICATE','QUESTION_PAIR',q1.id,q2.id,score,'QUESTION_TOKEN_SIMILARITY',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('algorithm',m.algorithm,'score_basis_points',score),'human_review_required',true),jsonb_build_object('recommended_action','HUMAN_COMPARE'));created_count:=created_count+1;end if;end loop;end loop;
  for q1 in select id,name_fr||' '||short_description_fr body from public.catalog_service_versions where id=any(coalesce(p_candidate_service_version_ids,'{}'))and status='PUBLISHED'loop for q2 in select id,name_fr||' '||short_description_fr body from public.catalog_service_versions where id=any(coalesce(p_candidate_service_version_ids,'{}'))and status='PUBLISHED'and id>q1.id loop score:=private.assistance_overlap_basis_points(q1.body,q2.body);if score>=dup_score then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,related_target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'SEMANTIC_DUPLICATE','SERVICE_PAIR',q1.id,q2.id,score,'SERVICE_TOKEN_SIMILARITY',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('algorithm',m.algorithm,'score_basis_points',score),'human_review_required',true),jsonb_build_object('recommended_action','HUMAN_COMPARE'));created_count:=created_count+1;end if;end loop;end loop;
 end if;
 if p_profile_reassessment_id is not null then update public.assistance_profile_reassessments set status='COMPLETED',completed_at=clock_timestamp()where id=p_profile_reassessment_id;end if;
 r:=jsonb_build_object('outcome','ASSISTANCE_PROPOSED','request_id',rid,'suggestion_count',created_count,'model_version_id',m.id,'human_confirmation_required',true);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','assistance.analysis.completed','assistance_request',rid::text,p_correlation_id,jsonb_build_object('context_type',p_context_type,'suggestion_count',created_count,'model_version_id',m.id,'candidate_service_count',cardinality(coalesce(p_candidate_service_version_ids,'{}')),'candidate_question_count',cardinality(coalesce(p_candidate_question_version_ids,'{}'))),repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'assistance_request',rid::text,'AssistanceSuggestionsProposedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'assistance.analyse',p_idempotency_key,r);return r;
end$$;

create function public.decide_assisted_suggestion(p_suggestion_id uuid,p_decision text,p_rationale text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();s public.assistance_suggestions%rowtype;h text;cached jsonb;r jsonb;did uuid;begin
 select*into s from public.assistance_suggestions where id=p_suggestion_id;if a is null or not found or not(private.is_active_org_member(s.organization_id,a)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a))then raise exception'ASSISTANCE_DECISION_DENIED'using errcode='42501';end if;if s.status<>'PROPOSED'or p_decision not in('ACCEPTED','REJECTED')or length(btrim(coalesce(p_rationale,'')))not between 3 and 1000 then raise exception'INVALID_ASSISTANCE_DECISION'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('suggestion',s.id,'decision',p_decision,'rationale',p_rationale));cached:=private.begin_contract_command(s.organization_id,'assistance.decide.'||s.id,p_idempotency_key,h,a);if cached is not null then return cached;end if;
 update public.assistance_suggestions set status=p_decision,decided_at=clock_timestamp()where id=s.id and status='PROPOSED';if not found then raise exception'STALE_ASSISTANCE_SUGGESTION'using errcode='40001';end if;insert into public.assistance_suggestion_decisions(organization_id,suggestion_id,decision,rationale,decided_by)values(s.organization_id,s.id,p_decision,p_rationale,a)returning id into did;
 r:=jsonb_build_object('outcome','ASSISTANCE_SUGGESTION_'||p_decision,'suggestion_id',s.id,'decision_id',did,'business_action_executed',false);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(s.organization_id,a,'USER','assistance.suggestion.'||lower(p_decision),'assistance_suggestion',s.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(s.organization_id,'assistance_suggestion',s.id::text,'AssistanceSuggestion'||initcap(lower(p_decision))||'V1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(s.organization_id,'assistance.decide.'||s.id,p_idempotency_key,r);return r;end$$;

insert into public.assistance_model_versions(id,model_key,version,algorithm,configuration,status,effective_from,content_hash,change_reason)values('a1000000-0000-4000-8000-000000000001','MATRICIA_ASSISTED_INTELLIGENCE',1,'TOKEN_OVERLAP_V1','{"minimum_score_basis_points":1800,"duplicate_score_basis_points":6500,"candidate_limit":10}','ACTIVE',timestamptz'2026-09-12 00:00:00+00','8d394f58a74121f481587243f97f287b70a92122b0ea21d6aa4341e04ff99642','Baseline déterministe V1 sans fournisseur externe');

do $$declare t text;begin foreach t in array array['assistance_model_versions','assistance_profile_reassessments','assistance_requests','assistance_suggestions','assistance_suggestion_decisions']loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);end loop;end$$;
grant select on public.assistance_model_versions,public.assistance_profile_reassessments,public.assistance_requests,public.assistance_suggestions,public.assistance_suggestion_decisions to authenticated;
create policy assistance_active_models_read on public.assistance_model_versions for select to authenticated using(status='ACTIVE'or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy assistance_reassessments_tenant_read on public.assistance_profile_reassessments for select to authenticated using(private.is_active_org_member(organization_id)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy assistance_requests_tenant_read on public.assistance_requests for select to authenticated using(private.is_active_org_member(organization_id)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy assistance_suggestions_tenant_read on public.assistance_suggestions for select to authenticated using(private.is_active_org_member(organization_id)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy assistance_decisions_tenant_read on public.assistance_suggestion_decisions for select to authenticated using(private.is_active_org_member(organization_id)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create trigger assistance_models_immutable before update or delete on public.assistance_model_versions for each row execute function private.protect_assistance_model_version();
create trigger assistance_requests_immutable before update or delete on public.assistance_requests for each row execute function private.prevent_update_delete();
create trigger assistance_decisions_immutable before update or delete on public.assistance_suggestion_decisions for each row execute function private.prevent_update_delete();
revoke all on function private.enqueue_profile_assistance_reassessment(),private.assistance_tokens(text),private.assistance_overlap_basis_points(text,text),private.protect_assistance_model_version()from public,anon,authenticated,service_role;
revoke all on function public.run_assisted_analysis(uuid,text,text,uuid[],uuid[],text[],uuid,uuid,text,uuid),public.decide_assisted_suggestion(uuid,text,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.run_assisted_analysis(uuid,text,text,uuid[],uuid[],text[],uuid,uuid,text,uuid),public.decide_assisted_suggestion(uuid,text,text,text,uuid)to authenticated;
