-- Versioned transversal prefill with freshness and explicit confirmation.
create table public.prefill_policy_versions(
 id uuid primary key default extensions.gen_random_uuid(),source_type text not null check(source_type in('PROFILE','ORGANIZATION','SITE','PREVIOUS_ANSWER','DOCUMENT')),version integer not null check(version>0),max_age_days integer not null check(max_age_days between 1 and 3650),requires_confirmation boolean not null,allowed_sensitivity text[]not null check(cardinality(allowed_sensitivity)>0),status text not null check(status in('ACTIVE','RETIRED')),effective_from timestamptz not null,effective_until timestamptz,content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),created_by uuid references auth.users(id),created_at timestamptz not null default clock_timestamp(),unique(source_type,version),check(effective_until is null or effective_until>effective_from));
create table public.prefill_fact_versions(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,data_key text not null check(data_key~'^[A-Za-z][A-Za-z0-9_.-]{1,159}$'),source_type text not null check(source_type in('PROFILE','ORGANIZATION','SITE','DOCUMENT')),source_reference_id uuid,value jsonb,sensitivity text not null check(sensitivity in('PUBLIC','BUSINESS','CONFIDENTIAL','RESTRICTED')),observed_at timestamptz not null,fresh_until timestamptz not null,content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),supersedes_id uuid references public.prefill_fact_versions(id)on delete restrict,created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),check(fresh_until>observed_at));
insert into public.prefill_policy_versions(source_type,version,max_age_days,requires_confirmation,allowed_sensitivity,status,effective_from,content_hash)values
('PROFILE',1,365,true,array['PUBLIC','BUSINESS','CONFIDENTIAL'], 'ACTIVE','2026-09-10',encode(extensions.digest('PROFILE:1:365:CONFIRM','sha256'),'hex')),
('ORGANIZATION',1,365,true,array['PUBLIC','BUSINESS','CONFIDENTIAL'], 'ACTIVE','2026-09-10',encode(extensions.digest('ORGANIZATION:1:365:CONFIRM','sha256'),'hex')),
('SITE',1,180,true,array['PUBLIC','BUSINESS','CONFIDENTIAL'], 'ACTIVE','2026-09-10',encode(extensions.digest('SITE:1:180:CONFIRM','sha256'),'hex')),
('PREVIOUS_ANSWER',1,90,true,array['PUBLIC','BUSINESS','CONFIDENTIAL'], 'ACTIVE','2026-09-10',encode(extensions.digest('PREVIOUS_ANSWER:1:90:CONFIRM','sha256'),'hex')),
('DOCUMENT',1,30,true,array['PUBLIC','BUSINESS'], 'ACTIVE','2026-09-10',encode(extensions.digest('DOCUMENT:1:30:CONFIRM','sha256'),'hex'));
create function private.prevent_prefill_history_change()returns trigger language plpgsql set search_path=pg_catalog as $$begin raise exception'PREFILL_HISTORY_IMMUTABLE'using errcode='55000';end$$;
create trigger prefill_policies_immutable before update or delete on public.prefill_policy_versions for each row execute function private.prevent_prefill_history_change();
create trigger prefill_facts_immutable before update or delete on public.prefill_fact_versions for each row execute function private.prevent_prefill_history_change();
create function public.record_prefill_fact(p_organization_id uuid,p_data_key text,p_source_type text,p_source_reference_id uuid,p_value jsonb,p_sensitivity text,p_observed_at timestamptz,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();policy public.prefill_policy_versions%rowtype;prior uuid;h text;x uuid;r jsonb;begin if a is null or not private.client_portfolio_manage(p_organization_id,a)then raise exception'PREFILL_FACT_DENIED'using errcode='42501';end if;select*into policy from public.prefill_policy_versions where source_type=p_source_type and status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp())order by version desc limit 1;if not found or p_source_type='PREVIOUS_ANSWER'or p_data_key!~'^[A-Za-z][A-Za-z0-9_.-]{1,159}$'or p_sensitivity<>all(policy.allowed_sensitivity)or p_observed_at>clock_timestamp()+interval'5 minutes'then raise exception'INVALID_PREFILL_FACT'using errcode='22023';end if;select id into prior from public.prefill_fact_versions where organization_id=p_organization_id and data_key=p_data_key and source_type=p_source_type order by created_at desc limit 1;h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'key',p_data_key,'source',p_source_type,'reference',p_source_reference_id,'value',p_value,'sensitivity',p_sensitivity,'observed',p_observed_at,'policy',policy.id));insert into public.prefill_fact_versions(organization_id,data_key,source_type,source_reference_id,value,sensitivity,observed_at,fresh_until,content_hash,supersedes_id,created_by)values(p_organization_id,p_data_key,p_source_type,p_source_reference_id,p_value,p_sensitivity,p_observed_at,p_observed_at+make_interval(days=>policy.max_age_days),h,prior,a)returning id into x;r:=jsonb_build_object('outcome','PREFILL_FACT_VERSION_RECORDED','fact_version_id',x,'fresh_until',p_observed_at+make_interval(days=>policy.max_age_days),'policy_version_id',policy.id);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','prefill.fact.version_recorded','prefill_fact_version',x::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'prefill_fact',x::text,'PrefillFactVersionRecordedV1',p_correlation_id,r,p_idempotency_key);return r;end$$;
create function public.questionnaire_prefill_suggestions(p_session_id uuid)returns table(question_version_id uuid,value jsonb,source text,source_updated_at timestamptz,fresh_until timestamptz,requires_confirmation boolean)language sql stable security definer set search_path=pg_catalog,public,private as $$
 with session_scope as(select s.*from public.questionnaire_sessions s where s.id=p_session_id and s.actor_user_id=auth.uid()and private.client_portfolio_read(s.organization_id,auth.uid())),targets as(select qv.id,qv.question_id,qv.data_key,qv.prefill_source,qv.sensitivity from session_scope s join public.questionnaire_version_questions ql on ql.questionnaire_version_id=s.questionnaire_version_id join public.question_versions qv on qv.id=ql.question_version_id where qv.prefill_source is not null and not exists(select 1 from public.questionnaire_answers a where a.session_id=s.id and a.question_version_id=qv.id)),policies as(select distinct on(source_type)*from public.prefill_policy_versions where status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp())order by source_type,version desc),previous as(select distinct on(t.id)t.id question_version_id,r.value,'PREVIOUS_ANSWER'::text source,r.answered_at source_updated_at,least(coalesce(r.expires_at,'infinity'),r.answered_at+make_interval(days=>p.max_age_days))fresh_until,p.requires_confirmation from targets t join policies p on p.source_type='PREVIOUS_ANSWER'and t.sensitivity=any(p.allowed_sensitivity)join public.question_versions oldq on oldq.question_id=t.question_id join public.questionnaire_answers a on a.question_version_id=oldq.id join public.questionnaire_sessions s on s.id=a.session_id join public.questionnaire_answer_revisions r on r.id=a.current_revision_id join session_scope current on current.organization_id=s.organization_id and current.actor_user_id=s.actor_user_id where t.prefill_source='PREVIOUS_ANSWER'and s.status='SUBMITTED'and r.answered_at>=clock_timestamp()-make_interval(days=>p.max_age_days)order by t.id,r.answered_at desc),facts as(select distinct on(t.id)t.id,f.value,f.source_type,f.observed_at,f.fresh_until,p.requires_confirmation from targets t join policies p on p.source_type=t.prefill_source and t.sensitivity=any(p.allowed_sensitivity)join public.prefill_fact_versions f on f.organization_id=(select organization_id from session_scope)and f.data_key=t.data_key and f.source_type=t.prefill_source where t.prefill_source<>'PREVIOUS_ANSWER'and f.fresh_until>clock_timestamp()order by t.id,f.observed_at desc)select*from previous where fresh_until>clock_timestamp()union all select*from facts
$$;
alter table public.prefill_policy_versions enable row level security;alter table public.prefill_fact_versions enable row level security;revoke all on public.prefill_policy_versions,public.prefill_fact_versions from public,anon,authenticated,service_role;create policy prefill_policies_read on public.prefill_policy_versions for select to authenticated using(true);create policy prefill_facts_tenant_read on public.prefill_fact_versions for select to authenticated using(private.client_portfolio_read(organization_id));grant select on public.prefill_policy_versions,public.prefill_fact_versions to authenticated;revoke all on function public.record_prefill_fact(uuid,text,text,uuid,jsonb,text,timestamptz,text,uuid),public.questionnaire_prefill_suggestions(uuid)from public,anon,authenticated,service_role;grant execute on function public.record_prefill_fact(uuid,text,text,uuid,jsonb,text,timestamptz,text,uuid),public.questionnaire_prefill_suggestions(uuid)to authenticated;create index prefill_facts_current_idx on public.prefill_fact_versions(organization_id,data_key,source_type,observed_at desc);

