-- Additive hotfix: keep the idempotency operation scope normalized and bounded.
create or replace function public.review_marketing_brand_evidence_v1(p_brand_kit_version_id uuid,p_evidence_type text,p_evidence_key text,p_decision text,p_evidence_hash text,p_valid_until timestamptz,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();bv public.brand_kit_versions%rowtype;bk public.brand_kits%rowtype;proposal jsonb;prior public.marketing_brand_evidence_review_versions%rowtype;next_version integer;record_id uuid;h text;cached jsonb;r jsonb;ready boolean;
begin
 select v.*into bv from public.brand_kit_versions v where v.id=p_brand_kit_version_id;
 select*into bk from public.brand_kits where id=bv.brand_kit_id for update;
 if a is null or bv.id is null or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a)or auth.jwt()->>'aal'is distinct from'aal2'then raise exception'MARKETING_BRAND_EVIDENCE_REVIEW_DENIED'using errcode='42501';end if;
 if bk.current_version_id is distinct from bv.id then raise exception'MARKETING_BRAND_EVIDENCE_VERSION_STALE'using errcode='40001';end if;
 if p_evidence_type not in('CLAIM','CERTIFICATION')or p_decision not in('VERIFIED','REJECTED','REVOKED')or p_evidence_hash!~'^[0-9a-f]{64}$'or length(btrim(coalesce(p_reason,'')))not between 3 and 1000 or p_valid_until<=clock_timestamp()then raise exception'INVALID_MARKETING_BRAND_EVIDENCE_REVIEW'using errcode='22023';end if;
 select value into proposal from jsonb_array_elements(case when p_evidence_type='CLAIM'then bv.claims else bv.certifications end)where value->>'key'=p_evidence_key and value->>'evidenceHash'=p_evidence_hash;
 if proposal is null then raise exception'MARKETING_BRAND_EVIDENCE_NOT_SUBMITTED'using errcode='P0002';end if;
 h:=private.canonical_request_hash(jsonb_build_object('brand_version',bv.id,'type',p_evidence_type,'key',p_evidence_key,'decision',p_decision,'evidence_hash',p_evidence_hash,'valid_until',p_valid_until,'reason',p_reason));cached:=private.begin_contract_command(bk.organization_id,'marketing.brand_evidence.review',p_idempotency_key,h,a);if cached is not null then return cached;end if;
 perform pg_advisory_xact_lock(hashtextextended('marketing-brand-evidence:'||bv.id::text||':'||p_evidence_type||':'||p_evidence_key,0));
 select*into prior from public.marketing_brand_evidence_review_versions where brand_kit_version_id=bv.id and evidence_type=p_evidence_type and evidence_key=p_evidence_key order by version desc limit 1;
 if p_decision='REVOKED'and(coalesce(prior.decision,'')<>'VERIFIED'or(prior.valid_until is not null and prior.valid_until<=clock_timestamp()))then raise exception'INVALID_MARKETING_BRAND_EVIDENCE_REVOCATION'using errcode='55000';end if;
 next_version:=coalesce(prior.version,0)+1;
 insert into public.marketing_brand_evidence_review_versions(organization_id,brand_kit_version_id,evidence_type,evidence_key,version,decision,evidence_hash,valid_until,reason,supersedes_id,reviewed_by)values(bk.organization_id,bv.id,p_evidence_type,p_evidence_key,next_version,p_decision,p_evidence_hash,case when p_decision='VERIFIED'then p_valid_until end,btrim(p_reason),prior.id,a)returning id into record_id;
 select not exists(select 1 from jsonb_array_elements(bv.claims)submitted where not exists(select 1 from public.marketing_brand_evidence_review_versions review where review.brand_kit_version_id=bv.id and review.evidence_type='CLAIM'and review.evidence_key=submitted->>'key'and review.evidence_hash=submitted->>'evidenceHash'and review.decision='VERIFIED'and(review.valid_until is null or review.valid_until>clock_timestamp())and review.version=(select max(latest.version)from public.marketing_brand_evidence_review_versions latest where latest.brand_kit_version_id=bv.id and latest.evidence_type='CLAIM'and latest.evidence_key=submitted->>'key')))and not exists(select 1 from jsonb_array_elements(bv.certifications)submitted where not exists(select 1 from public.marketing_brand_evidence_review_versions review where review.brand_kit_version_id=bv.id and review.evidence_type='CERTIFICATION'and review.evidence_key=submitted->>'key'and review.evidence_hash=submitted->>'evidenceHash'and review.decision='VERIFIED'and(review.valid_until is null or review.valid_until>clock_timestamp())and review.version=(select max(latest.version)from public.marketing_brand_evidence_review_versions latest where latest.brand_kit_version_id=bv.id and latest.evidence_type='CERTIFICATION'and latest.evidence_key=submitted->>'key')))into ready;
 update public.brand_kits set status=case when ready then'READY'else'DRAFT'end,row_version=row_version+1 where id=bk.id and current_version_id=bv.id;
 if not ready then update public.social_publication_jobs set status='SKIPPED'where organization_id=bk.organization_id and status='QUEUED';end if;
 r:=jsonb_build_object('outcome','MARKETING_BRAND_EVIDENCE_'||p_decision,'review_id',record_id,'brand_kit_version_id',bv.id,'evidence_type',p_evidence_type,'evidence_key',p_evidence_key,'version',next_version,'brand_kit_ready',ready);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(bk.organization_id,a,'USER','marketing.brand_evidence.'||lower(p_decision),'marketing_brand_evidence_review',record_id::text,p_correlation_id,r,repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(bk.organization_id,'brand_kit',bk.id::text,'MarketingBrandEvidenceReviewedV1',p_correlation_id,r,p_idempotency_key);
 perform private.finish_contract_command(bk.organization_id,'marketing.brand_evidence.review',p_idempotency_key,r);return r;
end$$;

revoke all on function public.review_marketing_brand_evidence_v1(uuid,text,text,text,text,timestamptz,text,text,uuid) from public,anon,authenticated,service_role;
grant execute on function public.review_marketing_brand_evidence_v1(uuid,text,text,text,text,timestamptz,text,text,uuid) to authenticated;
