-- P07 deterministic diagnostic completion, immutable results and client-controlled opportunities.
create table public.diagnostic_runs(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,questionnaire_session_id uuid not null references public.questionnaire_sessions(id)on delete restrict,library_id uuid not null references public.catalog_libraries(id)on delete restrict,site_id uuid,project_id uuid,status text not null check(status in('COMPLETED','SUPERSEDED')),input_manifest_hash text not null check(input_manifest_hash~'^[0-9a-f]{64}$'),scoring_policy_snapshot jsonb not null check(jsonb_typeof(scoring_policy_snapshot)='object'and scoring_policy_snapshot?&array['version','content_hash','thresholds']and scoring_policy_snapshot->>'content_hash'~'^[0-9a-f]{64}$'),overall_score numeric(5,2) not null check(overall_score between 0 and 100),rating text not null check(rating in('GOOD','ATTENTION','IMPORTANT','CRITICAL')),explanation jsonb not null check(jsonb_typeof(explanation)='object'),completed_by uuid not null references auth.users(id),completed_at timestamptz not null default clock_timestamp(),superseded_at timestamptz,correlation_id uuid not null,check((status='SUPERSEDED')=(superseded_at is not null)),unique(id,organization_id)
);
create unique index diagnostic_one_current_per_session_uidx on public.diagnostic_runs(questionnaire_session_id)where status='COMPLETED';
create table public.diagnostic_subscores(id uuid primary key default extensions.gen_random_uuid(),diagnostic_run_id uuid not null references public.diagnostic_runs(id)on delete restrict,dimension_key text not null check(dimension_key~'^[A-Z][A-Z0-9_.-]{1,119}$'),score numeric(5,2) not null check(score between 0 and 100),weighted_points numeric(30,6) not null check(weighted_points>=0),maximum_points numeric(30,6) not null check(maximum_points>0),explanation jsonb not null check(jsonb_typeof(explanation)='object'),unique(diagnostic_run_id,dimension_key));
create table public.diagnostic_anomalies(id uuid primary key default extensions.gen_random_uuid(),diagnostic_run_id uuid not null references public.diagnostic_runs(id)on delete restrict,organization_id uuid not null references public.organizations(id)on delete restrict,anomaly_code text not null check(anomaly_code~'^[A-Z][A-Z0-9_.-]{1,119}$'),severity text not null check(severity in('INFO','WARNING','HIGH','CRITICAL')),blocking boolean not null,title_fr text not null,title_ar text not null,explanation jsonb not null check(jsonb_typeof(explanation)='object'),rule_snapshot jsonb not null check(jsonb_typeof(rule_snapshot)='object'),status text not null default'OPEN'check(status in('OPEN','IGNORED','RESOLVED')),created_at timestamptz not null default clock_timestamp(),unique(diagnostic_run_id,anomaly_code),unique(id,organization_id));
create table public.diagnostic_recommendations(id uuid primary key default extensions.gen_random_uuid(),diagnostic_run_id uuid not null references public.diagnostic_runs(id)on delete restrict,organization_id uuid not null references public.organizations(id)on delete restrict,anomaly_id uuid not null,recommendation_key text not null check(recommendation_key~'^[A-Z][A-Z0-9_.-]{1,119}$'),priority integer not null check(priority between 1 and 100),title_fr text not null,title_ar text not null,client_text_fr text not null,client_text_ar text not null,service_id uuid references public.catalog_services(id)on delete restrict,solution_level text not null check(solution_level in('GUIDANCE','ASSISTED','MANAGED')),rule_snapshot jsonb not null check(jsonb_typeof(rule_snapshot)='object'),created_at timestamptz not null default clock_timestamp(),foreign key(anomaly_id,organization_id)references public.diagnostic_anomalies(id,organization_id)on delete restrict,unique(diagnostic_run_id,recommendation_key),unique(id,organization_id));
create table public.diagnostic_opportunities(id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,diagnostic_run_id uuid not null references public.diagnostic_runs(id)on delete restrict,anomaly_id uuid not null,recommendation_id uuid not null,service_id uuid references public.catalog_services(id)on delete restrict,origin text not null default'DIAGNOSTIC'check(origin='DIAGNOSTIC'),solution_level text not null check(solution_level in('GUIDANCE','ASSISTED','MANAGED')),priority integer not null check(priority between 1 and 100),known_data jsonb not null default'{}'check(jsonb_typeof(known_data)='object'),missing_fields jsonb not null default'[]'check(jsonb_typeof(missing_fields)='array'),status text not null default'DETECTED'check(status in('DETECTED','CLIENT_ACCEPTED','RFQ_READY','CONVERTED','CLOSED')),deferred_until timestamptz,service_request_id uuid references public.service_requests(id)on delete restrict,row_version integer not null default 1 check(row_version>0),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),foreign key(anomaly_id,organization_id)references public.diagnostic_anomalies(id,organization_id)on delete restrict,foreign key(recommendation_id,organization_id)references public.diagnostic_recommendations(id,organization_id)on delete restrict,unique(diagnostic_run_id,recommendation_id),check((status='CONVERTED')=(service_request_id is not null)),check(deferred_until is null or status='DETECTED'));

create function private.prevent_diagnostic_result_change()returns trigger language plpgsql set search_path=pg_catalog as $$begin raise exception'DIAGNOSTIC_RESULT_IMMUTABLE'using errcode='55000';end$$;
create function private.protect_diagnostic_run_history()returns trigger language plpgsql set search_path=pg_catalog as $$begin if tg_op='DELETE'or old.status='SUPERSEDED'or new.status<>'SUPERSEDED'or(to_jsonb(new)-array['status','superseded_at'])is distinct from(to_jsonb(old)-array['status','superseded_at'])then raise exception'DIAGNOSTIC_RESULT_IMMUTABLE'using errcode='55000';end if;return new;end$$;
create trigger diagnostic_runs_immutable before update or delete on public.diagnostic_runs for each row execute function private.protect_diagnostic_run_history();
create trigger diagnostic_subscores_immutable before update or delete on public.diagnostic_subscores for each row execute function private.prevent_diagnostic_result_change();
create trigger diagnostic_anomalies_immutable before update or delete on public.diagnostic_anomalies for each row execute function private.prevent_diagnostic_result_change();
create trigger diagnostic_recommendations_immutable before update or delete on public.diagnostic_recommendations for each row execute function private.prevent_diagnostic_result_change();

create function public.complete_diagnostic_session(p_session_id uuid,p_scoring_policy_snapshot jsonb,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();s public.questionnaire_sessions%rowtype;h text;r jsonb;cached jsonb;points numeric(30,6);maximum numeric(30,6);score numeric(5,2);rating text;run_id uuid;old_id uuid;rec jsonb;anomaly_id uuid;recommendation_id uuid;service uuid;thresholds jsonb;begin
 select*into s from public.questionnaire_sessions where id=p_session_id;if a is null or not found or s.status<>'SUBMITTED'or s.audience<>'CLIENT'or not private.has_org_role(s.organization_id,array['CLIENT_OWNER','CLIENT_ADMIN'],a)then raise exception'DIAGNOSTIC_COMPLETE_DENIED'using errcode='42501';end if;
 if length(p_idempotency_key)not between 8 and 200 or p_correlation_id is null or jsonb_typeof(p_scoring_policy_snapshot)<>'object'or not(p_scoring_policy_snapshot?&array['version','content_hash','thresholds','recommendations'])or p_scoring_policy_snapshot->>'content_hash'!~'^[0-9a-f]{64}$'or jsonb_typeof(p_scoring_policy_snapshot->'thresholds')<>'object'or jsonb_typeof(p_scoring_policy_snapshot->'recommendations')<>'object'then raise exception'INVALID_DIAGNOSTIC_POLICY'using errcode='22023';end if;
 thresholds:=p_scoring_policy_snapshot->'thresholds';if not(thresholds?&array['good','attention','important'])or(thresholds->>'good')::numeric<>(80)::numeric or(thresholds->>'attention')::numeric<>(60)::numeric or(thresholds->>'important')::numeric<>(40)::numeric then raise exception'INVALID_DIAGNOSTIC_THRESHOLDS'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('session',s.id,'manifest',s.answer_manifest_hash,'policy',p_scoring_policy_snapshot));cached:=private.begin_contract_command(s.organization_id,'diagnostic.complete.'||s.id::text,p_idempotency_key,h,a);if cached is not null then return cached;end if;
 select coalesce(sum((case when jsonb_typeof(ar.value)='number'then(ar.value#>>'{}')::numeric when jsonb_typeof(ar.value)='object'and ar.value?'score'then(ar.value->>'score')::numeric else null end)*qv.weight),0),coalesce(sum(qv.maximum_score*qv.weight),0)into points,maximum from public.questionnaire_answers qa join public.questionnaire_answer_revisions ar on ar.id=qa.current_revision_id join public.question_versions qv on qv.id=qa.question_version_id where qa.session_id=s.id and qv.maximum_score>0 and qv.weight>0;
 if maximum<=0 or points<0 or points>maximum then raise exception'INVALID_DIAGNOSTIC_SCORE_INPUT'using errcode='22023';end if;score:=round(points/maximum*100,2);rating:=case when score>=80 then'GOOD'when score>=60 then'ATTENTION'when score>=40 then'IMPORTANT'else'CRITICAL'end;
 select id into old_id from public.diagnostic_runs where questionnaire_session_id=s.id and status='COMPLETED'for update;if old_id is not null then update public.diagnostic_runs set status='SUPERSEDED',superseded_at=clock_timestamp()where id=old_id;end if;
 insert into public.diagnostic_runs(organization_id,questionnaire_session_id,library_id,site_id,project_id,status,input_manifest_hash,scoring_policy_snapshot,overall_score,rating,explanation,completed_by,correlation_id)values(s.organization_id,s.id,s.library_id,s.site_id,s.project_id,'COMPLETED',s.answer_manifest_hash,p_scoring_policy_snapshot,score,rating,jsonb_build_object('formula','SUM(score*weight)/SUM(maximum_score*weight)*100','weighted_points',points,'maximum_points',maximum,'questionnaire_version_id',s.questionnaire_version_id),a,p_correlation_id)returning id into run_id;
 insert into public.diagnostic_subscores(diagnostic_run_id,dimension_key,score,weighted_points,maximum_points,explanation)values(run_id,'OVERALL',score,points,maximum,jsonb_build_object('rating',rating));
 if rating<>'GOOD'then rec:=p_scoring_policy_snapshot->'recommendations'->rating;if jsonb_typeof(rec)<>'object'or not(rec?&array['key','title_fr','title_ar','client_text_fr','client_text_ar','priority','solution_level'])then raise exception'MISSING_DIAGNOSTIC_RECOMMENDATION'using errcode='22023';end if;service:=nullif(rec->>'service_id','')::uuid;
  insert into public.diagnostic_anomalies(diagnostic_run_id,organization_id,anomaly_code,severity,blocking,title_fr,title_ar,explanation,rule_snapshot)values(run_id,s.organization_id,'HEALTH_SCORE_'||rating,case rating when'CRITICAL'then'CRITICAL'when'IMPORTANT'then'HIGH'else'WARNING'end,rating='CRITICAL',rec->>'title_fr',rec->>'title_ar',jsonb_build_object('score',score,'rating',rating),jsonb_build_object('version',p_scoring_policy_snapshot->>'version','content_hash',p_scoring_policy_snapshot->>'content_hash'))returning id into anomaly_id;
  insert into public.diagnostic_recommendations(diagnostic_run_id,organization_id,anomaly_id,recommendation_key,priority,title_fr,title_ar,client_text_fr,client_text_ar,service_id,solution_level,rule_snapshot)values(run_id,s.organization_id,anomaly_id,rec->>'key',(rec->>'priority')::integer,rec->>'title_fr',rec->>'title_ar',rec->>'client_text_fr',rec->>'client_text_ar',service,rec->>'solution_level',rec)returning id into recommendation_id;
  insert into public.diagnostic_opportunities(organization_id,diagnostic_run_id,anomaly_id,recommendation_id,service_id,solution_level,priority,known_data,missing_fields)values(s.organization_id,run_id,anomaly_id,recommendation_id,service,rec->>'solution_level',(rec->>'priority')::integer,jsonb_build_object('diagnostic_score',score,'rating',rating),coalesce(rec->'missing_fields','[]'));
 end if;
 r:=jsonb_build_object('outcome','DIAGNOSTIC_COMPLETED','diagnostic_run_id',run_id,'score',score,'rating',rating,'supersedes',old_id,'opportunity_created',recommendation_id is not null);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(s.organization_id,a,'USER','diagnostic.completed','diagnostic_run',run_id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(s.organization_id,'diagnostic_run',run_id::text,'DiagnosticCompletedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(s.organization_id,'diagnostic.complete.'||s.id::text,p_idempotency_key,r);return r;
exception when invalid_text_representation or invalid_parameter_value then raise exception'INVALID_DIAGNOSTIC_POLICY'using errcode='22023';end$$;

create function public.transition_diagnostic_opportunity(p_opportunity_id uuid,p_action text,p_deferred_until timestamptz,p_expected_row_version integer,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();o public.diagnostic_opportunities%rowtype;h text;cached jsonb;r jsonb;next_status text;begin select*into o from public.diagnostic_opportunities where id=p_opportunity_id;if a is null or not found or not private.has_org_role(o.organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER'],a)then raise exception'OPPORTUNITY_ACTION_DENIED'using errcode='42501';end if;if o.row_version<>p_expected_row_version or p_action not in('ACCEPT','DEFER','REQUEST_RFQ','CLOSE')then raise exception'INVALID_OPPORTUNITY_ACTION'using errcode='22023';end if;next_status:=case p_action when'ACCEPT'then'CLIENT_ACCEPTED'when'REQUEST_RFQ'then'RFQ_READY'when'CLOSE'then'CLOSED'else'DETECTED'end;if(p_action='ACCEPT'and o.status<>'DETECTED')or(p_action='DEFER'and(o.status<>'DETECTED'or p_deferred_until is null or p_deferred_until<=clock_timestamp()))or(p_action='REQUEST_RFQ'and(o.status not in('DETECTED','CLIENT_ACCEPTED')or o.service_id is null or jsonb_array_length(o.missing_fields)>0))or(p_action='CLOSE'and o.status not in('DETECTED','CLIENT_ACCEPTED','RFQ_READY'))then raise exception'INVALID_OPPORTUNITY_TRANSITION'using errcode='55000';end if;h:=private.canonical_request_hash(jsonb_build_object('opportunity',o.id,'action',p_action,'deferred_until',p_deferred_until,'expected',p_expected_row_version));cached:=private.begin_contract_command(o.organization_id,'diagnostic.opportunity.'||o.id::text,p_idempotency_key,h,a);if cached is not null then return cached;end if;update public.diagnostic_opportunities set status=next_status,deferred_until=case when p_action='DEFER'then p_deferred_until end,row_version=row_version+1,updated_at=clock_timestamp()where id=o.id and row_version=p_expected_row_version;if not found then raise exception'STALE_OPPORTUNITY'using errcode='40001';end if;r:=jsonb_build_object('outcome','OPPORTUNITY_'||p_action,'opportunity_id',o.id,'status',next_status,'row_version',o.row_version+1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(o.organization_id,a,'USER','diagnostic.opportunity.'||lower(p_action),'diagnostic_opportunity',o.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(o.organization_id,'diagnostic_opportunity',o.id::text,'DiagnosticOpportunity'||initcap(lower(p_action))||'V1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(o.organization_id,'diagnostic.opportunity.'||o.id::text,p_idempotency_key,r);return r;end$$;

alter table public.diagnostic_runs enable row level security;alter table public.diagnostic_subscores enable row level security;alter table public.diagnostic_anomalies enable row level security;alter table public.diagnostic_recommendations enable row level security;alter table public.diagnostic_opportunities enable row level security;
create policy diagnostic_runs_tenant_read on public.diagnostic_runs for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER','CLIENT_VIEWER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy diagnostic_subscores_tenant_read on public.diagnostic_subscores for select to authenticated using(exists(select 1 from public.diagnostic_runs r where r.id=diagnostic_run_id));
create policy diagnostic_anomalies_tenant_read on public.diagnostic_anomalies for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER','CLIENT_VIEWER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy diagnostic_recommendations_tenant_read on public.diagnostic_recommendations for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER','CLIENT_VIEWER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
create policy diagnostic_opportunities_tenant_read on public.diagnostic_opportunities for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER','CLIENT_VIEWER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR']));
revoke all on public.diagnostic_runs,public.diagnostic_subscores,public.diagnostic_anomalies,public.diagnostic_recommendations,public.diagnostic_opportunities from public,anon,authenticated;grant select on public.diagnostic_runs,public.diagnostic_subscores,public.diagnostic_anomalies,public.diagnostic_recommendations,public.diagnostic_opportunities to authenticated;
revoke all on function private.prevent_diagnostic_result_change(),private.protect_diagnostic_run_history(),public.complete_diagnostic_session(uuid,jsonb,text,uuid),public.transition_diagnostic_opportunity(uuid,text,timestamptz,integer,text,uuid)from public,anon,authenticated,service_role;grant execute on function public.complete_diagnostic_session(uuid,jsonb,text,uuid),public.transition_diagnostic_opportunity(uuid,text,timestamptz,integer,text,uuid)to authenticated;
create index diagnostic_runs_org_time_idx on public.diagnostic_runs(organization_id,completed_at desc);create index diagnostic_runs_library_time_idx on public.diagnostic_runs(library_id,completed_at desc);create index diagnostic_anomalies_run_status_idx on public.diagnostic_anomalies(diagnostic_run_id,status,severity);create index diagnostic_recommendations_run_priority_idx on public.diagnostic_recommendations(diagnostic_run_id,priority);create index diagnostic_opportunities_org_status_idx on public.diagnostic_opportunities(organization_id,status,priority,created_at desc);create index diagnostic_answers_expiry_idx on public.questionnaire_answer_revisions(organization_id,expires_at)where expires_at is not null;
notify pgrst,'reload schema';
