-- MAT-FUNC-026: amendment submission, two-party signatures and immutable activation.

alter table public.contract_amendments add column activated_contract_version_id uuid unique references public.contract_versions(id) on delete restrict;
alter table public.contract_amendments add column activated_at timestamptz;

create table public.contract_amendment_signatures(
 id uuid primary key default extensions.gen_random_uuid(),
 amendment_id uuid not null references public.contract_amendments(id) on delete restrict,
 organization_id uuid not null references public.organizations(id) on delete restrict,
 signer_user_id uuid not null references auth.users(id),
 signer_role text not null check(signer_role~'^[A-Z][A-Z0-9_]{2,79}$'),
 amendment_hash text not null check(amendment_hash~'^[0-9a-f]{64}$'),
 proof jsonb not null check(jsonb_typeof(proof)='object'and proof?&array['method','signed_at','evidence_hash']and proof->>'evidence_hash'~'^[0-9a-f]{64}$'),
 signed_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,
 unique(amendment_id,organization_id)
);
alter table public.contract_amendment_signatures enable row level security;
create policy amendment_signatures_party_read on public.contract_amendment_signatures for select to authenticated using(private.contract_party_access((select a.contract_id from public.contract_amendments a where a.id=amendment_id)));
create trigger amendment_signatures_immutable before update or delete on public.contract_amendment_signatures for each row execute function private.prevent_contract_immutable_change();

drop trigger amendments_immutable on public.contract_amendments;
create function private.guard_contract_amendment_lifecycle()returns trigger language plpgsql set search_path=pg_catalog as $$
begin
 if tg_op='DELETE'then raise exception'IMMUTABLE_CONTRACT_AMENDMENT_CONTENT'using errcode='55000';end if;
 if old.id<>new.id or old.contract_id<>new.contract_id or old.change_request_id<>new.change_request_id or old.base_contract_version_id<>new.base_contract_version_id or old.amendment_number<>new.amendment_number or old.price_delta_minor<>new.price_delta_minor or old.deadline_delta_days<>new.deadline_delta_days or old.deliverables_delta is distinct from new.deliverables_delta or old.commission_rule_snapshot is distinct from new.commission_rule_snapshot or old.content_hash<>new.content_hash or old.created_by<>new.created_by or old.created_at<>new.created_at then raise exception'IMMUTABLE_CONTRACT_AMENDMENT_CONTENT'using errcode='55000';end if;
 if not((old.status='DRAFT'and new.status='PENDING_SIGNATURE'and new.activated_contract_version_id is null and new.activated_at is null)or(old.status='PENDING_SIGNATURE'and new.status='ACTIVE'and new.activated_contract_version_id is not null and new.activated_at is not null))then raise exception'INVALID_CONTRACT_AMENDMENT_LIFECYCLE'using errcode='55000';end if;return new;
end$$;
create trigger amendments_lifecycle_guard before update or delete on public.contract_amendments for each row execute function private.guard_contract_amendment_lifecycle();

create or replace function private.bind_selected_quote_version()returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare c public.contracts%rowtype;am public.contract_amendments%rowtype;base public.contract_versions%rowtype;am_id uuid;
begin
 new.selected_quote_version_id:=nullif(new.quote_snapshot->>'quote_version_id','')::uuid;select*into c from public.contracts where id=new.contract_id;
 am_id:=nullif(new.request_snapshot->>'amendment_id','')::uuid;
 if am_id is not null then
  select*into am from public.contract_amendments where id=am_id and contract_id=new.contract_id;select*into base from public.contract_versions where id=am.base_contract_version_id and contract_id=new.contract_id;
  if am.id is null or base.id is null or new.selected_quote_version_id<>base.selected_quote_version_id or new.price_minor<>base.price_minor+am.price_delta_minor or new.currency<>base.currency or new.version<>(select current_version+1 from public.contracts where id=new.contract_id)then raise exception'VALID_AMENDMENT_VERSION_REQUIRED'using errcode='22023';end if;
 elsif new.selected_quote_version_id is null or not exists(select 1 from public.quote_versions qv join public.quotes q on q.id=qv.quote_id join public.rfqs r on r.id=q.rfq_id join public.service_requests sr on sr.id=r.request_id where qv.id=new.selected_quote_version_id and q.selected_version_id=qv.id and q.status='SELECTED'and q.provider_organization_id=c.provider_organization_id and sr.client_organization_id=c.client_organization_id and qv.total_minor=new.price_minor and qv.currency=new.currency)then raise exception'SELECTED_QUOTE_VERSION_REQUIRED'using errcode='22023';end if;return new;
end$$;

create function public.submit_contract_amendment_for_signature(p_amendment_id uuid,p_expected_hash text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();am public.contract_amendments%rowtype;c public.contracts%rowtype;h text;r jsonb;
begin select*into am from public.contract_amendments where id=p_amendment_id;select*into c from public.contracts where id=am.contract_id;
 if a is null or am.id is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_org_role(c.client_organization_id,array['CLIENT_OWNER','CLIENT_ADMIN'],a)then raise exception'AMENDMENT_SUBMIT_AAL2_REQUIRED'using errcode='42501';end if;
 if p_expected_hash<>am.content_hash then raise exception'STALE_AMENDMENT'using errcode='40001';end if;h:=private.canonical_request_hash(jsonb_build_object('amendment',am.id,'hash',p_expected_hash));r:=private.begin_contract_command(c.client_organization_id,'contract.amendment.submit.'||am.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;
 update public.contract_amendments set status='PENDING_SIGNATURE'where id=am.id and status='DRAFT';if not found then raise exception'INVALID_AMENDMENT_SUBMIT_TRANSITION'using errcode='55000';end if;
 r:=jsonb_build_object('outcome','CONTRACT_AMENDMENT_PENDING_SIGNATURE','amendment_id',am.id,'contract_id',c.id);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(c.client_organization_id,a,'USER','contract.amendment.submitted','contract_amendment',am.id::text,p_correlation_id,jsonb_build_object('content_hash',am.content_hash),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(c.client_organization_id,'contract_amendment',am.id::text,'ContractAmendmentSignatureRequestedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(c.client_organization_id,'contract.amendment.submit.'||am.id::text,p_idempotency_key,r);return r;
end$$;

create function public.sign_and_activate_contract_amendment(p_amendment_id uuid,p_organization_id uuid,p_expected_hash text,p_signer_role text,p_proof jsonb,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare actor uuid:=auth.uid();am public.contract_amendments%rowtype;c public.contracts%rowtype;base public.contract_versions%rowtype;cr public.change_requests%rowtype;sig uuid;signature_count integer;new_version integer;new_version_id uuid;new_hash text;r jsonb;request_data jsonb;delta jsonb;
begin select*into am from public.contract_amendments where id=p_amendment_id;select*into c from public.contracts where id=am.contract_id;
 if actor is null or am.id is null or auth.jwt()->>'aal'is distinct from'aal2'or p_organization_id not in(c.client_organization_id,c.provider_organization_id)or not private.has_org_role(p_organization_id,case when p_organization_id=c.client_organization_id then array['CLIENT_OWNER','CLIENT_ADMIN']else array['PROVIDER_OWNER','PROVIDER_MANAGER']end,actor)then raise exception'AMENDMENT_SIGN_AAL2_REQUIRED'using errcode='42501';end if;
 if am.status<>'PENDING_SIGNATURE'or p_expected_hash<>am.content_hash then raise exception'STALE_AMENDMENT'using errcode='40001';end if;if jsonb_typeof(p_proof)<>'object'or not(p_proof?&array['method','signed_at','evidence_hash'])or p_proof->>'evidence_hash'!~'^[0-9a-f]{64}$'or p_signer_role!~'^[A-Z][A-Z0-9_]{2,79}$'then raise exception'INVALID_AMENDMENT_SIGNATURE'using errcode='22023';end if;
 new_hash:=private.canonical_request_hash(jsonb_build_object('amendment',am.id,'organization',p_organization_id,'hash',p_expected_hash,'role',p_signer_role,'proof',p_proof));r:=private.begin_contract_command(c.client_organization_id,'contract.amendment.sign.'||am.id::text||'.'||p_organization_id::text,p_idempotency_key,new_hash,actor);if r is not null then return r;end if;
 perform pg_advisory_xact_lock(hashtextextended('contract-amendment:'||am.id::text,0));select*into am from public.contract_amendments where id=am.id for update;if am.status<>'PENDING_SIGNATURE'then raise exception'INVALID_AMENDMENT_SIGN_TRANSITION'using errcode='55000';end if;
 insert into public.contract_amendment_signatures(amendment_id,organization_id,signer_user_id,signer_role,amendment_hash,proof,correlation_id)values(am.id,p_organization_id,actor,p_signer_role,am.content_hash,p_proof,p_correlation_id)returning id into sig;select count(*)into signature_count from public.contract_amendment_signatures where amendment_id=am.id;
 if signature_count=2 then
  select*into c from public.contracts where id=am.contract_id for update;select*into base from public.contract_versions where id=am.base_contract_version_id;select*into cr from public.change_requests where id=am.change_request_id;if base.version<>c.current_version or base.price_minor+am.price_delta_minor<0 then raise exception'STALE_AMENDMENT_BASE_VERSION'using errcode='40001';end if;new_version:=c.current_version+1;request_data:=base.request_snapshot||jsonb_build_object('amendment_id',am.id,'scope_delta',cr.scope_delta,'deadline_delta_days',am.deadline_delta_days);new_hash:=private.canonical_request_hash(jsonb_build_object('contract',c.id,'version',new_version,'request',request_data,'quote',base.quote_snapshot,'clauses',base.clauses,'price_minor',base.price_minor+am.price_delta_minor,'currency',base.currency,'commission',am.commission_rule_snapshot,'amendment_hash',am.content_hash));
  insert into public.contract_versions(contract_id,version,request_snapshot,quote_snapshot,clauses,price_minor,currency,commission_rule_snapshot,content_hash,change_reason,created_by)values(c.id,new_version,request_data,base.quote_snapshot,base.clauses,base.price_minor+am.price_delta_minor,base.currency,am.commission_rule_snapshot,new_hash,'Activated amendment #'||am.amendment_number,actor)returning id into new_version_id;
  insert into public.contract_parties(contract_version_id,organization_id,party_role,legal_snapshot)select new_version_id,organization_id,party_role,legal_snapshot from public.contract_parties where contract_version_id=base.id;
  insert into public.contract_items(contract_version_id,item_key,item_type,label_fr,label_ar,details,sort_order)select new_version_id,i.item_key,i.item_type,i.label_fr,i.label_ar,i.details,i.sort_order from public.contract_items i where i.contract_version_id=base.id and not exists(select 1 from jsonb_array_elements(am.deliverables_delta)d where d->>'item_key'=i.item_key and d->>'operation'in('REMOVE','REPLACE'));
  for delta in select*from jsonb_array_elements(am.deliverables_delta)loop if delta->>'operation'in('ADD','REPLACE')then if delta->>'item_key'!~'^[A-Z][A-Z0-9_-]{1,79}$'or delta->>'item_type'not in('DELIVERABLE','EXCLUSION','ACCEPTANCE_CRITERION','PAYMENT_TERM','CORRECTION','PENALTY')or length(btrim(coalesce(delta->>'label_fr','')))=0 or length(btrim(coalesce(delta->>'label_ar','')))=0 then raise exception'INVALID_AMENDMENT_DELIVERABLE_DELTA'using errcode='22023';end if;insert into public.contract_items(contract_version_id,item_key,item_type,label_fr,label_ar,details,sort_order)values(new_version_id,delta->>'item_key',delta->>'item_type',delta->>'label_fr',delta->>'label_ar',coalesce(delta->'details','{}'),(delta->>'sort_order')::integer);end if;end loop;
  update public.contract_amendments set status='ACTIVE',activated_contract_version_id=new_version_id,activated_at=clock_timestamp()where id=am.id;update public.change_requests set status='ACCEPTED',decided_at=clock_timestamp()where id=am.change_request_id and status='REQUESTED';update public.contracts set current_version=new_version,status='AMENDED',row_version=row_version+1,updated_at=clock_timestamp()where id=c.id;update public.missions set contract_version_id=new_version_id,row_version=row_version+1,updated_at=clock_timestamp()where contract_id=c.id and status not in('COMPLETED','CANCELLED');
 end if;
 r:=jsonb_build_object('outcome',case when signature_count=2 then'CONTRACT_AMENDMENT_ACTIVATED'else'CONTRACT_AMENDMENT_PARTIALLY_SIGNED'end,'amendment_id',am.id,'contract_id',c.id,'signature_id',sig,'signature_count',signature_count,'contract_version_id',new_version_id,'version',new_version);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(c.client_organization_id,actor,'USER',case when signature_count=2 then'contract.amendment.activated'else'contract.amendment.signed'end,'contract_amendment',am.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(c.client_organization_id,'contract_amendment',am.id::text,case when signature_count=2 then'ContractAmendmentActivatedV1'else'ContractAmendmentPartySignedV1'end,p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(c.client_organization_id,'contract.amendment.sign.'||am.id::text||'.'||p_organization_id::text,p_idempotency_key,r);return r;
end$$;

revoke all on public.contract_amendment_signatures from public,anon,authenticated,service_role;grant select on public.contract_amendment_signatures to authenticated;
revoke all on function private.guard_contract_amendment_lifecycle(),public.submit_contract_amendment_for_signature(uuid,text,text,uuid),public.sign_and_activate_contract_amendment(uuid,uuid,text,text,jsonb,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.submit_contract_amendment_for_signature(uuid,text,text,uuid),public.sign_and_activate_contract_amendment(uuid,uuid,text,text,jsonb,text,uuid)to authenticated;
