-- V4.1 P1: technology dependency registry, continuity evidence, secure exports and observable idempotent jobs.

create function private.v41_json_has_sensitive_keys(p_value jsonb) returns boolean
language sql immutable set search_path=pg_catalog as $$
 select case jsonb_typeof(p_value)
  when 'object' then exists(select 1 from jsonb_each(p_value)e where lower(e.key)=any(array['secret','password','token','credential','api_key','email','phone','prompt'])or private.v41_json_has_sensitive_keys(e.value))
  when 'array' then exists(select 1 from jsonb_array_elements(p_value)e where private.v41_json_has_sensitive_keys(e))
  else false end
$$;
revoke all on function private.v41_json_has_sensitive_keys(jsonb) from public,anon,authenticated,service_role;

create table public.third_party_services(
 id uuid primary key default extensions.gen_random_uuid(),
 service_code text not null check(service_code~'^[A-Z][A-Z0-9_]{2,63}$'),version integer not null check(version>0),
 provider_name text not null check(length(btrim(provider_name))between 2 and 120),service_name text not null check(length(btrim(service_name))between 2 and 160),owner_role_code text not null,
 purpose text not null check(length(btrim(purpose))between 10 and 1000),processed_data_categories text[] not null,processing_regions text[] not null,
 criticality text not null check(criticality in('LOW','MEDIUM','HIGH','CRITICAL')),contract_reference text,renewal_on date,
 cost_minor bigint not null default 0 check(cost_minor>=0),currency_code text not null default'MAD'check(currency_code~'^[A-Z]{3}$'),quota_units bigint check(quota_units is null or quota_units>=0),
 sla_availability_bps integer check(sla_availability_bps between 0 and 10000),sla_response_minutes integer check(sla_response_minutes is null or sla_response_minutes>0),
 dpa_status text not null check(dpa_status in('NOT_REQUIRED','REQUIRED_NOT_COMPLETED','VERIFIED','EXPIRED')),
 security_review_status text not null check(security_review_status in('REQUIRED_NOT_COMPLETED','ACCEPTED','REJECTED','EXPIRED')),
 secret_names text[] not null default'{}'check(secret_names<@array['SUPABASE_SERVICE_ROLE_KEY','VERCEL_TOKEN','RAILWAY_TOKEN','OPENAI_API_KEY','RESEND_API_KEY']::text[]),
 exit_plan text not null check(length(btrim(exit_plan))between 20 and 4000),alternative_provider text not null check(length(btrim(alternative_provider))between 2 and 200),
 status text not null check(status in('ACTIVE','SUSPENDED','RETIRED')),effective_from timestamptz not null,effective_to timestamptz,
 content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),created_by uuid references auth.users(id),correlation_id uuid not null,created_at timestamptz not null default clock_timestamp(),
 unique(service_code,version),check(cardinality(processed_data_categories)>0 and cardinality(processing_regions)>0),check(effective_to is null or effective_to>effective_from)
);

create table public.third_party_service_alerts(
 id uuid primary key default extensions.gen_random_uuid(),third_party_service_id uuid not null references public.third_party_services(id)on delete restrict,
 alert_type text not null check(alert_type in('RENEWAL','COST_INCREASE','QUOTA','OUTAGE','CERTIFICATE_EXPIRY','TOKEN_EXPIRY','NO_ALTERNATIVE')),
 severity text not null check(severity in('INFO','WARNING','HIGH','CRITICAL')),status text not null default'OPEN'check(status in('OPEN','ACKNOWLEDGED','RESOLVED')),
 redacted_details jsonb not null default'{}'check(jsonb_typeof(redacted_details)='object'and not private.v41_json_has_sensitive_keys(redacted_details)),
 detected_at timestamptz not null default clock_timestamp(),resolved_at timestamptz,correlation_id uuid not null,check((status='RESOLVED')=(resolved_at is not null))
);
create index third_party_service_alerts_open_idx on public.third_party_service_alerts(severity,detected_at,id)where status<>'RESOLVED';

create table public.continuity_service_objectives(
 id uuid primary key default extensions.gen_random_uuid(),third_party_service_id uuid not null references public.third_party_services(id)on delete restrict,version integer not null check(version>0),
 rpo_minutes integer not null,rto_minutes integer not null,db_backup_required boolean not null,storage_backup_required boolean not null,config_backup_required boolean not null,
 degradation_mode text not null check(degradation_mode in('READ_ONLY','QUEUE_AND_RETRY','FEATURE_DISABLED','MANUAL_FALLBACK')),
 runbook_path text not null check(runbook_path like'docs/runbooks/%'),status text not null check(status in('ACTIVE','RETIRED')),
 content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),effective_from timestamptz not null,created_by uuid references auth.users(id),correlation_id uuid not null,
 unique(third_party_service_id,version),check(rpo_minutes>0 and rto_minutes>0 and rto_minutes>=rpo_minutes)
);

create table public.restore_test_evidence(
 id uuid primary key default extensions.gen_random_uuid(),continuity_objective_id uuid not null references public.continuity_service_objectives(id)on delete restrict,
 status text not null check(status in('PLANNED','RUNNING','PASSED','FAILED','REQUIRED_NOT_COMPLETED')),executed_at timestamptz,
 source_backup_hash text check(source_backup_hash is null or source_backup_hash~'^[0-9a-f]{64}$'),restored_target_hash text check(restored_target_hash is null or restored_target_hash~'^[0-9a-f]{64}$'),
 evidence_hash text check(evidence_hash is null or evidence_hash~'^[0-9a-f]{64}$'),result_summary text not null check(length(btrim(result_summary))between 10 and 2000),
 recorded_by uuid references auth.users(id),correlation_id uuid not null,recorded_at timestamptz not null default clock_timestamp(),
 check((status in('PASSED','FAILED'))=(executed_at is not null and evidence_hash is not null and source_backup_hash is not null and restored_target_hash is not null)),
 check(executed_at is null or executed_at<=recorded_at)
);

create table public.security_control_evidence(
 id uuid primary key default extensions.gen_random_uuid(),control_code text not null check(control_code in('MFA','SESSION_REVOCATION','SECRET_ROTATION','SBOM','SAST','SECRET_SCAN','RLS_TEST','CSP','SSRF','ANTIVIRUS','ENCRYPTION','TAMPER_EVIDENCE','RESTORE_TEST')),
 environment text not null check(environment in('DEVELOPMENT','STAGING','PRODUCTION')),status text not null check(status in('PASSED','FAILED','ACCEPTED_RISK','REQUIRED_NOT_COMPLETED')),
 artifact_hash text check(artifact_hash is null or artifact_hash~'^[0-9a-f]{64}$'),tool_name text,tool_version text,performed_at timestamptz,
 expires_at timestamptz,summary text not null check(length(btrim(summary))between 10 and 2000),recorded_by uuid references auth.users(id),correlation_id uuid not null,recorded_at timestamptz not null default clock_timestamp(),
 check((status in('PASSED','FAILED'))=(artifact_hash is not null and performed_at is not null)),check(expires_at is null or performed_at is not null and expires_at>performed_at)
);

create table public.security_incidents(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid references public.organizations(id)on delete restrict,
 incident_code text not null unique check(incident_code~'^[A-Z0-9_-]{6,64}$'),severity text not null check(severity in('LOW','MEDIUM','HIGH','CRITICAL')),
 category text not null check(category in('RIB_FRAUD','ADMIN_TAKEOVER','WEBHOOK_REPLAY','PROMPT_INJECTION','MASS_EXPORT','PRIVILEGE_DRIFT','MALWARE','DATA_EXPOSURE','OTHER')),
 status text not null check(status in('OPEN','CONTAINED','ERADICATED','RECOVERED','CLOSED')),redacted_summary jsonb not null check(jsonb_typeof(redacted_summary)='object'and not private.v41_json_has_sensitive_keys(redacted_summary)),
 detected_at timestamptz not null,contained_at timestamptz,closed_at timestamptz,owner_role_code text not null,correlation_id uuid not null,created_at timestamptz not null default clock_timestamp(),
 check(contained_at is null or contained_at>=detected_at),check(closed_at is null or contained_at is not null and closed_at>=contained_at)
);

create table public.organization_exit_requests(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,
 status text not null default'REQUESTED'check(status in('REQUESTED','IDENTITY_VERIFIED','LEGAL_REVIEW','EXPORT_READY','SESSIONS_REVOKED','ARCHIVED','PURGED','REJECTED','LEGAL_HOLD')),
 scope_snapshot jsonb not null check(jsonb_typeof(scope_snapshot)='object'),legal_hold boolean not null default false,retention_policy_reference text not null,
 requested_by uuid not null references auth.users(id),requested_at timestamptz not null default clock_timestamp(),approved_by uuid references auth.users(id),approved_at timestamptz,completed_at timestamptz,correlation_id uuid not null,
 check(not legal_hold or status='LEGAL_HOLD'),check(approved_by is null or approved_by<>requested_by)
);
create index organization_exit_requests_org_idx on public.organization_exit_requests(organization_id,requested_at desc);

create table public.organization_export_artifacts(
 id uuid primary key default extensions.gen_random_uuid(),exit_request_id uuid not null references public.organization_exit_requests(id)on delete restrict,organization_id uuid not null references public.organizations(id)on delete restrict,
 artifact_kind text not null check(artifact_kind in('ORGANIZATION_DATA','CONTRACTS','INVOICES','EVIDENCE','CONFIGURATION')),
 storage_reference text not null check(length(storage_reference)between 3 and 500 and storage_reference!~'\.\.'),sha256 text not null check(sha256~'^[0-9a-f]{64}$'),size_bytes bigint not null check(size_bytes>=0),
 retention_until timestamptz not null,created_by uuid references auth.users(id),created_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,unique(exit_request_id,artifact_kind)
);

create table public.session_revocation_batches(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,exit_request_id uuid references public.organization_exit_requests(id)on delete restrict,
 reason text not null check(length(btrim(reason))between 10 and 500),status text not null check(status in('REQUESTED','RUNNING','COMPLETED','FAILED','REQUIRED_NOT_COMPLETED')),
 requested_by uuid references auth.users(id),requested_at timestamptz not null default clock_timestamp(),executed_at timestamptz,evidence_hash text check(evidence_hash is null or evidence_hash~'^[0-9a-f]{64}$'),correlation_id uuid not null,
 check((status='COMPLETED')=(executed_at is not null and evidence_hash is not null))
);

create table public.operational_jobs(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid references public.organizations(id)on delete restrict,
 job_type text not null check(job_type~'^[A-Z][A-Z0-9_.]{2,79}$'),provider_code text,request_id uuid not null,event_id text,
 status text not null default'READY'check(status in('READY','RUNNING','RETRY_WAIT','SUCCEEDED','DEAD_LETTER','CANCELLED')),
 redacted_payload jsonb not null default'{}'check(jsonb_typeof(redacted_payload)='object'and not private.v41_json_has_sensitive_keys(redacted_payload)),request_hash text not null check(request_hash~'^[0-9a-f]{64}$'),
 attempt_count integer not null default 0,max_attempts integer not null default 5,next_attempt_at timestamptz not null default clock_timestamp(),last_error_code text,
 reprocesses_job_id uuid unique references public.operational_jobs(id)on delete restrict,created_at timestamptz not null default clock_timestamp(),completed_at timestamptz,correlation_id uuid not null,
 unique(job_type,request_id),check(attempt_count>=0 and max_attempts between 1 and 20 and attempt_count<=max_attempts),check((status='SUCCEEDED')=(completed_at is not null))
);
create index operational_jobs_dispatch_idx on public.operational_jobs(next_attempt_at,id)where status in('READY','RETRY_WAIT');

create table public.operational_job_attempts(
 id bigint generated always as identity primary key,job_id uuid not null references public.operational_jobs(id)on delete restrict,attempt_number integer not null check(attempt_number>0),
 outcome text not null check(outcome in('SUCCEEDED','RETRYABLE_FAILURE','TERMINAL_FAILURE')),error_code text check(error_code is null or error_code~'^[A-Z0-9_.:-]{1,120}$'),latency_ms integer check(latency_ms is null or latency_ms>=0),
 provider_message_id_hash text check(provider_message_id_hash is null or provider_message_id_hash~'^[0-9a-f]{64}$'),idempotency_key text not null check(length(idempotency_key)between 8 and 200),request_hash text not null check(request_hash~'^[0-9a-f]{64}$'),job_status_after text not null check(job_status_after in('RETRY_WAIT','SUCCEEDED','DEAD_LETTER')),
 started_at timestamptz not null,finished_at timestamptz not null,correlation_id uuid not null,unique(job_id,attempt_number),unique(job_id,idempotency_key),check(finished_at>=started_at)
);
create unique index operational_job_attempt_provider_event_uidx on public.operational_job_attempts(provider_message_id_hash)where provider_message_id_hash is not null;

create table public.dead_letter_reprocess_requests(
 id uuid primary key default extensions.gen_random_uuid(),dead_letter_job_id uuid not null references public.operational_jobs(id)on delete restrict,
 status text not null default'PENDING_APPROVAL'check(status in('PENDING_APPROVAL','APPROVED','REJECTED','EXECUTED')),
 reason text not null check(length(btrim(reason))between 10 and 1000),requested_by uuid not null references auth.users(id),requested_at timestamptz not null default clock_timestamp(),
 decided_by uuid references auth.users(id),decided_at timestamptz,decision_reason text,replacement_job_id uuid unique references public.operational_jobs(id)on delete restrict,correlation_id uuid not null,
 unique(dead_letter_job_id),check(decided_by is null or decided_by<>requested_by),check((status='PENDING_APPROVAL')=(decided_by is null))
);

create trigger third_party_service_history_immutable before update or delete on public.third_party_services for each row execute function private.prevent_update_delete();
create trigger third_party_alert_history_immutable before update or delete on public.third_party_service_alerts for each row execute function private.prevent_update_delete();
create trigger continuity_objective_history_immutable before update or delete on public.continuity_service_objectives for each row execute function private.prevent_update_delete();
create trigger restore_evidence_immutable before update or delete on public.restore_test_evidence for each row execute function private.prevent_update_delete();
create trigger security_control_evidence_immutable before update or delete on public.security_control_evidence for each row execute function private.prevent_update_delete();
create trigger export_artifact_immutable before update or delete on public.organization_export_artifacts for each row execute function private.prevent_update_delete();
create trigger job_attempt_history_immutable before update or delete on public.operational_job_attempts for each row execute function private.prevent_update_delete();

alter table public.third_party_services enable row level security;alter table public.third_party_service_alerts enable row level security;alter table public.continuity_service_objectives enable row level security;alter table public.restore_test_evidence enable row level security;alter table public.security_control_evidence enable row level security;alter table public.security_incidents enable row level security;alter table public.organization_exit_requests enable row level security;alter table public.organization_export_artifacts enable row level security;alter table public.session_revocation_batches enable row level security;alter table public.operational_jobs enable row level security;alter table public.operational_job_attempts enable row level security;alter table public.dead_letter_reprocess_requests enable row level security;
revoke all on public.third_party_services,public.third_party_service_alerts,public.continuity_service_objectives,public.restore_test_evidence,public.security_control_evidence,public.security_incidents,public.organization_exit_requests,public.organization_export_artifacts,public.session_revocation_batches,public.operational_jobs,public.operational_job_attempts,public.dead_letter_reprocess_requests from anon,authenticated,service_role;
grant select on public.third_party_services,public.third_party_service_alerts,public.continuity_service_objectives,public.restore_test_evidence,public.security_control_evidence,public.security_incidents,public.organization_exit_requests,public.organization_export_artifacts,public.session_revocation_batches,public.operational_jobs,public.operational_job_attempts,public.dead_letter_reprocess_requests to authenticated;

create policy third_party_services_read on public.third_party_services for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy third_party_service_alerts_read on public.third_party_service_alerts for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy continuity_service_objectives_read on public.continuity_service_objectives for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy restore_test_evidence_read on public.restore_test_evidence for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy security_control_evidence_read on public.security_control_evidence for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy security_incidents_read on public.security_incidents for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy organization_exit_requests_read on public.organization_exit_requests for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','PROVIDER_OWNER','PROVIDER_MANAGER','FRANCHISE_OWNER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy organization_export_artifacts_read on public.organization_export_artifacts for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','PROVIDER_OWNER','PROVIDER_MANAGER','FRANCHISE_OWNER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy session_revocation_batches_read on public.session_revocation_batches for select to authenticated using(private.has_org_role(organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','PROVIDER_OWNER','PROVIDER_MANAGER','FRANCHISE_OWNER'])or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy operational_jobs_read on public.operational_jobs for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy operational_job_attempts_read on public.operational_job_attempts for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));
create policy dead_letter_reprocess_requests_read on public.dead_letter_reprocess_requests for select to authenticated using(private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','READ_ONLY_AUDITOR']));

create function public.register_third_party_service_version(p_service_code text,p_provider_name text,p_service_name text,p_owner_role_code text,p_purpose text,p_data_categories text[],p_regions text[],p_criticality text,p_contract_reference text,p_renewal_on date,p_cost_minor bigint,p_currency_code text,p_quota_units bigint,p_sla_availability_bps integer,p_sla_response_minutes integer,p_dpa_status text,p_security_review_status text,p_secret_names text[],p_exit_plan text,p_alternative_provider text,p_effective_from timestamptz,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;v integer;i uuid;begin
 if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a)then raise exception'THIRD_PARTY_REGISTRY_AAL2_REQUIRED'using errcode='42501';end if;
 h:=private.canonical_request_hash(jsonb_build_object('service_code',p_service_code,'provider',p_provider_name,'name',p_service_name,'owner',p_owner_role_code,'purpose',p_purpose,'data',p_data_categories,'regions',p_regions,'criticality',p_criticality,'contract',p_contract_reference,'renewal',p_renewal_on,'cost_minor',p_cost_minor,'currency',p_currency_code,'quota',p_quota_units,'availability',p_sla_availability_bps,'response',p_sla_response_minutes,'dpa',p_dpa_status,'security',p_security_review_status,'secret_names',p_secret_names,'exit',p_exit_plan,'alternative',p_alternative_provider,'effective',p_effective_from));r:=private.begin_admin_command('v41.third_party.register.'||p_service_code,p_idempotency_key,h,a);if r is not null then return r;end if;
 perform pg_advisory_xact_lock(hashtextextended('v41-third-party:'||p_service_code,0));select coalesce(max(version),0)+1 into v from public.third_party_services where service_code=p_service_code;
 insert into public.third_party_services(service_code,version,provider_name,service_name,owner_role_code,purpose,processed_data_categories,processing_regions,criticality,contract_reference,renewal_on,cost_minor,currency_code,quota_units,sla_availability_bps,sla_response_minutes,dpa_status,security_review_status,secret_names,exit_plan,alternative_provider,status,effective_from,content_hash,created_by,correlation_id)values(p_service_code,v,p_provider_name,p_service_name,p_owner_role_code,p_purpose,p_data_categories,p_regions,p_criticality,p_contract_reference,p_renewal_on,p_cost_minor,p_currency_code,p_quota_units,p_sla_availability_bps,p_sla_response_minutes,p_dpa_status,p_security_review_status,p_secret_names,p_exit_plan,p_alternative_provider,'ACTIVE',p_effective_from,h,a,p_correlation_id)returning id into i;
 r:=jsonb_build_object('outcome','THIRD_PARTY_SERVICE_VERSION_REGISTERED','service_id',i,'version',v,'content_hash',h);insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(a,'USER','resilience.third_party.version_registered','third_party_service',i::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values('third_party_service',i::text,'ThirdPartyServiceVersionRegisteredV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('v41.third_party.register.'||p_service_code,p_idempotency_key,a,r);return r;end$$;

create function public.record_restore_test_result(p_continuity_objective_id uuid,p_status text,p_executed_at timestamptz,p_source_backup_hash text,p_restored_target_hash text,p_evidence_hash text,p_result_summary text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;i uuid;begin if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER'],a)then raise exception'RESTORE_EVIDENCE_AAL2_REQUIRED'using errcode='42501';end if;
 if p_status in('PASSED','FAILED')and(p_executed_at is null or p_source_backup_hash is null or p_restored_target_hash is null or p_evidence_hash is null)then raise exception'RESTORE_EXECUTION_EVIDENCE_REQUIRED'using errcode='22023';end if;if p_status='REQUIRED_NOT_COMPLETED'and(p_executed_at is not null or p_evidence_hash is not null)then raise exception'RESTORE_NOT_COMPLETED_CANNOT_CLAIM_EVIDENCE'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('objective',p_continuity_objective_id,'status',p_status,'executed_at',p_executed_at,'source_hash',p_source_backup_hash,'target_hash',p_restored_target_hash,'evidence_hash',p_evidence_hash,'summary',p_result_summary));r:=private.begin_admin_command('v41.restore.record.'||p_continuity_objective_id::text,p_idempotency_key,h,a);if r is not null then return r;end if;
 insert into public.restore_test_evidence(continuity_objective_id,status,executed_at,source_backup_hash,restored_target_hash,evidence_hash,result_summary,recorded_by,correlation_id)values(p_continuity_objective_id,p_status,p_executed_at,p_source_backup_hash,p_restored_target_hash,p_evidence_hash,p_result_summary,a,p_correlation_id)returning id into i;r:=jsonb_build_object('outcome','RESTORE_TEST_EVIDENCE_RECORDED','evidence_id',i,'status',p_status);insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(a,'USER','resilience.restore_test.recorded','restore_test_evidence',i::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values('restore_test_evidence',i::text,'RestoreTestEvidenceRecordedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('v41.restore.record.'||p_continuity_objective_id::text,p_idempotency_key,a,r);return r;end$$;

create function public.request_organization_export(p_organization_id uuid,p_scope_snapshot jsonb,p_retention_policy_reference text,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;i uuid;begin if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not(private.has_org_role(p_organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','PROVIDER_OWNER','PROVIDER_MANAGER','FRANCHISE_OWNER'],a)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER'],a))then raise exception'ORGANIZATION_EXPORT_STEP_UP_REQUIRED'using errcode='42501';end if;if jsonb_typeof(p_scope_snapshot)<>'object'or private.v41_json_has_sensitive_keys(p_scope_snapshot)or length(btrim(coalesce(p_reason,'')))not between 10 and 1000 then raise exception'INVALID_ORGANIZATION_EXPORT_REQUEST'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('organization',p_organization_id,'scope',p_scope_snapshot,'retention',p_retention_policy_reference,'reason',p_reason));r:=private.begin_contract_command(p_organization_id,'v41.organization.export',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.organization_exit_requests(organization_id,status,scope_snapshot,retention_policy_reference,requested_by,correlation_id)values(p_organization_id,'REQUESTED',p_scope_snapshot,p_retention_policy_reference,a,p_correlation_id)returning id into i;r:=jsonb_build_object('outcome','ORGANIZATION_EXPORT_REQUESTED','exit_request_id',i);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','privacy.organization_export.requested','organization_exit_request',i::text,p_correlation_id,jsonb_build_object('reason',p_reason),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'organization_exit_request',i::text,'OrganizationExportRequestedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'v41.organization.export',p_idempotency_key,r);return r;end$$;

create function public.request_dead_letter_reprocess(p_dead_letter_job_id uuid,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();j public.operational_jobs%rowtype;h text;r jsonb;i uuid;begin if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a)then raise exception'DLQ_REPROCESS_AAL2_REQUIRED'using errcode='42501';end if;select*into j from public.operational_jobs where id=p_dead_letter_job_id and status='DEAD_LETTER';if not found then raise exception'DEAD_LETTER_JOB_REQUIRED'using errcode='P0002';end if;if length(btrim(coalesce(p_reason,'')))not between 10 and 1000 then raise exception'DLQ_REPROCESS_REASON_REQUIRED'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('job',j.id,'reason',p_reason));r:=private.begin_admin_command('v41.dlq.reprocess.request.'||j.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.dead_letter_reprocess_requests(dead_letter_job_id,reason,requested_by,correlation_id)values(j.id,p_reason,a,p_correlation_id)returning id into i;r:=jsonb_build_object('outcome','DLQ_REPROCESS_APPROVAL_REQUIRED','request_id',i);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(j.organization_id,a,'USER','operations.dlq_reprocess.requested','dead_letter_reprocess_request',i::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(j.organization_id,'dead_letter_reprocess_request',i::text,'DeadLetterReprocessApprovalRequiredV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('v41.dlq.reprocess.request.'||j.id::text,p_idempotency_key,a,r);return r;end$$;

create function public.decide_dead_letter_reprocess(p_request_id uuid,p_decision text,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();x public.dead_letter_reprocess_requests%rowtype;j public.operational_jobs%rowtype;h text;jh text;r jsonb;n uuid;q uuid;begin if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a)then raise exception'DLQ_REPROCESS_DECISION_AAL2_REQUIRED'using errcode='42501';end if;if p_decision not in('APPROVE','REJECT')or length(btrim(coalesce(p_reason,'')))not between 10 and 1000 then raise exception'INVALID_DLQ_REPROCESS_DECISION'using errcode='22023';end if;h:=private.canonical_request_hash(jsonb_build_object('request',p_request_id,'decision',p_decision,'reason',p_reason));r:=private.begin_admin_command('v41.dlq.reprocess.decide.'||p_request_id::text,p_idempotency_key,h,a);if r is not null then return r;end if;
 select*into x from public.dead_letter_reprocess_requests where id=p_request_id for update;if not found or x.status<>'PENDING_APPROVAL'then raise exception'DLQ_REPROCESS_REQUEST_NOT_PENDING'using errcode='55000';end if;if x.requested_by=a then raise exception'DLQ_REPROCESS_DUAL_CONTROL_REQUIRED'using errcode='42501';end if;select*into j from public.operational_jobs where id=x.dead_letter_job_id;
 if p_decision='REJECT'then update public.dead_letter_reprocess_requests set status='REJECTED',decided_by=a,decided_at=clock_timestamp(),decision_reason=p_reason where id=x.id;r:=jsonb_build_object('outcome','DLQ_REPROCESS_REJECTED','request_id',x.id);else q:=extensions.gen_random_uuid();jh:=private.canonical_request_hash(jsonb_build_object('organization_id',j.organization_id,'job_type',j.job_type,'provider_code',j.provider_code,'request_id',q,'event_id',j.event_id,'payload',j.redacted_payload,'max_attempts',j.max_attempts));begin insert into public.operational_jobs(organization_id,job_type,provider_code,request_id,event_id,status,redacted_payload,request_hash,max_attempts,reprocesses_job_id,correlation_id)values(j.organization_id,j.job_type,j.provider_code,q,j.event_id,'READY',j.redacted_payload,jh,j.max_attempts,j.id,p_correlation_id)returning id into n;exception when unique_violation then raise exception'REPROCESS_ALREADY_ENQUEUED'using errcode='23505';end;update public.dead_letter_reprocess_requests set status='EXECUTED',decided_by=a,decided_at=clock_timestamp(),decision_reason=p_reason,replacement_job_id=n where id=x.id;r:=jsonb_build_object('outcome','DLQ_REPROCESS_ENQUEUED','request_id',x.id,'replacement_job_id',n);end if;
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(j.organization_id,a,'USER','operations.dlq_reprocess.decided','dead_letter_reprocess_request',x.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(j.organization_id,'dead_letter_reprocess_request',x.id::text,'DeadLetterReprocessDecidedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('v41.dlq.reprocess.decide.'||x.id::text,p_idempotency_key,a,r);return r;end$$;

revoke all on function public.register_third_party_service_version(text,text,text,text,text,text[],text[],text,text,date,bigint,text,bigint,integer,integer,text,text,text[],text,text,timestamptz,text,uuid),public.record_restore_test_result(uuid,text,timestamptz,text,text,text,text,text,uuid),public.request_organization_export(uuid,jsonb,text,text,text,uuid),public.request_dead_letter_reprocess(uuid,text,text,uuid),public.decide_dead_letter_reprocess(uuid,text,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.register_third_party_service_version(text,text,text,text,text,text[],text[],text,text,date,bigint,text,bigint,integer,integer,text,text,text[],text,text,timestamptz,text,uuid),public.record_restore_test_result(uuid,text,timestamptz,text,text,text,text,text,uuid),public.request_organization_export(uuid,jsonb,text,text,text,uuid),public.request_dead_letter_reprocess(uuid,text,text,uuid),public.decide_dead_letter_reprocess(uuid,text,text,text,uuid)to authenticated;

with seed(service_code,provider_name,service_name,owner_role_code,purpose,data_categories,regions,criticality,secret_names,exit_plan,alternative_provider)as(values
 ('SUPABASE','Supabase','Database, authentication and storage','PLATFORM_OWNER','Operate tenant data, identity and durable application storage.',array['IDENTITY','BUSINESS_DATA','DOCUMENTS'],array['CONFIGURED_REGION'],'CRITICAL',array['SUPABASE_SERVICE_ROLE_KEY'],'Export PostgreSQL and storage, validate restore, then migrate to managed PostgreSQL and object storage.','Managed PostgreSQL plus S3-compatible storage'),
 ('VERCEL','Vercel','Web hosting and edge delivery','PLATFORM_OWNER','Serve the Matricia web application and public content.',array['TECHNICAL_LOGS','PUBLIC_CONTENT'],array['CONFIGURED_REGION'],'HIGH',array['VERCEL_TOKEN'],'Build portable web artifacts, preserve DNS configuration and redeploy to an alternative edge platform.','Cloudflare Pages or managed containers'),
 ('RAILWAY','Railway','Worker hosting','PLATFORM_OWNER','Execute asynchronous jobs and provider integrations.',array['JOB_METADATA','TECHNICAL_LOGS'],array['CONFIGURED_REGION'],'HIGH',array['RAILWAY_TOKEN'],'Export service configuration names, containerize workers and redeploy with queues drained or safely replayed.','Managed Kubernetes or container service'),
 ('OPENAI','OpenAI','Assisted intelligence provider','AI_OWNER','Provide explicitly authorized assisted intelligence features.',array['MINIMIZED_BUSINESS_CONTEXT'],array['PROVIDER_CONFIGURED_REGION'],'HIGH',array['OPENAI_API_KEY'],'Disable AI features safely, retain deterministic business workflows and route approved requests to another model provider.','Alternative approved model provider'),
 ('RESEND','Resend','Transactional email delivery','COMMUNICATIONS_OWNER','Deliver transactional notifications without treating ordinary email as qualified proof.',array['CONTACT_DATA','MESSAGE_METADATA'],array['PROVIDER_CONFIGURED_REGION'],'HIGH',array['RESEND_API_KEY'],'Queue outbound notifications, export templates and provider IDs, then switch DNS and delivery adapter.','Alternative transactional email provider'),
 ('PAYMENTS','CMI / PayPal','Matricia own-payment processing','FINANCE_OWNER','Collect Matricia own revenues and reconcile signed provider events.',array['PAYMENT_METADATA','CONTACT_DATA'],array['PROVIDER_CONFIGURED_REGION'],'CRITICAL',array[]::text[],'Disable new collections, reconcile all provider events and move tokenized customer instructions through an approved migration.','Alternative PCI-compliant payment provider'),
 ('SIGNATURE','Configured signature provider','Electronic signature delivery','LEGAL_OWNER','Execute electronic signature envelopes with immutable evidence.',array['IDENTITY','CONTRACTS','SIGNATURE_EVIDENCE'],array['PROVIDER_CONFIGURED_REGION'],'CRITICAL',array[]::text[],'Stop new envelopes, preserve evidence packages and configure another SignatureProvider adapter for new versions.','Alternative Morocco-compatible signature provider'),
 ('SOCIAL','Configured social networks','Authorized social publication','MARKETING_OWNER','Publish approved content under explicit brand authorization and consent.',array['PUBLIC_CONTENT','OAUTH_METADATA'],array['PROVIDER_CONFIGURED_REGION'],'MEDIUM',array[]::text[],'Revoke application grants, export publication evidence and disable each provider through the global kill switch.','Manual authorized publication'),
 ('SOURCE_CONTROL','GitHub','Source control and security evidence','SECURITY_OWNER','Preserve code history and attach versioned build and security evidence.',array['SOURCE_CODE','TECHNICAL_IDENTIFIERS'],array['PROVIDER_CONFIGURED_REGION'],'HIGH',array[]::text[],'Mirror all refs and release evidence to a second encrypted source-control repository before cutover.','Alternative managed Git provider')
)insert into public.third_party_services(service_code,version,provider_name,service_name,owner_role_code,purpose,processed_data_categories,processing_regions,criticality,cost_minor,currency_code,dpa_status,security_review_status,secret_names,exit_plan,alternative_provider,status,effective_from,content_hash,correlation_id)
select service_code,1,provider_name,service_name,owner_role_code,purpose,data_categories,regions,criticality,0,'MAD','REQUIRED_NOT_COMPLETED','REQUIRED_NOT_COMPLETED',secret_names,exit_plan,alternative_provider,'ACTIVE',clock_timestamp(),encode(extensions.digest(convert_to(service_code||':V1','UTF8'),'sha256'),'hex'),extensions.gen_random_uuid()from seed;

insert into public.continuity_service_objectives(third_party_service_id,version,rpo_minutes,rto_minutes,db_backup_required,storage_backup_required,config_backup_required,degradation_mode,runbook_path,status,content_hash,effective_from,correlation_id)
select id,1,case when criticality='CRITICAL'then 60 else 240 end,case when criticality='CRITICAL'then 240 else 480 end,service_code='SUPABASE',service_code in('SUPABASE','SIGNATURE'),true,case when service_code in('OPENAI','SOCIAL')then'FEATURE_DISABLED'when service_code in('RESEND','SIGNATURE')then'QUEUE_AND_RETRY'else'MANUAL_FALLBACK'end,'docs/runbooks/V4_1_CONTINUITY_AND_RESTORE.md','ACTIVE',encode(extensions.digest(convert_to(service_code||':BCP:V1','UTF8'),'sha256'),'hex'),clock_timestamp(),extensions.gen_random_uuid()from public.third_party_services where version=1;

insert into public.restore_test_evidence(continuity_objective_id,status,result_summary,correlation_id)
select id,'REQUIRED_NOT_COMPLETED','External restore execution and independently retained evidence are required before this objective can pass.',extensions.gen_random_uuid()from public.continuity_service_objectives where version=1;

insert into public.security_control_evidence(control_code,environment,status,summary,correlation_id)select c,'STAGING','REQUIRED_NOT_COMPLETED','Execution evidence must be attached by the independent security or release pipeline before production.',extensions.gen_random_uuid()from unnest(array['MFA','SECRET_ROTATION','SBOM','SAST','SECRET_SCAN','RLS_TEST','CSP','SSRF','ANTIVIRUS','ENCRYPTION','TAMPER_EVIDENCE','RESTORE_TEST'])c;

create function public.enqueue_operational_job(p_organization_id uuid,p_job_type text,p_provider_code text,p_request_id uuid,p_event_id text,p_redacted_payload jsonb,p_max_attempts integer,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare j public.operational_jobs%rowtype;h text;r jsonb;begin if auth.role()is distinct from'service_role'then raise exception'JOB_ENQUEUE_SERVICE_ROLE_REQUIRED'using errcode='42501';end if;if jsonb_typeof(p_redacted_payload)<>'object'or private.v41_json_has_sensitive_keys(p_redacted_payload)then raise exception'SENSITIVE_JOB_PAYLOAD_REJECTED'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('organization_id',p_organization_id,'job_type',p_job_type,'provider_code',p_provider_code,'request_id',p_request_id,'event_id',p_event_id,'payload',p_redacted_payload,'max_attempts',p_max_attempts));perform pg_advisory_xact_lock(hashtextextended('v41-job:'||p_job_type||':'||p_request_id::text,0));select*into j from public.operational_jobs where job_type=p_job_type and request_id=p_request_id;if found then if j.organization_id is distinct from p_organization_id or j.request_hash<>h then raise exception'JOB_IDEMPOTENCY_PAYLOAD_MISMATCH'using errcode='22000';end if;return jsonb_build_object('outcome','OPERATIONAL_JOB_ALREADY_ENQUEUED','job_id',j.id,'status',j.status);end if;
 insert into public.operational_jobs(organization_id,job_type,provider_code,request_id,event_id,redacted_payload,request_hash,max_attempts,correlation_id)values(p_organization_id,p_job_type,p_provider_code,p_request_id,p_event_id,p_redacted_payload,h,p_max_attempts,p_correlation_id)returning*into j;r:=jsonb_build_object('outcome','OPERATIONAL_JOB_ENQUEUED','job_id',j.id,'status',j.status);insert into public.audit_events(organization_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,'SERVICE','operations.job.enqueued','operational_job',j.id::text,p_correlation_id,jsonb_build_object('job_type',p_job_type,'provider_code',p_provider_code,'request_hash',h),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'operational_job',j.id::text,'OperationalJobEnqueuedV1',p_correlation_id,r,p_request_id::text);return r;end$$;

create function public.record_operational_job_attempt(p_job_id uuid,p_outcome text,p_error_code text,p_latency_ms integer,p_provider_message_id_hash text,p_started_at timestamptz,p_finished_at timestamptz,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare j public.operational_jobs%rowtype;o public.operational_job_attempts%rowtype;n integer;s text;h text;begin if auth.role()is distinct from'service_role'then raise exception'JOB_ATTEMPT_SERVICE_ROLE_REQUIRED'using errcode='42501';end if;h:=private.canonical_request_hash(jsonb_build_object('job_id',p_job_id,'outcome',p_outcome,'error_code',p_error_code,'latency_ms',p_latency_ms,'provider_event_hash',p_provider_message_id_hash,'started_at',p_started_at,'finished_at',p_finished_at));perform pg_advisory_xact_lock(hashtextextended('v41-job-attempt:'||p_job_id::text||':'||p_idempotency_key,0));select*into o from public.operational_job_attempts where(job_id=p_job_id and idempotency_key=p_idempotency_key)or(p_provider_message_id_hash is not null and provider_message_id_hash=p_provider_message_id_hash)order by id limit 1;if found then if o.job_id<>p_job_id or o.request_hash<>h then raise exception'JOB_ATTEMPT_REPLAY_MISMATCH'using errcode='22000';end if;return jsonb_build_object('outcome','JOB_ATTEMPT_ALREADY_RECORDED','job_id',o.job_id,'attempt_number',o.attempt_number,'status',o.job_status_after);end if;select*into j from public.operational_jobs where id=p_job_id for update;if not found or j.status not in('READY','RUNNING','RETRY_WAIT')then raise exception'JOB_NOT_EXECUTABLE'using errcode='55000';end if;n:=j.attempt_count+1;if n>j.max_attempts then raise exception'JOB_ATTEMPT_LIMIT_EXCEEDED'using errcode='22023';end if;
 s:=case when p_outcome='SUCCEEDED'then'SUCCEEDED'when p_outcome='TERMINAL_FAILURE'or n=j.max_attempts then'DEAD_LETTER'else'RETRY_WAIT'end;update public.operational_jobs set attempt_count=n,status=s,last_error_code=p_error_code,next_attempt_at=case when s='RETRY_WAIT'then clock_timestamp()+make_interval(secs=>least(3600,60*(1<<least(n,5))))else next_attempt_at end,completed_at=case when s='SUCCEEDED'then clock_timestamp()else null end where id=j.id;
 insert into public.operational_job_attempts(job_id,attempt_number,outcome,error_code,latency_ms,provider_message_id_hash,idempotency_key,request_hash,job_status_after,started_at,finished_at,correlation_id)values(j.id,n,p_outcome,p_error_code,p_latency_ms,p_provider_message_id_hash,p_idempotency_key,h,s,p_started_at,p_finished_at,p_correlation_id);
 insert into public.audit_events(organization_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(j.organization_id,'SYSTEM','operations.job.attempt_recorded','operational_job',j.id::text,p_correlation_id,jsonb_build_object('attempt_number',n,'outcome',p_outcome,'status',s,'error_code',p_error_code),repeat('0',64));if s='DEAD_LETTER'then insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(j.organization_id,'operational_job',j.id::text,'OperationalJobDeadLetteredV1',p_correlation_id,jsonb_build_object('job_id',j.id,'attempt_count',n,'error_code',p_error_code),j.request_id::text);end if;return jsonb_build_object('outcome','JOB_ATTEMPT_RECORDED','job_id',j.id,'attempt_number',n,'status',s);end$$;

create function public.advance_organization_exit(p_exit_request_id uuid,p_to_status text,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();x public.organization_exit_requests%rowtype;h text;r jsonb;subject_hash text;begin if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER'],a)then raise exception'ORGANIZATION_EXIT_AAL2_REQUIRED'using errcode='42501';end if;select*into x from public.organization_exit_requests where id=p_exit_request_id for update;if not found then raise exception'ORGANIZATION_EXIT_NOT_FOUND'using errcode='P0002';end if;h:=private.canonical_request_hash(jsonb_build_object('exit_request',p_exit_request_id,'to',p_to_status,'reason',p_reason));r:=private.begin_contract_command(x.organization_id,'v41.organization.exit.advance.'||p_exit_request_id::text,p_idempotency_key,h,a);if r is not null then return r;end if;
 if x.requested_by=a then raise exception'ORGANIZATION_EXIT_DUAL_CONTROL_REQUIRED'using errcode='42501';end if;subject_hash:=x.scope_snapshot->>'subject_reference_hash';if p_to_status='PURGED'and(x.legal_hold or x.status='LEGAL_HOLD'or exists(select 1 from public.privacy_legal_holds l where l.organization_id=x.organization_id and l.status='ACTIVE'and(l.ends_at is null or l.ends_at>clock_timestamp())))then raise exception'LEGAL_HOLD_BLOCKS_PURGE'using errcode='55000';end if;if p_to_status='PURGED'and(coalesce(subject_hash,'')!~'^[0-9a-f]{64}$'or exists(select 1 from public.retention_policies p where p.organization_id=x.organization_id and p.status='ACTIVE'and not exists(select 1 from public.privacy_retention_actions a1 where a1.organization_id=x.organization_id and a1.retention_policy_id=p.id and a1.subject_reference_hash=subject_hash and a1.action_type in('ANONYMIZE','PURGE','LEGAL_ARCHIVE')and a1.status='COMPLETED'))or exists(select 1 from public.organization_export_artifacts e where e.exit_request_id=x.id and e.retention_until>clock_timestamp()))then raise exception'RETENTION_ACTIONS_NOT_COMPLETED'using errcode='55000';end if;if p_to_status='EXPORT_READY'and not exists(select 1 from public.organization_export_artifacts where exit_request_id=x.id)then raise exception'EXPORT_ARTIFACT_EVIDENCE_REQUIRED'using errcode='55000';end if;if p_to_status='SESSIONS_REVOKED'and not exists(select 1 from public.session_revocation_batches where exit_request_id=x.id and status='COMPLETED')then raise exception'SESSION_REVOCATION_EVIDENCE_REQUIRED'using errcode='55000';end if;if not((x.status='REQUESTED'and p_to_status in('IDENTITY_VERIFIED','REJECTED','LEGAL_HOLD'))or(x.status='IDENTITY_VERIFIED'and p_to_status in('LEGAL_REVIEW','LEGAL_HOLD'))or(x.status='LEGAL_REVIEW'and p_to_status in('EXPORT_READY','LEGAL_HOLD'))or(x.status='EXPORT_READY'and p_to_status='SESSIONS_REVOKED')or(x.status='SESSIONS_REVOKED'and p_to_status='ARCHIVED')or(x.status='ARCHIVED'and p_to_status='PURGED'))then raise exception'INVALID_ORGANIZATION_EXIT_TRANSITION'using errcode='23514';end if;
 update public.organization_exit_requests set status=p_to_status,legal_hold=p_to_status='LEGAL_HOLD',approved_by=coalesce(approved_by,a),approved_at=coalesce(approved_at,clock_timestamp()),completed_at=case when p_to_status in('PURGED','REJECTED')then clock_timestamp()else null end where id=x.id;if p_to_status='EXPORT_READY'and not exists(select 1 from public.session_revocation_batches where exit_request_id=x.id)then insert into public.session_revocation_batches(organization_id,exit_request_id,reason,status,requested_by,correlation_id)values(x.organization_id,x.id,'External Auth session and token revocation requires independently retained evidence.','REQUIRED_NOT_COMPLETED',a,p_correlation_id);end if;r:=jsonb_build_object('outcome','ORGANIZATION_EXIT_ADVANCED','exit_request_id',x.id,'status',p_to_status);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(x.organization_id,a,'USER','privacy.organization_exit.advanced','organization_exit_request',x.id::text,p_correlation_id,jsonb_build_object('from_status',x.status,'to_status',p_to_status,'reason',p_reason),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(x.organization_id,'organization_exit_request',x.id::text,'OrganizationExitAdvancedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(x.organization_id,'v41.organization.exit.advance.'||x.id::text,p_idempotency_key,r);return r;end$$;

revoke all on function public.enqueue_operational_job(uuid,text,text,uuid,text,jsonb,integer,uuid),public.record_operational_job_attempt(uuid,text,text,integer,text,timestamptz,timestamptz,text,uuid),public.advance_organization_exit(uuid,text,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.enqueue_operational_job(uuid,text,text,uuid,text,jsonb,integer,uuid),public.record_operational_job_attempt(uuid,text,text,integer,text,timestamptz,timestamptz,text,uuid)to service_role;
grant execute on function public.advance_organization_exit(uuid,text,text,text,uuid)to authenticated;

create function public.record_security_control_result(p_control_code text,p_environment text,p_status text,p_artifact_hash text,p_tool_name text,p_tool_version text,p_performed_at timestamptz,p_expires_at timestamptz,p_summary text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;i uuid;begin if a is null or auth.jwt()->>'aal'is distinct from'aal2'or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER'],a)then raise exception'SECURITY_EVIDENCE_AAL2_REQUIRED'using errcode='42501';end if;if p_status in('PASSED','FAILED')and(p_artifact_hash is null or p_performed_at is null)then raise exception'SECURITY_ARTIFACT_EVIDENCE_REQUIRED'using errcode='22023';end if;if p_status='REQUIRED_NOT_COMPLETED'and(p_artifact_hash is not null or p_performed_at is not null)then raise exception'SECURITY_CONTROL_NOT_COMPLETED_CANNOT_CLAIM_EVIDENCE'using errcode='22023';end if;h:=private.canonical_request_hash(jsonb_build_object('control',p_control_code,'environment',p_environment,'status',p_status,'artifact_hash',p_artifact_hash,'tool',p_tool_name,'tool_version',p_tool_version,'performed_at',p_performed_at,'expires_at',p_expires_at,'summary',p_summary));r:=private.begin_admin_command('v41.security.control.'||p_control_code||'.'||p_environment,p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.security_control_evidence(control_code,environment,status,artifact_hash,tool_name,tool_version,performed_at,expires_at,summary,recorded_by,correlation_id)values(p_control_code,p_environment,p_status,p_artifact_hash,p_tool_name,p_tool_version,p_performed_at,p_expires_at,p_summary,a,p_correlation_id)returning id into i;r:=jsonb_build_object('outcome','SECURITY_CONTROL_EVIDENCE_RECORDED','evidence_id',i,'status',p_status);insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(a,'USER','security.control_evidence.recorded','security_control_evidence',i::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values('security_control_evidence',i::text,'SecurityControlEvidenceRecordedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('v41.security.control.'||p_control_code||'.'||p_environment,p_idempotency_key,a,r);return r;end$$;

create function public.record_organization_export_artifact(p_exit_request_id uuid,p_artifact_kind text,p_storage_reference text,p_sha256 text,p_size_bytes bigint,p_retention_until timestamptz,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare x public.organization_exit_requests%rowtype;e public.organization_export_artifacts%rowtype;i uuid;r jsonb;begin if auth.role()is distinct from'service_role'then raise exception'EXPORT_ARTIFACT_SERVICE_ROLE_REQUIRED'using errcode='42501';end if;select*into x from public.organization_exit_requests where id=p_exit_request_id for share;if not found then raise exception'EXPORT_REQUEST_NOT_FOUND'using errcode='P0002';end if;perform pg_advisory_xact_lock(hashtextextended('v41-export-artifact:'||p_exit_request_id::text||':'||p_artifact_kind,0));select*into e from public.organization_export_artifacts where exit_request_id=x.id and artifact_kind=p_artifact_kind;if found then if e.organization_id<>x.organization_id or e.storage_reference<>p_storage_reference or e.sha256<>p_sha256 or e.size_bytes<>p_size_bytes or e.retention_until<>p_retention_until then raise exception'EXPORT_ARTIFACT_REPLAY_MISMATCH'using errcode='22000';end if;return jsonb_build_object('outcome','ORGANIZATION_EXPORT_ARTIFACT_ALREADY_RECORDED','artifact_id',e.id);end if;if x.status not in('LEGAL_REVIEW','EXPORT_READY')then raise exception'EXPORT_REQUEST_NOT_READY'using errcode='55000';end if;insert into public.organization_export_artifacts(exit_request_id,organization_id,artifact_kind,storage_reference,sha256,size_bytes,retention_until,correlation_id)values(x.id,x.organization_id,p_artifact_kind,p_storage_reference,p_sha256,p_size_bytes,p_retention_until,p_correlation_id)returning id into i;r:=jsonb_build_object('outcome','ORGANIZATION_EXPORT_ARTIFACT_RECORDED','artifact_id',i,'sha256',p_sha256);insert into public.audit_events(organization_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(x.organization_id,'SERVICE','privacy.organization_export.artifact_recorded','organization_export_artifact',i::text,p_correlation_id,jsonb_build_object('artifact_kind',p_artifact_kind,'sha256',p_sha256,'size_bytes',p_size_bytes),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(x.organization_id,'organization_export_artifact',i::text,'OrganizationExportArtifactRecordedV1',p_correlation_id,r,x.id::text||':'||p_artifact_kind);return r;end$$;

create function public.complete_session_revocation_batch(p_batch_id uuid,p_executed_at timestamptz,p_evidence_hash text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare b public.session_revocation_batches%rowtype;begin if auth.role()is distinct from'service_role'then raise exception'SESSION_REVOCATION_SERVICE_ROLE_REQUIRED'using errcode='42501';end if;select*into b from public.session_revocation_batches where id=p_batch_id for update;if not found then raise exception'SESSION_REVOCATION_BATCH_NOT_FOUND'using errcode='P0002';end if;if b.status='COMPLETED'then if b.evidence_hash<>p_evidence_hash then raise exception'SESSION_REVOCATION_EVIDENCE_MISMATCH'using errcode='22000';end if;return jsonb_build_object('outcome','SESSION_REVOCATION_ALREADY_COMPLETED','batch_id',b.id);end if;update public.session_revocation_batches set status='COMPLETED',executed_at=p_executed_at,evidence_hash=p_evidence_hash,correlation_id=p_correlation_id where id=b.id;insert into public.audit_events(organization_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(b.organization_id,'SERVICE','security.sessions.revoked','session_revocation_batch',b.id::text,p_correlation_id,jsonb_build_object('evidence_hash',p_evidence_hash),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(b.organization_id,'session_revocation_batch',b.id::text,'OrganizationSessionsRevokedV1',p_correlation_id,jsonb_build_object('batch_id',b.id,'evidence_hash',p_evidence_hash),b.id::text);return jsonb_build_object('outcome','SESSION_REVOCATION_COMPLETED','batch_id',b.id);end$$;

revoke all on function public.record_security_control_result(text,text,text,text,text,text,timestamptz,timestamptz,text,text,uuid),public.record_organization_export_artifact(uuid,text,text,text,bigint,timestamptz,uuid),public.complete_session_revocation_batch(uuid,timestamptz,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.record_security_control_result(text,text,text,text,text,text,timestamptz,timestamptz,text,text,uuid)to authenticated;
grant execute on function public.record_organization_export_artifact(uuid,text,text,text,bigint,timestamptz,uuid),public.complete_session_revocation_batch(uuid,timestamptz,text,uuid)to service_role;
