-- Additive compatibility after 087: qualify outer policy columns and enforce strict KPI payloads.
drop policy franchise_activities_operator_territory_read on public.franchise_crm_activities;
drop policy franchise_pipeline_operator_territory_read on public.franchise_pipeline_events;
create policy franchise_activities_operator_territory_read on public.franchise_crm_activities for select to authenticated using(exists(select 1 from public.franchise_crm_prospects p where p.id=franchise_crm_activities.prospect_id and p.franchise_id=franchise_crm_activities.franchise_id and private.franchise_crm_row_access(p.franchise_id,p.territory_version_id)));
create policy franchise_pipeline_operator_territory_read on public.franchise_pipeline_events for select to authenticated using(exists(select 1 from public.franchise_crm_prospects p where p.id=franchise_pipeline_events.prospect_id and p.franchise_id=franchise_pipeline_events.franchise_id and private.franchise_crm_row_access(p.franchise_id,p.territory_version_id)));
create or replace function private.valid_franchise_performance_measurements(p_measurements jsonb)returns boolean language sql immutable set search_path=pg_catalog as $$select jsonb_typeof(p_measurements)='array'and jsonb_array_length(p_measurements)between 1 and 100 and not exists(select 1 from jsonb_array_elements(p_measurements)m where jsonb_typeof(m)<>'object'or(select array_agg(k order by k)from jsonb_object_keys(m)k)<>array['denominator','evidence_refs','metric_version_id','numerator']::text[]or coalesce(m->>'metric_version_id','')!~'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'or case when coalesce(m->>'numerator','')!~'^\d{1,19}$'or coalesce(m->>'denominator','')!~'^\d{1,19}$'then true else(m->>'numerator')::numeric>9223372036854775807 or(m->>'denominator')::numeric>9223372036854775807 or(m->>'denominator')::numeric<=0 end or jsonb_typeof(m->'evidence_refs')<>'array'or jsonb_array_length(m->'evidence_refs')>50)and not exists(select 1 from jsonb_array_elements(p_measurements)m group by m->>'metric_version_id'having count(*)>1)$$;
create or replace function private.guard_franchise_performance_measurements()returns trigger language plpgsql set search_path=pg_catalog,private as $$begin if not private.valid_franchise_performance_measurements(new.measurements_snapshot)then raise exception'INVALID_PERFORMANCE_MEASUREMENT_SCHEMA'using errcode='23514';end if;return new;end$$;
drop trigger if exists franchise_performance_measurements_guard on public.franchise_performance_score_snapshots;
create trigger franchise_performance_measurements_guard before insert on public.franchise_performance_score_snapshots for each row execute function private.guard_franchise_performance_measurements();
revoke all on function private.valid_franchise_performance_measurements(jsonb),private.guard_franchise_performance_measurements()from public,anon,authenticated,service_role;
notify pgrst,'reload schema';
