-- Reconcile every development deployment shape of 105 without rewriting applied history.

create or replace function private.protect_assistance_request()returns trigger language plpgsql set search_path=pg_catalog,private as $$begin
 if tg_op='DELETE'or(to_jsonb(new)-array['input_text','input_text_redacted_at','input_text_expires_at'])is distinct from(to_jsonb(old)-array['input_text','input_text_redacted_at','input_text_expires_at'])or not((new.input_text=private.minimize_assistance_input(old.input_text)and old.input_text_redacted_at is null and new.input_text_redacted_at is null and new.input_text_expires_at=old.created_at+interval'30 days')or(old.input_text is null and new.input_text is null and old.input_text_redacted_at is null and new.input_text_redacted_at is null and new.input_text_expires_at=old.created_at+interval'30 days')or(new.input_text is null and old.input_text is not null and new.input_text_redacted_at is not null and new.input_text_expires_at=old.input_text_expires_at))then raise exception'ASSISTANCE_REQUEST_IMMUTABLE'using errcode='55000';end if;return new;
end$$;

do $$declare c text;begin
 for c in select conname from pg_constraint where conrelid='public.assistance_requests'::regclass and contype='c'and pg_get_constraintdef(oid)like'%context_type%NEED_TEXT%input_text IS NOT NULL%'loop execute format('alter table public.assistance_requests drop constraint %I',c);end loop;
 if not exists(select 1 from pg_constraint where conrelid='public.assistance_requests'::regclass and conname='assistance_requests_need_input_or_redacted')then alter table public.assistance_requests add constraint assistance_requests_need_input_or_redacted check(context_type<>'NEED_TEXT'or input_text is not null or input_text_redacted_at is not null);end if;
end$$;
alter table public.assistance_requests alter column input_text_expires_at set default(clock_timestamp()+interval'30 days');

create or replace function public.run_assisted_anomaly_similarity(p_organization_id uuid,p_candidate_anomaly_ids uuid[],p_model_version_id uuid,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();h text;cached jsonb;r jsonb;rid uuid;m public.assistance_model_versions%rowtype;dup_score integer;x record;y record;score integer;cnt integer:=0;begin
 if a is null or not(private.is_active_org_member(p_organization_id,a)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a))then raise exception'ASSISTANCE_ACCESS_DENIED'using errcode='42501';end if;if cardinality(coalesce(p_candidate_anomaly_ids,'{}'))not between 2 and 50 then raise exception'INVALID_BOUNDED_ANOMALY_CANDIDATES'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'anomalies',p_candidate_anomaly_ids,'model',p_model_version_id));cached:=private.begin_contract_command(p_organization_id,'assistance.anomaly.runtime',p_idempotency_key,h,a);if cached is not null then return cached;end if;
 select*into m from public.assistance_model_versions where id=p_model_version_id and status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp());if not found then raise exception'ACTIVE_ASSISTANCE_MODEL_REQUIRED'using errcode='55000';end if;dup_score:=(m.configuration->>'duplicate_score_basis_points')::integer;
 if(select count(distinct id)from public.diagnostic_anomalies where organization_id=p_organization_id and id=any(p_candidate_anomaly_ids))<>cardinality(p_candidate_anomaly_ids)then raise exception'ANOMALY_CANDIDATE_SCOPE_MISMATCH'using errcode='42501';end if;
 insert into public.assistance_requests(organization_id,model_version_id,context_type,input_hash,candidate_anomaly_ids,created_by)values(p_organization_id,m.id,'SIMILARITY_REVIEW',h,p_candidate_anomaly_ids,a)returning id into rid;
 for x in select id,title_fr,title_ar from public.diagnostic_anomalies where organization_id=p_organization_id and id=any(p_candidate_anomaly_ids)loop for y in select id,title_fr,title_ar from public.diagnostic_anomalies where organization_id=p_organization_id and id=any(p_candidate_anomaly_ids)and id>x.id loop score:=private.assistance_overlap_basis_points(x.title_fr||' '||x.title_ar,y.title_fr||' '||y.title_ar);if score>=dup_score then insert into public.assistance_suggestions(organization_id,request_id,suggestion_kind,target_type,target_id,related_target_id,score_basis_points,explanation_code,explanation,proposed_payload)values(p_organization_id,rid,'SEMANTIC_DUPLICATE','ANOMALY_PAIR',x.id,y.id,score,'ANOMALY_FR_AR_SIMILARITY',jsonb_build_object('model_version',m.version,'evidence',jsonb_build_object('algorithm',m.algorithm,'languages',array['fr','ar'],'score_basis_points',score),'human_review_required',true),jsonb_build_object('recommended_action','HUMAN_COMPARE'));cnt:=cnt+1;end if;end loop;end loop;
 r:=jsonb_build_object('outcome','ANOMALY_SIMILARITY_PROPOSED','request_id',rid,'suggestion_count',cnt,'human_confirmation_required',true);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','assistance.anomaly.completed','assistance_request',rid::text,p_correlation_id,jsonb_build_object('candidate_count',cardinality(p_candidate_anomaly_ids),'suggestion_count',cnt,'model_version_id',m.id),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'assistance_request',rid::text,'AssistanceAnomalySuggestionsProposedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'assistance.anomaly.runtime',p_idempotency_key,r);return r;end$$;

create or replace function public.get_assistance_request_input(p_request_id uuid)returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();q public.assistance_requests%rowtype;r jsonb;begin select*into q from public.assistance_requests where id=p_request_id;if a is null or not found or not(private.has_org_role(q.organization_id,array['CLIENT_OWNER','CLIENT_ADMIN'],a)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a))then raise exception'ASSISTANCE_INPUT_ACCESS_DENIED'using errcode='42501';end if;if q.input_text is null or q.input_text_redacted_at is not null or clock_timestamp()>=q.input_text_expires_at then return jsonb_build_object('request_id',q.id,'available',false);end if;r:=jsonb_build_object('request_id',q.id,'available',true,'input_text',q.input_text,'expires_at',q.input_text_expires_at);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(q.organization_id,a,'USER','assistance.input.viewed','assistance_request',q.id::text,extensions.gen_random_uuid(),jsonb_build_object('expires_at',q.input_text_expires_at),repeat('0',64));return r;end$$;

create or replace function public.redact_expired_assistance_inputs(p_limit integer default 500)returns integer language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();q record;n integer:=0;begin if a is null or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a)or p_limit not between 1 and 1000 then raise exception'ASSISTANCE_RETENTION_ADMIN_REQUIRED'using errcode='42501';end if;for q in select id,organization_id from public.assistance_requests where input_text is not null and input_text_redacted_at is null and input_text_expires_at<=clock_timestamp()order by input_text_expires_at limit p_limit for update skip locked loop update public.assistance_requests set input_text=null,input_text_redacted_at=clock_timestamp()where id=q.id;insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(q.organization_id,a,'USER','assistance.input.redacted','assistance_request',q.id::text,extensions.gen_random_uuid(),'{}',repeat('0',64));n:=n+1;end loop;return n;end$$;

revoke select on public.assistance_requests from authenticated;
grant select(id,organization_id,model_version_id,profile_reassessment_id,context_type,input_hash,candidate_service_version_ids,candidate_question_version_ids,known_data_keys,status,created_by,created_at,candidate_anomaly_ids,input_text_expires_at,input_text_redacted_at)on public.assistance_requests to authenticated;
revoke all on function private.minimize_assistance_input(text),private.protect_assistance_request(),private.run_assisted_analysis_core_v1(uuid,text,text,uuid[],uuid[],text[],uuid,uuid,text,uuid),private.decide_assisted_suggestion_core_v1(uuid,text,text,text,uuid)from public,anon,authenticated,service_role;
revoke all on function public.run_assisted_analysis(uuid,text,text,uuid[],uuid[],text[],uuid,uuid,text,uuid),public.decide_assisted_suggestion(uuid,text,text,text,uuid),public.run_assisted_anomaly_similarity(uuid,uuid[],uuid,text,uuid),public.get_assistance_request_input(uuid),public.redact_expired_assistance_inputs(integer)from public,anon,authenticated,service_role;
grant execute on function public.run_assisted_analysis(uuid,text,text,uuid[],uuid[],text[],uuid,uuid,text,uuid),public.decide_assisted_suggestion(uuid,text,text,text,uuid),public.run_assisted_anomaly_similarity(uuid,uuid[],uuid,text,uuid),public.get_assistance_request_input(uuid),public.redact_expired_assistance_inputs(integer)to authenticated;
