-- P17 command center: prioritized work queues, human decisions and controlled operational commands.

create table public.admin_queue_versions(
 id uuid primary key default extensions.gen_random_uuid(),queue_key text not null check(queue_key~'^[A-Z][A-Z0-9_]{2,63}$'),version integer not null check(version>0),status text not null check(status in('DRAFT','ACTIVE','RETIRED')),label_fr text not null,label_ar text not null,
 required_role_codes text[] not null check(cardinality(required_role_codes)>0),sla_minutes integer not null check(sla_minutes between 1 and 43200),sort_weight integer not null check(sort_weight between 1 and 1000),created_at timestamptz not null default clock_timestamp(),unique(queue_key,version)
);
create unique index admin_queue_one_active_uidx on public.admin_queue_versions(queue_key)where status='ACTIVE';
insert into public.admin_queue_versions(queue_key,version,status,label_fr,label_ar,required_role_codes,sla_minutes,sort_weight)values
('EXECUTIVE_TODAY',1,'ACTIVE','À traiter aujourd’hui','مهام اليوم',array['SUPER_ADMIN','MATRICIA_ADMIN'],1440,100),
('CENTRAL_APPROVALS',1,'ACTIVE','Approbations centrales','الموافقات المركزية',array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER','LIBRARY_MANAGER'],480,90),
('EXCEPTIONS',1,'ACTIVE','Exceptions opérationnelles','الاستثناءات التشغيلية',array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','SUPPORT_AGENT'],240,95),
('RISK_FLAGS',1,'ACTIVE','Signaux de risque','إشارات المخاطر',array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','DISPUTE_MANAGER'],120,98);

create table public.admin_work_items(
 id uuid primary key default extensions.gen_random_uuid(),queue_version_id uuid not null references public.admin_queue_versions(id)on delete restrict,organization_id uuid references public.organizations(id)on delete restrict,
 source_kind text not null check(source_kind in('APPROVAL','EXCEPTION','RISK_FLAG','SLA_BREACH','DOCUMENT','DISPUTE','FINANCE','CATALOG','POOL','MANUAL_REVIEW')),resource_type text not null check(length(btrim(resource_type))between 2 and 100),resource_id text not null check(length(btrim(resource_id))between 1 and 200),
 title_fr text not null check(length(btrim(title_fr))between 3 and 240),title_ar text not null check(length(btrim(title_ar))between 3 and 240),priority text not null check(priority in('CRITICAL','HIGH','MEDIUM','LOW')),severity_rank integer generated always as(case priority when'CRITICAL'then 4 when'HIGH'then 3 when'MEDIUM'then 2 else 1 end)stored,
 status text not null default'OPEN'check(status in('OPEN','CLAIMED','WAITING_INFORMATION','RESOLVED','DISMISSED')),due_at timestamptz not null,redacted_context jsonb not null default'{}'check(jsonb_typeof(redacted_context)='object'),assigned_to uuid references auth.users(id),claimed_at timestamptz,resolution_code text,resolution_reason text,resolution_evidence jsonb,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),row_version integer not null default 1 check(row_version>0),
 unique(queue_version_id,source_kind,resource_type,resource_id),check((status in('RESOLVED','DISMISSED'))=(resolution_code is not null)),check(resolution_evidence is null or jsonb_typeof(resolution_evidence)='object')
);
create index admin_today_priority_idx on public.admin_work_items(status,severity_rank desc,due_at,id)where status in('OPEN','CLAIMED','WAITING_INFORMATION');
create index admin_work_items_org_idx on public.admin_work_items(organization_id,created_at desc)where organization_id is not null;

create table public.admin_work_item_events(
 id bigint generated always as identity primary key,work_item_id uuid not null references public.admin_work_items(id)on delete restrict,event_type text not null,from_status text,to_status text not null,actor_user_id uuid not null references auth.users(id),reason text not null check(length(btrim(reason))between 3 and 1000),evidence_snapshot jsonb not null default'{}'check(jsonb_typeof(evidence_snapshot)='object'),correlation_id uuid not null,occurred_at timestamptz not null default clock_timestamp()
);

create table public.admin_operational_action_requests(
 id uuid primary key default extensions.gen_random_uuid(),work_item_id uuid references public.admin_work_items(id)on delete restrict,organization_id uuid references public.organizations(id)on delete restrict,
 action_type text not null check(action_type in('ASSIGN_CASE','CHANGE_CONFIGURATION','GRANT_SUPPORT_ACCESS','RESTRICT_ENTITY','SUSPEND_ENTITY','MANUAL_EXCEPTION','AUTHORIZE_PRODUCTION_CHANGE')),
 target_environment text not null check(target_environment in('DEVELOPMENT','STAGING','PRODUCTION')),resource_type text not null,resource_id text not null,request_payload_hash text not null check(request_payload_hash~'^[0-9a-f]{64}$'),redacted_summary jsonb not null check(jsonb_typeof(redacted_summary)='object'),
 reason text not null check(length(btrim(reason))between 10 and 2000),production_authorization_reference text,approvals_required integer not null check(approvals_required in(1,2)),status text not null default'PENDING_APPROVAL'check(status in('PENDING_APPROVAL','AUTHORIZED','REJECTED','EXECUTED','FAILED','CANCELLED')),
 support_user_id uuid references auth.users(id),support_access_mode text check(support_access_mode in('READ_ONLY','CASE_SCOPED')),support_expires_at timestamptz,
 requested_by uuid not null references auth.users(id),requested_at timestamptz not null default clock_timestamp(),authorized_at timestamptz,executed_at timestamptz,execution_result_hash text check(execution_result_hash is null or execution_result_hash~'^[0-9a-f]{64}$'),row_version integer not null default 1 check(row_version>0),
 check((target_environment='PRODUCTION')=(production_authorization_reference is not null)),
 check((action_type='GRANT_SUPPORT_ACCESS')=(support_user_id is not null and support_access_mode is not null and support_expires_at is not null)),
 check(action_type<>'GRANT_SUPPORT_ACCESS'or support_expires_at<=requested_at+interval'1 hour')
);
create index admin_action_pending_idx on public.admin_operational_action_requests(status,requested_at,id)where status='PENDING_APPROVAL';

create table public.admin_operational_action_decisions(
 id uuid primary key default extensions.gen_random_uuid(),action_request_id uuid not null references public.admin_operational_action_requests(id)on delete restrict,decision text not null check(decision in('APPROVE','REJECT')),reason text not null check(length(btrim(reason))between 3 and 1000),request_payload_hash text not null check(request_payload_hash~'^[0-9a-f]{64}$'),decided_by uuid not null references auth.users(id),decided_at timestamptz not null default clock_timestamp(),unique(action_request_id,decided_by)
);
create table public.admin_support_access_grants(
 id uuid primary key default extensions.gen_random_uuid(),action_request_id uuid not null unique references public.admin_operational_action_requests(id)on delete restrict,target_organization_id uuid not null references public.organizations(id)on delete restrict,support_user_id uuid not null references auth.users(id),access_mode text not null check(access_mode in('READ_ONLY','CASE_SCOPED')),resource_type text not null,resource_id text not null,granted_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null,revoked_at timestamptz,check(expires_at>granted_at and expires_at<=granted_at+interval'1 hour')
);
create index admin_support_grants_active_idx on public.admin_support_access_grants(support_user_id,expires_at)where revoked_at is null;

create table private.admin_command_keys(actor_user_id uuid not null references auth.users(id),operation_scope text not null,key text not null check(length(key)between 8 and 200),request_hash text not null check(request_hash~'^[0-9a-f]{64}$'),response_body jsonb,created_at timestamptz not null default clock_timestamp(),completed_at timestamptz,primary key(actor_user_id,operation_scope,key));
revoke all on private.admin_command_keys from public,anon,authenticated,service_role;

create function private.admin_has_queue_access(p_queue_version_id uuid,p_actor uuid default auth.uid())returns boolean language sql stable security definer set search_path=pg_catalog,public,private as $$select exists(select 1 from public.admin_queue_versions q where q.id=p_queue_version_id and q.status='ACTIVE'and private.has_platform_role(q.required_role_codes,p_actor))or private.has_platform_role(array['READ_ONLY_AUDITOR'],p_actor)$$;
create function private.admin_command_access(p_actor uuid default auth.uid())returns boolean language sql stable security definer set search_path=pg_catalog,private as $$select private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','FINANCE_MANAGER','DISPUTE_MANAGER','LIBRARY_MANAGER','SUPPORT_AGENT'],p_actor)$$;
create function private.begin_admin_command(p_scope text,p_key text,p_hash text,p_actor uuid)returns jsonb language plpgsql security definer set search_path=pg_catalog,private as $$declare x private.admin_command_keys%rowtype;begin if p_actor is null or length(coalesce(p_key,''))not between 8 and 200 then raise exception'INVALID_ADMIN_IDEMPOTENCY_KEY'using errcode='22023';end if;perform pg_advisory_xact_lock(hashtextextended(p_actor::text||':'||p_scope||':'||p_key,0));select*into x from private.admin_command_keys where actor_user_id=p_actor and operation_scope=p_scope and key=p_key;if found then if x.request_hash<>p_hash then raise exception'IDEMPOTENCY_PAYLOAD_MISMATCH'using errcode='22000';end if;if x.response_body is not null then return x.response_body;end if;raise exception'ADMIN_COMMAND_IN_PROGRESS'using errcode='55000';end if;insert into private.admin_command_keys(actor_user_id,operation_scope,key,request_hash)values(p_actor,p_scope,p_key,p_hash);return null;end$$;
create function private.finish_admin_command(p_scope text,p_key text,p_actor uuid,p_response jsonb)returns void language sql security definer set search_path=pg_catalog,private as $$update private.admin_command_keys set response_body=p_response,completed_at=clock_timestamp()where actor_user_id=p_actor and operation_scope=p_scope and key=p_key$$;
create function private.prevent_admin_history_change()returns trigger language plpgsql set search_path=pg_catalog as $$begin raise exception'IMMUTABLE_ADMIN_HISTORY'using errcode='55000';end$$;
create trigger admin_queue_versions_immutable before update or delete on public.admin_queue_versions for each row execute function private.prevent_admin_history_change();create trigger admin_work_events_immutable before update or delete on public.admin_work_item_events for each row execute function private.prevent_admin_history_change();create trigger admin_action_decisions_immutable before update or delete on public.admin_operational_action_decisions for each row execute function private.prevent_admin_history_change();

create function public.open_admin_work_item(p_queue_key text,p_organization_id uuid,p_source_kind text,p_resource_type text,p_resource_id text,p_title_fr text,p_title_ar text,p_priority text,p_due_at timestamptz,p_redacted_context jsonb,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();q public.admin_queue_versions%rowtype;h text;r jsonb;w uuid;
begin select*into q from public.admin_queue_versions where queue_key=p_queue_key and status='ACTIVE';if a is null or not found or not private.has_platform_role(q.required_role_codes,a)then raise exception'ADMIN_QUEUE_WRITE_DENIED'using errcode='42501';end if;
 if p_source_kind not in('APPROVAL','EXCEPTION','RISK_FLAG','SLA_BREACH','DOCUMENT','DISPUTE','FINANCE','CATALOG','POOL','MANUAL_REVIEW')or p_priority not in('CRITICAL','HIGH','MEDIUM','LOW')or p_due_at<=clock_timestamp()or jsonb_typeof(p_redacted_context)<>'object'or p_redacted_context?|array['secret','password','token','credential','api_key']or length(btrim(coalesce(p_reason,'')))not between 3 and 1000 then raise exception'INVALID_ADMIN_WORK_ITEM'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('queue',q.id,'organization',p_organization_id,'source',p_source_kind,'resource_type',p_resource_type,'resource_id',p_resource_id,'title_fr',p_title_fr,'title_ar',p_title_ar,'priority',p_priority,'due',p_due_at,'context',p_redacted_context,'reason',p_reason));r:=private.begin_admin_command('admin.work.open',p_idempotency_key,h,a);if r is not null then return r;end if;
 insert into public.admin_work_items(queue_version_id,organization_id,source_kind,resource_type,resource_id,title_fr,title_ar,priority,due_at,redacted_context,created_by)values(q.id,p_organization_id,p_source_kind,p_resource_type,p_resource_id,p_title_fr,p_title_ar,p_priority,p_due_at,p_redacted_context,a)returning id into w;
 insert into public.admin_work_item_events(work_item_id,event_type,to_status,actor_user_id,reason,evidence_snapshot,correlation_id)values(w,'OPENED','OPEN',a,p_reason,p_redacted_context,p_correlation_id);r:=jsonb_build_object('outcome','ADMIN_WORK_ITEM_OPENED','work_item_id',w,'priority',p_priority,'due_at',p_due_at);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','admin.work_item.opened','admin_work_item',w::text,p_correlation_id,jsonb_build_object('source_kind',p_source_kind,'queue_key',p_queue_key,'target_resource_type',p_resource_type),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'admin_work_item',w::text,'AdminWorkItemOpenedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('admin.work.open',p_idempotency_key,a,r);return r;
end$$;

create function public.claim_admin_work_item(p_work_item_id uuid,p_expected_row_version integer,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();w public.admin_work_items%rowtype;h text;r jsonb;begin select*into w from public.admin_work_items where id=p_work_item_id;if a is null or not found or not private.admin_has_queue_access(w.queue_version_id,a)or private.has_platform_role(array['READ_ONLY_AUDITOR'],a)then raise exception'ADMIN_WORK_CLAIM_DENIED'using errcode='42501';end if;if length(btrim(coalesce(p_reason,'')))not between 3 and 1000 then raise exception'ADMIN_REASON_REQUIRED'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('work_item',w.id,'expected',p_expected_row_version,'reason',p_reason));r:=private.begin_admin_command('admin.work.claim.'||w.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;update public.admin_work_items set status='CLAIMED',assigned_to=a,claimed_at=clock_timestamp(),updated_at=clock_timestamp(),row_version=row_version+1 where id=w.id and status='OPEN'and row_version=p_expected_row_version;if not found then raise exception'STALE_ADMIN_WORK_ITEM'using errcode='40001';end if;
 insert into public.admin_work_item_events(work_item_id,event_type,from_status,to_status,actor_user_id,reason,correlation_id)values(w.id,'CLAIMED','OPEN','CLAIMED',a,p_reason,p_correlation_id);r:=jsonb_build_object('outcome','ADMIN_WORK_ITEM_CLAIMED','work_item_id',w.id,'row_version',w.row_version+1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(w.organization_id,a,'USER','admin.work_item.claimed','admin_work_item',w.id::text,p_correlation_id,jsonb_build_object('reason',p_reason),repeat('0',64));perform private.finish_admin_command('admin.work.claim.'||w.id::text,p_idempotency_key,a,r);return r;end$$;

create function public.resolve_admin_work_item(p_work_item_id uuid,p_resolution_code text,p_reason text,p_evidence jsonb,p_expected_row_version integer,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();w public.admin_work_items%rowtype;h text;r jsonb;begin select*into w from public.admin_work_items where id=p_work_item_id;if a is null or not found or not private.admin_has_queue_access(w.queue_version_id,a)or private.has_platform_role(array['READ_ONLY_AUDITOR'],a)or(w.assigned_to is distinct from a and not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],a))then raise exception'ADMIN_WORK_RESOLVE_DENIED'using errcode='42501';end if;if coalesce(p_resolution_code,'')!~'^[A-Z][A-Z0-9_]{2,63}$'or length(btrim(coalesce(p_reason,'')))not between 10 and 2000 or jsonb_typeof(p_evidence)<>'object'or p_evidence?|array['secret','password','token','credential','api_key']then raise exception'INVALID_ADMIN_RESOLUTION'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('work_item',w.id,'code',p_resolution_code,'reason',p_reason,'evidence',p_evidence,'expected',p_expected_row_version));r:=private.begin_admin_command('admin.work.resolve.'||w.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;update public.admin_work_items set status='RESOLVED',resolution_code=p_resolution_code,resolution_reason=p_reason,resolution_evidence=p_evidence,updated_at=clock_timestamp(),row_version=row_version+1 where id=w.id and status in('CLAIMED','WAITING_INFORMATION')and row_version=p_expected_row_version;if not found then raise exception'STALE_ADMIN_WORK_ITEM'using errcode='40001';end if;
 insert into public.admin_work_item_events(work_item_id,event_type,from_status,to_status,actor_user_id,reason,evidence_snapshot,correlation_id)values(w.id,'HUMAN_RESOLUTION',w.status,'RESOLVED',a,p_reason,p_evidence,p_correlation_id);r:=jsonb_build_object('outcome','ADMIN_WORK_ITEM_RESOLVED','work_item_id',w.id,'resolution_code',p_resolution_code,'row_version',w.row_version+1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(w.organization_id,a,'USER','admin.work_item.resolved','admin_work_item',w.id::text,p_correlation_id,jsonb_build_object('resolution_code',p_resolution_code,'reason',p_reason),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(w.organization_id,'admin_work_item',w.id::text,'AdminWorkItemResolvedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('admin.work.resolve.'||w.id::text,p_idempotency_key,a,r);return r;end$$;

create function public.request_admin_operational_action(p_work_item_id uuid,p_organization_id uuid,p_action_type text,p_target_environment text,p_resource_type text,p_resource_id text,p_request_payload_hash text,p_redacted_summary jsonb,p_reason text,p_production_authorization_reference text,p_support_user_id uuid,p_support_access_mode text,p_support_expires_at timestamptz,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;x uuid;n integer;begin if a is null or not private.admin_command_access(a)or private.has_platform_role(array['READ_ONLY_AUDITOR'],a)then raise exception'ADMIN_ACTION_REQUEST_DENIED'using errcode='42501';end if;
 if p_action_type not in('ASSIGN_CASE','CHANGE_CONFIGURATION','GRANT_SUPPORT_ACCESS','RESTRICT_ENTITY','SUSPEND_ENTITY','MANUAL_EXCEPTION','AUTHORIZE_PRODUCTION_CHANGE')or p_target_environment not in('DEVELOPMENT','STAGING','PRODUCTION')or p_request_payload_hash!~'^[0-9a-f]{64}$'or jsonb_typeof(p_redacted_summary)<>'object'or p_redacted_summary?|array['secret','password','token','credential','api_key']or length(btrim(coalesce(p_reason,'')))not between 10 and 2000 or(p_target_environment='PRODUCTION'and length(btrim(coalesce(p_production_authorization_reference,'')))<8)or(p_target_environment<>'PRODUCTION'and p_production_authorization_reference is not null)or(p_action_type='GRANT_SUPPORT_ACCESS'and(p_organization_id is null or p_support_user_id is null or p_support_access_mode not in('READ_ONLY','CASE_SCOPED')or p_support_expires_at<=clock_timestamp()or p_support_expires_at>clock_timestamp()+interval'1 hour'))or(p_action_type<>'GRANT_SUPPORT_ACCESS'and num_nonnulls(p_support_user_id,p_support_access_mode,p_support_expires_at)>0)then raise exception'INVALID_ADMIN_ACTION_REQUEST'using errcode='22023';end if;
 n:=case when p_action_type in('RESTRICT_ENTITY','SUSPEND_ENTITY','MANUAL_EXCEPTION','GRANT_SUPPORT_ACCESS','AUTHORIZE_PRODUCTION_CHANGE')or p_target_environment='PRODUCTION'then 2 else 1 end;h:=private.canonical_request_hash(jsonb_build_object('work_item',p_work_item_id,'organization',p_organization_id,'action',p_action_type,'environment',p_target_environment,'resource_type',p_resource_type,'resource_id',p_resource_id,'payload_hash',p_request_payload_hash,'summary',p_redacted_summary,'reason',p_reason,'production_authorization',p_production_authorization_reference,'support_user',p_support_user_id,'support_mode',p_support_access_mode,'support_expires',p_support_expires_at));r:=private.begin_admin_command('admin.action.request',p_idempotency_key,h,a);if r is not null then return r;end if;
 insert into public.admin_operational_action_requests(work_item_id,organization_id,action_type,target_environment,resource_type,resource_id,request_payload_hash,redacted_summary,reason,production_authorization_reference,approvals_required,support_user_id,support_access_mode,support_expires_at,requested_by)values(p_work_item_id,p_organization_id,p_action_type,p_target_environment,p_resource_type,p_resource_id,p_request_payload_hash,p_redacted_summary,p_reason,p_production_authorization_reference,n,p_support_user_id,p_support_access_mode,p_support_expires_at,a)returning id into x;r:=jsonb_build_object('outcome','ADMIN_ACTION_APPROVAL_REQUIRED','action_request_id',x,'approvals_required',n,'target_environment',p_target_environment);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','admin.action.requested','admin_action_request',x::text,p_correlation_id,jsonb_build_object('action_type',p_action_type,'environment',p_target_environment,'payload_hash',p_request_payload_hash,'approvals_required',n),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'admin_action_request',x::text,'AdminActionApprovalRequiredV1',p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('admin.action.request',p_idempotency_key,a,r);return r;end$$;

create function public.decide_admin_operational_action(p_action_request_id uuid,p_decision text,p_reason text,p_expected_row_version integer,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();x public.admin_operational_action_requests%rowtype;h text;r jsonb;n integer;next_status text;begin select*into x from public.admin_operational_action_requests where id=p_action_request_id;if a is null or not found or not private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','COMPLIANCE_MANAGER','FINANCE_MANAGER','DISPUTE_MANAGER','LIBRARY_MANAGER'],a)or a=x.requested_by then raise exception'ADMIN_ACTION_DECISION_DENIED'using errcode='42501';end if;if p_decision not in('APPROVE','REJECT')or length(btrim(coalesce(p_reason,'')))not between 3 and 1000 then raise exception'INVALID_ADMIN_ACTION_DECISION'using errcode='22023';end if;
 h:=private.canonical_request_hash(jsonb_build_object('request',x.id,'decision',p_decision,'reason',p_reason,'expected',p_expected_row_version,'payload_hash',x.request_payload_hash));r:=private.begin_admin_command('admin.action.decide.'||x.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;perform pg_advisory_xact_lock(hashtextextended('admin-action:'||x.id::text,0));select*into x from public.admin_operational_action_requests where id=x.id for update;if x.status<>'PENDING_APPROVAL'or x.row_version<>p_expected_row_version then raise exception'STALE_ADMIN_ACTION_REQUEST'using errcode='40001';end if;
 insert into public.admin_operational_action_decisions(action_request_id,decision,reason,request_payload_hash,decided_by)values(x.id,p_decision,p_reason,x.request_payload_hash,a);select count(*)into n from public.admin_operational_action_decisions where action_request_id=x.id and decision='APPROVE';next_status:=case when p_decision='REJECT'then'REJECTED'when n>=x.approvals_required then'AUTHORIZED'else'PENDING_APPROVAL'end;update public.admin_operational_action_requests set status=next_status,authorized_at=case when next_status='AUTHORIZED'then clock_timestamp()else authorized_at end,row_version=row_version+1 where id=x.id;
 r:=jsonb_build_object('outcome',case next_status when'AUTHORIZED'then'ADMIN_ACTION_AUTHORIZED'when'REJECTED'then'ADMIN_ACTION_REJECTED'else'ADMIN_ACTION_ADDITIONAL_APPROVAL_REQUIRED'end,'action_request_id',x.id,'approvals_recorded',n,'approvals_required',x.approvals_required,'row_version',x.row_version+1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(x.organization_id,a,'USER','admin.action.decided','admin_action_request',x.id::text,p_correlation_id,jsonb_build_object('decision',p_decision,'reason',p_reason,'payload_hash',x.request_payload_hash,'resulting_status',next_status),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(x.organization_id,'admin_action_request',x.id::text,case next_status when'AUTHORIZED'then'AdminActionAuthorizedV1'when'REJECTED'then'AdminActionRejectedV1'else'AdminActionApprovalRecordedV1'end,p_correlation_id,r,p_idempotency_key);perform private.finish_admin_command('admin.action.decide.'||x.id::text,p_idempotency_key,a,r);return r;end$$;

create function public.complete_admin_operational_action(p_action_request_id uuid,p_execution_result_hash text,p_success boolean,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare x public.admin_operational_action_requests%rowtype;r jsonb;g uuid;begin if auth.role()<>'service_role'then raise exception'ADMIN_ACTION_EXECUTION_DENIED'using errcode='42501';end if;if p_execution_result_hash!~'^[0-9a-f]{64}$'then raise exception'INVALID_ADMIN_EXECUTION_RESULT'using errcode='22023';end if;select*into x from public.admin_operational_action_requests where id=p_action_request_id for update;if not found or x.status<>'AUTHORIZED'then raise exception'ADMIN_ACTION_NOT_AUTHORIZED'using errcode='55000';end if;update public.admin_operational_action_requests set status=case when p_success then'EXECUTED'else'FAILED'end,executed_at=clock_timestamp(),execution_result_hash=p_execution_result_hash,row_version=row_version+1 where id=x.id;if p_success and x.action_type='GRANT_SUPPORT_ACCESS'then insert into public.admin_support_access_grants(action_request_id,target_organization_id,support_user_id,access_mode,resource_type,resource_id,expires_at)values(x.id,x.organization_id,x.support_user_id,x.support_access_mode,x.resource_type,x.resource_id,x.support_expires_at)returning id into g;end if;r:=jsonb_build_object('outcome',case when p_success then'ADMIN_ACTION_EXECUTED'else'ADMIN_ACTION_FAILED'end,'action_request_id',x.id,'support_access_grant_id',g,'result_hash',p_execution_result_hash);insert into public.audit_events(organization_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(x.organization_id,'SERVICE','admin.action.completed','admin_action_request',x.id::text,p_correlation_id,jsonb_build_object('success',p_success,'result_hash',p_execution_result_hash,'support_access_grant_id',g),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload)values(x.organization_id,'admin_action_request',x.id::text,case when p_success then'AdminActionExecutedV1'else'AdminActionFailedV1'end,p_correlation_id,r);return r;end$$;

alter table public.admin_queue_versions enable row level security;alter table public.admin_work_items enable row level security;alter table public.admin_work_item_events enable row level security;alter table public.admin_operational_action_requests enable row level security;alter table public.admin_operational_action_decisions enable row level security;alter table public.admin_support_access_grants enable row level security;
revoke all on public.admin_queue_versions,public.admin_work_items,public.admin_work_item_events,public.admin_operational_action_requests,public.admin_operational_action_decisions,public.admin_support_access_grants from public,anon,authenticated,service_role;grant select on public.admin_queue_versions,public.admin_work_items,public.admin_work_item_events,public.admin_operational_action_requests,public.admin_operational_action_decisions,public.admin_support_access_grants to authenticated;
create policy admin_queue_scoped_read on public.admin_queue_versions for select to authenticated using(private.has_platform_role(required_role_codes)or private.has_platform_role(array['READ_ONLY_AUDITOR']));create policy admin_work_scoped_read on public.admin_work_items for select to authenticated using(private.admin_has_queue_access(queue_version_id));create policy admin_work_events_scoped_read on public.admin_work_item_events for select to authenticated using(exists(select 1 from public.admin_work_items w where w.id=work_item_id and private.admin_has_queue_access(w.queue_version_id)));create policy admin_actions_scoped_read on public.admin_operational_action_requests for select to authenticated using(private.admin_command_access()or private.has_platform_role(array['READ_ONLY_AUDITOR']));create policy admin_action_decisions_scoped_read on public.admin_operational_action_decisions for select to authenticated using(exists(select 1 from public.admin_operational_action_requests x where x.id=action_request_id and(private.admin_command_access()or private.has_platform_role(array['READ_ONLY_AUDITOR']))));create policy admin_support_grants_scoped_read on public.admin_support_access_grants for select to authenticated using(support_user_id=auth.uid()or private.admin_command_access()or private.has_platform_role(array['READ_ONLY_AUDITOR']));
revoke all on function private.admin_has_queue_access(uuid,uuid),private.admin_command_access(uuid),private.begin_admin_command(text,text,text,uuid),private.finish_admin_command(text,text,uuid,jsonb)from public,anon,authenticated,service_role;grant execute on function private.admin_has_queue_access(uuid,uuid),private.admin_command_access(uuid)to authenticated;
revoke all on function public.open_admin_work_item(text,uuid,text,text,text,text,text,text,timestamptz,jsonb,text,text,uuid),public.claim_admin_work_item(uuid,integer,text,text,uuid),public.resolve_admin_work_item(uuid,text,text,jsonb,integer,text,uuid),public.request_admin_operational_action(uuid,uuid,text,text,text,text,text,jsonb,text,text,uuid,text,timestamptz,text,uuid),public.decide_admin_operational_action(uuid,text,text,integer,text,uuid),public.complete_admin_operational_action(uuid,text,boolean,uuid)from public,anon,authenticated,service_role;
grant execute on function public.open_admin_work_item(text,uuid,text,text,text,text,text,text,timestamptz,jsonb,text,text,uuid),public.claim_admin_work_item(uuid,integer,text,text,uuid),public.resolve_admin_work_item(uuid,text,text,jsonb,integer,text,uuid),public.request_admin_operational_action(uuid,uuid,text,text,text,text,text,jsonb,text,text,uuid,text,timestamptz,text,uuid),public.decide_admin_operational_action(uuid,text,text,integer,text,uuid)to authenticated;grant execute on function public.complete_admin_operational_action(uuid,text,boolean,uuid)to service_role;
notify pgrst,'reload schema';
