-- Runtime compatibility: disambiguate row variables and SQL aliases.
create or replace function public.create_recurring_service_plan(p_template_request_id uuid,p_cadence text,p_starts_on date,p_ends_on date,p_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare v_actor uuid:=auth.uid();v_request public.service_requests%rowtype;v_catalog_version public.catalog_service_versions%rowtype;v_request_hash text;v_response jsonb;v_plan_id uuid:=extensions.gen_random_uuid();v_plan_version_id uuid:=extensions.gen_random_uuid();
begin
 select request_row.* into v_request from public.service_requests request_row where request_row.id=p_template_request_id;
 if not found or not private.can_manage_client_request(v_request.client_organization_id,v_actor)then raise exception'REQUEST_SCOPE_DENIED'using errcode='42501';end if;
 if p_cadence not in('MONTHLY','QUARTERLY','ANNUALLY')or p_starts_on is null or(p_ends_on is not null and p_ends_on<p_starts_on)or length(btrim(coalesce(p_reason,'')))not between 3 and 500 or length(coalesce(p_idempotency_key,''))not between 8 and 200 then raise exception'INVALID_RECURRING_PLAN'using errcode='22023';end if;
 v_request_hash:=private.canonical_request_hash(jsonb_build_object('operation','recurring.plan.create.v2','template',p_template_request_id,'cadence',p_cadence,'starts_on',p_starts_on,'ends_on',p_ends_on,'reason',btrim(p_reason)));v_response:=private.begin_contract_command(v_request.client_organization_id,'recurring.plan.create.v2',p_idempotency_key,v_request_hash,v_actor);if v_response is not null then return v_response;end if;
 select service_version_row.* into v_catalog_version from public.catalog_services service_row join public.catalog_service_versions service_version_row on service_version_row.id=service_row.current_published_version_id and service_version_row.service_id=service_row.id and service_version_row.library_id=service_row.library_id where service_row.id=v_request.service_id and service_row.library_id=v_request.library_id and service_row.status='PUBLISHED'and service_version_row.status='PUBLISHED'and service_version_row.recurring_eligible;
 if not found then raise exception'SERVICE_NOT_RECURRING_ELIGIBLE'using errcode='22023';end if;
 insert into public.recurring_service_plans(id,client_organization_id,template_request_id,created_by)values(v_plan_id,v_request.client_organization_id,p_template_request_id,v_actor);insert into public.recurring_service_plan_versions(id,plan_id,version_number,cadence,starts_on,ends_on,status,reason,created_by)values(v_plan_version_id,v_plan_id,1,p_cadence,p_starts_on,p_ends_on,'ACTIVE',btrim(p_reason),v_actor);
 v_response:=jsonb_build_object('outcome','RECURRING_PLAN_CREATED','plan_id',v_plan_id,'plan_version_id',v_plan_version_id,'status','ACTIVE');insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(v_request.client_organization_id,v_actor,'USER','recurring.plan.created','recurring_service_plan',v_plan_id::text,p_correlation_id,jsonb_build_object('cadence',p_cadence,'template_request_id',p_template_request_id,'published_service_version_id',v_catalog_version.id),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(v_request.client_organization_id,'recurring_service_plan',v_plan_id::text,'RecurringServicePlanCreatedV2',p_correlation_id,v_response,p_idempotency_key);perform private.finish_contract_command(v_request.client_organization_id,'recurring.plan.create.v2',p_idempotency_key,v_response);return v_response;
end$$;
revoke all on function public.create_recurring_service_plan(uuid,text,date,date,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.create_recurring_service_plan(uuid,text,date,date,text,text,uuid)to authenticated;
notify pgrst,'reload schema';
