-- MAT-FUNC-004/021/029/039/050/063/064: durable notification dispatch and domain schedulers.

alter table public.notification_deliveries
  add column lease_token uuid,
  add column lease_owner text,
  add column leased_until timestamptz,
  add column terminal_at timestamptz,
  add column provider_idempotency_key text;

alter table public.notification_deliveries add constraint notification_delivery_lease_shape check (
  (lease_token is null and lease_owner is null and leased_until is null)
  or (lease_token is not null and length(lease_owner) between 8 and 160 and leased_until is not null)
);
alter table public.notification_deliveries add constraint notification_delivery_terminal_shape check (
  (status in ('DELIVERED','DEAD_LETTER','SKIPPED'))=(terminal_at is not null)
) not valid;
alter table public.notification_deliveries add constraint notification_provider_idempotency_format check (
  provider_idempotency_key is null or length(provider_idempotency_key) between 16 and 200
);
update public.notification_deliveries set terminal_at=coalesce(updated_at,created_at)
where status in ('DELIVERED','DEAD_LETTER','SKIPPED');
update public.notification_deliveries set provider_idempotency_key='notification-delivery:'||id::text
where channel='EMAIL';
alter table public.notification_deliveries validate constraint notification_delivery_terminal_shape;
create function private.sync_notification_delivery_runtime_shape()returns trigger language plpgsql set search_path=pg_catalog as $$begin
 if new.status in('DELIVERED','DEAD_LETTER','SKIPPED')then new.terminal_at:=coalesce(new.terminal_at,clock_timestamp());new.next_attempt_at:=null;new.lease_token:=null;new.lease_owner:=null;new.leased_until:=null;
 elsif tg_op='UPDATE'and old.status='FAILED'and new.status='PENDING'then new.terminal_at:=null;new.lease_token:=null;new.lease_owner:=null;new.leased_until:=null;
 else new.terminal_at:=null;end if;return new;end$$;
create trigger notification_delivery_runtime_shape before insert or update on public.notification_deliveries for each row execute function private.sync_notification_delivery_runtime_shape();
create unique index notification_provider_idempotency_uidx on public.notification_deliveries(provider_idempotency_key)
  where provider_idempotency_key is not null;
create index notification_delivery_claim_lease_idx on public.notification_deliveries(next_attempt_at,leased_until,id)
  where status in ('PENDING','QUEUED_DIGEST','FAILED');

insert into public.notification_preference_categories(code,label_fr,label_ar,mandatory)values('DOCUMENTS_REQUIRED','Documents obligatoires','الوثائق الإلزامية',true);
insert into public.notification_template_versions(template_code,version,event_type,category_code,locale,subject_template,body_template,cta_path_template,priority,mandatory,channels,variable_keys,status,effective_from,content_hash)values
('REQUIRED_DOCUMENT_EXPIRY',1,'RequiredDocumentExpiryReminderV1','DOCUMENTS_REQUIRED','fr-MA','Document obligatoire : {{document_kind}}','Expiration : {{expires_on}} (jalon {{milestone}}). Remplacez ce document pour préserver uniquement vos éligibilités concernées.','/fr/sous-traitant/qualification','CRITICAL',true,array['IN_APP','EMAIL'],array['document_kind','expires_on','milestone'],'ACTIVE','2026-09-13',private.canonical_request_hash('{"template":"REQUIRED_DOCUMENT_EXPIRY","version":1,"locale":"fr-MA"}'::jsonb)),
('REQUIRED_DOCUMENT_EXPIRY',1,'RequiredDocumentExpiryReminderV1','DOCUMENTS_REQUIRED','ar-MA','وثيقة إلزامية: {{document_kind}}','تاريخ الانتهاء: {{expires_on}} (مرحلة {{milestone}}). استبدل هذه الوثيقة للحفاظ على الأهلية المعنية فقط.','/ar/sous-traitant/qualification','CRITICAL',true,array['IN_APP','EMAIL'],array['document_kind','expires_on','milestone'],'ACTIVE','2026-09-13',private.canonical_request_hash('{"template":"REQUIRED_DOCUMENT_EXPIRY","version":1,"locale":"ar-MA"}'::jsonb));

insert into public.notification_preference_categories(code,label_fr,label_ar,mandatory)values('DIAGNOSTIC_REQUIRED','Diagnostic à actualiser','تحديث التشخيص مطلوب',true);
insert into public.notification_template_versions(template_code,version,event_type,category_code,locale,subject_template,body_template,cta_path_template,priority,mandatory,channels,variable_keys,status,effective_from,content_hash)values
('DIAGNOSTIC_REEVALUATION_REQUIRED',1,'DiagnosticReevaluationRequiredV1','DIAGNOSTIC_REQUIRED','fr-MA','Diagnostic à actualiser','Une réponse arrivée à expiration doit être confirmée avant un nouveau calcul.','/fr/client/questionnaires','IMPORTANT',true,array['IN_APP','EMAIL'],'{}','ACTIVE','2026-09-13',private.canonical_request_hash('{"template":"DIAGNOSTIC_REEVALUATION_REQUIRED","version":1,"locale":"fr-MA"}'::jsonb)),
('DIAGNOSTIC_REEVALUATION_REQUIRED',1,'DiagnosticReevaluationRequiredV1','DIAGNOSTIC_REQUIRED','ar-MA','يجب تحديث التشخيص','يجب تأكيد إجابة منتهية الصلاحية قبل إجراء حساب جديد.','/ar/client/questionnaires','IMPORTANT',true,array['IN_APP','EMAIL'],'{}','ACTIVE','2026-09-13',private.canonical_request_hash('{"template":"DIAGNOSTIC_REEVALUATION_REQUIRED","version":1,"locale":"ar-MA"}'::jsonb));

-- A mandatory category is exceptional and must retain the versioned legal
-- justification that permits delivery without an end-user preference.
create table public.notification_mandatory_policy_versions(
 id uuid primary key default extensions.gen_random_uuid(),category_code text not null references public.notification_preference_categories(code)on delete restrict,version integer not null check(version>0),legal_basis text not null check(legal_basis in('LEGAL_OBLIGATION','CONTRACT')),legal_basis_reference text not null check(length(btrim(legal_basis_reference))between 8 and 240),status text not null check(status in('ACTIVE','RETIRED')),effective_from timestamptz not null,effective_until timestamptz,content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),unique(category_code,version),check(effective_until is null or effective_until>effective_from)
);
create unique index notification_mandatory_policy_one_active_uidx on public.notification_mandatory_policy_versions(category_code)where status='ACTIVE';
create function private.guard_notification_mandatory_policy_version()returns trigger language plpgsql set search_path=pg_catalog as $$begin if tg_op='DELETE'or row(old.category_code,old.version,old.legal_basis,old.legal_basis_reference,old.effective_from,old.content_hash)is distinct from row(new.category_code,new.version,new.legal_basis,new.legal_basis_reference,new.effective_from,new.content_hash)or old.status='RETIRED'or new.status<>'RETIRED'or new.effective_until is null then raise exception'IMMUTABLE_NOTIFICATION_MANDATORY_POLICY'using errcode='55000';end if;return new;end$$;
create trigger notification_mandatory_policy_immutable before update or delete on public.notification_mandatory_policy_versions for each row execute function private.guard_notification_mandatory_policy_version();
insert into public.notification_mandatory_policy_versions(category_code,version,legal_basis,legal_basis_reference,status,effective_from,content_hash)
select c.code,1,case when c.code='BILLING_CRITICAL'then'CONTRACT'else'LEGAL_OBLIGATION'end,'MATRICIA-GM-V4-NOTIFICATION-'||c.code,'ACTIVE','2026-09-13',private.canonical_request_hash(jsonb_build_object('category',c.code,'version',1,'basis',case when c.code='BILLING_CRITICAL'then'CONTRACT'else'LEGAL_OBLIGATION'end))from public.notification_preference_categories c where c.mandatory;
alter table public.notification_instances add column mandatory_policy_version_id uuid references public.notification_mandatory_policy_versions(id)on delete restrict,add column legal_basis text;
update public.notification_instances n set mandatory_policy_version_id=p.id,legal_basis=p.legal_basis from public.notification_mandatory_policy_versions p where n.mandatory and p.category_code=n.category_code and p.status='ACTIVE';
alter table public.notification_instances add constraint notification_mandatory_basis_snapshot check((not mandatory and mandatory_policy_version_id is null and legal_basis is null)or(mandatory and mandatory_policy_version_id is not null and legal_basis in('LEGAL_OBLIGATION','CONTRACT')))not valid;
alter table public.notification_instances validate constraint notification_mandatory_basis_snapshot;
alter table public.notification_mandatory_policy_versions enable row level security;
revoke all on public.notification_mandatory_policy_versions from public,anon,authenticated,service_role;

create table public.notification_email_consent_challenges(
 id uuid primary key default extensions.gen_random_uuid(),user_id uuid not null references auth.users(id)on delete restrict,organization_id uuid not null references public.organizations(id)on delete restrict,category_code text not null references public.notification_preference_categories(code)on delete restrict,consent_version integer not null check(consent_version>0),challenge_hash text not null check(challenge_hash~'^[0-9a-f]{64}$'),expires_at timestamptz not null,confirmed_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default clock_timestamp(),correlation_id uuid not null,unique(user_id,organization_id,category_code,consent_version),check(expires_at>created_at),check(not(confirmed_at is not null and revoked_at is not null))
);
create unique index notification_email_consent_active_uidx on public.notification_email_consent_challenges(user_id,organization_id,category_code)where confirmed_at is not null and revoked_at is null;
create function private.guard_notification_email_consent()returns trigger language plpgsql set search_path=pg_catalog as $$begin if tg_op='DELETE'or row(old.id,old.user_id,old.organization_id,old.category_code,old.consent_version,old.challenge_hash,old.expires_at,old.created_at,old.correlation_id)is distinct from row(new.id,new.user_id,new.organization_id,new.category_code,new.consent_version,new.challenge_hash,new.expires_at,new.created_at,new.correlation_id)or old.revoked_at is not null or(old.confirmed_at is not null and new.confirmed_at is distinct from old.confirmed_at)or(new.confirmed_at is not null and old.confirmed_at is null and clock_timestamp()>old.expires_at)then raise exception'IMMUTABLE_NOTIFICATION_EMAIL_CONSENT'using errcode='55000';end if;return new;end$$;
create trigger notification_email_consent_guard before update or delete on public.notification_email_consent_challenges for each row execute function private.guard_notification_email_consent();
alter table public.notification_email_consent_challenges enable row level security;
create policy notification_email_consent_self_read on public.notification_email_consent_challenges for select to authenticated using(user_id=auth.uid()and private.is_active_org_member(organization_id,auth.uid()));
revoke all on public.notification_email_consent_challenges from public,anon,authenticated,service_role;grant select on public.notification_email_consent_challenges to authenticated;

create function public.request_notification_email_consent(p_organization_id uuid,p_category_code text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();c record;v integer;raw_token text;h text;r jsonb;cached jsonb;begin if a is null or not private.is_active_org_member(p_organization_id,a)then raise exception'NOTIFICATION_EMAIL_CONSENT_DENIED'using errcode='42501';end if;select*into c from public.notification_preference_categories where code=p_category_code and status='ACTIVE'and not mandatory;if not found or length(coalesce(p_idempotency_key,''))not between 8 and 200 then raise exception'INVALID_NOTIFICATION_EMAIL_CONSENT'using errcode='22023';end if;h:=private.canonical_request_hash(jsonb_build_object('organization_id',p_organization_id,'category_code',p_category_code));cached:=private.begin_contract_command(p_organization_id,'notification.email_consent.request.'||p_category_code,p_idempotency_key,h,a);if cached is not null then return cached;end if;select coalesce(max(consent_version),0)+1 into v from public.notification_email_consent_challenges where user_id=a and organization_id=p_organization_id and category_code=p_category_code;raw_token:=encode(extensions.gen_random_bytes(32),'hex');insert into public.notification_email_consent_challenges(user_id,organization_id,category_code,consent_version,challenge_hash,expires_at,correlation_id)values(a,p_organization_id,p_category_code,v,encode(extensions.digest(convert_to(raw_token,'UTF8'),'sha256'),'hex'),clock_timestamp()+interval'30 minutes',p_correlation_id);r:=jsonb_build_object('outcome','NOTIFICATION_EMAIL_CONSENT_CHALLENGE_ISSUED','category_code',p_category_code,'consent_version',v,'challenge_token',raw_token,'expires_in_seconds',1800);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','notification.email_consent.challenge_issued','notification_email_consent',p_category_code,p_correlation_id,jsonb_build_object('consent_version',v,'expires_in_seconds',1800),repeat('0',64));perform private.finish_contract_command(p_organization_id,'notification.email_consent.request.'||p_category_code,p_idempotency_key,r);return r;end$$;
create function public.confirm_notification_email_consent(p_organization_id uuid,p_category_code text,p_consent_version integer,p_challenge_token text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();x public.notification_email_consent_challenges%rowtype;h text;r jsonb;cached jsonb;begin if a is null or not private.is_active_org_member(p_organization_id,a)then raise exception'NOTIFICATION_EMAIL_CONSENT_DENIED'using errcode='42501';end if;h:=private.canonical_request_hash(jsonb_build_object('organization_id',p_organization_id,'category_code',p_category_code,'consent_version',p_consent_version,'challenge_token_hash',encode(extensions.digest(convert_to(coalesce(p_challenge_token,''),'UTF8'),'sha256'),'hex')));cached:=private.begin_contract_command(p_organization_id,'notification.email_consent.confirm.'||p_category_code,p_idempotency_key,h,a);if cached is not null then return cached;end if;select*into x from public.notification_email_consent_challenges where user_id=a and organization_id=p_organization_id and category_code=p_category_code and consent_version=p_consent_version for update;if not found or x.confirmed_at is not null or x.revoked_at is not null or x.expires_at<=clock_timestamp()or x.challenge_hash<>encode(extensions.digest(convert_to(coalesce(p_challenge_token,''),'UTF8'),'sha256'),'hex')then raise exception'INVALID_NOTIFICATION_EMAIL_CONSENT_CHALLENGE'using errcode='22023';end if;update public.notification_email_consent_challenges set confirmed_at=clock_timestamp()where id=x.id;r:=jsonb_build_object('outcome','NOTIFICATION_EMAIL_CONSENT_CONFIRMED','category_code',p_category_code,'consent_version',p_consent_version,'confirmed_at',clock_timestamp());insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','notification.email_consent.confirmed','notification_email_consent',x.id::text,p_correlation_id,jsonb_build_object('category_code',p_category_code,'consent_version',p_consent_version),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'notification_email_consent',x.id::text,'NotificationEmailConsentConfirmedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'notification.email_consent.confirm.'||p_category_code,p_idempotency_key,r);return r;end$$;
create function public.revoke_notification_email_consent(p_organization_id uuid,p_category_code text,p_consent_version integer,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare a uuid:=auth.uid();x public.notification_email_consent_challenges%rowtype;h text;r jsonb;cached jsonb;begin if a is null or not private.is_active_org_member(p_organization_id,a)then raise exception'NOTIFICATION_EMAIL_CONSENT_DENIED'using errcode='42501';end if;h:=private.canonical_request_hash(jsonb_build_object('organization_id',p_organization_id,'category_code',p_category_code,'consent_version',p_consent_version));cached:=private.begin_contract_command(p_organization_id,'notification.email_consent.revoke.'||p_category_code,p_idempotency_key,h,a);if cached is not null then return cached;end if;select*into x from public.notification_email_consent_challenges where user_id=a and organization_id=p_organization_id and category_code=p_category_code and consent_version=p_consent_version and confirmed_at is not null and revoked_at is null for update;if not found then raise exception'NOTIFICATION_EMAIL_CONSENT_NOT_ACTIVE'using errcode='55000';end if;update public.notification_email_consent_challenges set revoked_at=clock_timestamp()where id=x.id;r:=jsonb_build_object('outcome','NOTIFICATION_EMAIL_CONSENT_REVOKED','category_code',p_category_code,'consent_version',p_consent_version);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','notification.email_consent.revoked','notification_email_consent',x.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'notification_email_consent',x.id::text,'NotificationEmailConsentRevokedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'notification.email_consent.revoke.'||p_category_code,p_idempotency_key,r);return r;end$$;
create function private.notification_email_consent_active(p_user_id uuid,p_organization_id uuid,p_category_code text)returns boolean language sql stable security definer set search_path=pg_catalog,public as $$select exists(select 1 from public.notification_email_consent_challenges c where c.user_id=p_user_id and c.organization_id=p_organization_id and c.category_code=p_category_code and c.confirmed_at is not null and c.revoked_at is null and c.consent_version=(select max(v.consent_version)from public.notification_email_consent_challenges v where v.user_id=p_user_id and v.organization_id=p_organization_id and v.category_code=p_category_code))$$;

create or replace function public.enqueue_notification(p_recipient_user_id uuid,p_organization_id uuid,p_template_code text,p_event_type text,p_locale text,p_variables jsonb,p_deduplication_key text,p_source_aggregate_type text,p_source_aggregate_id text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare t public.notification_template_versions%rowtype;nid uuid;ch text;mode text;nextat timestamptz;r jsonb;mandatory_policy public.notification_mandatory_policy_versions%rowtype;
begin
 if auth.role()is distinct from'service_role'then raise exception'NOTIFICATION_ENQUEUE_DENIED'using errcode='42501';end if;
 if not private.is_active_org_member(p_organization_id,p_recipient_user_id)or jsonb_typeof(p_variables)<>'object'or length(coalesce(p_deduplication_key,''))not between 8 and 200 or length(coalesce(p_source_aggregate_type,''))not between 2 and 100 or length(coalesce(p_source_aggregate_id,''))not between 1 and 200 or exists(select 1 from jsonb_object_keys(p_variables)k where k~*'(password|secret|token|api.?key)')then raise exception'INVALID_NOTIFICATION_REQUEST'using errcode='22023';end if;
 select*into t from public.notification_template_versions where template_code=p_template_code and event_type=p_event_type and locale=p_locale and status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp())order by version desc limit 1;if not found then raise exception'NOTIFICATION_TEMPLATE_NOT_FOUND'using errcode='P0002';end if;
 if exists(select 1 from jsonb_object_keys(p_variables)k where not(k=any(t.variable_keys)))then raise exception'UNKNOWN_NOTIFICATION_VARIABLE'using errcode='22023';end if;
 if t.mandatory then select*into mandatory_policy from public.notification_mandatory_policy_versions where category_code=t.category_code and status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp())order by version desc limit 1;if not found then raise exception'MANDATORY_NOTIFICATION_LEGAL_BASIS_MISSING'using errcode='55000';end if;end if;
 insert into public.notification_instances(recipient_user_id,organization_id,template_version_id,category_code,event_type,locale,subject,body,cta_path,priority,mandatory,mandatory_policy_version_id,legal_basis,deduplication_key,source_aggregate_type,source_aggregate_id,variables_snapshot,correlation_id)values(p_recipient_user_id,p_organization_id,t.id,t.category_code,t.event_type,t.locale,private.render_notification_text(t.subject_template,p_variables),private.render_notification_text(t.body_template,p_variables),case when t.cta_path_template is null then null else private.render_notification_text(t.cta_path_template,p_variables)end,t.priority,t.mandatory,mandatory_policy.id,mandatory_policy.legal_basis,p_deduplication_key,p_source_aggregate_type,p_source_aggregate_id,p_variables,p_correlation_id)on conflict(recipient_user_id,organization_id,deduplication_key)do nothing returning id into nid;
 if nid is null then select id into nid from public.notification_instances where recipient_user_id=p_recipient_user_id and organization_id=p_organization_id and deduplication_key=p_deduplication_key;return jsonb_build_object('outcome','NOTIFICATION_DEDUPLICATED','notification_id',nid);end if;
 foreach ch in array t.channels loop
  mode:=null;select delivery_mode into mode from public.user_notification_preferences where user_id=p_recipient_user_id and organization_id=p_organization_id and category_code=t.category_code and channel=ch;
  if t.mandatory then mode:='IMMEDIATE';elsif ch='EMAIL'and(mode not in('IMMEDIATE','DIGEST')or not private.notification_email_consent_active(p_recipient_user_id,p_organization_id,t.category_code))then mode:='DISABLED';elsif mode is null then mode:='IMMEDIATE';end if;
  nextat:=case mode when'DISABLED'then null when'DIGEST'then date_trunc('day',clock_timestamp())+interval'1 day 8 hours'else clock_timestamp()end;
  insert into public.notification_deliveries(notification_id,channel,delivery_mode,status,next_attempt_at)values(nid,ch,mode,case mode when'DISABLED'then'SKIPPED'when'DIGEST'then'QUEUED_DIGEST'else'PENDING'end,nextat);
 end loop;
 r:=jsonb_build_object('outcome','NOTIFICATION_ENQUEUED','notification_id',nid,'template_version_id',t.id);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,null,'SERVICE','notification.enqueued','notification',nid::text,p_correlation_id,jsonb_build_object('template_code',t.template_code,'template_version',t.version,'recipient_user_id',p_recipient_user_id,'mandatory_policy_version_id',mandatory_policy.id,'legal_basis',mandatory_policy.legal_basis),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload)values(p_organization_id,'notification',nid::text,'NotificationPreparedV1',p_correlation_id,r);return r;
end$$;

create table private.notification_worker_command_keys(delivery_id uuid not null references public.notification_deliveries(id)on delete restrict,idempotency_key text not null,request_hash text not null check(request_hash~'^[0-9a-f]{64}$'),response_body jsonb,created_at timestamptz not null default clock_timestamp(),completed_at timestamptz,primary key(delivery_id,idempotency_key));
create trigger notification_worker_commands_immutable before update or delete on private.notification_worker_command_keys for each row when(old.completed_at is not null)execute function private.prevent_notification_history_change();
revoke all on private.notification_worker_command_keys from public,anon,authenticated,service_role;

create or replace function public.claim_notification_deliveries_v1(
  p_worker_id text,p_limit integer default 20,p_lease_seconds integer default 120
) returns setof jsonb language plpgsql security definer
set search_path=pg_catalog,public,private,extensions as $$
declare d record;token uuid;
begin
 if auth.role() is distinct from 'service_role' then raise exception 'NOTIFICATION_CLAIM_DENIED' using errcode='42501';end if;
 if length(btrim(coalesce(p_worker_id,'')))not between 8 and 160 or p_limit not between 1 and 100 or p_lease_seconds not between 30 and 900 then raise exception 'INVALID_NOTIFICATION_CLAIM' using errcode='22023';end if;
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)
 select n.organization_id,null,'SERVICE','notification.delivery.preference_blocked','notification_delivery',delivery.id::text,n.correlation_id,jsonb_build_object('reason','PREFERENCE_OR_CONSENT_NOT_GRANTED','channel','EMAIL'),repeat('0',64)from public.notification_deliveries delivery join public.notification_instances n on n.id=delivery.notification_id where delivery.channel='EMAIL'and not n.mandatory and delivery.status in('PENDING','QUEUED_DIGEST','FAILED')and(not private.notification_email_consent_active(n.recipient_user_id,n.organization_id,n.category_code)or not exists(select 1 from public.user_notification_preferences p where p.user_id=n.recipient_user_id and p.organization_id=n.organization_id and p.category_code=n.category_code and p.channel='EMAIL'and p.delivery_mode in('IMMEDIATE','DIGEST')and p.delivery_mode=delivery.delivery_mode));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)
 select n.organization_id,'notification_delivery',delivery.id::text,'NotificationDeliveryBlockedV1',n.correlation_id,jsonb_build_object('delivery_id',delivery.id,'reason','PREFERENCE_OR_CONSENT_NOT_GRANTED'),'notification-preference-not-granted:'||delivery.id::text from public.notification_deliveries delivery join public.notification_instances n on n.id=delivery.notification_id where delivery.channel='EMAIL'and not n.mandatory and delivery.status in('PENDING','QUEUED_DIGEST','FAILED')and(not private.notification_email_consent_active(n.recipient_user_id,n.organization_id,n.category_code)or not exists(select 1 from public.user_notification_preferences p where p.user_id=n.recipient_user_id and p.organization_id=n.organization_id and p.category_code=n.category_code and p.channel='EMAIL'and p.delivery_mode in('IMMEDIATE','DIGEST')and p.delivery_mode=delivery.delivery_mode))on conflict do nothing;
 update public.notification_deliveries delivery set status='SKIPPED',next_attempt_at=null,last_error_code='PREFERENCE_NOT_GRANTED',terminal_at=clock_timestamp(),lease_token=null,lease_owner=null,leased_until=null,row_version=delivery.row_version+1,updated_at=clock_timestamp()
 from public.notification_instances n where n.id=delivery.notification_id and delivery.channel='EMAIL'and not n.mandatory and delivery.status in('PENDING','QUEUED_DIGEST','FAILED')and(not private.notification_email_consent_active(n.recipient_user_id,n.organization_id,n.category_code)or not exists(select 1 from public.user_notification_preferences p where p.user_id=n.recipient_user_id and p.organization_id=n.organization_id and p.category_code=n.category_code and p.channel='EMAIL'and p.delivery_mode in('IMMEDIATE','DIGEST')and p.delivery_mode=delivery.delivery_mode));
 for d in
  select delivery.id
  from public.notification_deliveries delivery join public.notification_instances ni on ni.id=delivery.notification_id
  where delivery.status in('PENDING','QUEUED_DIGEST','FAILED')
    and delivery.next_attempt_at<=clock_timestamp()
    and(delivery.leased_until is null or delivery.leased_until<=clock_timestamp())
    and(delivery.channel<>'EMAIL'or(ni.mandatory and exists(select 1 from public.notification_mandatory_policy_versions mp where mp.id=ni.mandatory_policy_version_id and mp.category_code=ni.category_code and mp.status='ACTIVE'and mp.effective_from<=clock_timestamp()and(mp.effective_until is null or mp.effective_until>clock_timestamp())))or(not ni.mandatory and private.notification_email_consent_active(ni.recipient_user_id,ni.organization_id,ni.category_code)and exists(select 1 from public.user_notification_preferences p where p.user_id=ni.recipient_user_id and p.organization_id=ni.organization_id and p.category_code=ni.category_code and p.channel='EMAIL'and p.delivery_mode in('IMMEDIATE','DIGEST')and p.delivery_mode=delivery.delivery_mode)))
  order by delivery.next_attempt_at,delivery.id for update skip locked limit p_limit
 loop
  token:=extensions.gen_random_uuid();
  update public.notification_deliveries set lease_token=token,lease_owner=btrim(p_worker_id),leased_until=clock_timestamp()+make_interval(secs=>p_lease_seconds),provider_idempotency_key=case when channel='EMAIL'then coalesce(provider_idempotency_key,'notification-delivery:'||id::text)else provider_idempotency_key end,row_version=row_version+1,updated_at=clock_timestamp()where id=d.id;
  return next(
   select jsonb_build_object('outcome','NOTIFICATION_CLAIMED','delivery_id',x.id,'lease_token',x.lease_token,'worker_id',x.lease_owner,'row_version',x.row_version,'channel',x.channel,'attempt',x.attempt_count+1,'provider_idempotency_key',x.provider_idempotency_key,'recipient_email',case when x.channel='EMAIL'then u.email end,'locale',n.locale,'subject',n.subject,'body',n.body,'cta_path',n.cta_path,'mandatory',n.mandatory,'organization_id',n.organization_id,'notification_id',n.id)
   from public.notification_deliveries x join public.notification_instances n on n.id=x.notification_id join auth.users u on u.id=n.recipient_user_id where x.id=d.id
  );
 end loop;
end$$;

create function public.authorize_notification_delivery_send_v1(p_delivery_id uuid,p_lease_token uuid,p_worker_id text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare d public.notification_deliveries%rowtype;n public.notification_instances%rowtype;allowed boolean:=false;r jsonb;
begin
 if auth.role()is distinct from'service_role'then raise exception'NOTIFICATION_SEND_AUTH_DENIED'using errcode='42501';end if;
 select*into d from public.notification_deliveries where id=p_delivery_id for update;select*into n from public.notification_instances where id=d.notification_id;
 if d.id is null or d.lease_token is distinct from p_lease_token or d.lease_owner is distinct from btrim(p_worker_id)or d.leased_until<=clock_timestamp()then raise exception'NOTIFICATION_LEASE_INVALID'using errcode='40001';end if;
 if d.channel<>'EMAIL'then allowed:=true;
 elsif n.mandatory then allowed:=exists(select 1 from public.notification_mandatory_policy_versions mp where mp.id=n.mandatory_policy_version_id and mp.category_code=n.category_code and mp.legal_basis=n.legal_basis and mp.status='ACTIVE'and mp.effective_from<=clock_timestamp()and(mp.effective_until is null or mp.effective_until>clock_timestamp()));
 else allowed:=private.notification_email_consent_active(n.recipient_user_id,n.organization_id,n.category_code)and exists(select 1 from public.user_notification_preferences p where p.user_id=n.recipient_user_id and p.organization_id=n.organization_id and p.category_code=n.category_code and p.channel='EMAIL'and p.delivery_mode in('IMMEDIATE','DIGEST')and p.delivery_mode=d.delivery_mode);
 end if;
 if allowed then return jsonb_build_object('outcome','NOTIFICATION_SEND_AUTHORIZED','authorized',true,'delivery_id',d.id);end if;
 update public.notification_deliveries set status='SKIPPED',next_attempt_at=null,last_error_code=case when n.mandatory then'MANDATORY_LEGAL_BASIS_INACTIVE'else'PREFERENCE_WITHDRAWN'end,lease_token=null,lease_owner=null,leased_until=null,terminal_at=clock_timestamp(),row_version=row_version+1,updated_at=clock_timestamp()where id=d.id;
 r:=jsonb_build_object('outcome','NOTIFICATION_SEND_BLOCKED','authorized',false,'delivery_id',d.id,'reason',case when n.mandatory then'MANDATORY_LEGAL_BASIS_INACTIVE'else'PREFERENCE_WITHDRAWN'end);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(n.organization_id,null,'SERVICE','notification.delivery.send_blocked','notification_delivery',d.id::text,p_correlation_id,r,repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(n.organization_id,'notification_delivery',d.id::text,'NotificationDeliveryBlockedV1',p_correlation_id,r,'notification-send-blocked:'||d.id::text||':'||d.row_version::text)on conflict do nothing;
 return r;
end$$;

create or replace function public.record_notification_delivery_worker_result_v1(
 p_delivery_id uuid,p_lease_token uuid,p_worker_id text,p_outcome text,p_provider_message_id text,p_error_code text,p_result_snapshot jsonb,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid()
)returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare d public.notification_deliveries%rowtype;n public.notification_instances%rowtype;pol public.notification_retry_policy_versions%rowtype;prior public.notification_delivery_attempts%rowtype;attempt integer;nextat timestamptz;newstatus text;r jsonb;delay_seconds integer;attempt_status text;h text;cached jsonb;
begin
 if auth.role()is distinct from'service_role'then raise exception'NOTIFICATION_RESULT_DENIED'using errcode='42501';end if;
 h:=private.canonical_request_hash(jsonb_build_object('delivery_id',p_delivery_id,'lease_token',p_lease_token,'worker_id',btrim(p_worker_id),'outcome',p_outcome,'provider_message_id',p_provider_message_id,'error_code',p_error_code,'result',p_result_snapshot));perform pg_advisory_xact_lock(hashtextextended(p_delivery_id::text||':'||coalesce(p_idempotency_key,''),0));select request_hash,response_body into h,cached from private.notification_worker_command_keys where delivery_id=p_delivery_id and idempotency_key=p_idempotency_key;if found then if h<>private.canonical_request_hash(jsonb_build_object('delivery_id',p_delivery_id,'lease_token',p_lease_token,'worker_id',btrim(p_worker_id),'outcome',p_outcome,'provider_message_id',p_provider_message_id,'error_code',p_error_code,'result',p_result_snapshot))then raise exception'IDEMPOTENCY_PAYLOAD_MISMATCH'using errcode='22000';end if;if cached is not null then return cached||jsonb_build_object('outcome','NOTIFICATION_RESULT_REPLAYED');end if;raise exception'IDEMPOTENCY_IN_PROGRESS'using errcode='55000';end if;h:=private.canonical_request_hash(jsonb_build_object('delivery_id',p_delivery_id,'lease_token',p_lease_token,'worker_id',btrim(p_worker_id),'outcome',p_outcome,'provider_message_id',p_provider_message_id,'error_code',p_error_code,'result',p_result_snapshot));insert into private.notification_worker_command_keys(delivery_id,idempotency_key,request_hash)values(p_delivery_id,p_idempotency_key,h);
 select*into d from public.notification_deliveries where id=p_delivery_id for update;
 if not found or d.lease_token is distinct from p_lease_token or d.lease_owner is distinct from btrim(p_worker_id)or d.leased_until<=clock_timestamp()then raise exception'NOTIFICATION_LEASE_INVALID'using errcode='40001';end if;
 if p_outcome not in('DELIVERED','RETRYABLE_FAILURE','PERMANENT_FAILURE')or jsonb_typeof(p_result_snapshot)<>'object'or length(coalesce(p_idempotency_key,''))not between 8 and 200 then raise exception'INVALID_NOTIFICATION_RESULT'using errcode='22023';end if;
 if p_outcome='DELIVERED'and(p_error_code is not null or length(coalesce(p_provider_message_id,''))<3)then raise exception'INVALID_NOTIFICATION_RESULT'using errcode='22023';end if;
 if p_outcome<>'DELIVERED'and length(coalesce(p_error_code,''))<2 then raise exception'INVALID_NOTIFICATION_RESULT'using errcode='22023';end if;
 select*into n from public.notification_instances where id=d.notification_id;select*into pol from public.notification_retry_policy_versions where status='ACTIVE'order by version desc limit 1;if pol.id is null then raise exception'NOTIFICATION_RETRY_POLICY_MISSING'using errcode='55000';end if;
 attempt:=d.attempt_count+1;attempt_status:=case when p_outcome='DELIVERED'then'DELIVERED'else'FAILED'end;
 if p_outcome='DELIVERED'then newstatus:='DELIVERED';nextat:=null;
 elsif p_outcome='PERMANENT_FAILURE'or attempt>=pol.max_attempts then newstatus:='DEAD_LETTER';nextat:=null;
 else delay_seconds:=least(pol.max_backoff_seconds,(pol.base_backoff_seconds*power(2,attempt-1))::integer);newstatus:='FAILED';nextat:=clock_timestamp()+make_interval(secs=>delay_seconds);end if;
 insert into public.notification_delivery_attempts(delivery_id,attempt_number,status,scheduled_at,next_retry_at,provider_message_id,error_code,result_snapshot,idempotency_key,correlation_id)values(d.id,attempt,attempt_status,d.next_attempt_at,nextat,p_provider_message_id,p_error_code,p_result_snapshot,p_idempotency_key,p_correlation_id);
 update public.notification_deliveries set status=newstatus,attempt_count=attempt,next_attempt_at=nextat,last_error_code=p_error_code,provider_message_id=coalesce(p_provider_message_id,provider_message_id),lease_token=null,lease_owner=null,leased_until=null,terminal_at=case when newstatus in('DELIVERED','DEAD_LETTER')then clock_timestamp()end,row_version=row_version+1,updated_at=clock_timestamp()where id=d.id;
 r:=jsonb_build_object('outcome','NOTIFICATION_RESULT_RECORDED','delivery_id',d.id,'status',newstatus,'attempt_count',attempt,'next_retry_at',nextat);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(n.organization_id,null,'SERVICE','notification.delivery.worker_result','notification_delivery',d.id::text,p_correlation_id,jsonb_build_object('channel',d.channel,'status',newstatus,'attempt_count',attempt,'error_code',p_error_code,'worker_id_hash',encode(extensions.digest(convert_to(btrim(p_worker_id),'UTF8'),'sha256'),'hex')),repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(n.organization_id,'notification_delivery',d.id::text,case newstatus when'DELIVERED'then'NotificationDeliveredV1'when'DEAD_LETTER'then'NotificationDeadLetteredV1'else'NotificationDeliveryRetryScheduledV1'end,p_correlation_id,r,p_idempotency_key)on conflict do nothing;
 update private.notification_worker_command_keys set response_body=r,completed_at=clock_timestamp()where delivery_id=p_delivery_id and idempotency_key=p_idempotency_key;
 return r;
end$$;

create table public.domain_automation_runs(
 id uuid primary key default extensions.gen_random_uuid(),run_kind text not null check(run_kind in('DIAGNOSTIC_REEVALUATION','CALENDAR_PROJECTION','DOCUMENT_EXPIRATION','RECURRING_REQUESTS')),as_of date not null,status text not null check(status in('PENDING','PARTIAL','COMPLETED')),cursor_snapshot jsonb not null default'{}'check(jsonb_typeof(cursor_snapshot)='object'),result_snapshot jsonb not null check(jsonb_typeof(result_snapshot)='object'),correlation_id uuid not null,started_at timestamptz not null default clock_timestamp(),completed_at timestamptz,unique(run_kind,as_of),check((status='COMPLETED')=(completed_at is not null)));
create function private.protect_domain_automation_run()returns trigger language plpgsql set search_path=pg_catalog as $$begin if tg_op='DELETE'or old.status='COMPLETED'or new.id<>old.id or new.run_kind<>old.run_kind or new.as_of<>old.as_of or new.started_at<>old.started_at or new.status not in('PARTIAL','COMPLETED')or coalesce((new.cursor_snapshot->>'pages')::integer,0)<>coalesce((old.cursor_snapshot->>'pages')::integer,0)+1 then raise exception'IMMUTABLE_DOMAIN_AUTOMATION_RUN'using errcode='55000';end if;return new;end$$;
create trigger domain_automation_runs_immutable before update or delete on public.domain_automation_runs for each row execute function private.protect_domain_automation_run();
alter table public.domain_automation_runs enable row level security;
revoke all on public.domain_automation_runs from public,anon,authenticated,service_role;
create table public.domain_automation_run_pages(id bigint generated always as identity primary key,run_id uuid not null references public.domain_automation_runs(id)on delete restrict,page_number integer not null check(page_number>0),status text not null check(status in('PARTIAL','COMPLETED')),cursor_snapshot jsonb not null check(jsonb_typeof(cursor_snapshot)='object'),result_snapshot jsonb not null check(jsonb_typeof(result_snapshot)='object'),correlation_id uuid not null,created_at timestamptz not null default clock_timestamp(),unique(run_id,page_number));
create trigger domain_automation_run_pages_immutable before update or delete on public.domain_automation_run_pages for each row execute function private.prevent_notification_history_change();
alter table public.domain_automation_run_pages enable row level security;revoke all on public.domain_automation_run_pages from public,anon,authenticated,service_role;

create table public.diagnostic_reevaluation_queue(
 id uuid primary key default extensions.gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,questionnaire_session_id uuid not null references public.questionnaire_sessions(id)on delete restrict,reason_code text not null check(reason_code in('ANSWER_EXPIRED','PROFILE_CHANGED')),status text not null default'PENDING'check(status in('PENDING','WAITING_USER','COMPLETED','CANCELLED')),source_manifest_hash text check(source_manifest_hash is null or source_manifest_hash~'^[0-9a-f]{64}$'),actioned_at timestamptz,created_at timestamptz not null default clock_timestamp(),unique(questionnaire_session_id,reason_code),check((status='WAITING_USER')=(actioned_at is not null)));
alter table public.diagnostic_reevaluation_queue enable row level security;
revoke all on public.diagnostic_reevaluation_queue from public,anon,authenticated,service_role;

create function private.enqueue_profile_changed_diagnostic_reevaluation()returns trigger language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$declare item record;corr uuid;begin
 for item in select s.id,s.answer_manifest_hash from public.questionnaire_sessions s where s.organization_id=new.organization_id and s.audience='CLIENT'and s.status='SUBMITTED' loop
  insert into public.diagnostic_reevaluation_queue(organization_id,questionnaire_session_id,reason_code,source_manifest_hash)values(new.organization_id,item.id,'PROFILE_CHANGED',item.answer_manifest_hash)on conflict do nothing;
  if found then corr:=extensions.gen_random_uuid();insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(new.organization_id,new.created_by,'USER','diagnostic.reevaluation.profile_changed.queued','questionnaire_session',item.id::text,corr,jsonb_build_object('profile_version',new.version),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(new.organization_id,'questionnaire_session',item.id::text,'DiagnosticReevaluationQueuedV1',corr,jsonb_build_object('session_id',item.id,'reason_code','PROFILE_CHANGED','profile_version',new.version),'diagnostic-profile-changed:'||item.id::text||':'||new.version::text)on conflict do nothing;end if;
 end loop;return new;end$$;
create trigger client_profile_changed_diagnostic_reevaluation after insert on public.client_profile_versions for each row execute function private.enqueue_profile_changed_diagnostic_reevaluation();
revoke all on function private.enqueue_profile_changed_diagnostic_reevaluation()from public,anon,authenticated,service_role;

-- Replace the legacy first-page scheduler with a pending-work page. Completed
-- plans disappear from the workset, so later UUID pages cannot starve.
create or replace function public.schedule_recurring_service_requests(p_as_of date default current_date,p_limit integer default 100) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare candidate record;plan_row public.recurring_service_plans%rowtype;version_row public.recurring_service_plan_versions%rowtype;generated jsonb;next_date date;last_date date;months integer;iterations integer;processed integer:=0;created integer:=0;skipped integer:=0;correlation uuid;
begin
 if auth.role()<>'service_role'then raise exception'RECURRING_SCHEDULER_DENIED'using errcode='42501';end if;if p_as_of is null or p_as_of<current_date-1 or p_as_of>current_date+31 or p_limit not between 1 and 500 then raise exception'INVALID_RECURRING_SCHEDULER_BOUNDS'using errcode='22023';end if;
 for candidate in select p.id,m.user_id actor_user_id from public.recurring_service_plans p join public.recurring_service_plan_versions v on v.plan_id=p.id and v.version_number=p.current_version and v.status='ACTIVE'join lateral(select om.user_id from public.organization_memberships om join public.organization_member_roles r on r.membership_id=om.id and r.revoked_at is null and r.role_code in('CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER')where om.organization_id=p.client_organization_id and om.status='ACTIVE'order by case r.role_code when'CLIENT_OWNER'then 1 when'CLIENT_ADMIN'then 2 else 3 end,om.user_id limit 1)m on true where p.status='ACTIVE'and v.starts_on<=p_as_of and exists(select 1 from generate_series(v.starts_on::timestamp,least(p_as_of,coalesce(v.ends_on,p_as_of))::timestamp,make_interval(months=>case v.cadence when'MONTHLY'then 1 when'QUARTERLY'then 3 when'ANNUALLY'then 12 end))due where not exists(select 1 from public.recurring_service_occurrences o where o.plan_id=p.id and o.scheduled_on=due::date))order by p.id limit p_limit
 loop
  processed:=processed+1;iterations:=0;perform pg_advisory_xact_lock(hashtextextended('recurring-plan:'||candidate.id::text,0));select*into plan_row from public.recurring_service_plans where id=candidate.id and status='ACTIVE'for update;if not found then skipped:=skipped+1;continue;end if;select*into version_row from public.recurring_service_plan_versions where plan_id=plan_row.id and version_number=plan_row.current_version and status='ACTIVE';months:=case version_row.cadence when'MONTHLY'then 1 when'QUARTERLY'then 3 when'ANNUALLY'then 12 end;if months is null then skipped:=skipped+1;continue;end if;select max(o.scheduled_on)into last_date from public.recurring_service_occurrences o where o.plan_id=plan_row.id;next_date:=case when last_date is null then version_row.starts_on else(last_date+make_interval(months=>months))::date end;
  while next_date<=p_as_of and(version_row.ends_on is null or next_date<=version_row.ends_on)and iterations<24 loop iterations:=iterations+1;if not exists(select 1 from public.recurring_service_occurrences o where o.plan_id=plan_row.id and o.scheduled_on=next_date)then generated:=private.clone_request_core(plan_row.template_request_id,next_date,candidate.actor_user_id,'Génération planifiée automatique',false);insert into public.recurring_service_occurrences(plan_id,plan_version_id,client_organization_id,scheduled_on,generated_request_id,generated_request_version_id)values(plan_row.id,version_row.id,plan_row.client_organization_id,next_date,(generated->>'request_id')::uuid,(generated->>'request_version_id')::uuid)on conflict(plan_id,scheduled_on)do nothing;if found then created:=created+1;correlation:=extensions.gen_random_uuid();insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(plan_row.client_organization_id,candidate.actor_user_id,'SYSTEM','recurring.requests.scheduled','recurring_service_plan',plan_row.id::text,correlation,jsonb_build_object('scheduled_on',next_date,'plan_version_id',version_row.id,'autonomous_invitations',false,'autonomous_spend',false),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(plan_row.client_organization_id,'recurring_service_plan',plan_row.id::text,'RecurringServiceRequestScheduledV1',correlation,jsonb_build_object('plan_id',plan_row.id,'request_id',generated->>'request_id','scheduled_on',next_date,'autonomous_invitations',false,'autonomous_spend',false),'recurring-scheduler:'||plan_row.id::text||':'||next_date::text)on conflict do nothing;end if;end if;next_date:=(next_date+make_interval(months=>months))::date;end loop;
 end loop;return jsonb_build_object('outcome','RECURRING_SCHEDULER_PAGE_PROCESSED','as_of',p_as_of,'processed_plans',processed,'created_drafts',created,'skipped_plans',skipped,'per_plan_iteration_limit',24,'autonomous_invitations',false,'autonomous_spend',false);
end$$;

create or replace function public.run_domain_automation_schedulers_v1(p_as_of date default current_date,p_limit integer default 100)returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare corr uuid:=extensions.gen_random_uuid();actor uuid;queued integer:=0;calendar_count integer:=0;suspended integer:=0;recurring jsonb;row_item record;diagnostic_more boolean;calendar_more boolean;document_more boolean;recurring_more boolean;final_outcome text;
begin
 if auth.role()is distinct from'service_role'then raise exception'DOMAIN_SCHEDULER_DENIED'using errcode='42501';end if;if p_as_of is null or p_as_of<current_date-1 or p_as_of>current_date+31 or p_limit not between 1 and 500 then raise exception'INVALID_DOMAIN_SCHEDULER_BOUNDS'using errcode='22023';end if;
 if not pg_try_advisory_xact_lock(hashtextextended('domain-automation-schedulers:'||p_as_of::text,0))then return jsonb_build_object('outcome','DOMAIN_AUTOMATIONS_ALREADY_RUNNING','as_of',p_as_of);end if;
 if(select count(*)=4 from public.domain_automation_runs where as_of=p_as_of and status='COMPLETED')then return jsonb_build_object('outcome','DOMAIN_AUTOMATIONS_REPLAYED','as_of',p_as_of,'runs',(select jsonb_object_agg(run_kind,result_snapshot)from public.domain_automation_runs where as_of=p_as_of));end if;
 insert into public.diagnostic_reevaluation_queue(organization_id,questionnaire_session_id,reason_code,source_manifest_hash)
 select s.organization_id,s.id,'ANSWER_EXPIRED',s.answer_manifest_hash from public.questionnaire_sessions s where s.status='SUBMITTED'and exists(select 1 from public.questionnaire_answers a join public.questionnaire_answer_revisions r on r.id=a.current_revision_id where a.session_id=s.id and r.expires_at<=p_as_of::timestamp+interval'1 day')and not exists(select 1 from public.diagnostic_reevaluation_queue q where q.questionnaire_session_id=s.id and q.reason_code='ANSWER_EXPIRED')order by s.id limit p_limit on conflict do nothing;
 get diagnostics queued= row_count;
 for row_item in select q.*,om.user_id recipient_user_id,case when u.raw_user_meta_data->>'locale'in('ar','ar-MA')then'ar-MA'else'fr-MA'end locale from public.diagnostic_reevaluation_queue q join public.questionnaire_sessions s on s.id=q.questionnaire_session_id join public.organization_memberships om on om.organization_id=q.organization_id and om.user_id=s.actor_user_id and om.status='ACTIVE'join auth.users u on u.id=om.user_id where q.status='PENDING'order by q.created_at,q.id limit p_limit for update of q skip locked loop perform public.enqueue_notification(row_item.recipient_user_id,row_item.organization_id,'DIAGNOSTIC_REEVALUATION_REQUIRED','DiagnosticReevaluationRequiredV1',row_item.locale,'{}','diagnostic-reevaluation-required:'||row_item.questionnaire_session_id::text,'questionnaire_session',row_item.questionnaire_session_id::text,corr);insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(row_item.organization_id,'questionnaire_session',row_item.questionnaire_session_id::text,'DiagnosticReevaluationRequestedV1',corr,jsonb_build_object('session_id',row_item.questionnaire_session_id,'reason_code',row_item.reason_code,'source_manifest_hash',row_item.source_manifest_hash),'diagnostic-reevaluation:'||row_item.questionnaire_session_id::text||':'||row_item.reason_code)on conflict do nothing;update public.diagnostic_reevaluation_queue set status='WAITING_USER',actioned_at=clock_timestamp()where id=row_item.id and status='PENDING';end loop;
 for row_item in select r.id,r.client_organization_id,r.current_version_id,v.desired_date from public.service_requests r join public.service_request_versions v on v.id=r.current_version_id where v.desired_date is not null and r.status not in('CANCELLED','CLOSED')and not exists(select 1 from public.client_calendar_events e where e.organization_id=r.client_organization_id and e.source_type='SERVICE_REQUEST'and e.source_id=r.id)order by v.desired_date,r.id limit p_limit loop select om.user_id into actor from public.organization_memberships om where om.organization_id=row_item.client_organization_id and om.status='ACTIVE'order by om.activated_at nulls last,om.user_id limit 1;if actor is not null then insert into public.client_calendar_events(organization_id,event_type,title_fr,title_ar,starts_at,status,source_type,source_id,created_by)values(row_item.client_organization_id,'RFQ','Échéance demande de service','موعد طلب الخدمة',row_item.desired_date::timestamp at time zone'Africa/Casablanca','SCHEDULED','SERVICE_REQUEST',row_item.id,actor)on conflict(organization_id,source_type,source_id)do nothing;if found then calendar_count:=calendar_count+1;insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(row_item.client_organization_id,null,'SERVICE','calendar.service_request.projected','service_request',row_item.id::text,corr,jsonb_build_object('desired_date',row_item.desired_date),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(row_item.client_organization_id,'service_request',row_item.id::text,'ServiceRequestCalendarProjectedV1',corr,jsonb_build_object('request_id',row_item.id,'desired_date',row_item.desired_date),'calendar-service-request:'||row_item.id::text||':'||row_item.desired_date::text)on conflict do nothing;end if;end if;end loop;
 for row_item in select d.id,d.provider_organization_id,f.document_kind,d.expires_on,om.user_id recipient_user_id,case when u.raw_user_meta_data->>'locale'in('ar','ar-MA')then'ar-MA'else'fr-MA'end locale,(d.expires_on-p_as_of)days_left from public.provider_document_families f join public.provider_document_versions d on d.family_id=f.id and d.version_number=(select max(latest.version_number)from public.provider_document_versions latest where latest.family_id=f.id)join public.organization_memberships om on om.organization_id=d.provider_organization_id and om.status='ACTIVE'join public.organization_member_roles role on role.membership_id=om.id and role.revoked_at is null and role.role_code in('PROVIDER_OWNER','PROVIDER_MANAGER')join auth.users u on u.id=om.user_id where d.status='VERIFIED'and d.expires_on-p_as_of in(60,30,7,0)and(f.document_kind in('LEGAL','FISCAL','INSURANCE')or exists(select 1 from public.provider_document_service_links l where l.document_version_id=d.id and l.is_mandatory))and not exists(select 1 from public.notification_instances n where n.recipient_user_id=om.user_id and n.deduplication_key='required-document-expiry:'||d.id::text||':'||(d.expires_on-p_as_of)::text)order by d.expires_on,d.id,om.user_id limit p_limit loop perform public.enqueue_notification(row_item.recipient_user_id,row_item.provider_organization_id,'REQUIRED_DOCUMENT_EXPIRY','RequiredDocumentExpiryReminderV1',row_item.locale,jsonb_build_object('document_kind',row_item.document_kind,'expires_on',row_item.expires_on::text,'milestone',case when row_item.days_left=0 then'J0'else'J-'||row_item.days_left::text end),'required-document-expiry:'||row_item.id::text||':'||row_item.days_left::text,'provider_document',row_item.id::text,corr);end loop;
 for row_item in select ps.provider_organization_id,ps.service_id,d.id document_version_id from public.provider_services ps join public.provider_document_service_links l on l.provider_service_id=ps.id and l.is_mandatory join public.provider_document_versions d on d.id=l.document_version_id join public.provider_service_match_profiles m on m.provider_organization_id=ps.provider_organization_id and m.service_id=ps.service_id where d.status='VERIFIED'and d.expires_on<=p_as_of and d.version_number=(select max(latest.version_number)from public.provider_document_versions latest where latest.family_id=d.family_id)and(m.required_certifications_valid or m.qualification_status<>'SUSPENDED')order by ps.provider_organization_id,ps.service_id,d.id limit p_limit for update of m skip locked loop update public.provider_service_match_profiles set required_certifications_valid=false,qualification_status='SUSPENDED',updated_at=clock_timestamp(),row_version=row_version+1 where provider_organization_id=row_item.provider_organization_id and service_id=row_item.service_id and(required_certifications_valid or qualification_status<>'SUSPENDED');if found then suspended:=suspended+1;insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(row_item.provider_organization_id,null,'SERVICE','provider.documents.targeted_suspension','provider_service_match_profile',row_item.service_id::text,corr,jsonb_build_object('as_of',p_as_of,'scope','MATCH_ELIGIBILITY_ONLY','document_version_id',row_item.document_version_id),repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(row_item.provider_organization_id,'provider_service_match_profile',row_item.service_id::text,'ProviderDocumentExpiredTargetedSuspensionV1',corr,jsonb_build_object('provider_organization_id',row_item.provider_organization_id,'service_id',row_item.service_id,'document_version_id',row_item.document_version_id,'as_of',p_as_of,'scope','MATCH_ELIGIBILITY_ONLY'),'provider-document-expiry:'||row_item.provider_organization_id::text||':'||row_item.service_id::text||':'||row_item.document_version_id::text)on conflict do nothing;end if;end loop;
 recurring:=public.schedule_recurring_service_requests(p_as_of,least(p_limit,20));
 select exists(select 1 from public.diagnostic_reevaluation_queue q where q.status='PENDING')or exists(select 1 from public.questionnaire_sessions s where s.status='SUBMITTED'and exists(select 1 from public.questionnaire_answers a join public.questionnaire_answer_revisions r on r.id=a.current_revision_id where a.session_id=s.id and r.expires_at<=p_as_of::timestamp+interval'1 day')and not exists(select 1 from public.diagnostic_reevaluation_queue q where q.questionnaire_session_id=s.id and q.reason_code='ANSWER_EXPIRED'))into diagnostic_more;
 select exists(select 1 from public.service_requests r join public.service_request_versions v on v.id=r.current_version_id where v.desired_date is not null and r.status not in('CANCELLED','CLOSED')and not exists(select 1 from public.client_calendar_events e where e.organization_id=r.client_organization_id and e.source_type='SERVICE_REQUEST'and e.source_id=r.id))into calendar_more;
 select exists(select 1 from public.provider_services ps join public.provider_document_service_links l on l.provider_service_id=ps.id and l.is_mandatory join public.provider_document_versions d on d.id=l.document_version_id join public.provider_service_match_profiles m on m.provider_organization_id=ps.provider_organization_id and m.service_id=ps.service_id where d.status='VERIFIED'and d.expires_on<=p_as_of and d.version_number=(select max(latest.version_number)from public.provider_document_versions latest where latest.family_id=d.family_id)and(m.required_certifications_valid or m.qualification_status<>'SUSPENDED'))or exists(select 1 from public.provider_document_families f join public.provider_document_versions d on d.family_id=f.id and d.version_number=(select max(latest.version_number)from public.provider_document_versions latest where latest.family_id=f.id)join public.organization_memberships om on om.organization_id=d.provider_organization_id and om.status='ACTIVE'join public.organization_member_roles role on role.membership_id=om.id and role.revoked_at is null and role.role_code in('PROVIDER_OWNER','PROVIDER_MANAGER')where d.status='VERIFIED'and d.expires_on-p_as_of in(60,30,7,0)and(f.document_kind in('LEGAL','FISCAL','INSURANCE')or exists(select 1 from public.provider_document_service_links l where l.document_version_id=d.id and l.is_mandatory))and not exists(select 1 from public.notification_instances n where n.recipient_user_id=om.user_id and n.deduplication_key='required-document-expiry:'||d.id::text||':'||(d.expires_on-p_as_of)::text))into document_more;
 select exists(select 1 from public.recurring_service_plans p join public.recurring_service_plan_versions v on v.plan_id=p.id and v.version_number=p.current_version and v.status='ACTIVE'where p.status='ACTIVE'and v.starts_on<=p_as_of and exists(select 1 from generate_series(v.starts_on::timestamp,least(p_as_of,coalesce(v.ends_on,p_as_of))::timestamp,make_interval(months=>case v.cadence when'MONTHLY'then 1 when'QUARTERLY'then 3 when'ANNUALLY'then 12 end))due where not exists(select 1 from public.recurring_service_occurrences o where o.plan_id=p.id and o.scheduled_on=due::date)))into recurring_more;
 insert into public.domain_automation_runs(run_kind,as_of,status,cursor_snapshot,result_snapshot,correlation_id,completed_at)values
 ('DIAGNOSTIC_REEVALUATION',p_as_of,case when diagnostic_more then'PARTIAL'else'COMPLETED'end,jsonb_build_object('mode','PENDING_WORK_KEYSET','has_more',diagnostic_more,'pages',1),jsonb_build_object('queued',queued),corr,case when diagnostic_more then null else clock_timestamp()end),
 ('CALENDAR_PROJECTION',p_as_of,case when calendar_more then'PARTIAL'else'COMPLETED'end,jsonb_build_object('mode','PENDING_WORK_KEYSET','has_more',calendar_more,'pages',1),jsonb_build_object('projected',calendar_count),corr,case when calendar_more then null else clock_timestamp()end),
 ('DOCUMENT_EXPIRATION',p_as_of,case when document_more then'PARTIAL'else'COMPLETED'end,jsonb_build_object('mode','PENDING_WORK_KEYSET','has_more',document_more,'pages',1),jsonb_build_object('targeted_suspensions',suspended,'scope','MATCH_ELIGIBILITY_ONLY'),corr,case when document_more then null else clock_timestamp()end),
 ('RECURRING_REQUESTS',p_as_of,case when recurring_more then'PARTIAL'else'COMPLETED'end,jsonb_build_object('mode','PENDING_WORK_KEYSET','has_more',recurring_more,'pages',1),recurring,corr,case when recurring_more then null else clock_timestamp()end)
 on conflict(run_kind,as_of)do update set status=excluded.status,cursor_snapshot=public.domain_automation_runs.cursor_snapshot||jsonb_build_object('mode','PENDING_WORK_KEYSET','has_more',excluded.status='PARTIAL','pages',coalesce((public.domain_automation_runs.cursor_snapshot->>'pages')::integer,1)+1),result_snapshot=case excluded.run_kind
  when'DIAGNOSTIC_REEVALUATION'then jsonb_build_object('queued',coalesce((public.domain_automation_runs.result_snapshot->>'queued')::integer,0)+coalesce((excluded.result_snapshot->>'queued')::integer,0))
  when'CALENDAR_PROJECTION'then jsonb_build_object('projected',coalesce((public.domain_automation_runs.result_snapshot->>'projected')::integer,0)+coalesce((excluded.result_snapshot->>'projected')::integer,0))
  when'DOCUMENT_EXPIRATION'then jsonb_build_object('targeted_suspensions',coalesce((public.domain_automation_runs.result_snapshot->>'targeted_suspensions')::integer,0)+coalesce((excluded.result_snapshot->>'targeted_suspensions')::integer,0),'scope','MATCH_ELIGIBILITY_ONLY')
  else jsonb_build_object('outcome','RECURRING_SCHEDULER_PAGES_PROCESSED','processed_plans',coalesce((public.domain_automation_runs.result_snapshot->>'processed_plans')::integer,0)+coalesce((excluded.result_snapshot->>'processed_plans')::integer,0),'created_drafts',coalesce((public.domain_automation_runs.result_snapshot->>'created_drafts')::integer,0)+coalesce((excluded.result_snapshot->>'created_drafts')::integer,0),'skipped_plans',coalesce((public.domain_automation_runs.result_snapshot->>'skipped_plans')::integer,0)+coalesce((excluded.result_snapshot->>'skipped_plans')::integer,0),'autonomous_invitations',false,'autonomous_spend',false)
 end,correlation_id=excluded.correlation_id,completed_at=excluded.completed_at where public.domain_automation_runs.status<>'COMPLETED';
 insert into public.domain_automation_run_pages(run_id,page_number,status,cursor_snapshot,result_snapshot,correlation_id)select id,(cursor_snapshot->>'pages')::integer,status,cursor_snapshot,result_snapshot,corr from public.domain_automation_runs where as_of=p_as_of on conflict(run_id,page_number)do nothing;
 final_outcome:=case when diagnostic_more or calendar_more or document_more or recurring_more then'DOMAIN_AUTOMATIONS_PARTIAL'else'DOMAIN_AUTOMATIONS_COMPLETED'end;
 return jsonb_build_object('outcome',final_outcome,'as_of',p_as_of,'diagnostic_reevaluations_queued',queued,'calendar_events_projected',calendar_count,'provider_service_suspensions',suspended,'recurring',recurring,'has_more',diagnostic_more or calendar_more or document_more or recurring_more,'correlation_id',corr);
end$$;

revoke all on function public.claim_notification_deliveries_v1(text,integer,integer),public.authorize_notification_delivery_send_v1(uuid,uuid,text,uuid),public.record_notification_delivery_worker_result_v1(uuid,uuid,text,text,text,text,jsonb,text,uuid),public.run_domain_automation_schedulers_v1(date,integer)from public,anon,authenticated,service_role;
revoke all on function private.sync_notification_delivery_runtime_shape()from public,anon,authenticated,service_role;
revoke all on function private.protect_domain_automation_run()from public,anon,authenticated,service_role;
revoke all on function private.guard_notification_mandatory_policy_version()from public,anon,authenticated,service_role;
revoke all on function private.guard_notification_email_consent(),private.notification_email_consent_active(uuid,uuid,text)from public,anon,authenticated,service_role;
revoke all on function public.request_notification_email_consent(uuid,text,text,uuid),public.confirm_notification_email_consent(uuid,text,integer,text,text,uuid),public.revoke_notification_email_consent(uuid,text,integer,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.request_notification_email_consent(uuid,text,text,uuid),public.confirm_notification_email_consent(uuid,text,integer,text,text,uuid),public.revoke_notification_email_consent(uuid,text,integer,text,uuid)to authenticated;
grant execute on function public.claim_notification_deliveries_v1(text,integer,integer),public.authorize_notification_delivery_send_v1(uuid,uuid,text,uuid),public.record_notification_delivery_worker_result_v1(uuid,uuid,text,text,text,text,jsonb,text,uuid),public.run_domain_automation_schedulers_v1(date,integer)to service_role;
notify pgrst,'reload schema';

