-- MAT-FUNC-011/012/021/053: client projects, annual budgets, central calendar and cost centres.

create table public.client_sites(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
 code text not null check(code~'^[A-Z][A-Z0-9_-]{1,39}$'), status text not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE','ARCHIVED')),
 current_version integer not null default 1 check(current_version>0), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 updated_at timestamptz not null default clock_timestamp(), row_version integer not null default 1 check(row_version>0), unique(organization_id,code), unique(id,organization_id)
);
create table public.client_site_versions(
 id uuid primary key default extensions.gen_random_uuid(), site_id uuid not null references public.client_sites(id) on delete restrict, organization_id uuid not null,
 version integer not null check(version>0), name_fr text not null check(length(btrim(name_fr))between 2 and 160), name_ar text not null check(length(btrim(name_ar))between 2 and 160),
 address_snapshot jsonb not null check(jsonb_typeof(address_snapshot)='object'), change_reason text not null check(length(btrim(change_reason))between 3 and 500),
 content_hash text not null check(content_hash~'^[0-9a-f]{64}$'), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 unique(site_id,version), foreign key(site_id,organization_id)references public.client_sites(id,organization_id)on delete restrict
);

create table public.client_projects(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
 project_code text not null check(project_code~'^[A-Z][A-Z0-9_-]{1,39}$'), site_id uuid, status text not null default 'DRAFT' check(status in('DRAFT','PLANNED','ACTIVE','ON_HOLD','COMPLETED','CANCELLED','ARCHIVED')),
 current_version integer not null default 1 check(current_version>0), progress_basis_points integer not null default 0 check(progress_basis_points between 0 and 10000),
 started_on date, target_end_on date, completed_at timestamptz, created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(),
 row_version integer not null default 1 check(row_version>0), unique(organization_id,project_code), unique(id,organization_id), foreign key(site_id,organization_id)references public.client_sites(id,organization_id)on delete restrict,
 check(target_end_on is null or started_on is null or target_end_on>=started_on), check((status='COMPLETED')=(completed_at is not null))
);
create table public.client_project_versions(
 id uuid primary key default extensions.gen_random_uuid(), project_id uuid not null references public.client_projects(id)on delete restrict, organization_id uuid not null,
 version integer not null check(version>0), name_fr text not null check(length(btrim(name_fr))between 2 and 200), name_ar text not null check(length(btrim(name_ar))between 2 and 200),
 description_fr text not null check(length(btrim(description_fr))between 3 and 4000), description_ar text not null check(length(btrim(description_ar))between 3 and 4000),
 objectives jsonb not null default '[]' check(jsonb_typeof(objectives)='array'), scope_snapshot jsonb not null default '{}' check(jsonb_typeof(scope_snapshot)='object'),
 content_hash text not null check(content_hash~'^[0-9a-f]{64}$'), change_reason text not null check(length(btrim(change_reason))between 3 and 500), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 unique(project_id,version), foreign key(project_id,organization_id)references public.client_projects(id,organization_id)on delete restrict
);
create table public.client_project_tasks(
 id uuid primary key default extensions.gen_random_uuid(), project_id uuid not null references public.client_projects(id)on delete restrict, organization_id uuid not null,
 task_key text not null check(task_key~'^[A-Z][A-Z0-9_-]{1,79}$'), task_type text not null check(task_type in('TASK','MILESTONE')),
 status text not null default 'PENDING' check(status in('PENDING','IN_PROGRESS','BLOCKED','SUBMITTED','ACCEPTED','CANCELLED')),
 due_at timestamptz, assignee_user_id uuid references auth.users(id), current_version integer not null default 1 check(current_version>0), row_version integer not null default 1 check(row_version>0),
 created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(),
 unique(project_id,task_key), unique(id,organization_id), foreign key(project_id,organization_id)references public.client_projects(id,organization_id)on delete restrict
);
create table public.client_project_task_versions(
 id uuid primary key default extensions.gen_random_uuid(), task_id uuid not null references public.client_project_tasks(id)on delete restrict, organization_id uuid not null,
 version integer not null check(version>0), title_fr text not null check(length(btrim(title_fr))between 2 and 240), title_ar text not null check(length(btrim(title_ar))between 2 and 240),
 description_fr text, description_ar text, acceptance_criteria jsonb not null default '[]' check(jsonb_typeof(acceptance_criteria)='array'),
 content_hash text not null check(content_hash~'^[0-9a-f]{64}$'), change_reason text not null check(length(btrim(change_reason))between 3 and 500), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 unique(task_id,version), foreign key(task_id,organization_id)references public.client_project_tasks(id,organization_id)on delete restrict
);

create table public.client_annual_budgets(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id)on delete restrict, fiscal_year integer not null check(fiscal_year between 2000 and 2200),
 currency char(3) not null check(currency~'^[A-Z]{3}$'), library_id uuid references public.catalog_libraries(id)on delete restrict, site_id uuid, project_id uuid,
 current_version integer not null default 1 check(current_version>0), status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','CLOSED','ARCHIVED')),
 created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(), row_version integer not null default 1 check(row_version>0),
 unique nulls not distinct(organization_id,fiscal_year,currency,library_id,site_id,project_id), unique(id,organization_id),
 foreign key(site_id,organization_id)references public.client_sites(id,organization_id)on delete restrict, foreign key(project_id,organization_id)references public.client_projects(id,organization_id)on delete restrict,
 check(num_nonnulls(library_id,site_id,project_id)>=1)
);
create table public.client_annual_budget_versions(
 id uuid primary key default extensions.gen_random_uuid(), budget_id uuid not null references public.client_annual_budgets(id)on delete restrict, organization_id uuid not null,
 version integer not null check(version>0), amount_minor bigint not null check(amount_minor>=0), approved_amount_minor bigint check(approved_amount_minor is null or approved_amount_minor>=0),
 rationale text not null check(length(btrim(rationale))between 3 and 2000), assumptions jsonb not null default '{}' check(jsonb_typeof(assumptions)='object'),
 content_hash text not null check(content_hash~'^[0-9a-f]{64}$'), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 unique(budget_id,version), unique(id,budget_id), foreign key(budget_id,organization_id)references public.client_annual_budgets(id,organization_id)on delete restrict
);

create table public.client_cost_centers(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id)on delete restrict,
 code text not null check(code~'^[A-Z][A-Z0-9_-]{1,39}$'), status text not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE','ARCHIVED')),
 current_version integer not null default 1 check(current_version>0), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(), row_version integer not null default 1 check(row_version>0),
 unique(organization_id,code), unique(id,organization_id)
);
create table public.client_cost_center_versions(
 id uuid primary key default extensions.gen_random_uuid(), cost_center_id uuid not null references public.client_cost_centers(id)on delete restrict, organization_id uuid not null,
 version integer not null check(version>0), name_fr text not null check(length(btrim(name_fr))between 2 and 160), name_ar text not null check(length(btrim(name_ar))between 2 and 160),
 manager_user_id uuid references auth.users(id), allocation_policy_snapshot jsonb not null default '{}' check(jsonb_typeof(allocation_policy_snapshot)='object'), content_hash text not null check(content_hash~'^[0-9a-f]{64}$'),
 change_reason text not null check(length(btrim(change_reason))between 3 and 500), created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 unique(cost_center_id,version), foreign key(cost_center_id,organization_id)references public.client_cost_centers(id,organization_id)on delete restrict
);
create table public.client_cost_allocations(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id)on delete restrict,
 cost_center_id uuid not null, budget_id uuid not null, budget_version_id uuid not null, project_id uuid,
 allocation_type text not null check(allocation_type in('COMMITMENT','ACTUAL','RELEASE')), amount_minor bigint not null check(amount_minor>0), currency char(3) not null check(currency~'^[A-Z]{3}$'),
 reference_type text not null check(reference_type in('PROJECT','CONTRACT','MISSION','INVOICE','MANUAL')), reference_id uuid, evidence_hash text not null check(evidence_hash~'^[0-9a-f]{64}$'),
 idempotency_key text not null check(length(idempotency_key)between 8 and 200), correlation_id uuid not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(),
 unique(organization_id,idempotency_key), foreign key(cost_center_id,organization_id)references public.client_cost_centers(id,organization_id)on delete restrict,
 foreign key(budget_id,organization_id)references public.client_annual_budgets(id,organization_id)on delete restrict, foreign key(budget_version_id,budget_id)references public.client_annual_budget_versions(id,budget_id)on delete restrict,
 foreign key(project_id,organization_id)references public.client_projects(id,organization_id)on delete restrict
);

create table public.client_calendar_events(
 id uuid primary key default extensions.gen_random_uuid(), organization_id uuid not null references public.organizations(id)on delete restrict, project_id uuid,
 event_type text not null check(event_type in('CUSTOM','PROJECT_DEADLINE','APPROVAL','DOCUMENT','INVOICE','MISSION','RFQ')),
 title_fr text not null check(length(btrim(title_fr))between 2 and 240), title_ar text not null check(length(btrim(title_ar))between 2 and 240), starts_at timestamptz not null, ends_at timestamptz,
 status text not null default 'SCHEDULED' check(status in('SCHEDULED','COMPLETED','CANCELLED')), source_type text, source_id uuid,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default clock_timestamp(), row_version integer not null default 1 check(row_version>0),
 foreign key(project_id,organization_id)references public.client_projects(id,organization_id)on delete restrict, check(ends_at is null or ends_at>=starts_at), unique(organization_id,source_type,source_id)
);

create function private.client_portfolio_read(p_org uuid,p_actor uuid default auth.uid())returns boolean language sql stable security definer set search_path=pg_catalog,public,private as $$
 select private.has_org_role(p_org,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER','CLIENT_ACCOUNTING','CLIENT_MEMBER','CLIENT_VIEWER'],p_actor)
 or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','READ_ONLY_AUDITOR'],p_actor)
$$;
create function private.client_portfolio_manage(p_org uuid,p_actor uuid default auth.uid())returns boolean language sql stable security definer set search_path=pg_catalog,public,private as $$
 select private.has_org_role(p_org,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_BUYER'],p_actor)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN'],p_actor)
$$;
create function private.client_budget_manage(p_org uuid,p_actor uuid default auth.uid())returns boolean language sql stable security definer set search_path=pg_catalog,public,private as $$
 select private.has_org_role(p_org,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_ACCOUNTING'],p_actor)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER'],p_actor)
$$;

create function public.create_client_site(p_organization_id uuid,p_code text,p_name_fr text,p_name_ar text,p_address_snapshot jsonb,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;s uuid;begin if a is null or not private.client_portfolio_manage(p_organization_id,a)then raise exception'CLIENT_SITE_CREATE_DENIED'using errcode='42501';end if;
if p_code!~'^[A-Z][A-Z0-9_-]{1,39}$'or length(btrim(coalesce(p_name_fr,'')))not between 2 and 160 or length(btrim(coalesce(p_name_ar,'')))not between 2 and 160 or jsonb_typeof(p_address_snapshot)<>'object'or length(btrim(coalesce(p_change_reason,'')))not between 3 and 500 then raise exception'INVALID_CLIENT_SITE'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'code',p_code,'fr',p_name_fr,'ar',p_name_ar,'address',p_address_snapshot,'reason',p_change_reason));r:=private.begin_contract_command(p_organization_id,'client.site.create',p_idempotency_key,h,a);if r is not null then return r;end if;
insert into public.client_sites(organization_id,code,created_by)values(p_organization_id,p_code,a)returning id into s;insert into public.client_site_versions(site_id,organization_id,version,name_fr,name_ar,address_snapshot,change_reason,content_hash,created_by)values(s,p_organization_id,1,p_name_fr,p_name_ar,p_address_snapshot,p_change_reason,h,a);
r:=jsonb_build_object('outcome','CLIENT_SITE_CREATED','site_id',s,'version',1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','client.site.created','client_site',s::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'client_site',s::text,'ClientSiteCreatedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'client.site.create',p_idempotency_key,r);return r;end$$;

create function public.create_client_project(p_organization_id uuid,p_project_code text,p_site_id uuid,p_name_fr text,p_name_ar text,p_description_fr text,p_description_ar text,p_objectives jsonb,p_scope_snapshot jsonb,p_started_on date,p_target_end_on date,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;p uuid;v uuid;begin if a is null or not private.client_portfolio_manage(p_organization_id,a)then raise exception'CLIENT_PROJECT_CREATE_DENIED'using errcode='42501';end if;
if p_project_code!~'^[A-Z][A-Z0-9_-]{1,39}$'or(p_site_id is not null and not exists(select 1 from public.client_sites where id=p_site_id and organization_id=p_organization_id and status='ACTIVE'))or length(btrim(coalesce(p_name_fr,'')))<2 or length(btrim(coalesce(p_name_ar,'')))<2 or length(btrim(coalesce(p_description_fr,'')))<3 or length(btrim(coalesce(p_description_ar,'')))<3 or jsonb_typeof(p_objectives)<>'array'or jsonb_typeof(p_scope_snapshot)<>'object'or(p_started_on is not null and p_target_end_on<p_started_on)or length(btrim(coalesce(p_change_reason,'')))<3 then raise exception'INVALID_CLIENT_PROJECT'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'code',p_project_code,'site',p_site_id,'fr',p_name_fr,'ar',p_name_ar,'description_fr',p_description_fr,'description_ar',p_description_ar,'objectives',p_objectives,'scope',p_scope_snapshot,'start',p_started_on,'end',p_target_end_on,'reason',p_change_reason));r:=private.begin_contract_command(p_organization_id,'client.project.create',p_idempotency_key,h,a);if r is not null then return r;end if;
insert into public.client_projects(organization_id,project_code,site_id,status,started_on,target_end_on,created_by)values(p_organization_id,p_project_code,p_site_id,case when p_started_on is null then'DRAFT'else'PLANNED'end,p_started_on,p_target_end_on,a)returning id into p;insert into public.client_project_versions(project_id,organization_id,version,name_fr,name_ar,description_fr,description_ar,objectives,scope_snapshot,content_hash,change_reason,created_by)values(p,p_organization_id,1,p_name_fr,p_name_ar,p_description_fr,p_description_ar,p_objectives,p_scope_snapshot,h,p_change_reason,a)returning id into v;
r:=jsonb_build_object('outcome','CLIENT_PROJECT_CREATED','project_id',p,'project_version_id',v,'version',1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','client.project.created','client_project',p::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'client_project',p::text,'ClientProjectCreatedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'client.project.create',p_idempotency_key,r);return r;end$$;

create function public.save_client_project_version(p_project_id uuid,p_expected_row_version integer,p_site_id uuid,p_status text,p_name_fr text,p_name_ar text,p_description_fr text,p_description_ar text,p_objectives jsonb,p_scope_snapshot jsonb,p_started_on date,p_target_end_on date,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();p public.client_projects%rowtype;h text;r jsonb;v uuid;n integer;begin select * into p from public.client_projects where id=p_project_id;if a is null or not found or not private.client_portfolio_manage(p.organization_id,a)then raise exception'CLIENT_PROJECT_SAVE_DENIED'using errcode='42501';end if;
if p.status in('COMPLETED','CANCELLED','ARCHIVED')or p_status not in('DRAFT','PLANNED','ACTIVE','ON_HOLD','COMPLETED','CANCELLED')or(p_site_id is not null and not exists(select 1 from public.client_sites where id=p_site_id and organization_id=p.organization_id and status='ACTIVE'))or length(btrim(coalesce(p_name_fr,'')))<2 or length(btrim(coalesce(p_name_ar,'')))<2 or length(btrim(coalesce(p_description_fr,'')))<3 or length(btrim(coalesce(p_description_ar,'')))<3 or jsonb_typeof(p_objectives)<>'array'or jsonb_typeof(p_scope_snapshot)<>'object'or(p_started_on is not null and p_target_end_on<p_started_on)or length(btrim(coalesce(p_change_reason,'')))<3 then raise exception'INVALID_CLIENT_PROJECT_VERSION'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('project',p.id,'expected',p_expected_row_version,'site',p_site_id,'status',p_status,'fr',p_name_fr,'ar',p_name_ar,'description_fr',p_description_fr,'description_ar',p_description_ar,'objectives',p_objectives,'scope',p_scope_snapshot,'start',p_started_on,'end',p_target_end_on,'reason',p_change_reason));r:=private.begin_contract_command(p.organization_id,'client.project.save.'||p.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;
select * into p from public.client_projects where id=p.id for update;if p.row_version<>p_expected_row_version then raise exception'STALE_CLIENT_PROJECT'using errcode='40001';end if;n:=p.current_version+1;insert into public.client_project_versions(project_id,organization_id,version,name_fr,name_ar,description_fr,description_ar,objectives,scope_snapshot,content_hash,change_reason,created_by)values(p.id,p.organization_id,n,p_name_fr,p_name_ar,p_description_fr,p_description_ar,p_objectives,p_scope_snapshot,h,p_change_reason,a)returning id into v;update public.client_projects set site_id=p_site_id,status=p_status,current_version=n,started_on=p_started_on,target_end_on=p_target_end_on,completed_at=case when p_status='COMPLETED'then clock_timestamp()end,row_version=row_version+1,updated_at=clock_timestamp()where id=p.id;
r:=jsonb_build_object('outcome','CLIENT_PROJECT_VERSION_SAVED','project_id',p.id,'project_version_id',v,'version',n,'row_version',p.row_version+1,'status',p_status);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p.organization_id,a,'USER','client.project.version_saved','client_project',p.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p.organization_id,'client_project',p.id::text,'ClientProjectVersionSavedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p.organization_id,'client.project.save.'||p.id::text,p_idempotency_key,r);return r;end$$;

create function public.save_client_annual_budget(p_organization_id uuid,p_fiscal_year integer,p_currency char(3),p_library_id uuid,p_site_id uuid,p_project_id uuid,p_amount_minor bigint,p_rationale text,p_assumptions jsonb,p_approve boolean,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;b public.client_annual_budgets%rowtype;v uuid;n integer;begin if a is null or not private.client_budget_manage(p_organization_id,a)then raise exception'CLIENT_BUDGET_SAVE_DENIED'using errcode='42501';end if;
if p_fiscal_year not between 2000 and 2200 or p_currency!~'^[A-Z]{3}$'or num_nonnulls(p_library_id,p_site_id,p_project_id)<1 or p_amount_minor<0 or(p_library_id is not null and not exists(select 1 from public.catalog_libraries where id=p_library_id))or(p_site_id is not null and not exists(select 1 from public.client_sites where id=p_site_id and organization_id=p_organization_id))or(p_project_id is not null and not exists(select 1 from public.client_projects where id=p_project_id and organization_id=p_organization_id))or length(btrim(coalesce(p_rationale,'')))<3 or jsonb_typeof(p_assumptions)<>'object'then raise exception'INVALID_CLIENT_BUDGET'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'year',p_fiscal_year,'currency',p_currency,'library',p_library_id,'site',p_site_id,'project',p_project_id,'amount_minor',p_amount_minor,'rationale',p_rationale,'assumptions',p_assumptions,'approve',p_approve));r:=private.begin_contract_command(p_organization_id,'client.budget.save',p_idempotency_key,h,a);if r is not null then return r;end if;
perform pg_advisory_xact_lock(hashtextextended(p_organization_id::text||':'||p_fiscal_year::text||':'||p_currency||':'||coalesce(p_library_id::text,'')||':'||coalesce(p_site_id::text,'')||':'||coalesce(p_project_id::text,''),0));select * into b from public.client_annual_budgets where organization_id=p_organization_id and fiscal_year=p_fiscal_year and currency=p_currency and library_id is not distinct from p_library_id and site_id is not distinct from p_site_id and project_id is not distinct from p_project_id for update;
if found then if b.status in('CLOSED','ARCHIVED')then raise exception'CLIENT_BUDGET_NOT_EDITABLE'using errcode='55000';end if;n:=b.current_version+1;update public.client_annual_budgets set current_version=n,status=case when p_approve then'APPROVED'else'DRAFT'end,updated_at=clock_timestamp(),row_version=row_version+1 where id=b.id;else n:=1;insert into public.client_annual_budgets(organization_id,fiscal_year,currency,library_id,site_id,project_id,status,created_by)values(p_organization_id,p_fiscal_year,p_currency,p_library_id,p_site_id,p_project_id,case when p_approve then'APPROVED'else'DRAFT'end,a)returning * into b;end if;
insert into public.client_annual_budget_versions(budget_id,organization_id,version,amount_minor,approved_amount_minor,rationale,assumptions,content_hash,created_by)values(b.id,p_organization_id,n,p_amount_minor,case when p_approve then p_amount_minor end,p_rationale,p_assumptions,h,a)returning id into v;
r:=jsonb_build_object('outcome',case when p_approve then'CLIENT_BUDGET_APPROVED'else'CLIENT_BUDGET_VERSIONED'end,'budget_id',b.id,'budget_version_id',v,'version',n,'amount_minor',p_amount_minor,'currency',p_currency);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','client.budget.saved','client_annual_budget',b.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'client_annual_budget',b.id::text,case when p_approve then'ClientAnnualBudgetApprovedV1'else'ClientAnnualBudgetVersionedV1'end,p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'client.budget.save',p_idempotency_key,r);return r;end$$;

create function public.create_client_cost_center(p_organization_id uuid,p_code text,p_name_fr text,p_name_ar text,p_manager_user_id uuid,p_allocation_policy_snapshot jsonb,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;c uuid;v uuid;begin if a is null or not private.client_budget_manage(p_organization_id,a)then raise exception'CLIENT_COST_CENTER_CREATE_DENIED'using errcode='42501';end if;
if p_code!~'^[A-Z][A-Z0-9_-]{1,39}$'or length(btrim(coalesce(p_name_fr,'')))not between 2 and 160 or length(btrim(coalesce(p_name_ar,'')))not between 2 and 160 or jsonb_typeof(p_allocation_policy_snapshot)<>'object'or length(btrim(coalesce(p_change_reason,'')))not between 3 and 500 or(p_manager_user_id is not null and not private.is_active_org_member(p_organization_id,p_manager_user_id))then raise exception'INVALID_CLIENT_COST_CENTER'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'code',p_code,'fr',p_name_fr,'ar',p_name_ar,'manager',p_manager_user_id,'policy',p_allocation_policy_snapshot,'reason',p_change_reason));r:=private.begin_contract_command(p_organization_id,'client.cost_center.create',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.client_cost_centers(organization_id,code,created_by)values(p_organization_id,p_code,a)returning id into c;insert into public.client_cost_center_versions(cost_center_id,organization_id,version,name_fr,name_ar,manager_user_id,allocation_policy_snapshot,content_hash,change_reason,created_by)values(c,p_organization_id,1,p_name_fr,p_name_ar,p_manager_user_id,p_allocation_policy_snapshot,h,p_change_reason,a)returning id into v;
r:=jsonb_build_object('outcome','CLIENT_COST_CENTER_CREATED','cost_center_id',c,'cost_center_version_id',v,'version',1);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','client.cost_center.created','client_cost_center',c::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'client_cost_center',c::text,'ClientCostCenterCreatedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'client.cost_center.create',p_idempotency_key,r);return r;end$$;

create function public.record_client_cost_allocation(p_organization_id uuid,p_cost_center_id uuid,p_budget_id uuid,p_project_id uuid,p_allocation_type text,p_amount_minor bigint,p_reference_type text,p_reference_id uuid,p_evidence_hash text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;b public.client_annual_budgets%rowtype;bv public.client_annual_budget_versions%rowtype;allocated bigint;x uuid;begin if a is null or not private.client_budget_manage(p_organization_id,a)then raise exception'CLIENT_COST_ALLOCATION_DENIED'using errcode='42501';end if;
select * into b from public.client_annual_budgets where id=p_budget_id and organization_id=p_organization_id and status='APPROVED'for update;select * into bv from public.client_annual_budget_versions where budget_id=b.id and version=b.current_version;if not found or not exists(select 1 from public.client_cost_centers where id=p_cost_center_id and organization_id=p_organization_id and status='ACTIVE')or(p_project_id is not null and not exists(select 1 from public.client_projects where id=p_project_id and organization_id=p_organization_id))or p_allocation_type not in('COMMITMENT','ACTUAL','RELEASE')or p_amount_minor<=0 or p_reference_type not in('PROJECT','CONTRACT','MISSION','INVOICE','MANUAL')or p_evidence_hash!~'^[0-9a-f]{64}$'then raise exception'INVALID_CLIENT_COST_ALLOCATION'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'cost_center',p_cost_center_id,'budget',p_budget_id,'budget_version',bv.id,'project',p_project_id,'type',p_allocation_type,'amount_minor',p_amount_minor,'reference_type',p_reference_type,'reference_id',p_reference_id,'evidence_hash',p_evidence_hash));r:=private.begin_contract_command(p_organization_id,'client.cost.allocate',p_idempotency_key,h,a);if r is not null then return r;end if;
select coalesce(sum(case when allocation_type='RELEASE'then-amount_minor else amount_minor end),0)into allocated from public.client_cost_allocations where budget_id=b.id and budget_version_id=bv.id;if p_allocation_type<>'RELEASE'and allocated+p_amount_minor>bv.approved_amount_minor then raise exception'CLIENT_BUDGET_EXCEEDED'using errcode='23514';elsif p_allocation_type='RELEASE'and p_amount_minor>allocated then raise exception'CLIENT_ALLOCATION_RELEASE_EXCEEDED'using errcode='23514';end if;
insert into public.client_cost_allocations(organization_id,cost_center_id,budget_id,budget_version_id,project_id,allocation_type,amount_minor,currency,reference_type,reference_id,evidence_hash,idempotency_key,correlation_id,created_by)values(p_organization_id,p_cost_center_id,b.id,bv.id,p_project_id,p_allocation_type,p_amount_minor,b.currency,p_reference_type,p_reference_id,p_evidence_hash,p_idempotency_key,p_correlation_id,a)returning id into x;
r:=jsonb_build_object('outcome','CLIENT_COST_ALLOCATED','allocation_id',x,'budget_id',b.id,'budget_version_id',bv.id,'amount_minor',p_amount_minor,'allocation_type',p_allocation_type,'remaining_minor',bv.approved_amount_minor-(allocated+case when p_allocation_type='RELEASE'then-p_amount_minor else p_amount_minor end));insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','client.cost.allocated','client_cost_allocation',x::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'client_cost_allocation',x::text,'ClientCostAllocatedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'client.cost.allocate',p_idempotency_key,r);return r;end$$;

create function public.save_client_project_task(p_project_id uuid,p_task_key text,p_task_type text,p_status text,p_due_at timestamptz,p_assignee_user_id uuid,p_title_fr text,p_title_ar text,p_description_fr text,p_description_ar text,p_acceptance_criteria jsonb,p_change_reason text,p_expected_row_version integer,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();p public.client_projects%rowtype;t public.client_project_tasks%rowtype;h text;r jsonb;task_version integer;progress integer;v uuid;begin select * into p from public.client_projects where id=p_project_id;if a is null or not found or not private.client_portfolio_manage(p.organization_id,a)then raise exception'CLIENT_PROJECT_TASK_DENIED'using errcode='42501';end if;
if p_task_key!~'^[A-Z][A-Z0-9_-]{1,79}$'or p_task_type not in('TASK','MILESTONE')or p_status not in('PENDING','IN_PROGRESS','BLOCKED','SUBMITTED','ACCEPTED','CANCELLED')or length(btrim(coalesce(p_title_fr,'')))<2 or length(btrim(coalesce(p_title_ar,'')))<2 or jsonb_typeof(p_acceptance_criteria)<>'array'or length(btrim(coalesce(p_change_reason,'')))<3 then raise exception'INVALID_CLIENT_PROJECT_TASK'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('project',p.id,'key',p_task_key,'type',p_task_type,'status',p_status,'due',p_due_at,'assignee',p_assignee_user_id,'fr',p_title_fr,'ar',p_title_ar,'description_fr',p_description_fr,'description_ar',p_description_ar,'criteria',p_acceptance_criteria,'reason',p_change_reason,'expected',p_expected_row_version));r:=private.begin_contract_command(p.organization_id,'client.project.task.save.'||p.id::text,p_idempotency_key,h,a);if r is not null then return r;end if;
select * into t from public.client_project_tasks where project_id=p.id and task_key=p_task_key for update;if found then if t.row_version<>p_expected_row_version then raise exception'STALE_CLIENT_PROJECT_TASK'using errcode='40001';end if;task_version:=t.current_version+1;update public.client_project_tasks set status=p_status,due_at=p_due_at,assignee_user_id=p_assignee_user_id,current_version=task_version,row_version=row_version+1,updated_at=clock_timestamp()where id=t.id;else if p_expected_row_version<>0 then raise exception'STALE_CLIENT_PROJECT_TASK'using errcode='40001';end if;task_version:=1;insert into public.client_project_tasks(project_id,organization_id,task_key,task_type,status,due_at,assignee_user_id,created_by)values(p.id,p.organization_id,p_task_key,p_task_type,p_status,p_due_at,p_assignee_user_id,a)returning * into t;end if;
insert into public.client_project_task_versions(task_id,organization_id,version,title_fr,title_ar,description_fr,description_ar,acceptance_criteria,content_hash,change_reason,created_by)values(t.id,p.organization_id,task_version,p_title_fr,p_title_ar,p_description_fr,p_description_ar,p_acceptance_criteria,h,p_change_reason,a)returning id into v;
select coalesce((count(*)filter(where status='ACCEPTED')*10000/nullif(count(*),0))::integer,0)into progress from public.client_project_tasks where project_id=p.id and status<>'CANCELLED';update public.client_projects set progress_basis_points=progress,updated_at=clock_timestamp(),row_version=row_version+1 where id=p.id;
r:=jsonb_build_object('outcome','CLIENT_PROJECT_TASK_SAVED','task_id',t.id,'task_version_id',v,'task_version',task_version,'project_progress_basis_points',progress);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p.organization_id,a,'USER','client.project_task.saved','client_project_task',t.id::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p.organization_id,'client_project',p.id::text,'ClientProjectTaskSavedV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p.organization_id,'client.project.task.save.'||p.id::text,p_idempotency_key,r);return r;end$$;

create function public.schedule_client_calendar_event(p_organization_id uuid,p_project_id uuid,p_event_type text,p_title_fr text,p_title_ar text,p_starts_at timestamptz,p_ends_at timestamptz,p_source_type text,p_source_id uuid,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();h text;r jsonb;e uuid;begin if a is null or not private.client_portfolio_manage(p_organization_id,a)then raise exception'CLIENT_CALENDAR_SCHEDULE_DENIED'using errcode='42501';end if;if(p_project_id is not null and not exists(select 1 from public.client_projects where id=p_project_id and organization_id=p_organization_id))or p_event_type not in('CUSTOM','PROJECT_DEADLINE','APPROVAL','DOCUMENT','INVOICE','MISSION','RFQ')or length(btrim(coalesce(p_title_fr,'')))<2 or length(btrim(coalesce(p_title_ar,'')))<2 or p_starts_at is null or(p_ends_at is not null and p_ends_at<p_starts_at)or((p_source_type is null)<>(p_source_id is null))then raise exception'INVALID_CLIENT_CALENDAR_EVENT'using errcode='22023';end if;
h:=private.canonical_request_hash(jsonb_build_object('org',p_organization_id,'project',p_project_id,'type',p_event_type,'fr',p_title_fr,'ar',p_title_ar,'start',p_starts_at,'end',p_ends_at,'source_type',p_source_type,'source_id',p_source_id));r:=private.begin_contract_command(p_organization_id,'client.calendar.schedule',p_idempotency_key,h,a);if r is not null then return r;end if;insert into public.client_calendar_events(organization_id,project_id,event_type,title_fr,title_ar,starts_at,ends_at,source_type,source_id,created_by)values(p_organization_id,p_project_id,p_event_type,p_title_fr,p_title_ar,p_starts_at,p_ends_at,p_source_type,p_source_id,a)returning id into e;
r:=jsonb_build_object('outcome','CLIENT_CALENDAR_EVENT_SCHEDULED','calendar_event_id',e);insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(p_organization_id,a,'USER','client.calendar_event.scheduled','client_calendar_event',e::text,p_correlation_id,r,repeat('0',64));insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(p_organization_id,'client_calendar_event',e::text,'ClientCalendarEventScheduledV1',p_correlation_id,r,p_idempotency_key);perform private.finish_contract_command(p_organization_id,'client.calendar.schedule',p_idempotency_key,r);return r;end$$;

create view public.client_central_calendar with(security_invoker=true)as
 select e.organization_id,e.project_id,e.id as item_id,'CLIENT_EVENT'::text as source_kind,e.event_type,e.title_fr,e.title_ar,e.starts_at,e.ends_at,e.status from public.client_calendar_events e
 union all select t.organization_id,t.project_id,t.id,'PROJECT_TASK',t.task_type,v.title_fr,v.title_ar,t.due_at,null::timestamptz,t.status from public.client_project_tasks t join public.client_project_task_versions v on v.task_id=t.id and v.version=t.current_version where t.due_at is not null
 union all select m.client_organization_id,null::uuid,ms.id,'MISSION_MILESTONE','MISSION',ms.title_fr,ms.title_ar,ms.due_at,null::timestamptz,ms.status from public.mission_milestones ms join public.missions m on m.id=ms.mission_id where ms.due_at is not null;

create trigger client_site_versions_immutable before update or delete on public.client_site_versions for each row execute function private.prevent_update_delete();
create trigger client_project_versions_immutable before update or delete on public.client_project_versions for each row execute function private.prevent_update_delete();
create trigger client_project_task_versions_immutable before update or delete on public.client_project_task_versions for each row execute function private.prevent_update_delete();
create trigger client_budget_versions_immutable before update or delete on public.client_annual_budget_versions for each row execute function private.prevent_update_delete();
create trigger client_cost_center_versions_immutable before update or delete on public.client_cost_center_versions for each row execute function private.prevent_update_delete();
create trigger client_cost_allocations_immutable before update or delete on public.client_cost_allocations for each row execute function private.prevent_update_delete();

alter table public.client_sites enable row level security;alter table public.client_site_versions enable row level security;alter table public.client_projects enable row level security;alter table public.client_project_versions enable row level security;alter table public.client_project_tasks enable row level security;alter table public.client_project_task_versions enable row level security;alter table public.client_annual_budgets enable row level security;alter table public.client_annual_budget_versions enable row level security;alter table public.client_cost_centers enable row level security;alter table public.client_cost_center_versions enable row level security;alter table public.client_cost_allocations enable row level security;alter table public.client_calendar_events enable row level security;
create policy client_sites_read on public.client_sites for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_site_versions_read on public.client_site_versions for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_projects_read on public.client_projects for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_project_versions_read on public.client_project_versions for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_project_tasks_read on public.client_project_tasks for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_project_task_versions_read on public.client_project_task_versions for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_budgets_read on public.client_annual_budgets for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_budget_versions_read on public.client_annual_budget_versions for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_cost_centers_read on public.client_cost_centers for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_cost_center_versions_read on public.client_cost_center_versions for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_cost_allocations_read on public.client_cost_allocations for select to authenticated using(private.client_portfolio_read(organization_id));create policy client_calendar_events_read on public.client_calendar_events for select to authenticated using(private.client_portfolio_read(organization_id));

revoke all on public.client_sites,public.client_site_versions,public.client_projects,public.client_project_versions,public.client_project_tasks,public.client_project_task_versions,public.client_annual_budgets,public.client_annual_budget_versions,public.client_cost_centers,public.client_cost_center_versions,public.client_cost_allocations,public.client_calendar_events from public,anon,authenticated;grant select on public.client_sites,public.client_site_versions,public.client_projects,public.client_project_versions,public.client_project_tasks,public.client_project_task_versions,public.client_annual_budgets,public.client_annual_budget_versions,public.client_cost_centers,public.client_cost_center_versions,public.client_cost_allocations,public.client_calendar_events,public.client_central_calendar to authenticated;
revoke all on function private.client_portfolio_read(uuid,uuid),private.client_portfolio_manage(uuid,uuid),private.client_budget_manage(uuid,uuid)from public,anon,authenticated,service_role;grant execute on function private.client_portfolio_read(uuid,uuid)to authenticated;
revoke all on function public.create_client_site(uuid,text,text,text,jsonb,text,text,uuid),public.create_client_project(uuid,text,uuid,text,text,text,text,jsonb,jsonb,date,date,text,text,uuid),public.save_client_project_version(uuid,integer,uuid,text,text,text,text,text,jsonb,jsonb,date,date,text,text,uuid),public.save_client_annual_budget(uuid,integer,character,uuid,uuid,uuid,bigint,text,jsonb,boolean,text,uuid),public.create_client_cost_center(uuid,text,text,text,uuid,jsonb,text,text,uuid)from public,anon,authenticated,service_role;
-- Signature-safe grants are completed below using exact PostgreSQL argument types.
grant execute on function public.create_client_site(uuid,text,text,text,jsonb,text,text,uuid),public.create_client_project(uuid,text,uuid,text,text,text,text,jsonb,jsonb,date,date,text,text,uuid),public.save_client_project_version(uuid,integer,uuid,text,text,text,text,text,jsonb,jsonb,date,date,text,text,uuid),public.save_client_annual_budget(uuid,integer,character,uuid,uuid,uuid,bigint,text,jsonb,boolean,text,uuid),public.create_client_cost_center(uuid,text,text,text,uuid,jsonb,text,text,uuid),public.record_client_cost_allocation(uuid,uuid,uuid,uuid,text,bigint,text,uuid,text,text,uuid),public.save_client_project_task(uuid,text,text,text,timestamptz,uuid,text,text,text,text,jsonb,text,integer,text,uuid),public.schedule_client_calendar_event(uuid,uuid,text,text,text,timestamptz,timestamptz,text,uuid,text,uuid)to authenticated;
revoke all on function public.record_client_cost_allocation(uuid,uuid,uuid,uuid,text,bigint,text,uuid,text,text,uuid),public.save_client_project_task(uuid,text,text,text,timestamptz,uuid,text,text,text,text,jsonb,text,integer,text,uuid),public.schedule_client_calendar_event(uuid,uuid,text,text,text,timestamptz,timestamptz,text,uuid,text,uuid)from public,anon,service_role;

create index client_projects_status_idx on public.client_projects(organization_id,status,target_end_on);create index client_project_tasks_due_idx on public.client_project_tasks(organization_id,status,due_at)where due_at is not null;create index client_budgets_year_idx on public.client_annual_budgets(organization_id,fiscal_year,status);create index client_cost_allocations_budget_idx on public.client_cost_allocations(budget_id,budget_version_id,created_at);create index client_cost_allocations_project_idx on public.client_cost_allocations(project_id,created_at)where project_id is not null;create index client_calendar_timeline_idx on public.client_calendar_events(organization_id,starts_at,status);
