-- Additive MAT-FUNC-064 compatibility: bounded canonical idempotency scope.
create or replace function public.configure_franchise_daily_digest(
 p_franchise_id uuid,p_recipient_user_id uuid,p_enabled boolean,p_frequency text,p_local_send_time time without time zone,p_time_zone text,p_locale text,p_change_reason text,p_idempotency_key text,p_correlation_id uuid default extensions.gen_random_uuid()
)returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare a uuid:=auth.uid();org uuid;pol public.franchise_daily_digest_policy_versions%rowtype;prior public.franchise_daily_digest_config_versions%rowtype;n integer;h text;r jsonb;cid uuid;command_scope constant text:='franchise.daily_digest.configure';
begin
 if a is null or not private.franchise_crm_write_access(p_franchise_id,a)then raise exception'FRANCHISE_DIGEST_CONFIG_DENIED'using errcode='42501';end if;
 select operator_organization_id into org from public.franchises where id=p_franchise_id;
 if org is null or p_frequency not in('DAILY','WEEKDAYS')or p_locale not in('fr-MA','ar-MA')or p_local_send_time is null or length(btrim(coalesce(p_change_reason,'')))not between 3 and 1000 or not exists(select 1 from pg_timezone_names where name=p_time_zone)or not exists(select 1 from public.organization_memberships m join public.organization_member_roles mr on mr.membership_id=m.id and mr.revoked_at is null where m.organization_id=org and m.user_id=p_recipient_user_id and m.status='ACTIVE'and mr.role_code in('FRANCHISE_OWNER','FRANCHISE_MANAGER','FRANCHISE_VIEWER'))then raise exception'INVALID_FRANCHISE_DIGEST_CONFIG'using errcode='22023';end if;
 select*into pol from public.franchise_daily_digest_policy_versions where status='ACTIVE'and effective_from<=clock_timestamp()and(effective_until is null or effective_until>clock_timestamp())order by version desc limit 1;if not found then raise exception'FRANCHISE_DIGEST_POLICY_MISSING'using errcode='55000';end if;
 h:=private.canonical_request_hash(jsonb_build_object('franchise_id',p_franchise_id,'recipient_user_id',p_recipient_user_id,'enabled',p_enabled,'frequency',p_frequency,'local_send_time',p_local_send_time,'time_zone',p_time_zone,'locale',p_locale,'policy_version_id',pol.id,'change_reason',p_change_reason));
 r:=private.begin_contract_command(org,command_scope,p_idempotency_key,h,a);if r is not null then return r;end if;
 perform pg_advisory_xact_lock(hashtextextended('franchise-digest-config:'||p_franchise_id::text||':'||p_recipient_user_id::text,0));select*into prior from public.franchise_daily_digest_config_versions where franchise_id=p_franchise_id and recipient_user_id=p_recipient_user_id order by version desc limit 1;n:=coalesce(prior.version,0)+1;
 insert into public.franchise_daily_digest_config_versions(franchise_id,recipient_user_id,version,policy_version_id,enabled,frequency,local_send_time,time_zone,locale,supersedes_config_id,change_reason,content_hash,created_by)values(p_franchise_id,p_recipient_user_id,n,pol.id,p_enabled,p_frequency,p_local_send_time,p_time_zone,p_locale,prior.id,p_change_reason,h,a)returning id into cid;
 r:=jsonb_build_object('outcome','FRANCHISE_DAILY_DIGEST_CONFIGURED','config_version_id',cid,'version',n,'enabled',p_enabled,'frequency',p_frequency,'local_send_time',p_local_send_time,'time_zone',p_time_zone,'locale',p_locale);
 insert into public.audit_events(organization_id,actor_user_id,actor_type,action,resource_type,resource_id,correlation_id,metadata,event_hash)values(org,a,'USER','franchise.daily_digest.configured','franchise_daily_digest_config',cid::text,p_correlation_id,jsonb_build_object('franchise_id',p_franchise_id,'recipient_user_id',p_recipient_user_id,'version',n,'enabled',p_enabled,'frequency',p_frequency,'time_zone',p_time_zone,'policy_version_id',pol.id),repeat('0',64));
 insert into public.event_outbox(organization_id,aggregate_type,aggregate_id,event_type,correlation_id,payload,idempotency_key)values(org,'franchise_daily_digest_config',cid::text,'FranchiseDailyDigestConfiguredV1',p_correlation_id,r,p_idempotency_key);
 perform private.finish_contract_command(org,command_scope,p_idempotency_key,r);return r;
end$$;
revoke all on function public.configure_franchise_daily_digest(uuid,uuid,boolean,text,time without time zone,text,text,text,text,uuid)from public,anon,authenticated,service_role;
grant execute on function public.configure_franchise_daily_digest(uuid,uuid,boolean,text,time without time zone,text,text,text,text,uuid)to authenticated;
