-- MAT-FUNC-030/047/053/062: one read model over separated ledgers and verified value evidence.

create or replace function private.financial_center_access(p_organization_id uuid,p_actor uuid default auth.uid())returns boolean language sql stable security definer set search_path=pg_catalog,private as $$
 select p_actor is not null and(private.has_org_role(p_organization_id,array['CLIENT_OWNER','CLIENT_ADMIN','CLIENT_ACCOUNTING','PROVIDER_OWNER','PROVIDER_MANAGER','PROVIDER_ACCOUNTING','FRANCHISE_OWNER','FRANCHISE_MANAGER','FRANCHISE_ACCOUNTING'],p_actor)or private.has_platform_role(array['SUPER_ADMIN','MATRICIA_ADMIN','FINANCE_MANAGER','READ_ONLY_AUDITOR'],p_actor))
$$;

create or replace function public.get_unified_financial_value_center_v1(p_organization_id uuid,p_limit integer default 100)returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,private as $$
declare a uuid:=auth.uid();result jsonb;
begin
 if not private.financial_center_access(p_organization_id,a)then raise exception'FINANCIAL_CENTER_DENIED'using errcode='42501';end if;if p_limit not between 1 and 200 then raise exception'INVALID_FINANCIAL_CENTER_LIMIT'using errcode='22023';end if;
 select jsonb_build_object(
  'organization_id',p_organization_id,'generated_at',statement_timestamp(),
  'ledger',jsonb_build_object('currency_balances',coalesce((select jsonb_agg(x order by x.currency,x.account_code)from(select account.currency,account.code account_code,account.name,account.account_type,coalesce(sum(case entry.direction when'DEBIT'then entry.amount_minor else-entry.amount_minor end),0)::text balance_minor from public.financial_accounts account left join public.financial_entries entry on entry.organization_id=account.organization_id and entry.account_id=account.id where account.organization_id=p_organization_id group by account.id order by account.code limit p_limit)x),'[]'::jsonb)),
  'provider_billing',jsonb_build_object('invoices',coalesce((select jsonb_agg(x order by x.due_on desc,x.id)from(select invoice.id,invoice.invoice_number,invoice.currency,invoice.total_minor::text,invoice.issued_on,invoice.due_on,coalesce(sum(allocation.amount_minor),0)::text paid_minor,(invoice.total_minor-coalesce(sum(allocation.amount_minor),0))::text outstanding_minor,invoice.document_hash from public.provider_invoices invoice left join public.provider_payment_allocations allocation on allocation.provider_organization_id=invoice.provider_organization_id and allocation.invoice_id=invoice.id where invoice.provider_organization_id=p_organization_id group by invoice.id order by invoice.due_on desc limit p_limit)x),'[]'::jsonb)),
  'cost_centers',coalesce((select jsonb_agg(x order by x.code)from(select center.id,center.code,version.name_fr,version.name_ar,coalesce(sum(case allocation.allocation_type when'RELEASE'then-allocation.amount_minor else allocation.amount_minor end),0)::text allocated_minor,count(allocation.id)::integer evidence_count from public.client_cost_centers center join public.client_cost_center_versions version on version.cost_center_id=center.id and version.version=center.current_version left join public.client_cost_allocations allocation on allocation.organization_id=center.organization_id and allocation.cost_center_id=center.id where center.organization_id=p_organization_id and center.status='ACTIVE'group by center.id,version.id order by center.code limit p_limit)x),'[]'::jsonb),
  'verified_value',jsonb_build_object(
   'savings',coalesce((select jsonb_agg(to_jsonb(x)order by x.recorded_at desc)from(select saving.id,saving.baseline_id,saving.actual_amount_minor::text,saving.savings_amount_minor::text,saving.currency,saving.actual_period_start,saving.actual_period_end,saving.source_type,saving.source_reference,saving.evidence_hash,saving.formula_version,saving.recorded_at from public.savings_measurements saving where saving.organization_id=p_organization_id order by saving.recorded_at desc limit p_limit)x),'[]'::jsonb),
   'recommendation_roi',coalesce((select jsonb_agg(to_jsonb(x)order by x.calculated_at desc)from(select roi.id,roi.recommendation_id,roi.baseline_id,roi.actual_amount_minor::text,roi.realized_value_minor::text,roi.implementation_cost_minor::text,roi.net_value_minor::text,roi.roi_basis_points::text,roi.currency,roi.actual_source_type,roi.actual_source_reference,roi.evidence_hash,roi.formula_version,roi.calculated_at from public.recommendation_roi_snapshots roi where roi.organization_id=p_organization_id order by roi.calculated_at desc limit p_limit)x),'[]'::jsonb),
   'verified_baselines',coalesce((select jsonb_agg(to_jsonb(x)order by x.verified_at desc)from(select baseline.id,baseline.subject_type,baseline.subject_id,baseline.metric_code,baseline.version_number,baseline.baseline_amount_minor::text,baseline.currency,baseline.period_start,baseline.period_end,baseline.source_type,baseline.source_reference,baseline.evidence_hash,baseline.methodology_version,baseline.verified_at from public.measurement_baselines baseline where baseline.organization_id=p_organization_id and baseline.verification_status='VERIFIED'order by baseline.verified_at desc limit p_limit)x),'[]'::jsonb)
  ),
  'invariants',jsonb_build_object('ledgers_separated_by_organization',true,'minor_units_only',true,'verified_baseline_required',true,'evidence_hash_required',true)
 )into result;return result;
end$$;

revoke all on function private.financial_center_access(uuid,uuid),public.get_unified_financial_value_center_v1(uuid,integer)from public,anon,authenticated,service_role;
grant execute on function public.get_unified_financial_value_center_v1(uuid,integer)to authenticated;
notify pgrst,'reload schema';
