import { Badge } from "@/modules/shared/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/modules/shared/ui/card";

type Intake = { id: string; organizationId: string; organizationName: string; priorities: unknown; createdAt: string };
const labels = { fr: { title: "Bilans indicatifs enregistrés", intro: "Ces bilans proviennent du parcours public et restent distincts d’un diagnostic complet.", empty: "Aucun bilan indicatif enregistré.", status: "Indicatif", error: "Les bilans indicatifs sont temporairement indisponibles.", organization: "Organisation", sales: "Suivi commercial", security: "Continuité numérique", verify: "Point à vérifier" }, ar: { title: "التقييمات الإرشادية المحفوظة", intro: "تأتي هذه التقييمات من المسار العام وتبقى منفصلة عن التشخيص الكامل.", empty: "لا يوجد تقييم إرشادي محفوظ.", status: "إرشادي", error: "التقييمات الإرشادية غير متاحة مؤقتا.", organization: "التنظيم", sales: "المتابعة التجارية", security: "الاستمرارية الرقمية", verify: "نقطة للتحقق" } } as const;

export function IndicativeIntakes({ locale, rows, failed }: { locale: "fr" | "ar"; rows: Intake[]; failed: boolean }) {
  const copy = labels[locale];
  return <section aria-labelledby="indicative-intakes"><h2 id="indicative-intakes" className="text-xl font-semibold">{copy.title}</h2><p className="mt-2 text-sm text-muted-foreground">{copy.intro}</p>{failed ? <p role="alert" className="mt-3 rounded-xl border p-4 text-destructive">{copy.error}</p> : !rows.length ? <p className="mt-3 rounded-xl border bg-card p-4">{copy.empty}</p> : <div className="mt-3 grid gap-4 sm:grid-cols-2">{rows.map((row) => <Card key={row.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-2"><CardTitle className="text-base">{row.organizationName}</CardTitle><Badge variant="secondary">{copy.status}</Badge></div></CardHeader><CardContent><ul className="flex flex-wrap gap-2">{priorityCodes(row.priorities).map((code) => <li key={code} className="rounded-full border px-3 py-1 text-sm">{copy[code]}</li>)}</ul><time className="mt-3 block text-sm text-muted-foreground" dateTime={row.createdAt}>{new Intl.DateTimeFormat(locale === "ar" ? "ar-MA" : "fr-MA", { dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Casablanca" }).format(new Date(row.createdAt))}</time></CardContent></Card>)}</div>}</section>;
}
function priorityCodes(value: unknown): Array<"organization" | "sales" | "security" | "verify"> { if (!Array.isArray(value)) return []; return value.flatMap((item) => { if (!item || typeof item !== "object" || !("code" in item)) return []; const code = item.code; return code === "organization" || code === "sales" || code === "security" || code === "verify" ? [code] : []; }); }
