import { z } from "zod";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import type { MarketingDashboard } from "./model";

const id=z.string().uuid(), exact=z.union([z.string().regex(/^\d+$/),z.number().int().nonnegative()]).transform(String);
const membership=z.object({id,organization_id:id}), role=z.object({membership_id:id,role_code:z.string(),revoked_at:z.string().nullable()}), org=z.object({id,display_name:z.string()});
const consent=z.object({organization_id:id,purpose:z.enum(["SOCIAL_PUBLISHING","MARKETING_ANALYTICS","PERSONAL_DATA_CONTENT"]),decision:z.enum(["GRANTED","WITHDRAWN"]),policy_version:z.string(),decided_at:z.string()});
const kit=z.object({id,organization_id:id,status:z.string(),current_version_id:id.nullable()}), kitVersion=z.object({id,brand_kit_id:id,version:z.number().int().positive(),payload:z.record(z.string(),z.unknown())});
const connection=z.object({id,organization_id:id,provider:z.enum(["LINKEDIN","META"]),status:z.string()});
const campaign=z.object({id,organization_id:id,mode:z.enum(["MANUAL","ASSISTED","AUTOPILOT"]),title_fr:z.string(),title_ar:z.string(),status:z.string(),frequency_max_weekly:z.number().int(),risk_threshold:z.number().int(),row_version:z.number().int(),approved_at:z.string().nullable()});
const content=z.object({id,campaign_id:id,channel:z.enum(["LINKEDIN","FACEBOOK","INSTAGRAM","REEL"]),current_version_id:id.nullable()});
const version=z.object({id,content_id:id,language:z.enum(["FR","AR"]),hook:z.string(),body:z.string(),cta:z.string(),hashtags:z.array(z.string()),risk_score:z.number().int(),status:z.string(),expires_at:z.string().nullable()});
const calendar=z.object({id,campaign_id:id,content_version_id:id,scheduled_at:z.string(),status:z.string()});
const performance=z.object({campaign_id:id,contents_published:exact,impressions:exact,clicks:exact,leads:exact,attributed_value_minor:exact,marketing_cost_minor:exact,feedback:z.string()});
const MANAGE_ROLES=new Set(["CLIENT_OWNER","CLIENT_ADMIN","PROVIDER_OWNER","PROVIDER_MANAGER","PROVIDER_SALES","FRANCHISE_OWNER","FRANCHISE_MANAGER"]), PLATFORM_ROLES=new Set(["SUPER_ADMIN","MATRICIA_ADMIN"]);
export type MarketingLoadResult={status:"success";dashboard:MarketingDashboard}|{status:"error";reason:"UNAUTHENTICATED"|"FORBIDDEN"|"QUERY_FAILED"|"INVALID_RESPONSE"};
function parsed<T>(schema:z.ZodType<T>,data:unknown){const result=z.array(schema).safeParse(data);return result.success?result.data:null;}

export async function loadMarketingDashboard():Promise<MarketingLoadResult>{
  const client=await getSupabaseServerClient(),{data:auth}=await client.auth.getUser();if(!auth.user)return{status:"error",reason:"UNAUTHENTICATED"};
  const[membershipsQuery,platformQuery]=await Promise.all([client.from("organization_memberships").select("id,organization_id").eq("user_id",auth.user.id).eq("status","ACTIVE").limit(100),client.from("platform_user_roles").select("role_code").eq("user_id",auth.user.id).is("revoked_at",null).limit(20)]);
  if(membershipsQuery.error||platformQuery.error)return{status:"error",reason:"QUERY_FAILED"};const memberships=parsed(membership,membershipsQuery.data);if(!memberships)return{status:"error",reason:"INVALID_RESPONSE"};
  const roleQuery=memberships.length?await client.from("organization_member_roles").select("membership_id,role_code,revoked_at").in("membership_id",memberships.map(v=>v.id)).limit(300):{data:[],error:null};if(roleQuery.error)return{status:"error",reason:"QUERY_FAILED"};const roles=parsed(role,roleQuery.data);if(!roles)return{status:"error",reason:"INVALID_RESPONSE"};
  const platformAdmin=(platformQuery.data??[]).some((v:{role_code:string})=>PLATFORM_ROLES.has(v.role_code)),allowedMemberships=new Set(roles.filter(v=>v.revoked_at===null&&MANAGE_ROLES.has(v.role_code)).map(v=>v.membership_id)),orgIds=memberships.filter(v=>allowedMemberships.has(v.id)).map(v=>v.organization_id);if(!platformAdmin&&!orgIds.length)return{status:"error",reason:"FORBIDDEN"};
  let organizationsQuery=client.from("organizations").select("id,display_name").order("display_name").limit(100);if(!platformAdmin)organizationsQuery=organizationsQuery.in("id",orgIds);
  const[organizationsResult,consentsResult,kitsResult,connectionsResult,campaignsResult]=await Promise.all([organizationsQuery,client.from("marketing_consents").select("organization_id,purpose,decision,policy_version,decided_at").order("decided_at",{ascending:false}).limit(500),client.from("brand_kits").select("id,organization_id,status,current_version_id").limit(100),client.from("social_connections").select("id,organization_id,provider,status").limit(100),client.from("marketing_campaigns").select("id,organization_id,mode,title_fr,title_ar,status,frequency_max_weekly,risk_threshold,row_version,approved_at").order("created_at",{ascending:false}).limit(300)]);
  if([organizationsResult,consentsResult,kitsResult,connectionsResult,campaignsResult].some(v=>v.error))return{status:"error",reason:"QUERY_FAILED"};
  const organizations=parsed(org,organizationsResult.data),consents=parsed(consent,consentsResult.data),kits=parsed(kit,kitsResult.data),connections=parsed(connection,connectionsResult.data),campaigns=parsed(campaign,campaignsResult.data);if(!organizations||!consents||!kits||!connections||!campaigns)return{status:"error",reason:"INVALID_RESPONSE"};
  const[versionsResult,contentResult,calendarResult,performanceResult]=await Promise.all([client.from("brand_kit_versions").select("id,brand_kit_id,version,payload").limit(300),client.from("marketing_content").select("id,campaign_id,channel,current_version_id").limit(1000),client.from("marketing_calendar_items").select("id,campaign_id,content_version_id,scheduled_at,status").order("scheduled_at",{ascending:true}).limit(1000),client.from("marketing_campaign_performance").select("campaign_id,contents_published,impressions,clicks,leads,attributed_value_minor,marketing_cost_minor,feedback").limit(300)]);
  if([versionsResult,contentResult,calendarResult,performanceResult].some(v=>v.error))return{status:"error",reason:"QUERY_FAILED"};const kitVersions=parsed(kitVersion,versionsResult.data),contents=parsed(content,contentResult.data),calendarItems=parsed(calendar,calendarResult.data),performances=parsed(performance,performanceResult.data);if(!kitVersions||!contents||!calendarItems||!performances)return{status:"error",reason:"INVALID_RESPONSE"};
  const currentIds=contents.flatMap(v=>v.current_version_id?[v.current_version_id]:[]),contentVersionsResult=currentIds.length?await client.from("marketing_content_versions").select("id,content_id,language,hook,body,cta,hashtags,risk_score,status,expires_at").in("id",currentIds).limit(1000):{data:[],error:null};if(contentVersionsResult.error)return{status:"error",reason:"QUERY_FAILED"};const contentVersions=parsed(version,contentVersionsResult.data);if(!contentVersions)return{status:"error",reason:"INVALID_RESPONSE"};
  return{status:"success",dashboard:{organizations:organizations.map(v=>({id:v.id,name:v.display_name})),consents:consents.map(v=>({organizationId:v.organization_id,purpose:v.purpose,decision:v.decision,policyVersion:v.policy_version,decidedAt:v.decided_at})),brandVersions:kits.flatMap(k=>{const v=kitVersions.find(x=>x.id===k.current_version_id),trade=v?.payload.trade_name;return v?[{id:v.id,organizationId:k.organization_id,version:v.version,status:k.status,tradeName:typeof trade==="string"?trade:"—"}]:[]}),connections:connections.map(v=>({id:v.id,organizationId:v.organization_id,provider:v.provider,status:v.status})),campaigns:campaigns.map(v=>({id:v.id,organizationId:v.organization_id,mode:v.mode,titleFr:v.title_fr,titleAr:v.title_ar,status:v.status,frequencyMaxWeekly:v.frequency_max_weekly,riskThreshold:v.risk_threshold,rowVersion:v.row_version,approvedAt:v.approved_at})),contents:contents.flatMap(c=>{const v=contentVersions.find(x=>x.id===c.current_version_id);return v?[{id:c.id,campaignId:c.campaign_id,channel:c.channel,versionId:v.id,language:v.language,hook:v.hook,body:v.body,cta:v.cta,hashtags:v.hashtags,riskScore:v.risk_score,status:v.status,expiresAt:v.expires_at}]:[]}),calendar:calendarItems.map(v=>({id:v.id,campaignId:v.campaign_id,contentVersionId:v.content_version_id,scheduledAt:v.scheduled_at,status:v.status})),performance:performances.map(v=>({campaignId:v.campaign_id,published:String(v.contents_published),impressions:String(v.impressions),clicks:String(v.clicks),leads:String(v.leads),attributedValueMinor:String(v.attributed_value_minor),marketingCostMinor:String(v.marketing_cost_minor),feedback:v.feedback}))}};
}
