import{createHash}from"node:crypto";import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({getUser:vi.fn(),rpc:vi.fn(),from:vi.fn()}));vi.mock("@/modules/shared/lib/supabase/server",()=>({getSupabaseServerClient:async()=>({auth:{getUser:mocks.getUser},rpc:mocks.rpc,from:mocks.from})}));vi.mock("@/modules/shared/lib/i18n/locale",()=>({isLocale:(value:string)=>value==="fr"||value==="ar"}));vi.mock("@/modules/provider/data/billing/model",async()=>await import("@/modules/provider/data/billing/model"));import{issueStatement,reconcilePayment,recordPayment,type BillingActionState}from"./actions";
const idle:BillingActionState={status:"idle"},id="11111111-1111-4111-8111-111111111111",key="22222222-2222-4222-8222-222222222222",invoice="33333333-3333-4333-8333-333333333333",pdf=new Uint8Array([0x25,0x50,0x44,0x46,0x2d,1]);function base(){const form=new FormData();form.set("locale","fr");form.set("organizationId",id);form.set("idempotencyKey",key);return form}beforeEach(()=>{mocks.getUser.mockReset().mockResolvedValue({data:{user:{id:"u"}}});mocks.rpc.mockReset().mockResolvedValue({data:{outcome:"PROVIDER_OPERATION_RECORDED"},error:null});mocks.from.mockReset().mockReturnValue({select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),maybeSingle:vi.fn().mockResolvedValue({data:{currency:"MAD"},error:null})})});
describe("provider billing actions",()=>{
 it("maps a statement to the immutable RPC",async()=>{const form=base();form.set("statementNumber","REL-2026-01");form.set("periodStart","2026-01-01");form.set("periodEnd","2026-01-31");form.set("currency","mad");await expect(issueStatement(idle,form)).resolves.toEqual({status:"success",outcome:"PROVIDER_OPERATION_RECORDED"});expect(mocks.rpc).toHaveBeenCalledWith("issue_provider_statement",expect.objectContaining({p_currency:"MAD",p_provider_organization_id:id}))});
 it("convertit un montant MAD et dérive l’empreinte d’un vrai justificatif",async()=>{const form=base();form.set("paymentReference","VIR-2026-1");form.set("paidOn","2026-09-15");form.set("paymentMethod","BANK_TRANSFER");form.set("currency","MAD");form.set("amount","1 250,50");form.set("cashAccountId",id);form.set("receivableAccountId",invoice);form.set("proofFile",new File([pdf],"preuve.pdf",{type:"application/pdf"}));await expect(recordPayment(idle,form)).resolves.toEqual({status:"success",outcome:"PROVIDER_OPERATION_RECORDED"});expect(mocks.rpc).toHaveBeenCalledWith("record_provider_payment",expect.objectContaining({p_amount_minor:"125050",p_proof_hash:createHash("sha256").update(pdf).digest("hex")}))});
 it("maps one exact allocation after authoritative currency lookup",async()=>{const form=base();form.set("paymentId",id);form.set("invoiceId",invoice);form.set("amount","125,00");await reconcilePayment(idle,form);expect(mocks.rpc).toHaveBeenCalledWith("reconcile_provider_payment",expect.objectContaining({p_allocations:[{invoice_id:invoice,amount_minor:"12500"}]}))});
 it("never calls RPC for invalid dates",async()=>{const form=base();form.set("statementNumber","REL");form.set("periodStart","2026-02-01");form.set("periodEnd","2026-01-01");form.set("currency","MAD");await expect(issueStatement(idle,form)).resolves.toEqual({status:"error",reason:"VALIDATION"});expect(mocks.rpc).not.toHaveBeenCalled()});
 it("blocks RPC without session",async()=>{mocks.getUser.mockResolvedValueOnce({data:{user:null}});const form=base();form.set("statementNumber","REL");form.set("periodStart","2026-01-01");form.set("periodEnd","2026-01-31");form.set("currency","MAD");await expect(issueStatement(idle,form)).resolves.toEqual({status:"error",reason:"UNAUTHENTICATED"})});
});
