"use server";

import { z } from "zod";
import { companyDecisionInput, documentDecisionInput, qualificationDecisionInput } from "@/lib/admin-providers/model";
import { invoiceInput, paymentInput, reconciliationInput, statementInput } from "@/lib/provider-billing/model";
import { getSupabaseServerClient } from "@/lib/supabase/server";

export type AdminProviderActionState = { status: "idle" } | { status: "success"; outcome: string } | { status: "error"; reason: "VALIDATION" | "UNAUTHENTICATED" | "FORBIDDEN" | "CONFLICT" | "FAILED" };
const output = z.object({ outcome: z.string().min(3) }).passthrough(); const text = (data: FormData, key: string) => String(data.get(key) ?? ""); const nullable = (value: string) => value.trim() || null;
function parseArray(value: string): unknown[] | null { try { const parsed: unknown = JSON.parse(value); return Array.isArray(parsed) ? parsed : null; } catch { return null; } }
function failure(error: { code?: string; message?: string } | null): AdminProviderActionState { if (error?.code === "42501") return { status: "error", reason: "FORBIDDEN" }; if (["40001", "23505", "23514", "55000"].includes(error?.code ?? "") || error?.message?.includes("IDEMPOTENCY") || error?.message?.includes("OVERALLOCATED")) return { status: "error", reason: "CONFLICT" }; return { status: "error", reason: "FAILED" }; }
async function rpc(name: string, args: Record<string, unknown>): Promise<AdminProviderActionState> { const client = await getSupabaseServerClient(); const { data } = await client.auth.getUser(); if (!data.user) return { status: "error", reason: "UNAUTHENTICATED" }; const result = await client.rpc(name, args); if (result.error) return failure(result.error); const parsed = output.safeParse(result.data); return parsed.success ? { status: "success", outcome: parsed.data.outcome } : { status: "error", reason: "FAILED" }; }

export async function decideCompany(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const parsed = companyDecisionInput.safeParse({ organizationId: text(data, "organizationId"), companyStatus: text(data, "companyStatus"), partnerContractStatus: text(data, "partnerContractStatus"), partnerContractExpiresAt: nullable(text(data, "partnerContractExpiresAt")), reason: text(data, "reason"), ruleVersion: text(data, "ruleVersion").toUpperCase(), expectedRowVersion: text(data, "expectedRowVersion"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("decide_provider_company", { p_provider_organization_id: value.organizationId, p_company_status: value.companyStatus, p_partner_contract_status: value.partnerContractStatus, p_partner_contract_expires_at: value.partnerContractExpiresAt, p_reason: value.reason, p_rule_version: value.ruleVersion, p_expected_row_version: value.expectedRowVersion, p_idempotency_key: value.idempotencyKey }); }
export async function reviewDocument(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const parsed = documentDecisionInput.safeParse({ documentVersionId: text(data, "documentVersionId"), status: text(data, "status"), rationale: text(data, "rationale"), ruleVersion: text(data, "ruleVersion").toUpperCase(), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("review_provider_document", { p_document_version_id: value.documentVersionId, p_status: value.status, p_rationale: value.rationale, p_rule_version: value.ruleVersion, p_idempotency_key: value.idempotencyKey }); }
export async function decideQualification(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const mandatoryChecks = parseArray(text(data, "mandatoryChecks")), blockingConditions = parseArray(text(data, "blockingConditions")); if (!mandatoryChecks || !blockingConditions) return { status: "error", reason: "VALIDATION" }; const score = nullable(text(data, "scoreBasisPoints")); const parsed = qualificationDecisionInput.safeParse({ qualificationId: text(data, "qualificationId"), status: text(data, "status"), questionnaireSessionId: nullable(text(data, "questionnaireSessionId")), scoreBasisPoints: score === null ? null : score, mandatoryChecks, blockingConditions, rationale: text(data, "rationale"), ruleVersion: text(data, "ruleVersion").toUpperCase(), expiresAt: nullable(text(data, "expiresAt")), expectedRowVersion: text(data, "expectedRowVersion"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("decide_provider_qualification", { p_qualification_id: value.qualificationId, p_status: value.status, p_questionnaire_session_id: value.questionnaireSessionId, p_score_basis_points: value.scoreBasisPoints, p_mandatory_checks: value.mandatoryChecks, p_blocking_conditions: value.blockingConditions, p_rationale: value.rationale, p_rule_version: value.ruleVersion, p_expires_at: value.expiresAt, p_expected_row_version: value.expectedRowVersion, p_idempotency_key: value.idempotencyKey }); }
export async function issueAdminStatement(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const parsed = statementInput.safeParse({ organizationId: text(data, "organizationId"), statementNumber: text(data, "statementNumber"), periodStart: text(data, "periodStart"), periodEnd: text(data, "periodEnd"), currency: text(data, "currency").toUpperCase(), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("issue_provider_statement", { p_provider_organization_id: value.organizationId, p_statement_number: value.statementNumber, p_period_start: value.periodStart, p_period_end: value.periodEnd, p_currency: value.currency, p_idempotency_key: value.idempotencyKey }); }
export async function issueAdminInvoice(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const parsed = invoiceInput.safeParse({ statementId: text(data, "statementId"), invoiceNumber: text(data, "invoiceNumber"), issuedOn: text(data, "issuedOn"), dueOn: text(data, "dueOn"), receivableAccountId: text(data, "receivableAccountId"), revenueAccountId: text(data, "revenueAccountId"), taxLiabilityAccountId: text(data, "taxLiabilityAccountId"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("issue_provider_invoice", { p_statement_id: value.statementId, p_invoice_number: value.invoiceNumber, p_issued_on: value.issuedOn, p_due_on: value.dueOn, p_receivable_account_id: value.receivableAccountId, p_revenue_account_id: value.revenueAccountId, p_tax_liability_account_id: value.taxLiabilityAccountId, p_idempotency_key: value.idempotencyKey }); }
export async function recordAdminPayment(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const parsed = paymentInput.safeParse({ organizationId: text(data, "organizationId"), paymentReference: text(data, "paymentReference"), paidOn: text(data, "paidOn"), paymentMethod: text(data, "paymentMethod"), currency: text(data, "currency").toUpperCase(), amountMinor: text(data, "amountMinor"), proofHash: text(data, "proofHash"), cashAccountId: text(data, "cashAccountId"), receivableAccountId: text(data, "receivableAccountId"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("record_provider_payment", { p_provider_organization_id: value.organizationId, p_payment_reference: value.paymentReference, p_paid_on: value.paidOn, p_payment_method: value.paymentMethod, p_currency: value.currency, p_amount_minor: value.amountMinor, p_proof_hash: value.proofHash, p_cash_account_id: value.cashAccountId, p_receivable_account_id: value.receivableAccountId, p_idempotency_key: value.idempotencyKey }); }
export async function reconcileAdminPayment(_: AdminProviderActionState, data: FormData): Promise<AdminProviderActionState> { const parsed = reconciliationInput.safeParse({ paymentId: text(data, "paymentId"), invoiceId: text(data, "invoiceId"), amountMinor: text(data, "amountMinor"), idempotencyKey: text(data, "idempotencyKey") }); if (!parsed.success) return { status: "error", reason: "VALIDATION" }; const value = parsed.data; return rpc("reconcile_provider_payment", { p_payment_id: value.paymentId, p_allocations: [{ invoice_id: value.invoiceId, amount_minor: value.amountMinor }], p_idempotency_key: value.idempotencyKey }); }
